import {presentation} from '../app/presentation';
import {ContactShadow,contactPlaneNormal} from './shadow';
import type {Entrance} from '../data/poi';
import {appStore} from '../app/state';
import type {Selection} from '../app/state';
import {sharedSurface} from './sharedSurface';
import {workspaceLoader,loadedAsset} from '../app/assets';
// SPDX-License-Identifier: GPL-3.0-only
import {evaluateTraversal} from '../data/traversal';
import {Matrix4,PerspectiveCamera,Vector3} from 'three';
import {decodeExplorer} from '../data/explorer';
import type {ExplorerPack,Surface} from '../data/explorer';
import type {GaiaViewer} from '../viewer/GaiaViewer';
import type {NativeViewer} from '../viewer/NativeViewer';
import type {MapId} from '../data/nativeMaps';
import type {ProjectionId} from '../projections/Projection';
import {OriginalModel} from './model';
import {advance,barycentric,compatible,locate} from './walker';
import type {Barycentric,WalkerState} from './walker';
import {sourceGlobe,sourceGeographic,geographicSource,tangentFrame} from './coordinates';
import {t,formatNumber,onLocaleChange} from '../i18n';

export interface ExplorerState extends Omit<WalkerState,'sourceTriangleId'|'barycentricPosition'|'rawInterpolatedHeight'> {sourceTriangleId:number|null;barycentricPosition:Barycentric|null;rawInterpolatedHeight:number|null;mapId:MapId;explorerType:string;modelId:number|null;heading:number;speedState:string;movementState:string;animationState:number;airborne:boolean;flightAltitude:number;runtimeClaim:false;}
export let activeExplorer:ExplorerController|undefined;
export class ExplorerController {
 loadFile:(file:File)=>Promise<void>=async()=>{throw Error('Explorer not initialized');};
 pack:ExplorerPack|null=null;state:ExplorerState|null=null;surface:Surface|null=null;model:OriginalModel|null=null;armed=false;profile='foot';
 readonly diagnostics={loadMs:0,modelGeometryBytes:0,modelTextureBytes:0,modelDrawCalls:0,modelSwitchMs:0,shadowDrawCalls:0,packBytes:0,stepMs:0};
 private viewer:GaiaViewer|NativeViewer|undefined;private snapshot:{projection?:ProjectionId;position:Vector3;up:Vector3;target:Vector3;near:number;zoom:number;topdown?:boolean}|null=null;
 private lockedControls:{element:HTMLInputElement|HTMLSelectElement|HTMLButtonElement;disabled:boolean}[]=[];private compared=false;
 private party='cloud';private shadow:ContactShadow|null=null;private presentationChanged=()=>this.model?.lighting(presentation.lighting);private seconds=0;private yaw=0;private pitch=.45;private distance=1500;private keys=new Set<string>();private drag:{x:number;y:number;id:number}|null=null;private restoreTimer:ReturnType<typeof setTimeout>|null=null;
 private selectionSnapshot:Selection|null|undefined;private disposed=false;private loadEpoch=0;private readonly pageHide=()=>this.dispose();
 private modelNote=document.createElement('p');private panel=document.createElement('details');private title=document.createElement('summary');private load=document.createElement('button');private input=document.createElement('input');private selector=document.createElement('select');private visual=document.createElement('select');private modeLabel=document.createElement('label');private visualLabel=document.createElement('label');private start=document.createElement('button');private exitButton=document.createElement('button');private land=document.createElement('button');private status=document.createElement('p');private note=document.createElement('p');private controlsNote=document.createElement('p');private details=document.createElement('details');private detailsTitle=document.createElement('summary');private inspector=document.createElement('pre');private pad=document.createElement('section');private stopLocale:()=>void;
 constructor(private getWM0:()=>GaiaViewer|undefined,private getNative:()=>NativeViewer|undefined){
  activeExplorer=this;this.panel.className='explorer-panel';this.panel.id='explorer-panel';this.input.type='file';this.input.accept='.bin';this.input.hidden=true;this.input.id='explorer-file';this.load.id='load-explorer';this.start.id='explorer-start';this.exitButton.id='explorer-exit';this.selector.id='explorer-mode';this.visual.id='explorer-model';this.land.id='explorer-land';this.pad.id='explorer-pad';this.pad.className='explorer-pad';this.pad.hidden=true;this.land.hidden=true;
  this.modeLabel.htmlFor=this.selector.id;this.visualLabel.htmlFor=this.visual.id;this.details.append(this.detailsTitle,this.inspector);this.panel.append(this.title,this.load,this.input,this.modeLabel,this.selector,this.visualLabel,this.visual,this.modelNote,this.start,this.exitButton,this.land,this.status,this.note,this.controlsNote,this.details);document.querySelector('.multimap-bar')!.append(this.panel);document.body.append(this.pad);
  this.load.onclick=()=>this.input.click();this.start.onclick=()=>this.arm();this.exitButton.onclick=()=>this.exit();this.land.onclick=()=>this.toggleFlight();this.selector.onchange=()=>this.change(this.selector.value);this.visual.onchange=()=>this.selectVisual(this.visual.value);
  const loadFile=async(file:File)=>{const stamp=++this.loadEpoch,began=performance.now();const pack=await decodeExplorer(await file.arrayBuffer());await this.prepare(pack);if(stamp!==this.loadEpoch||this.disposed)throw Error('Superseded Explorer load');this.validate(pack);this.exit();this.pack=pack;loadedAsset('explorer',file.size,pack.header.version);this.diagnostics.loadMs=performance.now()-began;this.diagnostics.packBytes=file.size;this.status.textContent=t('explore.ready');this.translate();};this.loadFile=loadFile;workspaceLoader.register('explorer',async files=>loadFile(files[0]));
  this.input.onchange=async()=>{const file=this.input.files?.[0];if(!file)return;try{await loadFile(file);}catch(e){this.status.textContent=t('explore.corrupt');this.status.title=String(e);}finally{this.input.value='';}};
  for(const [key,label,symbol]of [['w','forward','▲'],['a','left','◀'],['s','backward','▼'],['d','right','▶'],['q','up','＋'],['e','down','−']]){const button=document.createElement('button');button.dataset.key=key;button.dataset.label=label;button.textContent=symbol;button.onpointerdown=e=>{e.preventDefault();button.setPointerCapture(e.pointerId);this.keys.add(key);};button.onpointerup=button.onpointercancel=()=>this.keys.delete(key);this.pad.append(button);}
  document.addEventListener('keydown',this.keyDown,true);document.addEventListener('keyup',this.keyUp,true);window.addEventListener('blur',this.blur);document.addEventListener('pointerdown',this.pointerDown,true);document.addEventListener('pointermove',this.pointerMove,true);document.addEventListener('pointerup',this.pointerUp,true);document.addEventListener('pointercancel',this.pointerUp,true);document.addEventListener('wheel',this.wheel,{capture:true,passive:false});document.addEventListener('gaiagis-map-changing',this.mapChanging);window.addEventListener('pagehide',this.pageHide,{once:true});document.addEventListener('gaiagis-presentation',this.presentationChanged);this.stopLocale=onLocaleChange(()=>this.translate());this.translate();
 }
 private mapId():MapId{return (document.getElementById('map-selector') as HTMLSelectElement).value as MapId;}
 private async prepare(pack:ExplorerPack){if(pack.header.version!==2)return;const wm=this.getWM0();if(wm)pack.bindSurface?.(await sharedSurface(wm.mesh,wm.meta));const native=this.getNative();if(native)pack.bindSurface?.(await sharedSurface(native.map));}
 private validate(pack:ExplorerPack){for(const [id,modelId]of Object.entries({cloud:0,tifa:1,cid:2,highwind:3,chocobo:19,'tiny-bronco':5,buggy:6,submarine:13}))if(!pack.header.models.some(m=>m.id===id&&m.model_id===modelId))throw Error('Missing required Explorer identity');const wm=this.getWM0();if(wm)this.bind(pack.surface('WM0'),wm);const native=this.getNative();if(native)this.bind(pack.surface(native.map.header.mapId),native);}
 private bind(surface:Surface,viewer:GaiaViewer|NativeViewer){
  const extent='mesh' in viewer?[294912,229376]:viewer.map.header.extent;if(extent.some((n,i)=>n!==surface.header.extent[i]))throw Error('Explorer source extent mismatch');
  const mesh='mesh' in viewer?viewer.mesh:viewer.map;if(mesh.sourceTriangleCount!==surface.count)throw Error('Explorer source triangle count mismatch');
  const hash='mesh' in viewer?(viewer.meta as typeof viewer.meta&{stage1:{source_wm0_sha256:string}}).stage1?.source_wm0_sha256:viewer.map.header.source_sha256;
  if(hash?.toLowerCase()!==surface.header.source_sha256)throw Error('Explorer source fingerprint mismatch');
  for(let i=0;i<surface.count;i++){const a=surface.attrs(i),b=mesh.attributes(i);if(a.section!==b.section||a.mesh!==b.mesh||a.triangle!==b.triangle||a.terrain!==b.terrain||a.script!==b.script)throw Error('Explorer source lineage mismatch');
   const points=surface.points(i);for(let j=0;j<3;j++){if('mesh' in viewer){const expected=sourceGeographic(...points[j]),index=viewer.mesh.indices[i*3+j]*3,actual=viewer.mesh.geographic;const longitude=Math.abs(expected[0]-actual[index]);if(Math.min(longitude,Math.abs(longitude-360))>1e-4||Math.abs(expected[1]-actual[index+1])>1e-4||Math.abs(expected[2]-actual[index+2])>1e-3)throw Error('Explorer native vertices disagree with V1 geometry');}else for(let axis=0;axis<3;axis++)if(points[j][axis]!==viewer.map.positions[i*9+j*3+axis])throw Error('Explorer native vertices disagree with loaded map');}
  }
 }

 async arm(){if(!this.pack)return;try{await this.prepare(this.pack);}catch(e){this.status.textContent=t("explore.corrupt");this.status.title=String(e);return;}this.exit(false);const id=this.mapId(),viewer=id==='WM0'?this.getWM0():this.getNative();if(!viewer){this.status.textContent=t('load.required');return;}const surface=this.pack.surface(id);try{this.bind(surface,viewer);}catch(e){this.status.textContent=t('explore.corrupt');this.status.title=String(e);return;}
  this.selectionSnapshot=appStore.state.selection;this.viewer=viewer;this.surface=surface;
  const compare=document.getElementById('compare-projections') as HTMLInputElement|null;this.compared=!!compare?.checked;if(compare?.checked){compare.checked=false;compare.dispatchEvent(new Event('change'));}
  for(const control of document.querySelectorAll<HTMLInputElement|HTMLSelectElement|HTMLButtonElement>('#projection,#compare-projections,#compare-projection-a,#compare-projection-b,#native-view')){this.lockedControls.push({element:control,disabled:control.disabled});control.disabled=true;}
  const native='map' in viewer;const bridge=native?viewer:{...viewer.explorerBridge};const overview=native?viewer:viewer.overviewBridge,camera=overview.camera,controls=overview.controls;this.snapshot={projection:native?undefined:viewer.projectionId,position:camera.position.clone(),up:camera.up.clone(),target:controls.target.clone(),near:camera.near,zoom:camera.zoom,topdown:native?viewer.topdown:undefined};
  if(native){if(viewer.topdown)viewer.setView(false);viewer.onExplorerPick=(triangle,b)=>this.place(triangle,b);viewer.onExplorerFrame=dt=>this.frame(dt);}else{viewer.setProjection('globe');viewer.onExplorerPick=(triangle,geo)=>{if(!this.surface||triangle>=this.surface.count)return;const [x,z]=geographicSource(geo[0],geo[1]),points=this.surface.points(triangle),center=points.reduce((sum,p)=>sum+p[0]/3,0),width=this.surface.header.extent[0],corrected=x+Math.round((center-x)/width)*width,b=barycentric(points,corrected,z);if(b&&b.every(v=>v>=-1e-5))this.place(triangle,b.map(v=>Math.max(0,v)) as Barycentric);else this.status.textContent=t('explore.rejected');};viewer.onExplorerFrame=dt=>this.frame(dt);}
  viewer.captureExplorer=true;('map' in viewer?viewer.controls:bridge.controls).enabled=false;this.armed=true;appStore.dispatch({type:'explorer',phase:'placing'});this.profile=this.selector.value;this.panel.dataset.state='placing';this.status.textContent=t('explore.placing');this.exitButton.disabled=false;this.start.disabled=true;
 }
 place(triangle:number,b:Barycentric){if(!this.armed||!this.surface||!this.viewer||!this.pack)return false;try{const flight=this.profile==='highwind';if(!flight&&!compatible(this.surface,triangle,this.profile)){this.status.textContent=t('explore.rejected');return false;}
  const p=locate(this.surface,triangle,b),model=this.pack.header.models.find(m=>m.id===this.modelIdentity())!;this.state={...p,mapId:this.surface.header.mapId,explorerType:this.profile,modelId:model.model_id,heading:0,speedState:'idle',movementState:'stationary',animationState:0,airborne:flight,flightAltitude:flight?4000:this.profile==='submarine-native'?400:0,runtimeClaim:false};this.seconds=0;this.yaw=0;this.distance=this.profile==='highwind'?4500:1500;this.spawnModel();const camera='map' in this.viewer?this.viewer.camera:this.viewer.explorerBridge.camera;camera.near=.00001;camera.updateProjectionMatrix();this.pad.hidden=false;this.panel.dataset.state='active';appStore.dispatch({type:'explorer',phase:'active'});appStore.dispatch({type:'select',selection:{kind:'explorer',id:'current',mapId:this.surface.header.mapId}});this.status.textContent=t('explore.preview');this.translate();if(innerWidth<=700)this.panel.open=false;return true;
 }catch(e){this.status.textContent=t('explore.rejected');this.status.title=String(e);return false;}}
 selectVisual(id:string){const previous=this.modelIdentity(),party=['cloud','barret','tifa','aerith','red-xiii','yuffie','cait-sith','vincent','cid'].includes(id);if(!this.pack?.header.models.some(m=>m.id===(id.startsWith('chocobo-')?'chocobo':id))){this.visual.value=previous;return false;}
  const profile=party?(this.mapId()==='WM3'?'glacier-native':'foot'):id==='submarine'?'submarine-native':id;
  const oldParty=this.party;this.visual.value=id;if(party)this.party=id;if(!this.change(profile)){this.party=oldParty;this.visual.value=previous;return false;}return true;
 }
 private choices(){const selected=this.modelIdentity();this.visual.replaceChildren();const party=['cloud','barret','tifa','aerith','red-xiii','yuffie','cait-sith','vincent','cid'];for(const [group,ids] of [['party',party],['vehicles',['buggy','tiny-bronco','highwind','submarine']],['chocobos',['chocobo-yellow','chocobo-green','chocobo-blue','chocobo-black','chocobo-gold']]] as [string,string[]][]){const g=document.createElement('optgroup');g.label=t('present.'+group);for(const id of ids){const o=document.createElement('option');o.value=id;o.textContent=party.includes(id)?t('party.'+id):id==='highwind'?t('explore.highwind'):id==='submarine'?t('explore.submarine'):t('mode.'+id);const exists=this.pack?.header.models.some(m=>m.id===(id.startsWith('chocobo-')?'chocobo':id));o.disabled=!exists||(this.mapId()==='WM2'?id!=='submarine':this.mapId()==='WM3'?!party.includes(id):id==='submarine');if(!exists)o.title=t('present.unavailable');g.append(o);}this.visual.append(g);}this.visual.value=selected;const model=this.pack?.header.models.find(m=>m.id===selected);this.modelNote.textContent=(model?.sourceKind==='extended_field'?t('present.extended')+'\n':'')+t('present.profile')+'\n'+t('present.shadow');
 }
 private modelIdentity(){return this.profile==='foot'||this.profile==='glacier-native'?this.party:this.profile.startsWith('chocobo-')?'chocobo':this.profile==='submarine-native'?'submarine':this.profile;}
 private spawnModel(){const began=performance.now();if(!this.pack||!this.viewer||!this.state)return;const m=this.pack.header.models.find(m=>m.id===this.modelIdentity());if(!m)throw Error('Missing visual model');this.model?.dispose();this.model=new OriginalModel(this.pack,m);this.model.lighting(presentation.lighting);if(!this.shadow){this.shadow=new ContactShadow();('map' in this.viewer?this.viewer.scene:this.viewer.explorerBridge.scene).add(this.shadow.object);}if(this.profile.startsWith('chocobo-'))this.model.tint(['chocobo-yellow','chocobo-green','chocobo-blue','chocobo-black','chocobo-gold'].indexOf(this.profile));this.state.modelId=m.model_id;('map' in this.viewer?this.viewer.scene:this.viewer.explorerBridge.scene).add(this.model.object);this.diagnostics.modelGeometryBytes=this.model.geometryBytes;this.diagnostics.modelTextureBytes=this.model.textureBytes;this.diagnostics.modelDrawCalls=this.model.meshes.length;this.diagnostics.shadowDrawCalls=1;this.diagnostics.modelSwitchMs=performance.now()-began;}
 change(profile:string){if(this.state&&this.surface){const ground=this.state.airborne?this.groundAt(this.state.nativeX,this.state.nativeZ):this.state as WalkerState;if(profile!=='highwind'&&(!ground||!compatible(this.surface,ground.sourceTriangleId,profile))){this.selector.value=this.profile;this.status.textContent=t('explore.rejected');return false;}if(ground)Object.assign(this.state,ground);this.profile=profile;this.state.explorerType=profile;this.state.airborne=profile==='highwind';this.state.flightAltitude=this.state.airborne?4000:profile==='submarine-native'?400:0;this.spawnModel();}else this.profile=profile;this.translate();return true;}
 private groundAt(x:number,z:number){if(!this.surface)return null;let hit:WalkerState|null=null;for(const i of this.surface.candidates(x,z)){const p=this.surface.points(i);if(p.every(v=>v[0]<x)||p.every(v=>v[0]>x)||p.every(v=>v[1]<z)||p.every(v=>v[1]>z))continue;const b=barycentric(p,x,z);if(b&&b.every(v=>v>=-1e-8)){if(hit)return null;hit=locate(this.surface,i,b);}}return hit;}
 toggleFlight(){const s=this.state;if(!s||!this.surface||this.profile!=='highwind')return false;if(!s.airborne){s.airborne=true;s.flightAltitude=4000;this.translate();return true;}const ground=this.groundAt(s.nativeX,s.nativeZ);if(!ground||!compatible(this.surface,ground.sourceTriangleId,'highwind-landing')){this.status.textContent=t('explore.landingBlocked');return false;}Object.assign(s,ground,{airborne:false,flightAltitude:0});this.translate();return true;}
 frame(dt:number){const s=this.state;if(!s||!this.surface||!this.viewer||!this.model)return;const began=performance.now();dt=Math.min(.05,Math.max(0,dt));this.seconds+=dt;const forward=Number(this.keys.has('w'))-Number(this.keys.has('s')),turn=Number(this.keys.has('d'))-Number(this.keys.has('a'));s.heading=(s.heading+turn*dt*1.8+Math.PI*2)%(Math.PI*2);const speed=(s.airborne?3500:this.profile==='buggy'?1500:this.profile==='tiny-bronco'?1800:900)*(this.keys.has('shift')?2:1),dx=Math.sin(s.heading)*forward*dt*speed,dz=-Math.cos(s.heading)*forward*dt*speed;
  if(forward&&(!s.airborne&&this.profile==='highwind')){this.status.textContent=t('explore.grounded');}else if(s.airborne){s.nativeX=((s.nativeX+dx)%this.surface.header.extent[0]+this.surface.header.extent[0])%this.surface.header.extent[0];s.nativeZ=Math.max(0,Math.min(this.surface.header.extent[1],s.nativeZ+dz));if(forward){const ground=this.groundAt(s.nativeX,s.nativeZ);s.sourceTriangleId=ground?.sourceTriangleId??null;s.barycentricPosition=ground?.barycentricPosition??null;s.rawInterpolatedHeight=ground?.rawInterpolatedHeight??null;}}else if(forward){const result=advance(this.surface,s as WalkerState,dx,dz,this.profile);Object.assign(s,result.state);if(result.blocked)this.status.textContent=t('explore.boundary');}
  if(s.airborne||this.profile==='submarine-native')s.flightAltitude=Math.max(0,Math.min(20000,s.flightAltitude+(Number(this.keys.has('q'))-Number(this.keys.has('e')))*dt*1000));
  s.speedState=forward?'moving':'idle';s.movementState=s.airborne?'airborne':forward?'moving':'stationary';s.animationState=this.profile==='buggy'&&forward?([4,5,6,11].includes(this.surface.attrs(s.sourceTriangleId!).terrain)?3:1):forward&&this.model.model.animation_identity==='stationary_0_moving_1'?1:0;this.model.pose(s.animationState,this.seconds);
  const native='map' in this.viewer,bridge='map' in this.viewer?this.viewer:this.viewer.explorerBridge,camera=bridge.camera as PerspectiveCamera;let position:Vector3,scale:number,up:Vector3,east:Vector3,north:Vector3;
  if(native){const v=this.viewer as NativeViewer;position=new Vector3((s.nativeX-this.surface.header.extent[0]/2)/v.scale,((s.rawInterpolatedHeight??0)*v.exaggeration+s.flightAltitude)/v.scale,(s.nativeZ-this.surface.header.extent[1]/2)/v.scale);scale=1/v.scale;up=new Vector3(0,1,0);east=new Vector3(1,0,0);north=new Vector3(0,0,-1);}else{const v=this.viewer as GaiaViewer;position=sourceGlobe(s.nativeX,s.nativeZ,s.rawInterpolatedHeight??0,v.relief,v.context);if(!s.airborne&&s.sourceTriangleId!==null&&s.barycentricPosition){position.set(0,0,0);this.surface.points(s.sourceTriangleId).forEach((p,j)=>position.addScaledVector(sourceGlobe(...p,v.relief,v.context),s.barycentricPosition![j]));}const basis=tangentFrame(position);({up,east,north}=basis);scale=2*Math.PI/this.surface.header.extent[0]*Math.sqrt(up.x*up.x+up.z*up.z);position.addScaledVector(up,s.flightAltitude*scale);}
  const direction=east.clone().multiplyScalar(Math.sin(s.heading)).addScaledVector(north,Math.cos(s.heading)),right=new Vector3().crossVectors(direction,up).normalize(),back=direction.clone().negate(),matrix=new Matrix4().makeBasis(right,up,back);this.model.object.position.copy(position);this.model.object.quaternion.setFromRotationMatrix(matrix);this.model.object.scale.setScalar(this.model.displayScale*scale);
  this.model.direction(east.clone().multiplyScalar(-.35).addScaledVector(up,.8).addScaledVector(north,.5));if(this.shadow){let normal=up.clone();if(s.sourceTriangleId!==null){const points=this.surface.points(s.sourceTriangleId).map(p=>native?new Vector3((p[0]-this.surface!.header.extent[0]/2)/(this.viewer as NativeViewer).scale,p[2]*(this.viewer as NativeViewer).exaggeration/(this.viewer as NativeViewer).scale,(p[1]-this.surface!.header.extent[1]/2)/(this.viewer as NativeViewer).scale):sourceGlobe(...p,(this.viewer as GaiaViewer).relief,(this.viewer as GaiaViewer).context));normal=contactPlaneNormal(points,up);}
   this.shadow.object.position.copy(position).addScaledVector(up,-s.flightAltitude*scale).addScaledVector(normal,scale*1.5);this.shadow.object.quaternion.setFromUnitVectors(new Vector3(0,0,1),normal);this.shadow.update(this.model.model.id,s.flightAltitude,scale);}
  const cameraForward=east.clone().multiplyScalar(Math.sin(s.heading+this.yaw)).addScaledVector(north,Math.cos(s.heading+this.yaw)),target=position.clone().addScaledVector(up,this.model.size*scale*.35),desired=target.clone().addScaledVector(cameraForward,-Math.cos(this.pitch)*this.distance*scale).addScaledVector(up,Math.sin(this.pitch)*this.distance*scale),reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  camera.up.copy(up);camera.position.lerp(desired,reduced?1:1-Math.exp(-dt*7));bridge.controls.target.copy(target);camera.lookAt(target);camera.updateMatrixWorld();
  if(Math.floor(this.seconds*4)!==Math.floor((this.seconds-dt)*4)){this.inspector.textContent=[`${s.mapId} · ${this.profile} · ${this.model.model.hrc}`,`${t('inspect.terrain')}: ${s.sourceTriangleId===null?'—':this.surface.attrs(s.sourceTriangleId).terrain}`,`${t('inspect.compatibility')}: ${s.airborne?t('explore.highwind'):s.mapId!=='WM0'?t('explore.native'):s.sourceTriangleId===null?'—':t('state.'+evaluateTraversal(this.profile==='highwind'?'highwind-landing':this.profile,this.surface.attrs(s.sourceTriangleId).terrain,this.surface.attrs(s.sourceTriangleId).script).state)}`,`${t('explore.source')}: ${s.sourceTriangleId??'—'} / ${s.barycentricPosition?.map(v=>formatNumber(v,4)).join(' / ')??'—'}`,`X/Z: ${formatNumber(s.nativeX)} / ${formatNumber(s.nativeZ)}`,`${t('explore.height')}: ${s.rawInterpolatedHeight===null?'—':formatNumber(s.rawInterpolatedHeight)}`,`${t('explore.altitude')}: ${formatNumber(s.flightAltitude)}`,`${t('explore.clip')}: ${s.animationState} · ${this.model.model.clips[s.animationState]?.name??this.model.model.clips[0].name}`,`runtimeClaim: false`].join('\n');}
  this.diagnostics.stepMs=performance.now()-began;
 }
 private keyDown=(e:KeyboardEvent)=>{if(!this.state||e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement)return;const key=({ArrowUp:'w',ArrowDown:'s',ArrowLeft:'a',ArrowRight:'d'} as Record<string,string>)[e.key]??e.key.toLowerCase();if(key==='escape'){e.preventDefault();e.stopImmediatePropagation();this.exit();return;}if(['w','a','s','d','q','e','shift'].includes(key)){e.preventDefault();e.stopImmediatePropagation();this.keys.add(key);}};
 private keyUp=(e:KeyboardEvent)=>{const key=({ArrowUp:'w',ArrowDown:'s',ArrowLeft:'a',ArrowRight:'d'} as Record<string,string>)[e.key]??e.key.toLowerCase();this.keys.delete(key);};private blur=()=>this.keys.clear();
 async fromEntrance(e:Entrance){const wm=this.getWM0();if(!wm||this.mapId()!=='WM0')return false;let triangle=-1;for(let i=0;i<wm.mesh.sourceTriangleCount;i++){const a=wm.mesh.attributes(i);if(a.section===e.section_id&&a.mesh===e.mesh_id&&a.triangle===e.triangle_id){triangle=i;break;}}if(triangle<0)return false;await this.arm();if(!this.surface)return false;const b=barycentric(this.surface.points(triangle),e.game_x,e.game_north);return !!b&&this.place(triangle,b);}
 private canvas(){return this.viewer?.renderer.domElement;}
 private pointerDown=(e:PointerEvent)=>{if(!this.state||e.target!==this.canvas())return;(document.activeElement as HTMLElement)?.blur();this.drag={x:e.clientX,y:e.clientY,id:e.pointerId};this.canvas()?.setPointerCapture(e.pointerId);e.stopImmediatePropagation();};
 private pointerMove=(e:PointerEvent)=>{if(!this.drag||e.pointerId!==this.drag.id)return;this.yaw-=(e.clientX-this.drag.x)*.006;this.pitch=Math.max(.1,Math.min(1.35,this.pitch+(e.clientY-this.drag.y)*.006));this.drag={x:e.clientX,y:e.clientY,id:e.pointerId};e.stopImmediatePropagation();};
 private pointerUp=(e:PointerEvent)=>{if(!this.drag||e.pointerId!==this.drag.id)return;this.drag=null;e.stopImmediatePropagation();};
 private wheel=(e:WheelEvent)=>{if(!this.state||e.target!==this.canvas())return;e.preventDefault();e.stopImmediatePropagation();this.distance=Math.max(500,Math.min(12000,this.distance*Math.exp(e.deltaY*.001)));};
 private mapChanging=()=>{if(this.armed){this.exit();if(this.restoreTimer){clearTimeout(this.restoreTimer);this.restoreTimer=null;}this.status.textContent=t('explore.transition');}queueMicrotask(()=>this.translate());};
 exit(translate=true){appStore.dispatch({type:'explorer',phase:'idle'});if(this.selectionSnapshot!==undefined){const selection=this.selectionSnapshot;this.selectionSnapshot=undefined;appStore.dispatch({type:'select',selection});}if(this.restoreTimer){clearTimeout(this.restoreTimer);this.restoreTimer=null;}this.model?.dispose();this.model=null;this.shadow?.dispose();this.shadow=null;this.diagnostics.shadowDrawCalls=0;this.state=null;this.keys.clear();this.drag=null;this.pad.hidden=true;this.armed=false;delete this.panel.dataset.state;this.diagnostics.modelGeometryBytes=this.diagnostics.modelTextureBytes=this.diagnostics.modelDrawCalls=0;const v=this.viewer,snapshot=this.snapshot;if(v){v.captureExplorer=false;v.onExplorerFrame=()=>{};v.onExplorerPick=()=>{};const bridge='map' in v?v:v.explorerBridge;bridge.camera.near=snapshot?.near??.005;bridge.camera.updateProjectionMatrix();bridge.controls.enabled=true;if(snapshot){const restore=()=>{if('map' in v&&snapshot.topdown!==v.topdown)v.setView(!!snapshot.topdown);const b='map' in v?v:v.overviewBridge;b.camera.near=snapshot.near;b.camera.position.copy(snapshot.position);b.camera.up.copy(snapshot.up);b.camera.zoom=snapshot.zoom;b.camera.updateProjectionMatrix();b.controls.target.copy(snapshot.target);b.controls.update();};if('mesh' in v&&snapshot.projection&&v.projectionId!==snapshot.projection){v.setProjection(snapshot.projection);this.restoreTimer=setTimeout(restore,1250);}else restore();}}
  for(const lock of this.lockedControls)lock.element.disabled=lock.disabled;this.lockedControls=[];
  const compare=document.getElementById('compare-projections') as HTMLInputElement|null;if(this.compared&&compare){compare.checked=true;compare.dispatchEvent(new Event('change'));}this.compared=false;
  this.viewer=undefined;this.snapshot=null;this.surface=null;if(translate)this.translate();
 }
 translate(){const id=this.mapId(),old=this.selector.value;this.selector.replaceChildren();const profiles=id==='WM0'?['foot','buggy','tiny-bronco','chocobo-yellow','chocobo-green','chocobo-blue','chocobo-black','chocobo-gold','highwind']:id==='WM2'?['submarine-native']:['glacier-native'];for(const profile of profiles){const o=document.createElement('option');o.value=profile;o.textContent=profile==='highwind'?t('explore.highwind'):profile==='submarine-native'?t('explore.submarine'):profile==='glacier-native'?t('explore.glacier'):t('mode.'+profile);this.selector.append(o);}this.selector.value=profiles.includes(old)?old:profiles[0];if(!this.state)this.profile=this.selector.value;this.title.textContent=t('explore.title');this.load.textContent=t('explore.load');this.start.textContent=t('explore.start');this.exitButton.textContent=t('explore.exit');this.modeLabel.textContent=t('explore.mode');this.visualLabel.textContent=t('present.character');this.visual.hidden=this.visualLabel.hidden=false;this.choices();this.land.hidden=!this.state||this.profile!=='highwind';this.land.textContent=t(this.state?.airborne?'explore.land':'explore.takeoff');this.note.textContent=t(id==='WM0'?'explore.preview':'explore.native');this.controlsNote.textContent=t('explore.controls');this.detailsTitle.textContent=t('explore.animation');this.start.disabled=!this.pack||this.armed;this.exitButton.disabled=!this.armed;this.selector.disabled=!this.pack;this.load.disabled=this.armed;for(const button of this.pad.querySelectorAll('button'))button.setAttribute('aria-label',t('explore.'+(button as HTMLElement).dataset.label));if(!this.pack)this.status.textContent=t('explore.unavailable');this.panel.dataset.mapId=id;}
 resetData(){this.loadEpoch++;this.exit();this.pack=null;this.surface=null;this.diagnostics.packBytes=0;this.translate();}
 dispose(){if(this.disposed)return;this.disposed=true;this.loadEpoch++;window.removeEventListener('pagehide',this.pageHide);this.exit(false);if(this.restoreTimer)clearTimeout(this.restoreTimer);this.pack=null;this.stopLocale();document.removeEventListener('gaiagis-presentation',this.presentationChanged);document.removeEventListener('keydown',this.keyDown,true);document.removeEventListener('keyup',this.keyUp,true);window.removeEventListener('blur',this.blur);document.removeEventListener('pointerdown',this.pointerDown,true);document.removeEventListener('pointermove',this.pointerMove,true);document.removeEventListener('pointerup',this.pointerUp,true);document.removeEventListener('pointercancel',this.pointerUp,true);document.removeEventListener('wheel',this.wheel,true);document.removeEventListener('gaiagis-map-changing',this.mapChanging);this.panel.remove();this.pad.remove();activeExplorer=undefined;}
}
