// SPDX-License-Identifier: GPL-3.0-only
export const helpCatalog=[
['help.intro','Explore the same V1 polygons in thirteen views. V1 is a mathematical reconstruction, not official FF7 geography.','用十三种视图探索同一套 V1 多边形。V1 是数学重建，不是官方 FF7 地理。','用十三種檢視探索同一套 V1 多邊形。V1 是數學重建，不是官方 FF7 地理。','同じ V1 ポリゴンを13の表示で探索します。V1 は数学的再構成であり、公式 FF7 地理ではありません。','동일한 V1 폴리곤을 13가지 뷰로 탐색합니다. V1은 수학적 재구성이며 공식 FF7 지리가 아닙니다.'],
['help.local','Select gaia-meta.json and gaia-mesh.bin together. Generated files stay in your browser and are never uploaded. The code-only release contains no game-derived datasets.','同时选择 gaia-meta.json 和 gaia-mesh.bin。生成文件只留在浏览器中，不会上传。仅代码版本不包含游戏派生数据集。','同時選擇 gaia-meta.json 和 gaia-mesh.bin。產生的檔案只留在瀏覽器中，不會上傳。僅程式碼版本不包含遊戲衍生資料集。','gaia-meta.json と gaia-mesh.bin を同時に選択してください。生成ファイルはブラウザー内に留まり、アップロードされません。コードのみの配布にはゲーム由来データは含まれません。','gaia-meta.json과 gaia-mesh.bin을 함께 선택하세요. 생성 파일은 브라우저에만 남으며 업로드되지 않습니다. 코드 전용 배포에는 게임 파생 데이터가 없습니다.'],
['help.optional','Optional local datasets: Locations, Encounters, World Events and Routing load independently. Use the matching buttons in Display or Analysis. File generation commands are listed below and in README.','地点、遭遇、世界事件与路由数据均为可选本地文件，独立加载。使用显示或分析面板中的对应按钮。生成命令见下方与 README。','地點、遭遇、世界事件與路由資料均為選用本機檔案，獨立載入。使用顯示或分析面板中的對應按鈕。產生指令見下方與 README。','地点・エンカウント・イベント・経路は任意のローカルデータで、個別に読み込めます。表示または解析のボタンを使ってください。生成コマンドは下記と README にあります。','장소·조우·이벤트·경로는 선택적 로컬 데이터이며 개별적으로 불러옵니다. 표시 또는 분석의 버튼을 사용하세요. 생성 명령은 아래와 README에 있습니다.'],
['help.rules','Traversal uses static classic-PC rules, not current reachability. Highwind checks landing initiation. Random encounters, Chocobo tracks and scripted events are separate attributes. Story/save/model/vehicle state is not simulated.','通行层使用经典 PC 静态规则，不代表当前可达性。Highwind 检查着陆启动。随机遭遇、Chocobo 足迹和脚本事件是独立属性。不模拟剧情、存档、模型或载具状态。','通行層使用經典 PC 靜態規則，不代表目前可達性。Highwind 檢查著陸啟動。隨機遭遇、Chocobo 足跡和腳本事件是獨立屬性。不模擬劇情、存檔、模型或載具狀態。','通行レイヤーは Classic PC の静的規則で、現在の到達可能性ではありません。Highwind は着陸開始を調べます。ランダム戦闘・Chocobo 足跡・スクリプトイベントは別属性です。物語・セーブ・モデル・乗り物状態は再現しません。','이동 레이어는 Classic PC 정적 규칙이며 현재 도달 가능성을 뜻하지 않습니다. Highwind는 착륙 시작을 확인합니다. 무작위 조우·Chocobo 발자국·스크립트 이벤트는 별개입니다. 스토리·저장·모델·탈것 상태는 시뮬레이션하지 않습니다.'],
['help.routing','Analysis uses exact shared WM0 source edges. East/west wraps; north/south stays cut and synthetic caps are excluded. Routes are static triangle corridors with reference-sphere distance, not travel time or guaranteed gameplay paths.','分析使用 WM0 源数据精确共享边。东西周期闭合，南北保持切开，合成极帽不入图。路径是静态三角形走廊，显示参考球面距离，不代表行程时间或保证的游戏路径。','分析使用 WM0 來源資料精確共享邊。東西週期閉合，南北保持切開，合成極帽不入圖。路徑是靜態三角形走廊，顯示參考球面距離，不代表行程時間或保證的遊戲路徑。','解析は WM0 の正確な共有辺を使います。東西は周期接続し、南北は切断、合成極冠は除外します。経路は静的な三角形コリドーで、参照球面距離を表示します。移動時間やゲーム内通行の保証ではありません。','분석은 정확한 WM0 공유 간선을 사용합니다. 동서는 주기 연결, 남북은 절단하며 합성 극관을 제외합니다. 경로는 정적 삼각형 통로로 기준 구면 거리를 표시합니다. 이동 시간이나 게임 통행을 보장하지 않습니다.'],
['help.controls','Drag to orbit or pan; scroll or pinch to zoom; tap a triangle to inspect. Focus the map with Tab: arrows move, +/− zoom, N points north, Home resets, Escape clears selection. Reduced motion disables morph animation.','拖动旋转或平移，滚动或双指缩放，点击三角形检查。Tab 聚焦地图：方向键移动，+/− 缩放，N 北向上，Home 重置，Escape 清除选择。减少动态效果偏好会关闭变形动画。','拖曳旋轉或平移，捲動或雙指縮放，點擊三角形檢查。Tab 聚焦地圖：方向鍵移動，+/− 縮放，N 北向上，Home 重設，Escape 清除選取。減少動態效果偏好會關閉變形動畫。','ドラッグで回転・移動、スクロールやピンチで拡大縮小、三角形タップで調査。Tab で地図にフォーカス：矢印で移動、+/− で倍率、N で北、Home でリセット、Escape で選択解除。動きを減らす設定では変形アニメーションを無効にします。','드래그 회전·이동, 스크롤·핀치 확대, 삼각형 탭 조사. Tab으로 지도 초점: 화살표 이동, +/− 확대, N 북쪽, Home 초기화, Escape 선택 해제. 동작 줄이기는 변형 애니메이션을 끕니다.'],
['help.assumptions','Radius, height scale and orientation are reconstruction assumptions. Polar ocean caps are synthetic without FF7 lineage. Gameplay terrain is not real-world land cover. Current Steam 2026 executable equivalence remains unverified.','半径、高度比例和方向属于重建假设。合成海洋极帽没有 FF7 数据血统。游戏地形不是现实土地覆盖。Steam 2026 可执行程序等价性仍未验证。','半徑、高度比例和方向屬於重建假設。合成海洋極帽沒有 FF7 資料血統。遊戲地形不是現實土地覆蓋。Steam 2026 執行檔等價性仍未驗證。','半径・高さ尺度・方位は再構成の仮定です。合成海洋極冠には FF7 出典がありません。ゲーム地形は現実の土地被覆ではありません。Steam 2026 実行ファイルの同等性は未検証です。','반지름·높이 축척·방향은 재구성 가정입니다. 합성 해양 극관에는 FF7 출처가 없습니다. 게임 지형은 실제 토지 피복이 아닙니다. Steam 2026 실행 파일 동등성은 미검증입니다.'],
['help.climate','V2/V2.1/V2.2 research is concluded and preserved as Experimental / Inconclusive. No physically robust replacement latitude mapping was established; no climate warp is selectable.','V2/V2.1/V2.2 研究已结束并保留为实验性 / 结论未定。未建立物理上可靠的替代纬度映射，无法选择气候变形。','V2/V2.1/V2.2 研究已結束並保留為實驗性 / 結論未定。未建立物理上可靠的替代緯度映射，無法選擇氣候變形。','V2/V2.1/V2.2 研究は実験的・結論未確定として終了・保存しています。物理的に堅牢な代替緯度写像は確立せず、気候変形は選択できません。','V2/V2.1/V2.2 연구는 실험적·결론 미확정으로 종료·보존됩니다. 물리적으로 견고한 대체 위도 매핑은 확립되지 않았으며 기후 변형을 선택할 수 없습니다.'],
['help.license','GPL-3.0-only applies to GaiaGIS original code. Third-party licenses are retained. FF7 names, designs and assets belong to their respective rights holders. GaiaGIS is independent and not endorsed by Square Enix.','GPL-3.0-only 仅适用于 GaiaGIS 原创代码，第三方许可证保持不变。FF7 名称、设计与资产归各自权利人所有。GaiaGIS 为独立项目，未经 Square Enix 认可。','GPL-3.0-only 僅適用於 GaiaGIS 原創程式碼，第三方授權保持不變。FF7 名稱、設計與資產歸各自權利人所有。GaiaGIS 為獨立專案，未經 Square Enix 認可。','GPL-3.0-only は GaiaGIS 独自コードに適用され、第三者ライセンスは保持します。FF7 の名称・デザイン・資産は各権利者に帰属します。GaiaGIS は独立プロジェクトで、Square Enix の承認はありません。','GPL-3.0-only는 GaiaGIS 원본 코드에 적용되며 제삼자 라이선스는 유지됩니다. FF7 이름·디자인·자산은 각 권리자 소유입니다. GaiaGIS는 독립 프로젝트로 Square Enix의 승인을 받지 않았습니다.'],
['help.environment','Run from the project root with your Python/QGIS setup. Your FF7 installation remains read-only. See README for setup and generation instructions.','从项目根目录使用 Python/QGIS 环境运行。FF7 安装目录始终只读。配置与生成说明见 README。','從專案根目錄使用 Python/QGIS 環境執行。FF7 安裝目錄始終唯讀。設定與產生說明見 README。','プロジェクトルートで Python/QGIS 環境を使って実行してください。FF7 インストールは読み取り専用です。設定・生成手順は README にあります。','프로젝트 루트에서 Python/QGIS 환경으로 실행하세요. FF7 설치는 읽기 전용입니다. 설정·생성 방법은 README를 참조하세요.'],
] as const;
