import {appStore} from '../app/state';
import {saveSession} from '../app/saveSession';
import {workspaceLoader,loadedAsset} from '../app/assets';
// SPDX-License-Identifier: GPL-3.0-only
import {t,formatNumber,onLocaleChange} from '../i18n';
import {parseRouting,loadOptionalRouting,routeProfiles,entranceEndpoints} from '../data/routing';
import type {RoutingData,Component,Endpoint} from '../data/routing';
import type {GaiaMeta} from '../data/mesh';
import type {PoiDataset,Location} from '../data/poi';
import {searchLocations} from '../data/poi';
import type {GaiaViewer} from '../viewer/GaiaViewer';
import {mountCartography} from './cartography';
import {classifyComparison,comparisonPalette} from '../analysis/comparison';
import {evaluateTraversal} from '../data/traversal';
import {mountSpatialAnalysis} from './spatialAnalysis';
interface Route {nodes:number[];distance:number;startEntrance:string;targetEntrance:string;component:number;}
export function mountAnalysis(viewer:GaiaViewer,meta:GaiaMeta,isCurrent:()=>boolean){
  const panel=document.createElement('aside');panel.className='analysis-panel panel';panel.id='analysis-panel';panel.hidden=true;
  panel.innerHTML=`<div class="panel-heading"><h2>${t('routing.title')}</h2><button id="analysis-close" aria-label="${t('nav.close')}">×</button></div><p class="control-note">${t('routing.scope')}</p><button id="load-routing">${t('routing.load')}</button><input id="routing-file" type="file" accept=".bin" hidden/><p id="routing-status" role="status" class="control-note">${t('routing.unavailable')}</p><p id="analysis-location-status" class="control-note">${t('routing.locationsRequired')}</p><label for="route-from">${t('routing.from')}</label><input id="route-from" list="route-locations" aria-label="${t('routing.from')}"/><label for="route-to">${t('routing.to')}</label><input id="route-to" list="route-locations" aria-label="${t('routing.to')}"/><datalist id="route-locations"></datalist><label for="route-mode">${t('routing.mode')}</label><select id="route-mode"></select><label class="toggle-row"><input type="checkbox" id="route-conditional"/><span>${t('routing.conditional')}</span></label><div class="analysis-actions"><button id="show-reachable">${t('routing.reachable')}</button><button id="find-route">${t('routing.find')}</button><button id="go-route-start">${t('routing.goStart')}</button><button id="go-route-target">${t('routing.goTarget')}</button><button id="clear-analysis">${t('routing.clear')}</button></div><p id="route-result" role="status" class="control-note"></p><h3>${t('routing.reachableList')}</h3><ul id="reachable-locations"></ul>`;
  document.getElementById('app')!.append(panel);const open=document.createElement('button');open.id='open-analysis';open.textContent=t('nav.analysis');document.querySelector('footer')!.append(open);open.onclick=()=>{panel.hidden=!panel.hidden;document.querySelector('.controls')!.classList.remove('mobile-open');};
  const el=<E extends HTMLElement=HTMLElement>(id:string)=>panel.querySelector(`#${id}`) as E;el('analysis-close').onclick=()=>panel.hidden=true;
  const modes=el<HTMLSelectElement>('route-mode');for(const p of routeProfiles){const option=document.createElement('option');option.value=p.id;option.textContent=t(`mode.${p.id}`);modes.append(option);}
  for(const id of ['route-from','route-to']){const input=el(id),label=panel.querySelector(`label[for="${id}"]`)!;const block=document.createElement('div');block.className='route-endpoint';label.before(block);block.append(label,input);}el('route-result').classList.add('analysis-result');
  const componentDetails=document.createElement('details'),componentTitle=document.createElement('summary'),componentList=document.createElement('ul');componentDetails.id='route-components';componentTitle.textContent=t('routing.components',{count:0,triangles:0});componentDetails.append(componentTitle,componentList);panel.append(componentDetails);const legend=document.createElement('p');legend.className='control-note';legend.textContent=t('routing.legend');panel.append(legend);
  let graph:RoutingData|null=null,poi:PoiDataset|null=null,worker:Worker|null=null,ticket=0,seq=0,loadRevision=0,disposed=false;const pending=new Map<number,{resolve:(value:any)=>void;reject:(error:Error)=>void}>();
  const rpc=(kind:string,extra:Record<string,unknown>={})=>new Promise<any>((resolve,reject)=>{const request=++seq;pending.set(request,{resolve,reject});worker!.postMessage({request,kind,...extra});});
  let spatial:ReturnType<typeof mountSpatialAnalysis>|undefined;
  const clear=()=>{ticket++;appStore.dispatch({type:'analysis',tool:'none'});spatial?.clear();viewer.setAnalysis(null,[],null,null,null);viewer.setComparisonFlags(null);viewer.setComparedRoutes([]);const result=panel.querySelector<HTMLElement>('#comparison-results');if(result){result.replaceChildren();delete result.dataset.counts;result.dataset.routes='0';result.dataset.overlays='0';}el('route-result').textContent='';el('route-result').removeAttribute('title');panel.dataset.routeNodes='0';el('reachable-locations').replaceChildren();componentList.replaceChildren();componentTitle.textContent=t('routing.components',{count:0,triangles:0});};
  async function adopt(buffer:ArrayBuffer,revision:number){const begin=performance.now(),next=parseRouting(buffer,meta,viewer.mesh);const nextWorker=new Worker(new URL('../analysis/routing.worker.ts',import.meta.url),{type:'module'});
    try{await new Promise<void>((resolve,reject)=>{nextWorker.onmessage=({data})=>data.error?reject(new Error(data.error)):resolve();nextWorker.onerror=()=>reject(new Error(t('error.worker')));nextWorker.postMessage({request:0,kind:'init',buffer});});}catch(e){nextWorker.terminate();throw e;}
    if(disposed||!isCurrent()||revision!==loadRevision){nextWorker.terminate();return;}worker?.terminate();pending.forEach(p=>p.reject(new Error(t('error.cancelled'))));pending.clear();worker=nextWorker;worker.onmessage=({data})=>{const p=pending.get(data.request);pending.delete(data.request);if(p)data.error?p.reject(new Error(data.error)):p.resolve(data.result);};worker.onerror=()=>{for(const p of pending.values())p.reject(new Error(t('error.worker')));pending.clear();};graph=next;loadedAsset("routing",buffer.byteLength);clear();panel.dataset.loadMs=String(performance.now()-begin);el('routing-status').textContent=t('routing.loaded',{nodes:next.count,edges:next.arcs/2});el('routing-status').removeAttribute('title');}
  const file=el<HTMLInputElement>('routing-file');file.setAttribute('aria-label',t('routing.load'));el('load-routing').onclick=()=>file.click();file.onchange=async()=>{const f=file.files?.[0];if(!f)return;const revision=++loadRevision;try{if(f.name!=='gaia-routing.bin'||f.size>100_000_000)throw new Error(t('routing.badFile'));await adopt(await f.arrayBuffer(),revision);}catch(error){if(revision===loadRevision){el('routing-status').textContent=t('error.dataset');el('routing-status').title=String(error);}}file.value='';};
  let playerStart:Location|null=null,playerNode=-1;
  const choose=(id:string)=>id==='route-from'&&playerStart&&el<HTMLInputElement>(id).value===playerStart.display_name?playerStart:poi?searchLocations(poi.locations,el<HTMLInputElement>(id).value,'all')[0]??null:null;
  const endpoints=(l:Location)=>l===playerStart?[{node:playerNode,entrance:'session-player'}]:entranceEndpoints(graph!,poi!.entrances.filter(e=>e.location_id===l.id));
  const acceptPlayer=(event:Event)=>{const d=(event as CustomEvent).detail,b=saveSession.slot?.binding;if(!graph||!b||!d||!Number.isInteger(d.node)||d.node<0||d.node>=graph.count||JSON.stringify(d.geographic)!==JSON.stringify(b.geographic))return;clear();playerNode=d.node;playerStart={id:'session-player',display_name:t('save27.position'),longitude:b.geographic[0],latitude:b.geographic[1],height:0} as Location;el<HTMLInputElement>('route-from').value=t('save27.position');el('route-result').textContent=t('save27.previewState');};
  document.addEventListener('gaiagis:save-route',acceptPlayer);
  const stopSave=saveSession.subscribe(()=>{if(playerStart){playerStart=null;playerNode=-1;el<HTMLInputElement>('route-from').value='';clear();}});
  async function analyze(route:boolean){if(!graph||!poi){el('route-result').textContent=t(!graph?'routing.unavailable':'routing.locationsRequired');return;}const start=choose('route-from'),target=choose('route-to');if(!start||route&&!target){el('route-result').textContent=t('routing.choose');return;}const stamp=++ticket,mode=modes.value,conditional=el<HTMLInputElement>('route-conditional').checked;el('route-result').textContent=t('routing.busy');const begin=performance.now();try{const result=await rpc('components',{mode,conditional}) as {labels:Int32Array;components:Component[]};if(stamp!==ticket||!isCurrent())return;
      const starts=endpoints(start),ids=new Set(starts.map(e=>result.labels[e.node]).filter(i=>i>=0));const flags=new Uint8Array(graph.count);for(let i=0;i<flags.length;i++)flags[i]=Number(ids.has(result.labels[i]));const reachable=new Set<string>();const list=el('reachable-locations');list.replaceChildren();for(const l of poi.locations){const e=endpoints(l).find(e=>ids.has(result.labels[e.node]));if(!e)continue;reachable.add(l.id);const row=document.createElement('li');row.textContent=t('routing.locationRow',{name:l.display_name,entrance:e.entrance,component:result.labels[e.node]});list.append(row);}
      const initial=t('routing.components',{count:result.components.length,triangles:flags.reduce((s,v)=>s+v,0)});el('route-result').textContent=initial;componentTitle.textContent=initial;componentList.replaceChildren();const locationCounts=new Map<number,Set<string>>();for(const l of poi.locations)for(const e of endpoints(l)){const id=result.labels[e.node];if(id>=0){if(!locationCounts.has(id))locationCounts.set(id,new Set());locationCounts.get(id)!.add(l.id);}}for(const c of result.components){const row=document.createElement('li');row.textContent=t('message.component',{id:c.id,triangles:c.triangles,area:formatNumber(c.area/1e6,2),locations:locationCounts.get(c.id)?.size??0});componentList.append(row);}viewer.setAnalysis(flags,[],start.id,target?.id??null,reachable);panel.dataset.componentMs=String(performance.now()-begin);
      if(route&&target){const query=performance.now(),path=await rpc('route',{mode,conditional,starts,targets:endpoints(target)}) as Route|null;if(stamp!==ticket||!isCurrent())return;panel.dataset.queryMs=String(performance.now()-query);el('route-result').textContent=path?t('routing.result',{km:formatNumber(path.distance/1000,2),steps:path.nodes.length-1})+'\n'+t('routing.entrances',{from:path.startEntrance,to:path.targetEntrance}):t('routing.noRoute');panel.dataset.routeNodes=String(path?.nodes.length??0);spatial?.setRoute(path?.nodes??[],path?.distance??0);viewer.setAnalysis(flags,path?.nodes??[],start.id,target.id,reachable);}
    }catch(error){if(stamp===ticket){el('route-result').textContent=t('error.dataset');el('route-result').title=String(error);}}}
  el('show-reachable').onclick=()=>void analyze(false);el('find-route').onclick=()=>void analyze(true);el('clear-analysis').onclick=clear;el('go-route-start').onclick=()=>{const l=choose('route-from');if(l)viewer.flyToLocation(l.longitude,l.latitude);};el('go-route-target').onclick=()=>{const l=choose('route-to');if(l)viewer.flyToLocation(l.longitude,l.latitude);};modes.onchange=clear;el('route-conditional').onchange=clear;
  const acceptPoi=(event:Event)=>{poi=(event as CustomEvent<PoiDataset|null>).detail;clear();el('analysis-location-status').textContent=poi?'':t('routing.locationsRequired');el('route-locations').replaceChildren();for(const l of poi?.locations??[]){const option=document.createElement('option');option.value=l.display_name;el('route-locations').append(option);}};document.addEventListener('gaiagis:poi',acceptPoi);
  const unsubscribe=onLocaleChange(()=>{if(graph)el('routing-status').textContent=t('routing.loaded',{nodes:graph.count,edges:graph.arcs/2});});const revision=loadRevision;void loadOptionalRouting(meta,viewer.mesh).then(next=>{if(next&&!disposed&&isCurrent()&&revision===loadRevision)return adopt(next.buffer,revision);}).catch(e=>{if(!disposed&&revision===loadRevision){el('routing-status').textContent=t('error.dataset');el('routing-status').title=String(e);}});
  const cartography=mountCartography(viewer,panel),compare=cartography.compare;
  const selects=['a','b'].map((name,index)=>{const label=document.createElement('label'),s=document.createElement('select');s.id=`compare-movement-${name}`;label.htmlFor=s.id;label.textContent=t(index?'compare.modeB':'compare.modeA');for(const p of routeProfiles){const o=document.createElement('option');o.value=p.id;o.textContent=t(`mode.${p.id}`);s.append(o);}s.value=index?'buggy':'foot';s.onchange=clear;compare.append(label,s);return s;});
  const limit=document.createElement('p');limit.className='control-note';limit.textContent=t('compare.limit');compare.append(limit);const scope=document.createElement('p');scope.className='control-note';scope.textContent=t('routing.scope');compare.append(scope);
  const occupancyScope=document.createElement('p');occupancyScope.className='control-note';occupancyScope.textContent=t('compare.occupancyScope');compare.append(occupancyScope);
  const result=document.createElement('div');result.id='comparison-results';result.setAttribute('role','status');
  const action=(key:string,id:string,fn:()=>void)=>{const b=document.createElement('button');b.id=id;b.textContent=t(key);b.onclick=fn;compare.append(b);};
  const classified=(a:Uint8Array,b:Uint8Array)=>{const c=classifyComparison(a,b);viewer.setAnalysis(null,[],null,null,null);viewer.setComparisonFlags(c.flags);viewer.setComparedRoutes([]);result.replaceChildren();const p=document.createElement('p');p.textContent=t('compare.classes',{neither:c.counts[0],a:c.counts[1],b:c.counts[2],both:c.counts[3]});result.append(p);result.dataset.counts=JSON.stringify(c.counts);for(const [i,key]of ['neither','onlyA','onlyB','both'].entries()){const row=document.createElement('div'),swatch=document.createElement('i');row.className='legend-row';swatch.style.background=comparisonPalette[i];row.append(swatch,document.createTextNode(t(`compare.${key}`)));result.append(row);}};
  action('compare.traversal','compare-traversal',()=>{ticket++;const flags=selects.map(s=>{const f=new Uint8Array(viewer.mesh.sourceTriangleCount);for(let i=0;i<f.length;i++){const a=viewer.mesh.attributes(i);f[i]=Number(evaluateTraversal(s.value,a.terrain,a.script??0,a.origin).state==='allowed');}return f;});classified(flags[0],flags[1]);});
  async function compareGraph(routes:boolean){if(!graph||!poi){result.textContent=t(!graph?'routing.unavailable':'routing.locationsRequired');return;}const start=choose('route-from'),target=choose('route-to');if(!start||routes&&!target){result.textContent=t('routing.choose');return;}const stamp=++ticket,conditional=el<HTMLInputElement>('route-conditional').checked,starts=endpoints(start),begin=performance.now();result.textContent=t('routing.busy');try{if(!routes){const flags:Uint8Array[]=[];for(const s of selects){const c=await rpc('components',{mode:s.value,conditional}) as {labels:Int32Array};if(stamp!==ticket||!isCurrent())return;const ids=new Set(starts.map(e=>c.labels[e.node]).filter(id=>id>=0)),f=new Uint8Array(graph.count);for(let i=0;i<f.length;i++)f[i]=Number(ids.has(c.labels[i]));flags.push(f);}classified(flags[0],flags[1]);}else{viewer.setComparisonFlags(null);viewer.setAnalysis(null,[],start.id,target!.id,null);viewer.setComparedRoutes([]);const rows:{mode:string;path:Route|null}[]=[];for(const mode of routeProfiles){const path=await rpc('route',{mode:mode.id,conditional,starts,targets:endpoints(target!)}) as Route|null;if(stamp!==ticket||!isCurrent())return;rows.push({mode:mode.id,path});}result.replaceChildren();result.dataset.routes=String(rows.length);const selected=new Set<number>();rows.forEach(({mode,path},index)=>{const card=document.createElement('section');card.className='compared-route';card.dataset.mode=mode;const h=document.createElement('h4');h.textContent=t(`mode.${mode}`);card.append(h);const dl=document.createElement('dl');dl.className='property-list';const values:[string,string][]=[['compare.exists',t(path?'compare.exists':'compare.none')],['compare.nodes',String(path?.nodes.length??0)],['compare.entrance',path?`${path.startEntrance} → ${path.targetEntrance}`:'—'],['compare.distance',path?formatNumber(path.distance/1000,2):'—'],['compare.component',path?String(path.component):'—']];for(const [key,value]of values){const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t(key);dd.textContent=value;d.append(dt,dd);dl.append(d);}card.append(dl);if(path){const label=document.createElement('label'),input=document.createElement('input'),text=document.createElement('span');input.type='checkbox';input.dataset.routeOverlay=String(index);text.textContent=t('compare.overlay');label.className='toggle-row';label.append(input,text);card.append(label);input.onchange=()=>{if(input.checked&&selected.size>=3){input.checked=false;limit.textContent=t('compare.limit');return;}if(input.checked)selected.add(index);else selected.delete(index);viewer.setComparedRoutes([...selected].map(i=>rows[i].path!.nodes));result.dataset.overlays=String(selected.size);};}result.append(card);});}panel.dataset.comparisonMs=String(performance.now()-begin);}catch(error){if(stamp===ticket){result.textContent=t('error.dataset');result.title=String(error);}}}
  action('compare.reachable','compare-reachable',()=>void compareGraph(false));action('compare.routes','compare-routes',()=>void compareGraph(true));action('compare.clear','compare-clear',clear);compare.append(result);
  for(const id of ['route-from','route-to'])el(id).addEventListener('input',clear);
  workspaceLoader.register("routing",async files=>adopt(await files[0].arrayBuffer(),++loadRevision));
  spatial=mountSpatialAnalysis(viewer,meta,panel,rpc,()=>{const start=choose('route-from');return graph&&poi&&start?{mode:modes.value,conditional:el<HTMLInputElement>('route-conditional').checked,starts:endpoints(start)}:null;});
  return {dispose(){stopSave();document.removeEventListener('gaiagis:save-route',acceptPlayer);disposed=true;ticket++;spatial?.dispose();cartography.dispose();unsubscribe();worker?.terminate();pending.forEach(p=>p.reject(new Error(t('error.cancelled'))));pending.clear();document.removeEventListener('gaiagis:poi',acceptPoi);panel.remove();open.remove();}};
}
