import '../styles/atlas.css';
// SPDX-License-Identifier: GPL-3.0-only
import curated from '../../../src/gaiagis/atlas_data/content.json';
import {appStore} from '../app/state';
import {registerNavigation,clearNavigation,searchNavigation,setNavigationSelection} from '../app/navigation';
import {workspaceLoader} from '../app/assets';
import {ResourceScope} from '../app/resources';
import {locale,onLocaleChange,t} from '../i18n';
import {atlasKinds,parseAtlasContent,parseAtlasPack,validateAtlasPoi,resolveBinding,atlasAnchor,spoilerVisible,searchAtlas} from '../data/atlas';
import type {AtlasContent,AtlasEntity,AtlasPack,AtlasBinding,AtlasCategory,Spoiler} from '../data/atlas';
import type {PoiDataset,Location} from '../data/poi';
import type {GaiaViewer} from '../viewer/GaiaViewer';

export function mountAtlas(viewer?:GaiaViewer,getPoi?:()=>PoiDataset|null){
 const scope=new ResourceScope(),started=performance.now();let content:AtlasContent=parseAtlasContent(curated),pack:AtlasPack|null=null,poi=getPoi?.()??null,active:string|null=null,embedded=false,revision=0;
 const input=document.getElementById('location-search') as HTMLInputElement,results=document.getElementById('location-results')!;
 const controls=document.createElement('details');controls.id='atlas-filters';const controlsTitle=document.createElement('summary');controlsTitle.textContent=t('atlas.title');controls.append(controlsTitle);document.querySelector('.locations-controls')!.append(controls);scope.own(()=>controls.remove());
 const select=(id:string,key:string,values:string[])=>{const label=document.createElement('label'),field=document.createElement('select');field.id=id;label.htmlFor=id;label.textContent=t(key);for(const value of values){const o=document.createElement('option');o.value=value;o.textContent=t('atlas.'+(value==='unknown'?'unknownRegion':value));field.append(o);}controls.append(label,field);field.onchange=refresh;return field;};
 const category=select('atlas-category','atlas.category',['all','places','secrets','collectibles']);const region=select('atlas-region','atlas.region',['all','eastern','western','northern','wutai','islands','underwater','unknown']);const kind=select('atlas-kind','atlas.kind',['all',...atlasKinds]);const spoilers=select('atlas-spoilers','atlas.spoilers',['hide-major','show-all','hide-all']);
 const note=document.createElement('p');note.className='control-note';note.textContent=t('atlas.offline');controls.append(note);
 const layers=document.createElement('details');layers.id='atlas-layers';const layersTitle=document.createElement('summary');layersTitle.textContent=t('atlas.title');layers.append(layersTitle);document.querySelector('.controls')!.append(layers);scope.own(()=>layers.remove());
 const toggles=new Map<string,HTMLInputElement>();for(const name of ['places','secrets','collectibles']){const label=document.createElement('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.id='atlas-'+name;label.htmlFor=checkbox.id;label.append(checkbox,document.createTextNode(t('atlas.'+name)));layers.append(label);checkbox.onchange=refresh;toggles.set(name,checkbox);}
 const mode=()=>spoilers.value as 'hide-major'|'show-all'|'hide-all';const visible=(level:Spoiler)=>spoilerVisible(level,mode());
 const entity=(id:string)=>content.entities.find(e=>e.id===id);
 const binding=(e:AtlasEntity):AtlasBinding=>pack?.bindings[e.id]??resolveBinding(e,poi);
 function section(target:HTMLElement,key:string,open=false){const detail=document.createElement('details'),summary=document.createElement('summary');detail.open=open;summary.textContent=t(key);detail.append(summary);target.append(detail);return detail;}
 const paragraph=(parent:HTMLElement,text:string)=>{const node=document.createElement('p');node.textContent=text;parent.append(node);return node;};
 function card(e:AtlasEntity,target:HTMLElement){
  const old=document.getElementById('atlas-card');old?.remove();const card=document.createElement('section');card.id='atlas-card';card.className='atlas-card';card.dataset.entity=e.id;target.append(card);
  if(!visible(e.spoilerLevel)){paragraph(card,t('atlas.hidden'));return;}
  const title=document.createElement('h3');title.textContent=t('atlas.title')+' · '+e.localizedNames[locale()];card.append(title);
  paragraph(section(card,'atlas.overview',true),e.summary[locale()]);paragraph(section(card,'atlas.typeRegion'),t('atlas.'+e.kind)+' · '+t('atlas.'+(e.region==='unknown'?'unknownRegion':e.region)));
  for(const key of ['access','gameplay'] as const){const group=section(card,'atlas.'+key),facts=e.facts.filter(f=>f.kind===key&&visible(f.spoilerLevel));for(const f of facts)paragraph(group,f.text[locale()]);if(!facts.length)paragraph(group,t('atlas.unknown'));}
  const discoveries=section(card,'atlas.discoveries'),ids=[...e.secrets,...e.collectibles];const children=ids.map(entity).filter((child):child is AtlasEntity=>!!child&&visible(child.spoilerLevel));
  for(const child of children){const button=document.createElement('button');button.textContent=child.localizedNames[locale()];button.dataset.atlasEntity=child.id;button.onclick=()=>inspect(child);discoveries.append(button);}if(!children.length)paragraph(discoveries,t('atlas.unknown'));if(children.length<ids.length)paragraph(discoveries,t('atlas.hidden'));
  const b=binding(e),spatial=section(card,'atlas.precision',true);paragraph(spatial,t('atlas.'+b.precision));paragraph(spatial,t('atlas.evidence')+': '+t('atlas.'+b.evidence));if(b.fieldNames.length)paragraph(spatial,b.fieldNames.join(', '));paragraph(spatial,t(b.marker?'atlas.anchorNote':b.locationId?'atlas.parentNote':'atlas.unresolvedNote'));
  const anchor=atlasAnchor(b,poi),parent=atlasAnchor(b,poi,true);if(viewer&&(anchor||parent)){const button=document.createElement('button');button.id='atlas-fly';button.textContent=t(anchor?'atlas.fly':'atlas.flyParent');button.onclick=()=>{const context=anchor??parent!;viewer.flyToLocation(context.entrance.longitude,context.entrance.latitude);};spatial.append(button);if(!anchor)paragraph(spatial,t('atlas.parentLocation')+' · '+parent!.location.display_name);}
  const related=section(card,'atlas.related');for(const id of e.relatedEntities){const child=entity(id);if(!child||!visible(child.spoilerLevel))continue;const button=document.createElement('button');button.textContent=child.localizedNames[locale()];button.onclick=()=>inspect(child);related.append(button);}if(!related.querySelector('button'))paragraph(related,t('atlas.unknown'));
  const provenance=section(card,'atlas.sources');paragraph(provenance,t('atlas.sourceNote'));const refs=new Set([...e.sources,...e.facts.filter(f=>visible(f.spoilerLevel)).flatMap(f=>f.sources)]);for(const id of refs){const source=content.sources.find(s=>s.id===id)!;const link=document.createElement('a');link.textContent=source.provider+' · '+source.title;link.href=source.url;link.target='_blank';link.rel='noopener noreferrer';provenance.append(link);paragraph(provenance,t('atlas.reviewed')+': '+source.reviewed);}
 }
 function inspect(e:AtlasEntity){
  if(!visible(e.spoilerLevel)||appStore.state.map.id!=='WM0'||appStore.state.explorer.phase!=='idle')return;viewer?.clearSelection();active=e.id;embedded=false;const b=binding(e),anchor=atlasAnchor(b,poi);setNavigationSelection(anchor);viewer?.selectLocation(null);if(anchor)viewer?.selectLocation(anchor.location.id,anchor.entrance);
  const detail=document.getElementById('selection-details')!;detail.hidden=false;detail.replaceChildren();delete detail.dataset.location;delete detail.dataset.entrance;delete detail.dataset.sourceTriangle;delete detail.dataset.origin;detail.dataset.atlas=e.id;document.getElementById('selection-empty')!.hidden=true;document.getElementById('inspector-title')!.textContent=t('atlas.title');
  appStore.dispatch({type:'select',selection:{kind:'atlas',id:e.id,mapId:'WM0',...(anchor?{geographicPoint:[anchor.entrance.longitude,anchor.entrance.latitude,anchor.entrance.height] as [number,number,number]}:{})}});card(e,detail);results.replaceChildren();input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');document.getElementById('integrated-panel')?.classList.remove('open');document.getElementById('app-menu')?.setAttribute('aria-expanded','false');
 }
 function refresh(){
  const entities=searchAtlas(content,'',locale(),mode(),category.value as AtlasCategory,region.value,kind.value);const visibleIds=new Set(entities.map(e=>e.id));
  registerNavigation('atlas',entities.map(e=>({id:'atlas:'+e.id,kind:'atlas',name:e.localizedNames[locale()],aliases:[e.canonicalName,...Object.values(e.localizedNames),...e.aliases,e.kind,e.region,...e.tags,t('atlas.'+e.kind),t('atlas.'+(e.region==='unknown'?'unknownRegion':e.region)),...e.collectibles.map(entity).filter((e):e is AtlasEntity=>!!e&&visible(e.spoilerLevel)).flatMap(e=>[e.canonicalName,...Object.values(e.localizedNames),...e.aliases])],mapId:'WM0',navigate:()=>inspect(e)})));
  input.disabled=false;const searchLabel=document.querySelector('label[for="location-search"]');if(searchLabel)searchLabel.textContent=t('atlas.search');input.placeholder=t('atlas.search');input.setAttribute('aria-label',t('atlas.search'));
  const markers:Location[]=[];for(const e of entities){const b=binding(e),anchor=atlasAnchor(b,poi);if(!anchor)continue;const show=toggles.get('places')!.checked&&e.tags.includes('place')||toggles.get('secrets')!.checked&&e.tags.includes('secret')||toggles.get('collectibles')!.checked&&e.collectibles.some(id=>{const child=entity(id);return child&&visible(child.spoilerLevel);});if(!show)continue;markers.push({...anchor.location,id:e.id,display_name:e.localizedNames[locale()],name:e.canonicalName});}
  viewer?.setAtlasLocations(markers);viewer?.setAtlasDisplay(appStore.state.map.id==='WM0'&&appStore.state.explorer.phase==='idle');layers.hidden=!viewer||!poi;
  if(active){const e=entity(active);if(e&&document.getElementById('atlas-card'))card(e,document.getElementById('selection-details')!);if(e&&!visible(e.spoilerLevel)&&appStore.state.selection?.kind==='atlas'){setNavigationSelection(null);appStore.dispatch({type:'select',selection:null});active=null;}}
  controls.dataset.entityCount=String(visibleIds.size);if(!viewer)drawStandalone();
 }
 let standaloneMatches:ReturnType<typeof searchNavigation>=[],standaloneIndex=-1;
 function drawStandalone(){standaloneMatches=searchNavigation(input.value).filter(e=>e.kind==='atlas');results.replaceChildren();standaloneIndex=-1;for(const [i,e] of standaloneMatches.slice(0,60).entries()){const button=document.createElement('button');button.id='atlas-result-'+i;button.dataset.navigationId=e.id;button.className='location-result';button.setAttribute('role','option');button.setAttribute('aria-selected','false');button.textContent=e.name+' · '+t('atlas.title');button.onclick=e.navigate;results.append(button);}input.setAttribute('aria-expanded','true');}
 if(!viewer){scope.listen(input,'input',drawStandalone);scope.listen(input,'focus',drawStandalone);scope.listen(input,'keydown',((event:KeyboardEvent)=>{if(!['ArrowDown','ArrowUp','Enter','Escape'].includes(event.key))return;event.preventDefault();event.stopPropagation();if(event.key==='Escape'){results.replaceChildren();input.setAttribute('aria-expanded','false');return;}if(event.key==='Enter'){standaloneMatches[Math.max(0,standaloneIndex)]?.navigate();return;}standaloneIndex=Math.max(0,Math.min(Math.min(60,standaloneMatches.length)-1,standaloneIndex+(event.key==='ArrowDown'?1:-1)));for(const [i,b]of [...results.querySelectorAll('button')].entries()){b.setAttribute('aria-selected',String(i===standaloneIndex));if(i===standaloneIndex){input.setAttribute('aria-activedescendant',b.id);b.scrollIntoView({block:'nearest'});}}}) as EventListener);}
 scope.listen(document,'gaiagis:poi',((event:CustomEvent<PoiDataset|null>)=>{poi=event.detail;pack=null;refresh();}) as EventListener);
 scope.listen(document,'gaiagis-location-inspect',((event:CustomEvent<string>)=>{const e=content.entities.find(e=>e.spatialBinding.kind==='location'&&e.spatialBinding.locationId===event.detail);if(e){active=e.id;embedded=true;card(e,document.getElementById('selection-details')!);}}) as EventListener);
 scope.own(workspaceLoader.register('atlas',async files=>{const attempt=++revision,file=files[0],begin=performance.now();if(file.name!=='gaia-atlas.json'||file.size>2_000_000)throw Error('Atlas size/name');const next=parseAtlasPack(JSON.parse(await file.text()));if(!poi)throw Error('Atlas requires matching POI identity');validateAtlasPoi(next,poi);if(attempt!==revision)return;pack=next;content=next.content;refresh();controls.dataset.loadMs=String(performance.now()-begin);}));
 scope.own(appStore.subscribe(s=>{viewer?.setAtlasDisplay(s.map.id==='WM0'&&s.explorer.phase==='idle');if(s.selection?.kind!=='atlas'&&!['location','entrance'].includes(s.selection?.kind??'')){active=null;document.getElementById('atlas-card')?.remove();}if(!embedded&&s.selection?.kind==='atlas'&&active!==s.selection.id)active=null;}));
 scope.own(onLocaleChange(refresh));if(viewer)viewer.onAtlas=id=>{const e=entity(id);if(e)inspect(e);};refresh();controls.dataset.initMs=String(performance.now()-started);
 return {dispose(){revision++;clearNavigation('atlas');viewer?.setAtlasLocations([]);if(viewer)viewer.onAtlas=()=>{};scope.dispose();document.getElementById('atlas-card')?.remove();}};
}
