// SPDX-License-Identifier: GPL-3.0-only
import {t,formatNumber,onLocaleChange} from '../i18n';
import {GRID_FIXED} from '../analysis/adaptive';
import {measureDistance,measureArea,validPoint} from '../analysis/sphere';
import {distortion} from '../analysis/distortion';
import {projectionRegistry} from '../projections/registry';
import type {GeoPoint,ProjectionId} from '../projections/Projection';
import type {GaiaViewer} from '../viewer/GaiaViewer';

/** Tools own only small analysis state. Source datasets and projection formulas remain authoritative. */
export function mountCartography(viewer:GaiaViewer,panel:HTMLElement){
 const group=(key:string,id:string)=>{const d=document.createElement('details'),s=document.createElement('summary');d.className='analysis-group';d.id=id;s.textContent=t(key);d.append(s);panel.append(d);return d;};
 const row=(host:HTMLElement,key:string,node:HTMLElement)=>{const l=document.createElement('label');l.textContent=t(key);if(node.id)l.htmlFor=node.id;host.append(l,node);return node;};
 const button=(host:HTMLElement,key:string,id:string,action:()=>void)=>{const b=document.createElement('button');b.textContent=t(key);b.id=id;b.onclick=action;host.append(b);return b;};
 const note=(host:HTMLElement,key:string)=>{const p=document.createElement('p');p.className='control-note';p.textContent=t(key);host.append(p);return p;};
 const check=(host:HTMLElement,key:string,id:string,action:(v:boolean)=>void,checked=false)=>{const l=document.createElement('label'),i=document.createElement('input'),s=document.createElement('span');l.className='toggle-row';i.type='checkbox';i.id=id;i.checked=checked;s.textContent=t(key);i.onchange=()=>action(i.checked);l.append(i,s);host.append(l);return i;};
 const coordinate=(host:HTMLElement,prefix:string)=>{const inputs=document.createElement('div');inputs.className='coordinate-inputs';const lon=document.createElement('input'),lat=document.createElement('input');for(const [i,id,key]of [[lon,'lon','ui.longitude'],[lat,'lat','ui.latitude']] as const){i.type='number';i.step='any';i.value='0';i.min=id==='lat'?'-90':'-180';i.max=id==='lat'?'90':'180';i.id=`${prefix}-${id}`;i.setAttribute('aria-label',t(key));row(inputs,key,i);}host.append(inputs);return ()=>{if(!lon.value.trim()||!lat.value.trim())throw new Error('Empty coordinate');return validPoint([Number(lon.value),Number(lat.value),0]);};};
 const grid=document.createElement('div');grid.className='adaptive-controls';document.getElementById('graticule')!.closest('label')!.after(grid);
 const spacing=document.createElement('select');spacing.id='graticule-spacing';for(const value of ['auto',...GRID_FIXED,'off']){const o=document.createElement('option');o.value=String(value);o.textContent=typeof value==='number'?`${value}°`:t(`grid.${value}`);spacing.append(o);}row(grid,'grid.mode',spacing);
 const syncGrid=()=>{const value=spacing.value;viewer.setGridMode(value==='auto'||value==='off'?value:Number(value));(document.getElementById('graticule') as HTMLInputElement).checked=value!=='off';document.getElementById('toggle-graticule')!.setAttribute('aria-pressed',String(value!=='off'));};spacing.onchange=syncGrid;
 const legacy=()=>{spacing.value=(document.getElementById('graticule') as HTMLInputElement).checked?(spacing.value==='off'?'auto':spacing.value):'off';};
 document.getElementById('graticule')!.addEventListener('change',legacy);const toolbar=()=>setTimeout(legacy,0);document.getElementById('toggle-graticule')!.addEventListener('click',toolbar);
 check(grid,'grid.minor','graticule-minor',v=>viewer.setGridMinor(v),true);const gridStatus=note(grid,'grid.auto');gridStatus.id='graticule-status';syncGrid();
 // Keep the established routing IDs, grouping their controls without changing their behavior.
 panel.querySelector('h2')!.textContent=t('analysis.title');const routing=group('analysis.routing','analysis-routing');routing.open=true;
 for(const node of [...panel.children])if(node!==routing&&!node.classList.contains('panel-heading'))routing.append(node);
 const common=document.createElement('div');common.className='analysis-endpoints';routing.before(common);for(const selector of ['label[for="route-from"]','#route-from','label[for="route-to"]','#route-to','#route-locations'])common.append(panel.querySelector(selector)!);
 common.append(panel.querySelector('#route-conditional')!.parentElement!);
 const measurement=group('analysis.measure','analysis-measurement'),projection=group('analysis.projection','analysis-projection'),compare=group('analysis.compare','analysis-compare');
 for(const d of [routing,measurement,projection,compare])d.addEventListener('toggle',()=>{if(d.open)for(const other of [routing,measurement,projection,compare])if(other!==d)other.open=false;common.hidden=!routing.open&&!compare.open;});
 note(measurement,'measure.scope');note(measurement,'measure.hint');const type=document.createElement('select');type.id='measure-type';for(const value of ['distance','area']){const o=document.createElement('option');o.value=value;o.textContent=t(`measure.${value}`);type.append(o);}measurement.append(type);
 let points:GeoPoint[]=[],drawing=false;const result=document.createElement('p'),list=document.createElement('ol');result.id='measurement-result';result.className='control-note';result.setAttribute('role','status');list.id='measurement-segments';
 const renderMeasurement=()=>{list.replaceChildren();measurement.dataset.points=String(points.length);start.setAttribute('aria-pressed',String(drawing));viewer.captureMeasurement=drawing;try{const distance=measureDistance(points);measurement.dataset.distance=String(distance.total);measurement.dataset.area='';viewer.setMeasurement(points,type.value==='area'&&points.length>=3);if(type.value==='area'&&points.length>=3){const area=measureArea(points);measurement.dataset.area=String(area.area);result.textContent=t('measure.resultArea',{area:formatNumber(area.area/1e6,2),percent:formatNumber(area.percent,5)});}else result.textContent=t('measure.total',{km:formatNumber(distance.total/1000,3)});for(let i=0;i<distance.segments.length;i++){const li=document.createElement('li');li.textContent=t('measure.segment',{index:i+1,km:formatNumber(distance.segments[i]/1000,3)});list.append(li);}const count=document.createElement('li');count.textContent=t('measure.points',{count:points.length});list.prepend(count);result.removeAttribute('title');}catch(error){result.textContent=t('measure.invalid');result.title=String(error);viewer.setMeasurement([]);measurement.dataset.area='';}};
 const actions=document.createElement('div');actions.className='analysis-actions';measurement.append(actions);const start=button(actions,'measure.start','measure-start',()=>{drawing=true;renderMeasurement();});button(actions,'measure.finish','measure-finish',()=>{drawing=false;renderMeasurement();});button(actions,'measure.undo','measure-undo',()=>{points.pop();renderMeasurement();});button(actions,'measure.clear','measure-clear',()=>{points=[];drawing=false;renderMeasurement();});
 const exact=coordinate(measurement,'measure');const add=(p:GeoPoint)=>{if(points.length>=512){result.textContent=t('measure.invalid');return;}points.push(validPoint(p));renderMeasurement();};button(measurement,'measure.add','measure-add',()=>{try{add(exact());}catch(e){result.textContent=t('measure.invalid');result.title=String(e);}});note(measurement,'measure.need');measurement.append(result,list);type.onchange=renderMeasurement;viewer.onGeographicPick=p=>{if(drawing)add(p);};renderMeasurement();
 note(projection,'distortion.scope');check(projection,'distortion.tissot','show-tissot',v=>viewer.setTissot(v));let follow=true,probe:GeoPoint=[0,0,0];const following=check(projection,'distortion.follow','distortion-follow',v=>{follow=v;renderMetrics();},true),exactProbe=coordinate(projection,'distortion');button(projection,'distortion.probe','distortion-probe',()=>{try{probe=exactProbe();follow=false;following.checked=false;renderMetrics();}catch(e){metrics.textContent=t('measure.invalid');metrics.title=String(e);}});const metrics=document.createElement('dl');metrics.id='distortion-metrics';metrics.className='property-list';projection.append(metrics);const sanity=note(projection,'distortion.sanity');
 const renderMetrics=()=>{const p=follow?viewer.viewState().center:probe,m=follow&&viewer.viewState().centerResolved===false?null:distortion(viewer.projectionId,p[0],p[1],viewer.context);metrics.replaceChildren();projection.dataset.probe=`${p[0]},${p[1]}`;projection.dataset.areaScale=m?String(m.areaScale):'';sanity.hidden=!['equal-earth','mollweide','sinusoidal','gall-peters','laea'].includes(viewer.projectionId)||!m;if(!m){const info=document.createElement('p');info.textContent=t('distortion.unavailable');metrics.append(info);return;}for(const [key,value]of [['area',m.areaScale],['max',m.maxScale],['min',m.minScale],['angle',m.angularDeformation],['parallel',m.parallelScale],['meridional',m.meridionalScale]] as const){const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t(`distortion.${key}`);dd.textContent=formatNumber(value,5)+(key==='angle'?'°':'');d.append(dt,dd);metrics.append(d);}sanity.dataset.pass=String(Math.abs(m.areaScale-1)<.005);};
 const a=document.createElement('select'),b=document.createElement('select');a.id='compare-projection-a';b.id='compare-projection-b';for(const p of Object.values(projectionRegistry))for(const select of [a,b]){const option=document.createElement('option');option.value=p.id;option.textContent=t(`projection.${p.id}`);select.append(option);}b.value='equal-earth';row(compare,'compare.a',a);row(compare,'compare.b',b);const enabled=check(compare,'compare.projections','compare-projections',v=>viewer.setProjectionComparison(v?b.value as ProjectionId:null));a.onchange=()=>{const existing=document.getElementById('projection') as HTMLSelectElement;existing.value=a.value;existing.dispatchEvent(new Event('change'));};b.onchange=()=>{if(enabled.checked)viewer.setProjectionComparison(b.value as ProjectionId);};note(compare,'compare.linked');
 let last=-Infinity;viewer.onViewChange=()=>{if(performance.now()-last<200)return;last=performance.now();a.value=viewer.projectionId;gridStatus.textContent=t('grid.actual',{interval:formatNumber(viewer.diagnostics.gridInterval,2),pixels:formatNumber(viewer.diagnostics.gridSpacingPx,0)});gridStatus.dataset.interval=String(viewer.diagnostics.gridInterval);gridStatus.dataset.regenerations=String(viewer.diagnostics.gridRegenerations);if(projection.open)renderMetrics();};
 const unsub=onLocaleChange(()=>{renderMeasurement();renderMetrics();});renderMetrics();
 return {compare,dispose(){unsub();viewer.captureMeasurement=false;viewer.onGeographicPick=()=>{};viewer.onViewChange=()=>{};viewer.setProjectionComparison(null);document.getElementById('graticule')?.removeEventListener('change',legacy);document.getElementById('toggle-graticule')?.removeEventListener('click',toolbar);grid.remove();}};
}
