import {navigationActions} from '../app/navigationActions';
import {legendRow} from './legend';
// SPDX-License-Identifier: GPL-3.0-only
import '../styles/discovery.css';
import {appStore} from '../app/state';
import {findNavigation,navigationEntries} from '../app/navigation';
import type {NavigationEntry} from '../app/navigation';
import {userStateStorage} from '../app/userState';
import type {IdentityTarget,LocalView,Bookmark,TourStop,UserTour} from '../app/userState';
import {layerDefinitions,defaultOpacities,defaultVisibility,layerAvailable,visibilityDefinitions} from '../app/layers';
import type {LayerId,VisibilityId} from '../app/layers';
import {decodeShare,encodeShare,isPublicTarget} from '../app/shareState';
import {NearbyIndex} from '../navigation/nearby';
import type {NearbyAnchor} from '../navigation/nearby';
import {TourPlayback,RoutePlayback} from '../navigation/playback';
import {localScreenScale,screenGeographic} from '../navigation/scale';
import {locale,setLocale,t,onLocaleChange,formatNumber} from '../i18n';
import type {GaiaViewer} from '../viewer/GaiaViewer';
import type {NativeViewer} from '../viewer/NativeViewer';
import type {MapId} from '../data/nativeMaps';
import type {GeoPoint} from '../projections/Projection';
import {ResourceScope} from '../app/resources';

export function mountDiscovery(getViewer:()=>GaiaViewer|undefined,getNative:()=>NativeViewer|undefined,switchMap:(id:MapId)=>Promise<void>){
 const scope=new ResourceScope(),storage=userStateStorage(),root=document.createElement('section');root.id='discovery';
 const uid=()=>crypto.randomUUID();let disposed=false,restoreGeneration=0,historyKey='',tour:TourPlayback|null=null,draft:TourStop[]=[],index=new NearbyIndex([]),origin:GeoPoint|null=null,picking=false;
 const route=new RoutePlayback();let routePoints:GeoPoint[]=[],routeFollowLast=0;
 const button=(key:string,id:string,fn:()=>void)=>{const b=document.createElement('button');b.id=id;b.textContent=t('nav23.'+key);b.onclick=fn;return b;};
 const note=(key:string)=>{const p=document.createElement('p');p.className='control-note';p.textContent=t('nav23.'+key);return p;};
 const section=(key:string,parent:HTMLElement=root)=>{const d=document.createElement('details'),s=document.createElement('summary');d.id='discovery-'+key;s.textContent=t('nav23.'+key);d.append(s);parent.append(d);return d;};
 function showPanel(panel:'explore'|'analysis'|'view'){appStore.dispatch({type:'panel',panel});document.getElementById('integrated-panel')?.classList.add('open');document.getElementById('app-menu')?.setAttribute('aria-expanded','true');}
 const live=document.createElement('p');live.id='discovery-status';live.setAttribute('role','status');root.append(live);const message=(key:string)=>live.textContent=t('nav23.'+key);
 document.getElementById('app-group-explore')!.append(root);scope.own(()=>root.remove());
 const bookmarks=section('bookmarks'),bookmarkList=document.createElement('div');bookmarkList.id='bookmark-list';bookmarks.append(button('saveView','save-view',()=>editBookmark(null,captureView())),bookmarkList);
 const recent=section('recent'),recentList=document.createElement('div');recentList.id='recent-list';recent.append(recentList);
 const tours=section('tours'),tourList=document.createElement('div'),draftList=document.createElement('div'),tourStatus=document.createElement('p');tourList.id='tour-list';draftList.id='tour-draft';tourStatus.id='tour-status';tourStatus.setAttribute('role','status');
 tours.append(note('tourNote'),button('fromBookmarks','tour-from-bookmarks',()=>{draft=storage.state.bookmarks.filter(b=>b.target?.mapId==='WM0'&&findNavigation(b.target)?.canTour).map(b=>makeStop(b.target!,b.name)).slice(0,100);drawDraft();}),draftList,button('saveTour','save-tour',()=>saveTour()),tourList,tourStatus);
 const tourControls=document.createElement('div');tourControls.className='discovery-actions';tours.append(tourControls);
 for(const [key,action]of [['play',()=>tour?.play()],['pause',()=>{tour?.pause();getViewer()?.cancelMotion();}],['previous',()=>tour?.previous()],['next',()=>tour?.next()],['stop',()=>tour?.stop()]] as const)tourControls.append(button(key,'tour-'+key,()=>{action();updatePlayback();}));
 const nearby=section('nearby'),radius=document.createElement('select'),radiusLabel=document.createElement('label'),nearbyList=document.createElement('div');radius.id='nearby-radius';radiusLabel.htmlFor=radius.id;radiusLabel.textContent=t('nav23.radius');nearbyList.id='nearby-results';
 for(const n of [0,50,100,250,500]){const o=document.createElement('option');o.value=String(n);o.textContent=n?n+' km':t('nav23.nearest');radius.append(o);}
 nearby.append(note('reference'),button('viewCenter','nearby-center',()=>{const view=getViewer()?.viewState();origin=appStore.state.map.id==='WM0'&&view?.centerResolved?view.center:null;drawNearby();}),button('whatsHere','whats-here',()=>{picking=true;message('pickNote');}),radiusLabel,radius,nearbyList);radius.onchange=drawNearby;
 const layers=section('opacity',document.getElementById('app-group-layers')!),ranges=new Map<LayerId,HTMLInputElement>();scope.own(()=>layers.remove());
 for(const def of layerDefinitions){const label=document.createElement('label'),range=document.createElement('input'),out=document.createElement('output');range.type='range';range.min='0';range.max='1';range.step='.05';range.id='opacity-'+def.id;label.htmlFor=range.id;label.textContent=t(def.label);range.setAttribute('aria-label',t(def.label));range.oninput=()=>{storage.update(s=>s.preferences.opacity[def.id]=Number(range.value));out.textContent=formatNumber(Number(range.value)*100,0)+'%';};ranges.set(def.id,range);const row=document.createElement('div');row.className='opacity-row';row.append(label,range,out);layers.append(row);}
 layers.append(button('resetLayers','reset-layers',()=>{storage.update(s=>{s.preferences.opacity=defaultOpacities();s.preferences.visibility=defaultVisibility();});applyVisibility(defaultVisibility());}));
 const legends=section('legend',document.getElementById('app-group-layers')!);scope.own(()=>legends.remove());const moved:{el:HTMLElement;parent:Node;next:ChildNode|null}[]=[];
 for(const el of [document.querySelector<HTMLElement>('.legend'),document.getElementById('tracks-legend')])if(el?.parentNode){moved.push({el,parent:el.parentNode,next:el.nextSibling});legends.append(el);}
 for(const [color,key]of [['#83939a','routing.reachable'],['#dfb4ff','distortion.tissot'],['#ffe18c','routing.title'],['#73e4ed','nav23.route'],['#e5cc77','atlas.title']])legendRow(legends,color,t(key));legends.append(note('atlasLegend'));scope.own(()=>{for(const {el,parent,next}of moved)if(parent.isConnected)parent.insertBefore(el,next?.parentNode===parent?next:null);});
 const scale=document.createElement('div');scale.id='local-scale';scale.className='local-scale';scale.title=t('nav23.reference');document.body.append(scale);scope.own(()=>scale.remove());
 const scaleLabel=document.createElement('label'),scaleToggle=document.createElement('input');scaleToggle.type='checkbox';scaleToggle.id='scale-toggle';scaleLabel.htmlFor=scaleToggle.id;scaleLabel.append(scaleToggle,document.createTextNode(t('nav23.scale')));document.getElementById('app-group-view')!.append(scaleLabel);scope.own(()=>scaleLabel.remove());scaleToggle.onchange=()=>storage.update(s=>s.preferences.scale=scaleToggle.checked);
 const routeSection=section('route',document.getElementById('app-group-analysis')!),routeStatus=document.createElement('p');routeStatus.id='route-playback-status';routeStatus.setAttribute('role','status');routeSection.append(note('routeNote'),routeStatus);scope.own(()=>routeSection.remove());
 const routeControls=document.createElement('div');routeControls.className='discovery-actions';routeSection.append(routeControls);
 for(const [key,action]of [['play',()=>{tour?.pause();getViewer()?.cancelMotion();getViewer()?.setAnalysisVisibility({routes:true});route.play();}],['pause',()=>route.pause()],['restart',()=>{tour?.pause();getViewer()?.cancelMotion();getViewer()?.setAnalysisVisibility({routes:true});route.restart();}],['stop',()=>{route.stop();getViewer()?.setRouteProgress(0);}]] as const)routeControls.append(button(key,'route-'+key,()=>{action();updatePlayback();}));
 const speed=document.createElement('select'),speedLabel=document.createElement('label');speed.id='route-speed';speedLabel.htmlFor=speed.id;speedLabel.textContent=t('nav23.speed');for(const n of [.5,1,2,4]){const o=document.createElement('option');o.value=String(n);o.textContent=n+'×';speed.append(o);}speed.value='1';speed.onchange=()=>route.speed=Number(speed.value);
 const follow=document.createElement('input'),followLabel=document.createElement('label');follow.type='checkbox';follow.id='route-follow';followLabel.htmlFor=follow.id;followLabel.append(follow,document.createTextNode(t('nav23.follow')));follow.onchange=()=>route.follow=follow.checked;routeSection.append(speedLabel,speed,followLabel);
 const share=document.createElement('section');share.id='share-controls';const sharedLink=document.createElement('textarea');sharedLink.id='share-link';sharedLink.readOnly=true;sharedLink.hidden=true;sharedLink.setAttribute('aria-label',t('nav23.share'));share.append(button('share','copy-link',()=>void copyLink()),note('shareNote'),sharedLink);document.getElementById('app-group-view')!.append(share);scope.own(()=>share.remove());
 const actions=document.createElement('div');actions.id='discovery-context';actions.className='discovery-actions';document.getElementById('selection-context')!.append(actions);scope.own(()=>actions.remove());
 const bookmarkAction=button('bookmark','bookmark-selection',()=>{const target=currentTarget();if(target)editBookmark(target,null);});
 const nearbyAction=button('nearby','nearby-selection',()=>{origin=currentEntry()?.anchor??null;nearby.open=true;showPanel('explore');drawNearby();});
 const tourAction=button('addTour','tour-add-selection',()=>{const target=currentTarget();if(target?.mapId==='WM0'&&draft.length<100){draft.push(makeStop(target,currentEntry()?.name??target.id));drawDraft();tours.open=true;showPanel('explore');}});
 const shareAction=button('share','share-selection',()=>void copyLink());const playRouteAction=button('route','play-route-context',()=>{tour?.pause();getViewer()?.cancelMotion();getViewer()?.setAnalysisVisibility({routes:true});route.play();routeSection.open=true;showPanel('analysis');updatePlayback();});actions.append(bookmarkAction,nearbyAction,tourAction,shareAction,playRouteAction);
 const clear=document.createElement('section'),clearGroup=document.createElement('select');clear.id='user-data-controls';clearGroup.id='clear-user-group';clearGroup.setAttribute('aria-label',t('nav23.clear'));
 for(const name of ['all','bookmarks','recent','tours','preferences']){const o=document.createElement('option');o.value=name;o.textContent=t('nav23.'+name);clearGroup.append(o);}clear.append(clearGroup,button('clear','clear-user-data',()=>confirmClear()));document.getElementById('app-group-data')!.append(clear);scope.own(()=>clear.remove());
 const dialog=document.createElement('dialog');dialog.id='user-state-dialog';document.body.append(dialog);scope.own(()=>dialog.remove());
 function currentTarget():IdentityTarget|null{const s=appStore.state.selection;return s&&['location','atlas','entrance','transition'].includes(s.kind)?{kind:s.kind as IdentityTarget['kind'],id:s.id.replace(/^atlas:/,''),mapId:s.mapId}:null;}
 function currentEntry(){const target=currentTarget();return target?findNavigation(target):undefined;}
 function captureView():LocalView {const state=appStore.state,v=getViewer(),native=getNative(),bridge=state.map.id==='WM0'?v?.overviewBridge:native?{camera:native.camera,controls:native.controls}:undefined;return {mapId:state.map.id,projection:state.view.projection,native:state.view.native,camera:bridge?{position:bridge.camera.position.toArray(),target:bridge.controls.target.toArray(),up:bridge.camera.up.toArray(),zoom:bridge.camera.zoom,center:[v?.context.centerLon??0,v?.context.centerLat??0]}:null,layers:readVisibility(),opacity:{...storage.state.preferences.opacity},selected:currentTarget()};}
 async function openView(view:LocalView){const generation=++restoreGeneration;route.pause();tour?.pause();if(view.mapId!==appStore.state.map.id)await switchMap(view.mapId);if(disposed||generation!==restoreGeneration)return;getViewer()?.cancelMotion();const projection=document.getElementById('projection') as HTMLSelectElement|null;if(projection&&view.mapId==='WM0'){projection.value=view.projection;projection.dispatchEvent(new Event('change'));}else if(view.mapId!=='WM0'){const field=document.getElementById('native-view') as HTMLSelectElement|null;if(field){field.value=view.native;field.dispatchEvent(new Event('change'));}}
  applyVisibility(view.layers);storage.update(s=>{s.preferences.opacity={...view.opacity};});
  const apply=()=>{if(disposed||generation!==restoreGeneration||appStore.state.explorer.phase!=='idle')return;if(getViewer()?.isMorphing&&view.mapId==='WM0'){requestAnimationFrame(apply);return;}if(view.selected)findNavigation(view.selected)?.navigate();getViewer()?.cancelMotion();const v=getViewer(),n=getNative(),bridge=view.mapId==='WM0'?v?.overviewBridge:n?{camera:n.camera,controls:n.controls}:null;if(bridge&&view.camera){if(view.mapId==='WM0'&&v){v.focusLocation(view.camera.center[0],view.camera.center[1]);}bridge.camera.position.fromArray(view.camera.position);bridge.camera.up.fromArray(view.camera.up);bridge.controls.target.fromArray(view.camera.target);bridge.camera.zoom=view.camera.zoom;bridge.camera.updateProjectionMatrix();bridge.camera.lookAt(bridge.controls.target);bridge.controls.update();}};apply();
 }
 function navigate(target:IdentityTarget){const entry=findNavigation(target);if(!entry){message('missing');return false;}if(appStore.state.explorer.phase!=='idle'){message('unavailable');return false;}if(appStore.state.map.id!==target.mapId){void switchMap(target.mapId).then(()=>{if(!disposed)findNavigation(target)?.navigate();});}else entry.navigate();return true;}
 function openBookmark(b:Bookmark){if(b.view)void openView(b.view);else if(b.target)navigate(b.target);storage.addRecent(null,b.id);}
 function input(parent:HTMLElement,key:string,id:string,value:string,max:number){const label=document.createElement('label'),field=document.createElement('input');label.htmlFor=id;label.textContent=t('nav23.'+key);field.id=id;field.value=value;field.maxLength=max;parent.append(label,field);return field;}
 function editBookmark(target:IdentityTarget|null,view:LocalView|null,existing?:Bookmark){dialog.replaceChildren();const form=document.createElement('form');form.method='dialog';dialog.append(form);const name=input(form,'name','bookmark-name',existing?.name??(target?findNavigation(target)?.name??target.id:t('nav23.view')),80),noteInput=input(form,'note','bookmark-note',existing?.note??'',240);form.append(button('cancel','bookmark-cancel',()=>dialog.close()),button('save','bookmark-save',()=>{}));form.onsubmit=e=>{e.preventDefault();if((e as SubmitEvent).submitter?.id==='bookmark-cancel'){dialog.close();return;}if(!name.value.trim())return;if(!existing&&storage.state.bookmarks.length>=200){message('limit');return;}storage.update(s=>{const b={id:existing?.id??uid(),name:name.value.trim(),note:noteInput.value.trim(),created:existing?.created??Date.now(),target,view};if(existing)s.bookmarks=s.bookmarks.map(old=>old.id===existing.id?b:old);else s.bookmarks.push(b);});dialog.close();};dialog.showModal();name.focus();}
 function confirmClear(){dialog.replaceChildren();const group=clearGroup.value as 'all'|'bookmarks'|'recent'|'tours'|'preferences';const p=document.createElement('p');p.textContent=t('nav23.clearConfirm',{group:t('nav23.'+group)});dialog.append(p,button('cancel','clear-cancel',()=>dialog.close()),button('confirm','clear-confirm',()=>{tour?.stop();storage.clear(group);if(group==='all'||group==='preferences')applyVisibility(defaultVisibility());dialog.close();}));dialog.showModal();document.getElementById('clear-cancel')?.focus();}
 function makeStop(target:IdentityTarget,title:string):TourStop{return {id:uid(),target,duration:5,title};}
 function drawDraft(){draftList.replaceChildren(note('draft'));draftList.firstElementChild!.textContent=t('nav23.draft',{count:draft.length});for(let i=0;i<draft.length;i++){const stop=draft[i],row=document.createElement('div');row.className='saved-row';const title=input(row,'stopTitle','stop-title-'+stop.id,stop.title,80),duration=input(row,'duration','stop-duration-'+stop.id,String(stop.duration),3);duration.type='number';duration.min='1';duration.max='120';title.onchange=()=>stop.title=title.value;duration.onchange=()=>{stop.duration=Math.max(1,Math.min(120,Number(duration.value)||5));duration.value=String(stop.duration);};for(const [key,delta]of [['up',-1],['down',1]] as const)row.append(button(key,'stop-'+key+'-'+stop.id,()=>{const n=i+delta;if(n>=0&&n<draft.length){[draft[i],draft[n]]=[draft[n],draft[i]];drawDraft();}}));row.append(button('remove','stop-remove-'+stop.id,()=>{draft.splice(i,1);drawDraft();}));draftList.append(row);}}
 function saveTour(){if(!draft.length||storage.state.tours.length>=30){message(draft.length?'limit':'empty');return;}dialog.replaceChildren();const form=document.createElement('form');form.method='dialog';dialog.append(form);const name=input(form,'name','tour-name',t('nav23.tours'),80);form.append(button('cancel','tour-cancel',()=>dialog.close()),button('save','tour-save',()=>{}));form.onsubmit=e=>{e.preventDefault();if((e as SubmitEvent).submitter?.id==='tour-cancel'){dialog.close();return;}if(!name.value.trim())return;storage.update(s=>s.tours.push({id:uid(),name:name.value.trim(),stops:structuredClone(draft),created:Date.now()}));draft=[];drawDraft();dialog.close();};dialog.showModal();name.focus();}
 function loadTour(saved:UserTour){tour?.stop();let snapshot:LocalView|null=null;tour=new TourPlayback(saved.stops,(stop,reduced)=>{const entry=findNavigation(stop.target);if(!entry||stop.target.mapId!=='WM0')return false;const drawer=document.getElementById('integrated-panel'),opened=drawer?.classList.contains('open');navigate(stop.target);if(opened){drawer?.classList.add('open');document.getElementById('app-menu')?.setAttribute('aria-expanded','true');}if(entry.anchor){if(reduced)getViewer()?.focusLocation(entry.anchor[0],entry.anchor[1]);else getViewer()?.flyToLocation(entry.anchor[0],entry.anchor[1]);}return true;},()=>{route.pause();snapshot=captureView();getViewer()?.setAutoRotate(false);},()=>{getViewer()?.cancelMotion();if(snapshot&&!disposed&&appStore.state.map.id===snapshot.mapId&&appStore.state.explorer.phase==='idle')void openView(snapshot);},matchMedia('(prefers-reduced-motion: reduce)').matches);tours.open=true;updatePlayback();}
 function drawSaved(){bookmarkList.replaceChildren();for(const b of storage.state.bookmarks){const row=document.createElement('div');row.className='saved-row';row.dataset.bookmark=b.id;const open=button('open','bookmark-open-'+b.id,()=>openBookmark(b));open.textContent=b.name;open.dataset.userText='true';const n=document.createElement('p');n.textContent=b.note;n.dataset.userText='true';row.append(open,n,button('rename','bookmark-edit-'+b.id,()=>editBookmark(b.target,b.view,b)),button('delete','bookmark-delete-'+b.id,()=>storage.deleteBookmark(b.id)));if(b.target?.mapId==='WM0'&&findNavigation(b.target)?.canTour)row.append(button('addTour','bookmark-tour-'+b.id,()=>{if(draft.length<100){draft.push(makeStop(b.target!,b.name));drawDraft();tours.open=true;}}));bookmarkList.append(row);}if(!storage.state.bookmarks.length)bookmarkList.append(note('empty'));
  recentList.replaceChildren();for(const r of storage.state.recent){const b=r.bookmarkId?storage.state.bookmarks.find(b=>b.id===r.bookmarkId):undefined,entry=r.target?findNavigation(r.target):undefined;const row=button('open','recent-'+(r.bookmarkId??r.target!.kind+'-'+r.target!.id),()=>{if(b)openBookmark(b);else if(r.target)navigate(r.target);});row.textContent=b?.name??entry?.name??t('nav23.missing');if(b)row.dataset.userText='true';recentList.append(row);}if(!storage.state.recent.length)recentList.append(note('empty'));
  tourList.replaceChildren();for(const saved of storage.state.tours){const row=document.createElement('div');row.className='saved-row';const title=document.createElement('p');title.textContent=saved.name;title.dataset.userText='true';row.append(title,button('play','tour-play-'+saved.id,()=>{loadTour(saved);tour!.play();updatePlayback();}),button('rename','tour-edit-'+saved.id,()=>{draft=structuredClone(saved.stops);drawDraft();tours.open=true;}),button('delete','tour-delete-'+saved.id,()=>{tour?.stop();storage.update(s=>s.tours=s.tours.filter(t=>t.id!==saved.id));}));tourList.append(row);}if(!storage.state.tours.length)tourList.append(note('empty'));
  root.dataset.storageBytes=String(storage.bytes);root.dataset.storageStatus=storage.status;message(storage.status);for(const [id,range]of ranges){range.value=String(storage.state.preferences.opacity[id]);range.nextElementSibling!.textContent=formatNumber(Number(range.value)*100,0)+'%';}scaleToggle.checked=storage.state.preferences.scale;applyOpacity();
 }
 function rebuildIndex(){const entries=navigationEntries().filter(e=>e.anchor&&e.target&&e.mapId==='WM0'&&e.kind!=='entrance'&&e.group),points=new Set<string>(),anchors:NearbyAnchor[]=[];for(const e of [...entries].sort((a,b)=>Number(b.kind==='atlas')-Number(a.kind==='atlas'))){const key=e.group+':'+e.anchor!.slice(0,2).join(':');if(points.has(key))continue;points.add(key);anchors.push({target:e.target!,name:e.name,point:e.anchor!,group:e.group!,precision:e.precision!});}index=new NearbyIndex(anchors);root.dataset.nearbyEntities=String(index.size);drawNearby();drawSaved();applyDeepTarget();}
 function drawNearby(){nearbyList.replaceChildren();const available=!!getViewer()&&appStore.state.map.id==='WM0'&&appStore.state.explorer.phase==='idle';document.getElementById('nearby-center')!.toggleAttribute('disabled',!available);document.getElementById('whats-here')!.toggleAttribute('disabled',!available);if(!available){nearbyList.append(note('unavailable'));return;}if(!origin){nearbyList.append(note('pickNote'));return;}const began=performance.now(),results=index.query(origin,Number(radius.value)?Number(radius.value)*1000:Infinity,20);root.dataset.nearbyMs=String(performance.now()-began);if(!results.length)nearbyList.append(note('noResults'));for(const group of ['places','secrets','transitions'] as const){const matches=results.filter(r=>r.group===group);if(!matches.length)continue;const h=document.createElement('h3');h.textContent=t('nav23.'+group);nearbyList.append(h);for(const r of matches){const b=button('open','nearby-'+r.target.kind+'-'+r.target.id,()=>navigate(r.target));b.textContent=r.name+' · '+formatNumber(r.distance/1000,1)+' km';b.dataset.distance=String(r.distance);nearbyList.append(b);}}}
 function readVisibility(){const visibility=defaultVisibility();for(const def of visibilityDefinitions){const control=document.getElementById(def.control) as HTMLInputElement|null;if(control?.type==='checkbox')visibility[def.id]=control.checked;else if(def.id==='encounters')visibility[def.id]=['encounter','encounter-rate'].includes((document.getElementById('color-layer') as HTMLSelectElement|null)?.value??'');else if(def.id==='traversal')visibility[def.id]=(document.getElementById('color-layer') as HTMLSelectElement|null)?.value==='traversal';else if(def.id==='routes')visibility[def.id]=route.available&&!!getViewer()?.analysisVisibility.routes;else if(def.id==='reachability')visibility[def.id]=!!getViewer()?.hasReachability&&!!getViewer()?.analysisVisibility.reachability;}return visibility;}
 function applyVisibility(visibility:ReturnType<typeof defaultVisibility>){getViewer()?.setAnalysisVisibility({reachability:visibility.reachability,routes:visibility.routes});for(const def of visibilityDefinitions){const field=document.getElementById(def.control) as HTMLInputElement|null;if(field?.type==='checkbox'&&field.checked!==visibility[def.id]){field.checked=visibility[def.id];field.dispatchEvent(new Event('change',{bubbles:true}));}}const colors=document.getElementById('color-layer') as HTMLSelectElement|null;if(colors){colors.value=visibility.traversal?'traversal':visibility.encounters?'encounter':'terrain';colors.dispatchEvent(new Event('change',{bubbles:true}));}}
 function applyOpacity(){const values=storage.state.preferences.opacity;if(JSON.stringify(appStore.state.preferences.layerOpacity)!==JSON.stringify(values))appStore.dispatch({type:'preference',preferences:{layerOpacity:{...values}}});const v=getViewer();if(v)for(const id of ranges.keys())v.setLayerOpacity(id,storage.state.preferences.opacity[id]);}
 async function copyLink(){const target=currentTarget(),publicTarget=target&&isPublicTarget(target.kind,target.id)?{kind:target.kind as 'location'|'atlas',id:target.id}:null;const layers=readVisibility();const url=encodeShare(location.href,{schema:'gaiagis-share-state',version:1,language:locale(),mapId:appStore.state.map.id,projection:appStore.state.view.projection,native:appStore.state.view.native,layers:visibilityDefinitions.filter(d=>layers[d.id]).map(d=>d.id),spoilers:(document.getElementById('atlas-spoilers') as HTMLSelectElement).value as 'hide-major'|'show-all'|'hide-all',target:publicTarget});sharedLink.hidden=false;sharedLink.value=url;try{await navigator.clipboard.writeText(url);message('copied');}catch{showPanel('view');sharedLink.focus();sharedLink.select();message('copyFailed');}}
 const deep=location.search?decodeShare(location.href):null;let deepTargetDone=false;
 function applyDeepTarget(){if(!deep?.target||deepTargetDone||appStore.state.localWorkspace==='loading')return;let target:IdentityTarget={...deep.target,mapId:'WM0'};if(!findNavigation(target)&&target.kind==='location')target={...target,kind:'atlas'};const entry=findNavigation(target);if(entry){deepTargetDone=true;navigate(target);}else message('missing');}
 async function applyDeep(){if(!deep)return;setLocale(deep.language,false);if(deep.mapId!==appStore.state.map.id)await switchMap(deep.mapId);const projection=document.getElementById('projection') as HTMLSelectElement|null;if(projection){projection.value=deep.projection;projection.dispatchEvent(new Event('change'));}const native=document.getElementById('native-view') as HTMLSelectElement|null;if(deep.mapId!=='WM0'&&native){native.value=deep.native;native.dispatchEvent(new Event('change'));}const spoilers=document.getElementById('atlas-spoilers') as HTMLSelectElement;spoilers.value=deep.spoilers;spoilers.dispatchEvent(new Event('change'));const visibility=defaultVisibility();for(const id of Object.keys(visibility) as VisibilityId[])visibility[id]=deep.layers.includes(id);applyVisibility(visibility);applyDeepTarget();}
 function updateContext(){const entry=currentEntry(),target=currentTarget(),overview=appStore.state.explorer.phase==='idle';const caps=navigationActions(appStore.state,target,entry,route.available);bookmarkAction.hidden=!caps.bookmark;nearbyAction.hidden=!caps.nearby;tourAction.hidden=!caps.addTour;shareAction.hidden=!caps.share;playRouteAction.hidden=!caps.playRoute;root.hidden=!overview;if(!overview||appStore.state.map.id!=='WM0')scale.hidden=true;for(const [id,range]of ranges)range.disabled=!getViewer()||!layerAvailable(id,appStore.state);const key=target?JSON.stringify(target):'';if(key&&key!==historyKey){historyKey=key;storage.addRecent(target);}else if(!key)historyKey='';drawNearby();updatePlayback();}
 let playbackKey='';function updatePlayback(){const key=[tour?.phase,tour?.index,route.phase,Math.floor(route.progress*1000),route.available,appStore.state.map.id,appStore.state.explorer.phase].join(':');if(key===playbackKey)return;playbackKey=key;tourStatus.textContent=t('nav23.'+(tour?.phase??'idle'))+(tour&&tour.index>=0?' · '+(tour.stops[tour.index].title||tour.stops[tour.index].target.id):'');routeStatus.textContent=t('nav23.'+route.phase)+' · '+formatNumber(route.progress*100,0)+'%';routeSection.dataset.phase=route.phase;routeSection.dataset.progress=String(route.progress);tours.dataset.phase=tour?.phase??'idle';tours.dataset.index=String(tour?.index??-1);for(const b of routeControls.querySelectorAll('button'))b.disabled=!route.available||appStore.state.map.id!=='WM0'||appStore.state.explorer.phase!=='idle';for(const b of tourControls.querySelectorAll('button'))b.disabled=!tour||appStore.state.map.id!=='WM0'||appStore.state.explorer.phase!=='idle';}
 const v=getViewer();if(v){routePoints=v.routePoints;route.setRoute(routePoints.length);v.onRouteChange=points=>{routePoints=points;route.setRoute(points.length);updatePlayback();};v.onNavigationFrame=seconds=>{tour?.tick(seconds);route.tick(seconds);v.setRouteProgress(route.progress);if(route.phase==='playing'&&route.follow&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&performance.now()-routeFollowLast>120){routeFollowLast=performance.now();const point=routePoints[Math.min(routePoints.length-1,Math.floor(route.progress*(routePoints.length-1)))];if(point)v.focusLocation(point[0],point[1]);}updatePlayback();playRouteAction.hidden=!navigationActions(appStore.state,currentTarget(),currentEntry(),route.available).playRoute;};}
 let raf=0,lastScale=0;function frame(time:number){if(disposed)return;if(time-lastScale>250){lastScale=time;const v=getViewer(),available=v&&appStore.state.map.id==='WM0'&&appStore.state.explorer.phase==='idle'&&!v.isMorphing&&storage.state.preferences.scale;const box=v?.renderer.domElement.getBoundingClientRect(),result=available&&box?localScreenScale(v.overviewBridge.camera,v.projectionId,v.context,box.width,box.height,v.viewState().center):null;scale.hidden=!result;if(result){scale.textContent=formatNumber(result.meters/1000,2)+' km';scale.style.width=result.pixels+'px';scale.dataset.metresPerPixel=String(result.metersPerPixel);}}raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);scope.own(()=>cancelAnimationFrame(raf));
 scope.listen(document,'pointerup',((event:PointerEvent)=>{if(!picking||!(event.target instanceof HTMLCanvasElement))return;picking=false;const v=getViewer();if(!v||appStore.state.map.id!=='WM0'||v.isMorphing)return;const box=v.renderer.domElement.getBoundingClientRect();origin=screenGeographic(v.overviewBridge.camera,v.projectionId,v.context,event.clientX-box.left,event.clientY-box.top,box.width,box.height,v.viewState().center);nearby.open=true;drawNearby();}) as EventListener);
 scope.listen(document,'gaiagis-navigation',rebuildIndex);scope.listen(document,'change',((e:Event)=>{const id=(e.target as HTMLElement).id;if(visibilityDefinitions.some(d=>d.control===id))storage.update(s=>s.preferences.visibility=readVisibility());}) as EventListener);
 scope.listen(document,'gaiagis-map-changing',()=>{picking=false;origin=null;route.pause();tour?.pause();getViewer()?.cancelMotion();});
 scope.own(appStore.subscribe(()=>{if(appStore.state.explorer.phase!=='idle'){restoreGeneration++;tour?.pause();route.pause();}updateContext();applyDeepTarget();}));scope.own(storage.subscribe(drawSaved));scope.own(onLocaleChange(()=>{drawSaved();drawDraft();drawNearby();updatePlayback();}));
 applyVisibility(storage.state.preferences.visibility);drawSaved();drawDraft();rebuildIndex();updateContext();void applyDeep();
 return {dispose(){disposed=true;restoreGeneration++;tour?.stop();route.stop();if(v){v.onNavigationFrame=()=>{};v.onRouteChange=()=>{};v.setRouteProgress(0);}scope.dispose();}};
}
