import {t,formatNumber} from '../i18n';
// SPDX-License-Identifier: GPL-3.0-only
import type {GaiaMeta} from '../data/mesh';
import type {GaiaViewer} from '../viewer/GaiaViewer';
import {filterEvent,loadOptionalEvents,readLocalEvents,validateEventsMesh} from '../data/events';
import type {WorldEvent,EventsDataset,EventFilter} from '../data/events';
export function renderEventInspector(parent:HTMLElement,e:WorldEvent){
  parent.replaceChildren();parent.dataset.event=e.id;delete parent.dataset.sourceTriangle;delete parent.dataset.location;delete parent.dataset.origin;
  const title=document.createElement('h3');title.textContent=e.display_name;parent.append(title);
  const rows:[string,string][]=[[t('inspect.eventType'),t(`event.${e.event_type}`)],[t('inspect.lonlat'),`${formatNumber(e.longitude,5)}° / ${formatNumber(e.latitude,5)}°`],[t('inspect.rawXY'),`${formatNumber(e.game_x,2)} / ${formatNumber(e.game_north,2)}`],[t('inspect.anchor'),e.anchor_kind],[t('inspect.function'),`0x${e.function_id.toString(16).toUpperCase()}`],[t('inspect.opcode'),e.opcode_name],[t('inspect.condition'),e.condition_kind.length?e.condition_kind.join(', '):t('inspect.noBranch')],[t('inspect.runtime'),t('ui.notSimulated')],[t('inspect.evidence'),e.confidence],[t('ui.source'),'wm0.ev + WM0 base surface']];
  if(e.height!==null)rows.splice(3,0,[t('inspect.height'),`${formatNumber(e.height,2)} raw / assumed m · ${t('message.interpolated')}`]);
  if(e.triangle_id!==null)rows.push([t('inspect.sourceTriangle'),`${e.section_id} / ${e.mesh_id} / ${e.triangle_id}`]);
  if(e.model_id!==null)rows.push([t('inspect.model'),String(e.model_id)]);
  if(e.field_id!==null)rows.push([t('inspect.destination'),`${e.field_id} / ${e.field_name}`],[t('inspect.entryScenario'),`${e.entrance_table_id} / ${e.scenario}`]);
  if(e.battle_id!==null)rows.push([t('inspect.battle'),String(e.battle_id)]);
  if(e.location_id!==null)rows.push([t('inspect.locationIdentity'),e.location_id]);
  const dl=document.createElement('dl');dl.className='property-list';for(const [key,value]of rows){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;row.append(dt,dd);dl.append(row);}parent.append(dl);
  const note=document.createElement('p');note.className='control-note';note.textContent=e.notes;parent.append(note);
  const detail=document.createElement('details');detail.className='event-advanced';const summary=document.createElement('summary');summary.textContent=t('inspect.advanced');const text=document.createElement('p');text.className='control-note';text.textContent=t('message.eventProvenance',{call:e.call_table_record,word:e.instruction_offset,block:e.basic_block,anchor:`0x${e.anchor_function.toString(16)}`,args:JSON.stringify(e.raw_arguments),triangles:e.trigger_triangle_ids.length})+'. '+t('message.markerBaseline')+' '+t('inspect.classic');detail.append(summary,text);parent.append(detail);
}
export function mountEvents(viewer:GaiaViewer,meta:GaiaMeta,isCurrent:()=>boolean){
  const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
  const file=el<HTMLInputElement>('local-events-file'),status=el('event-status'),toggle=el<HTMLInputElement>('events-toggle'),filter=el<HTMLSelectElement>('event-filter'),list=el<HTMLSelectElement>('event-list');let data:EventsDataset|null=null,revision=0;
  const clear=()=>{viewer.selectEvent(null);delete el('selection-details').dataset.event;};
  function select(e:WorldEvent){viewer.clearSelection();viewer.selectEvent(e);el('inspector-title').textContent=t('ui.eventInspector');const parent=el('selection-details');parent.hidden=false;el('selection-empty').hidden=true;renderEventInspector(parent,e);el('info-panel').classList.add('mobile-open');document.querySelector('.controls')!.classList.remove('mobile-open');el('mobile-display').setAttribute('aria-expanded','false');el<HTMLInputElement>('auto-rotate').checked=false;el('coordinates').textContent=`${formatNumber(e.longitude,2)}° / ${formatNumber(e.latitude,2)}°`;viewer.flyToLocation(e.longitude,e.latitude);}
  function display(){viewer.setEventsDisplay(toggle.checked,filter.value as EventFilter);list.replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent=t('ui.goEvent');list.append(placeholder);for(const e of data?.events??[]){if(!filterEvent(e,filter.value as EventFilter))continue;const option=document.createElement('option');option.value=e.id;option.textContent=`${e.display_name} · ${e.call_table_record}:${e.instruction_offset}`;list.append(option);}}
  function adopt(next:EventsDataset|null){if(next)validateEventsMesh(next,viewer.mesh);data=next;clear();viewer.setEvents(next?.events??[]);display();toggle.disabled=filter.disabled=list.disabled=!next;status.textContent=next?t('message.events',{events:next.events.length,unresolved:next.unresolved.length}):t('ui.eventsUnavailable');}
  viewer.onEvent=select;toggle.addEventListener('change',display);filter.addEventListener('change',display);list.addEventListener('change',()=>{const e=data?.events.find(e=>e.id===list.value);if(e)select(e);});el<HTMLInputElement>('script-triggers').addEventListener('change',e=>viewer.setScriptTriggers((e.target as HTMLInputElement).checked));el('load-events').addEventListener('click',()=>file.click());
  file.addEventListener('change',async()=>{const chosen=file.files?.[0];if(!chosen)return;const request=++revision;status.textContent=t('load.events');try{const next=await readLocalEvents(chosen,meta);if(isCurrent()&&request===revision)adopt(next);}catch(error){if(isCurrent()&&request===revision)status.textContent=t('error.dataset');status.title=error instanceof Error?error.message:String(error);}file.value='';});const request=revision;void loadOptionalEvents(meta).then(next=>{if(isCurrent()&&revision===request)adopt(next);}).catch(error=>{if(isCurrent()&&revision===request)status.textContent=t('ui.eventsUnavailable');status.title=error.message;});return {clear};
}
