// SPDX-License-Identifier: GPL-3.0-only
import type {GaiaMeta} from '../data/mesh';
import type {GaiaViewer} from '../viewer/GaiaViewer';
import {filterEvent,loadOptionalEvents,readLocalEvents,validateEventsMesh} from '../data/events';
import type {WorldEvent,EventsDataset,EventFilter} from '../data/events';
export function renderEventInspector(parent:HTMLElement,e:WorldEvent){
  parent.replaceChildren();parent.dataset.event=e.id;delete parent.dataset.sourceTriangle;delete parent.dataset.location;delete parent.dataset.origin;
  const title=document.createElement('h3');title.textContent=e.display_name;parent.append(title);
  const rows:[string,string][]=[['Event type',e.event_type.replaceAll('_',' ')],['Longitude / latitude',`${e.longitude.toFixed(5)}° / ${e.latitude.toFixed(5)}°`],['Raw east / north',`${e.game_x.toFixed(2)} / ${e.game_north.toFixed(2)}`],['Anchor',e.anchor_kind],['Function ID',`0x${e.function_id.toString(16).toUpperCase()}`],['Opcode',e.opcode_name],['Condition type',e.condition_kind.length?e.condition_kind.join(', '):'No static branch condition observed'],['Runtime availability','Not simulated'],['Evidence',e.confidence],['Source','wm0.ev + WM0 base surface']];
  if(e.height!==null)rows.splice(3,0,['Height',`${e.height.toFixed(2)} raw / assumed m · surface interpolation`]);
  if(e.triangle_id!==null)rows.push(['Source triangle',`${e.section_id} / ${e.mesh_id} / ${e.triangle_id}`]);
  if(e.model_id!==null)rows.push(['Model ID',String(e.model_id)]);
  if(e.field_id!==null)rows.push(['Destination field',`${e.field_id} / ${e.field_name}`],['Entry / scenario',`${e.entrance_table_id} / ${e.scenario}`]);
  if(e.battle_id!==null)rows.push(['Scripted battle ID',String(e.battle_id)]);
  if(e.location_id!==null)rows.push(['Verified location identity',e.location_id]);
  const dl=document.createElement('dl');dl.className='property-list';for(const [key,value]of rows){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;row.append(dt,dd);dl.append(row);}parent.append(dl);
  const note=document.createElement('p');note.className='control-note';note.textContent=e.notes;parent.append(note);
  const detail=document.createElement('details');detail.className='event-advanced';const summary=document.createElement('summary');summary.textContent='Script provenance / advanced';const text=document.createElement('p');text.className='control-note';text.textContent=`Call table ${e.call_table_record} · instruction word ${e.instruction_offset} · basic block ${e.basic_block} · anchor function 0x${e.anchor_function.toString(16)} · raw arguments ${JSON.stringify(e.raw_arguments)} · trigger triangles ${e.trigger_triangle_ids.length}. Height unknown uses a display-only marker baseline. Current 2026 executable equivalence is not verified.`;detail.append(summary,text);parent.append(detail);
}
export function mountEvents(viewer:GaiaViewer,meta:GaiaMeta,isCurrent:()=>boolean){
  const el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
  const file=el<HTMLInputElement>('local-events-file'),status=el('event-status'),toggle=el<HTMLInputElement>('events-toggle'),filter=el<HTMLSelectElement>('event-filter'),list=el<HTMLSelectElement>('event-list');let data:EventsDataset|null=null,revision=0;
  const clear=()=>{viewer.selectEvent(null);delete el('selection-details').dataset.event;};
  function select(e:WorldEvent){viewer.clearSelection();viewer.selectEvent(e);el('inspector-title').textContent='World Event inspector';const parent=el('selection-details');parent.hidden=false;el('selection-empty').hidden=true;renderEventInspector(parent,e);el('info-panel').classList.add('mobile-open');document.querySelector('.controls')!.classList.remove('mobile-open');el('mobile-display').setAttribute('aria-expanded','false');el<HTMLInputElement>('auto-rotate').checked=false;el('coordinates').textContent=`${e.longitude.toFixed(2)}° / ${e.latitude.toFixed(2)}°`;viewer.flyToLocation(e.longitude,e.latitude);}
  function display(){viewer.setEventsDisplay(toggle.checked,filter.value as EventFilter);list.replaceChildren();const placeholder=document.createElement('option');placeholder.value='';placeholder.textContent='Go to event…';list.append(placeholder);for(const e of data?.events??[]){if(!filterEvent(e,filter.value as EventFilter))continue;const option=document.createElement('option');option.value=e.id;option.textContent=`${e.display_name} · ${e.call_table_record}:${e.instruction_offset}`;list.append(option);}}
  function adopt(next:EventsDataset|null){if(next)validateEventsMesh(next,viewer.mesh);data=next;clear();viewer.setEvents(next?.events??[]);display();toggle.disabled=filter.disabled=list.disabled=!next;status.textContent=next?`${next.events.length} events · ${next.unresolved.length} unresolved · local data`:'Events unavailable · optional local file';}
  viewer.onEvent=select;toggle.addEventListener('change',display);filter.addEventListener('change',display);list.addEventListener('change',()=>{const e=data?.events.find(e=>e.id===list.value);if(e)select(e);});el<HTMLInputElement>('script-triggers').addEventListener('change',e=>viewer.setScriptTriggers((e.target as HTMLInputElement).checked));el('load-events').addEventListener('click',()=>file.click());
  file.addEventListener('change',async()=>{const chosen=file.files?.[0];if(!chosen)return;const request=++revision;status.textContent='Verifying local events…';try{const next=await readLocalEvents(chosen,meta);if(isCurrent()&&request===revision)adopt(next);}catch(error){if(isCurrent()&&request===revision)status.textContent=error instanceof Error?error.message:String(error);}file.value='';});const request=revision;void loadOptionalEvents(meta).then(next=>{if(isCurrent()&&revision===request)adopt(next);}).catch(error=>{if(isCurrent()&&revision===request)status.textContent=`Events unavailable: ${error.message}`;});return {clear};
}
