import {registerNavigation} from '../app/navigation';
import {workspaceLoader,loadedAsset} from '../app/assets';
import {appStore} from '../app/state';
// SPDX-License-Identifier: GPL-3.0-only
import {decodeNativeMap,parseTransitions} from '../data/nativeMaps';
import type {MapId,NativeMap,NativeMapId,MapTransition} from '../data/nativeMaps';
import {decodeTextures} from '../data/textures';
import type {NativeViewer} from '../viewer/NativeViewer';
import {t,formatNumber,onLocaleChange} from '../i18n';
import type {GaiaViewer} from '../viewer/GaiaViewer';

export function mountMultimap(wm0Root:HTMLElement,getWM0:()=>GaiaViewer|undefined){
 const bar=document.createElement('nav');bar.className='multimap-bar';const label=document.createElement('label'),select=document.createElement('select');select.id='map-selector';label.htmlFor=select.id;
 for(const id of ['WM0','WM2','WM3']){const o=document.createElement('option');o.value=id;select.append(o);}bar.append(label,select);wm0Root.before(bar);
 const host=document.createElement('section');host.className='native-host';host.hidden=true;wm0Root.after(host);
 const panel=document.createElement('aside');panel.className='native-panel';const viewport=document.createElement('div');viewport.className='native-viewport';const status=document.createElement('p'),note=document.createElement('p'),stats=document.createElement('p'),detail=document.createElement('section');detail.id='native-inspector';
 const geometry=document.createElement('input');geometry.type='file';geometry.accept='.bin';geometry.hidden=true;geometry.id='native-map-file';
 const texture=document.createElement('input');texture.type='file';texture.accept='.bin';texture.hidden=true;texture.id='native-texture-file';
 const transitionFile=document.createElement('input');transitionFile.type='file';transitionFile.accept='.json';transitionFile.hidden=true;transitionFile.id='map-transitions-file';
 const load=document.createElement('button'),loadTexture=document.createElement('button'),loadTransitions=document.createElement('button'),back=document.createElement('button'),reset=document.createElement('button');
 load.id='load-native-map';loadTexture.id='load-native-textures';loadTransitions.id='load-map-transitions';back.id='native-return';
 const view=document.createElement('select');view.id='native-view';for(const id of ['3d','topdown']){const o=document.createElement('option');o.value=id;view.append(o);}
 const layer=document.createElement('select');layer.id='native-layer';for(const id of ['terrain','region','texture']){const o=document.createElement('option');o.value=id;layer.append(o);}
 const relief=document.createElement('select');relief.id='native-relief';for(const value of [0,1,10,25,50,100]){const o=document.createElement('option');o.value=String(value);o.textContent=value+'×';relief.append(o);}relief.value='1';
 const reliefLabel=document.createElement('label');reliefLabel.htmlFor=relief.id;
 const filter=document.createElement('select');filter.id='native-filter';for(const id of ['nearest','linear']){const o=document.createElement('option');o.value=id;filter.append(o);}
 const shading=document.createElement('input');shading.type='checkbox';shading.id='native-shading';const shadeLabel=document.createElement('label');shadeLabel.htmlFor=shading.id;
 const transitionsToggle=document.createElement('input');transitionsToggle.type='checkbox';transitionsToggle.id='map-transitions-toggle';const transLabel=document.createElement('label');transLabel.htmlFor=transitionsToggle.id;const list=document.createElement('section');list.id='map-transition-list';
 panel.append(load,status,note,view,layer,loadTexture,reliefLabel,relief,filter,shadeLabel,shading,transLabel,transitionsToggle,loadTransitions,list,reset,back,stats,detail);host.append(viewport,panel,geometry,texture,transitionFile);
 const wm0Transitions=document.createElement('button');wm0Transitions.id='wm0-load-transitions';bar.append(wm0Transitions);wm0Transitions.onclick=()=>transitionFile.click();
 const wm0List=document.createElement('details'),wm0Summary=document.createElement('summary'),wm0Records=document.createElement('section');wm0List.append(wm0Summary,wm0Records);bar.append(wm0List);
 const maps=new Map<NativeMapId,NativeMap>(),textureBuffers=new Map<NativeMapId,ArrayBuffer>();let current:MapId='WM0',viewer:NativeViewer|undefined,request=0,transitions:ReturnType<typeof parseTransitions>|undefined;
 function properties(rows:[string,string][],target=detail){const dl=document.createElement('dl');dl.className='property-list';for(const [k,v]of rows){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;row.append(dt,dd);dl.append(row);}target.append(dl);}
 function inspect(triangle:number){if(!viewer)return;const map=viewer.map,a=map.attributes(triangle);appStore.dispatch({type:'select',selection:{kind:'triangle',id:String(triangle),mapId:map.header.mapId}});detail.replaceChildren();detail.dataset.triangle=String(triangle);detail.dataset.mapId=map.header.mapId;
  const centroid=[0,1,2].map(axis=>[0,1,2].reduce((sum,j)=>sum+map.positions[triangle*9+j*3+axis],0)/3);
  properties([[t('map.title'),map.header.mapId],[t('map.space'),map.header.coordinate_space],[t('map.x'),formatNumber(centroid[0])],[t('map.z'),formatNumber(centroid[1])],[t('map.height'),formatNumber(centroid[2])],[t('ui.section'),String(a.section)],[t('ui.mesh'),String(a.mesh)],[t('ui.triangle'),String(a.triangle)],[t('ui.terrainID'),`${a.terrain} · ${map.header.terrain_names[a.terrain!]}`],[t('ui.regionID'),`${a.region} · ${map.header.region_names[a.region!]??''}`],[t('ui.scriptTexture'),`${a.script} / ${a.texture}`],[t('ui.source'),map.header.source_sha256]]);
  const p=document.createElement('p');p.textContent=t('map.geographic');detail.append(p);
  const r=viewer.pack?.resources.get(a.texture!);if(r){const uv=[0,1,2].map(j=>[map.records.getUint8(triangle*72+66+j*2),map.records.getUint8(triangle*72+67+j*2)].join(',')).join(' / ');properties([[t('map.textures'),`${map.header.mapId}:${r.id} · ${r.name} · ${r.width}×${r.height}`],['UV',uv]]);}
 }
 function inspectTransition(record:MapTransition,target=detail){if(target===detail)appStore.dispatch({type:'select',selection:{kind:'transition',id:record.id,mapId:current}});target.replaceChildren();properties([[t('map.from'),record.from_map],[t('map.to'),record.to_map],[t('map.anchor'),record.from_anchor_kind],[t('map.x'),record.from_native_position?.map(x=>formatNumber(x)).join(' / ')??t('map.none')],[t('map.transform'),record.transform_kind],[t('map.evidence'),record.evidence_class],[t('ui.source'),`${record.source_file} · ${record.source_function??''} · ${record.instruction_offset??''}`]],target);const p=document.createElement('p');p.textContent=t('map.runtime');target.append(p);const advanced=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent=t('map.evidence');pre.textContent=JSON.stringify(record,null,2);advanced.append(summary,pre);target.append(advanced);if(['WM0','WM2','WM3'].includes(record.to_map)){const button=document.createElement('button');button.textContent=t('map.open');button.onclick=()=>{const destination=record.to_map as MapId;wm0List.open=false;void switchMap(destination).then(()=>{if(record.to_native_position)viewer?.focus(record.to_native_position);});};target.append(button);}}
 function drawTransitions(){registerNavigation('transitions',(transitions?.transitions??[]).filter(r=>['WM0','WM2','WM3'].includes(r.from_map)&&r.to_map!=='FIELD').map(r=>({id:r.id,kind:'transition' as const,name:r.from_map+' → '+r.to_map,aliases:[r.field_name??''],mapId:r.from_map as MapId,navigate:()=>{void switchMap(r.from_map as MapId).then(()=>inspectTransition(r));}})));list.replaceChildren();wm0Records.replaceChildren();const records=transitions?.transitions??[];for(const record of records.filter(r=>r.from_map===current)){const button=document.createElement('button');button.textContent=`${record.from_map} → ${record.to_map} · ${record.field_name??record.field_id??record.evidence_class}`;button.onclick=()=>inspectTransition(record);list.append(button);}for(const record of records.filter(r=>(r.from_map==='WM0'&&r.to_map!=='FIELD')||(r.from_map==='FIELD'&&r.to_map==='WM3'))){const box=document.createElement('div');inspectTransition(record,box);wm0Records.append(box);}viewer?.setTransitions(records,transitionsToggle.checked);}
 async function switchMap(id:MapId){if(id!==current){document.getElementById('clear-analysis')?.click();document.getElementById('measure-clear')?.click();const compare=document.getElementById('compare-projections') as HTMLInputElement|null;if(compare?.checked){compare.checked=false;compare.dispatchEvent(new Event('change'));}}appStore.dispatch({type:'map',id});document.dispatchEvent(new Event('gaiagis-map-changing'));const token=++request;viewer?.dispose();viewer=undefined;detail.replaceChildren();stats.textContent='';delete detail.dataset.triangle;delete detail.dataset.mapId;current=id;select.value=id;wm0Root.hidden=id!=='WM0';host.hidden=id==='WM0';getWM0()?.setSuspended(id!=='WM0');
  if(id==='WM0'){drawTransitions();return;}const map=maps.get(id);status.textContent=map?t('map.loaded'):t('map.unavailable');note.textContent=t('map.noGlobal');view.disabled=layer.disabled=relief.disabled=filter.disabled=shading.disabled=loadTexture.disabled=!map;
  if(map){const {NativeViewer}=await import('../viewer/NativeViewer');if(token!==request)return;viewer=new NativeViewer(viewport,map);viewer.onPick=inspect;viewer.onTransition=r=>inspectTransition(r);viewer.setView(view.value==='topdown');viewer.setRelief(Number(relief.value));viewer.shading(shading.checked);const buffer=textureBuffers.get(id);if(buffer){try{const pack=await decodeTextures(buffer,map,{sha256:map.sha256},{mapId:id,sourceHash:map.header.source_sha256});if(token!==request){pack.image.close();return;}viewer?.loadTextures(pack);if(appStore.state.localWorkspace!=='none')layer.value='texture';viewer?.filtering(filter.value==='linear');}catch{textureBuffers.delete(id);status.textContent=t('map.reject');}}viewer?.setLayer(layer.value as 'terrain'|'region'|'texture');}drawTransitions();}
 load.onclick=()=>geometry.click();loadTexture.onclick=()=>texture.click();loadTransitions.onclick=()=>transitionFile.click();back.onclick=()=>void switchMap('WM0');reset.onclick=()=>viewer?.reset();select.onchange=()=>void switchMap(select.value as MapId);
 geometry.onchange=async()=>{const file=geometry.files?.[0],token=request;if(!file)return;try{const map=await decodeNativeMap(await file.arrayBuffer());if(token!==request)return;if(current!==map.header.mapId)throw Error('Map chooser identity mismatch');if(transitions&&transitions.sources[map.header.mapId.toLowerCase()+'.map']!==map.header.source_sha256)throw Error('Transition source mismatch');maps.set(map.header.mapId,map);loadedAsset(map.header.mapId,file.size,map.header.version);textureBuffers.delete(map.header.mapId);await switchMap(map.header.mapId);}catch(e){status.textContent=t('map.reject');status.title=String(e);}finally{geometry.value='';}};
 texture.onchange=async()=>{const file=texture.files?.[0],map=viewer?.map,token=request;if(!file||!map)return;try{const buffer=await file.arrayBuffer(),pack=await decodeTextures(buffer,map,{sha256:map.sha256},{mapId:map.header.mapId,sourceHash:map.header.source_sha256});if(token!==request){pack.image.close();return;}textureBuffers.set(map.header.mapId,buffer);loadedAsset('textures-'+map.header.mapId as 'textures-WM2'|'textures-WM3',file.size);viewer?.loadTextures(pack);layer.value='texture';status.textContent=t('map.loaded');}catch(e){status.textContent=t('map.reject');status.title=String(e);}finally{texture.value='';}};
 transitionFile.onchange=async()=>{const file=transitionFile.files?.[0];if(!file)return;try{const hashes:Partial<Record<MapId,string>>={WM0:'43e72295212311fcec3a513051a96ca4475185a72211ebc3a5e4f89a50eca78c'};for(const [id,map]of maps)hashes[id]=map.header.source_sha256;transitions=parseTransitions(await file.text(),hashes);loadedAsset('transitions',file.size);drawTransitions();}catch(e){status.textContent=t('map.reject');status.title=String(e);}finally{transitionFile.value='';}};
 view.onchange=()=>viewer?.setView(view.value==='topdown');relief.onchange=()=>viewer?.setRelief(Number(relief.value));layer.onchange=()=>viewer?.setLayer(layer.value as 'terrain'|'region'|'texture');filter.onchange=()=>viewer?.filtering(filter.value==='linear');shading.onchange=()=>viewer?.shading(shading.checked);transitionsToggle.onchange=drawTransitions;
 function translate(){label.textContent=t('map.title');for(const option of select.options)option.textContent=t('map.'+option.value);load.textContent=t('map.load');loadTexture.textContent=t('texture.load');loadTransitions.textContent=wm0Transitions.textContent=t('map.loadTransitions');wm0Summary.textContent=transLabel.textContent=t('map.transitions');view.options[0].textContent=t('map.native3d');view.options[1].textContent=t('map.topdown');for(const option of layer.options)option.textContent=option.value==='texture'?t('map.textures'):option.value==='region'?t('ui.regions'):t('ui.terrain');filter.options[0].textContent=t('texture.nearest');filter.options[1].textContent=t('texture.linear');reliefLabel.textContent=t('map.height')+' ×';shadeLabel.textContent=t('texture.shading');back.textContent=t('map.return');reset.textContent=t('map.reset');note.textContent=t('map.noGlobal');if(current!=='WM0')status.textContent=maps.has(current)?t('map.loaded'):t('map.unavailable');if(viewer?.selected!=null)inspect(viewer.selected);drawTransitions();}
 for(const id of ['WM2','WM3'] as const){
  workspaceLoader.register(id,async files=>{const map=await decodeNativeMap(await files[0].arrayBuffer());if(map.header.mapId!==id)throw Error('Workspace native map identity mismatch');maps.set(id,map);textureBuffers.delete(id);loadedAsset(id,files[0].size,map.header.version);if(current===id)await switchMap(id);});
  workspaceLoader.register('textures-'+id as 'textures-WM2'|'textures-WM3',async files=>{const map=maps.get(id);if(!map)throw Error('Native texture dependency missing');const buffer=await files[0].arrayBuffer(),pack=await decodeTextures(buffer,map,{sha256:map.sha256},{mapId:id,sourceHash:map.header.source_sha256});textureBuffers.set(id,buffer);loadedAsset('textures-'+id as 'textures-WM2'|'textures-WM3',files[0].size);if(current===id&&viewer){viewer.loadTextures(pack);layer.value='texture';}else pack.image.close();});
 }
 workspaceLoader.register('transitions',async files=>{const hashes:Partial<Record<MapId,string>>={WM0:(getWM0()?.meta as {stage1?:{source_wm0_sha256:string}})?.stage1?.source_wm0_sha256.toLowerCase()};for(const [id,map]of maps)hashes[id]=map.header.source_sha256;transitions=parseTransitions(await files[0].text(),hashes);loadedAsset('transitions',files[0].size);drawTransitions();});
 translate();const stopLocale=onLocaleChange(translate);const timer=setInterval(()=>{if(viewer){stats.textContent=`${formatNumber(viewer.diagnostics.fps,0)} FPS · ${viewer.diagnostics.drawCalls} calls`;host.dataset.drawCalls=String(viewer.diagnostics.drawCalls);host.dataset.fps=String(viewer.diagnostics.fps);}},500);
 return {switchMap,async resetData(){await switchMap('WM0');maps.clear();textureBuffers.clear();transitions=undefined;drawTransitions();},get viewer(){return viewer;},get maps(){return maps;},dispose(){request++;viewer?.dispose();maps.clear();textureBuffers.clear();transitions=undefined;clearInterval(timer);stopLocale();host.remove();bar.remove();getWM0()?.setSuspended(false);}};
}
