// SPDX-License-Identifier: GPL-3.0-only
import '../styles/spatial.css';
import {t,formatNumber,onLocaleChange} from '../i18n';
import {appStore,capabilities} from '../app/state';
import {analyzeRoute,slopeRamp,aspectRamp,undefinedColor,serviceColor} from '../analysis/spatial';
import {serviceProfiles} from '../analysis/serviceArea';
import type {GaiaViewer} from '../viewer/GaiaViewer';
import type {GaiaMeta} from '../data/mesh';
import type {Endpoint} from '../data/routing';
export function mountSpatialUnavailable(){const root=document.createElement('section');root.id='spatial-unavailable';for(const key of ['profile','terrain','exposure','slope','aspect','service']){const card=document.createElement('section'),title=document.createElement('h3'),note=document.createElement('p');card.className='spatial-card';title.textContent=t('sp25.'+key);note.textContent=t('sp25.unavailable');card.append(title,note);root.append(card);}document.getElementById('app-group-analysis')?.append(root);return {dispose(){root.remove();}};}
interface Context {mode:string;conditional:boolean;starts:Endpoint[];}
export function mountSpatialAnalysis(viewer:GaiaViewer,meta:GaiaMeta,panel:HTMLElement,rpc:(kind:string,extra:Record<string,unknown>)=>Promise<any>,context:()=>Context|null){
 const root=document.createElement('section');root.id='spatial-analysis';root.innerHTML=`<h2>${t('sp25.title')}</h2>`;panel.append(root);
 const cards=new Map<string,HTMLElement>(),methodLabels:{input:HTMLElement;method:HTMLElement;key:string}[]=[];
 const card=(id:string,label:string,method:string,limit:string)=>{const c=document.createElement('section');c.id='spatial-'+id;c.className='spatial-card';c.innerHTML=`<h3>${t(label)}</h3><div class="spatial-result" role="status"></div><details><summary>${t('sp25.assumptions')}</summary><p>${t('sp25.input')}: WM0 source TIN</p><p>${t('sp25.method')}: ${t(method)}</p><p>${t(limit)}</p></details>`;root.append(c);cards.set(id,c);const notes=c.querySelectorAll<HTMLElement>('details p');methodLabels.push({input:notes[0],method:notes[1],key:method});return c.querySelector<HTMLElement>('.spatial-result')!;};
 const profile=card('profile','sp25.profile','sp25.routeMethod','sp25.routeLimit'),terrain=card('terrain','sp25.terrain','sp25.terrainMethod','sp25.routeLimit'),exposure=card('exposure','sp25.exposure','sp25.terrainMethod','sp25.encLimit');
 const surface=card('surface','sp25.surface','sp25.slope','sp25.slopeLimit'),service=card('network','sp25.service','sp25.service','sp25.serviceLimit');
 const controls=new Map<string,HTMLInputElement>();let path:number[]=[],graphDistance=0,revision=0,disposed=false,activeMode:string|null=null,summary:ReturnType<typeof analyzeRoute>|null=null;
 const layer=(id:string,key:string,parent:HTMLElement)=>{const label=document.createElement('label'),c=document.createElement('input');c.type='checkbox';c.id='spatial-'+id;label.htmlFor=c.id;label.className='toggle-row';label.append(c,document.createTextNode(t(key)));parent.append(label);controls.set(id,c);c.onchange=()=>{if(c.checked){for(const [other,v]of controls)if(other!==id)v.checked=false;activeMode=id;}else if(activeMode===id)activeMode=null;viewer.setSpatialLayer(activeMode as 'slope'|'aspect'|'service-area'|null);if(id==='slope'||id==='aspect'){const a=viewer.sourceSurfaceAnalysis;surface.dataset.triangles=String(a.slope.length);surface.dataset.cacheBytes=String(a.bytes);surface.dataset.elapsedMs=String(a.elapsedMs);}document.dispatchEvent(new Event('gaiagis-spatial-layer'));};return c;};
 layer('slope','sp25.slope',surface);layer('aspect','sp25.aspect',surface);layer('service-area','sp25.service',service);
 const limitLabel=document.createElement('label'),limit=document.createElement('input'),calculate=document.createElement('button'),networkResult=document.createElement('div');limitLabel.htmlFor='service-threshold';limitLabel.textContent=t('sp25.threshold');limit.id='service-threshold';limit.type='number';limit.min='0';limit.max='40000';limit.step='50';limit.value='100';calculate.id='calculate-service';calculate.textContent=t('sp25.calculate');service.append(limitLabel,limit,calculate,networkResult);
 const metrics=(parent:HTMLElement,rows:[string,number,string?][])=>{const dl=document.createElement('dl');dl.className='spatial-metrics';for(const [key,value,unit]of rows){const d=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t(key);dd.textContent=formatNumber(value,2)+(unit?' '+unit:'');d.append(dt,dd);dl.append(d);}parent.append(dl);};
 const table=(parent:HTMLElement,rows:{id:string;distance:number;percentage:number;set?:any}[],isTerrain=false)=>{const table=document.createElement('table'),thead=document.createElement('thead'),tr=document.createElement('tr');for(const text of [t(isTerrain?'sp25.terrain':'sp25.exposure'),'km',t('sp25.share')]){const th=document.createElement('th');th.scope='col';th.textContent=text;tr.append(th);}thead.append(tr);table.append(thead);const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const text of [isTerrain?meta.terrain_names[row.id]??row.id:row.id,formatNumber(row.distance/1000,2),formatNumber(row.percentage,1)+'%']){const td=document.createElement('td');td.textContent=text;tr.append(td);}body.append(tr);}table.append(body);parent.append(table);};
 function drawRoute(){profile.replaceChildren();terrain.replaceChildren();exposure.replaceChildren();if(!path.length){for(const c of [profile,terrain,exposure])c.textContent=t('sp25.solveFirst');summary=null;return;}summary=analyzeRoute(viewer.mesh,path,viewer.encounterData);root.dataset.routeMs=String(summary.elapsedMs);root.dataset.samples=String(summary.samples.length);root.dataset.summary=JSON.stringify({metrics:summary.metrics,terrain:summary.terrain,exposure:summary.exposure.map(r=>({id:r.id,distance:r.distance,percentage:r.percentage})),chocoboDistance:summary.chocoboDistance});
  const m=summary.metrics;if(m){metrics(profile,[['sp25.distance',m.distance/1000],['sp25.graphDistance',graphDistance/1000],['sp25.min',m.min,'m'],['sp25.max',m.max,'m'],['sp25.ascent',m.ascent,'m'],['sp25.descent',m.descent,'m']]);const heading=document.createElement('p');heading.textContent=t('sp25.displayHeight');profile.append(heading);
   const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 300 120');svg.setAttribute('role','img');svg.setAttribute('aria-label',t('sp25.profile'));const line=document.createElementNS(ns,'polyline'),x=(i:number)=>8+summary!.samples[i].distance/Math.max(1,m.distance)*284,y=(i:number)=>108-(summary!.samples[i].elevation-m.min)/Math.max(1,m.max-m.min)*100;line.setAttribute('points',summary.samples.map((_,i)=>`${x(i)},${y(i)}`).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','var(--accent)');line.setAttribute('stroke-width','2');svg.append(line);const mark=document.createElementNS(ns,'circle');mark.setAttribute('r','3');mark.setAttribute('fill','var(--accent)');svg.append(mark);const slider=document.createElement('input'),label=document.createElement('label'),out=document.createElement('output');slider.type='range';slider.id='profile-sample';slider.min='0';slider.max=String(summary.samples.length-1);slider.step='1';slider.value='0';label.htmlFor=slider.id;label.textContent=t('sp25.inspect');const inspect=(i:number)=>{slider.value=String(i);const s=summary!.samples[i];mark.setAttribute('cx',String(x(i)));mark.setAttribute('cy',String(y(i)));out.textContent=`${t('sp25.distance')}: ${formatNumber(s.distance/1000,2)}\n${t('sp25.displayHeight')}: ${formatNumber(s.elevation,2)}\n${t('sp25.raw')}: ${formatNumber(s.rawHeight,2)}`;};slider.oninput=()=>inspect(Number(slider.value));svg.onpointermove=e=>{const b=svg.getBoundingClientRect(),target=Math.max(0,Math.min(1,(e.clientX-b.left)/b.width))*m.distance;let index=0;for(let i=1;i<summary!.samples.length;i++)if(Math.abs(summary!.samples[i].distance-target)<Math.abs(summary!.samples[index].distance-target))index=i;inspect(index);};profile.append(svg,label,slider,out);inspect(0);
  }table(terrain,summary.terrain,true);if(summary.encountersAvailable){table(exposure,summary.exposure);metrics(exposure,[['sp25.chocobo',summary.chocoboDistance/1000,'km']]);for(const row of summary.exposure){const d=document.createElement('details'),s=document.createElement('summary'),p=document.createElement('p');s.textContent=row.id;p.textContent=Object.entries(row.set!.records).map(([kind,records])=>`${kind}: ${records.map(r=>r.scene_id).join(', ')}`).join('\n');d.append(s,p);exposure.append(d);}}else exposure.textContent=t('sp25.encMissing');
 }
 calculate.onclick=async()=>{const c=context();if(!c){networkResult.textContent=t('routing.choose');return;}if(!serviceProfiles.includes(c.mode)){networkResult.textContent=t('sp25.unavailable');return;}const threshold=Number(limit.value)*1000;if(!limit.value||!Number.isFinite(threshold)||threshold<0||threshold>40_000_000){limit.reportValidity();return;}const stamp=++revision;networkResult.textContent=t('routing.busy');try{const r=await rpc('service',{...c,threshold});if(stamp!==revision||disposed||!available())return;viewer.setServiceArea(r.flags);networkResult.replaceChildren();const provenance=document.createElement('p');provenance.textContent=t('routing.from')+': '+(panel.querySelector<HTMLInputElement>('#route-from')?.value??'')+' · '+t('routing.mode')+': '+t('mode.'+c.mode)+' · '+t('routing.conditional')+': '+String(c.conditional);networkResult.append(provenance);metrics(networkResult,[['sp25.visited',r.visited],['sp25.components',r.components],['sp25.threshold',r.threshold/1000],['sp25.elapsed',r.elapsedMs]]);service.dataset.visited=String(r.visited);service.dataset.elapsedMs=String(r.elapsedMs);service.dataset.profile=c.mode;service.dataset.conditional=String(c.conditional);controls.get('service-area')!.checked=true;controls.get('service-area')!.dispatchEvent(new Event('change',{bubbles:true}));}catch(e){if(stamp===revision){networkResult.textContent=t('error.dataset');networkResult.title=String(e);}}};
 const legend=document.createElement('section');legend.className='spatial-legend';legend.id='spatial-legends';root.append(legend);for(const [key,colors,names]of [['sp25.slope',slopeRamp,['0°','20°','40°','60°+']],['sp25.aspect',aspectRamp,['N','NE','E','SE','S','SW','W','NW']],['sp25.service',[serviceColor],['sp25.visited']]] as [string,readonly string[],string[]][]){const h=document.createElement('h4');h.textContent=t(key);legend.append(h);colors.forEach((color,i)=>{const p=document.createElement('div'),swatch=document.createElement('i');swatch.style.background=color;p.append(swatch,document.createTextNode(names[i].startsWith('sp25.')?t(names[i]):names[i]));legend.append(p);});}const flat=document.createElement('p');flat.textContent=t('sp25.undefined');flat.style.borderLeft=`16px solid ${undefinedColor}`;legend.append(flat);
 const unavailable=document.createElement('p');unavailable.id='spatial-map-unavailable';unavailable.className='spatial-card';unavailable.textContent=t('sp25.unavailable');unavailable.hidden=true;
 const available=()=>appStore.state.map.id==='WM0'&&appStore.state.explorer.phase==='idle';const unsubscribe=appStore.subscribe(()=>{const group=document.getElementById('app-group-layers');if(group&&legend.parentElement!==group)group.append(legend);const ag=document.getElementById('app-group-analysis');if(ag&&unavailable.parentElement!==ag)ag.append(unavailable);const ok=available();unavailable.hidden=ok;for(const c of controls.values())c.disabled=!ok;calculate.disabled=!ok||!capabilities(appStore.state).canRoute;controls.get('service-area')!.disabled=!ok||appStore.state.data.assets.routing?.status!=='loaded';limit.disabled=calculate.disabled;root.dataset.available=String(ok);if(!ok)revision++;});
 const stopLocale=onLocaleChange(()=>{for(const row of methodLabels){row.input.textContent=t('sp25.input')+': WM0 source TIN';row.method.textContent=t('sp25.method')+': '+t(row.key);}drawRoute();}),encounterChanged=()=>{if(path.length)drawRoute();};document.addEventListener('gaiagis-encounters-loaded',encounterChanged);drawRoute();
 return {setRoute(nodes:number[],distance=0){path=nodes;graphDistance=distance;drawRoute();},clear(){revision++;path=[];viewer.setServiceArea(null);networkResult.replaceChildren();delete service.dataset.visited;controls.get('service-area')!.checked=false;if(activeMode==='service-area'){activeMode=null;viewer.setSpatialLayer(null);}drawRoute();},dispose(){disposed=true;revision++;unsubscribe();stopLocale();document.removeEventListener('gaiagis-encounters-loaded',encounterChanged);root.remove();legend.remove();unavailable.remove();}};
}
