import {workspaceLoader,loadedAsset} from '../app/assets';
// SPDX-License-Identifier: GPL-3.0-only
import {decodeTextures} from '../data/textures';
import type {GaiaViewer} from '../viewer/GaiaViewer';
import {t,formatNumber} from '../i18n';
export function mountTextures(viewer:GaiaViewer,current:()=>boolean){
 const host=document.createElement('section');host.className='texture-controls';host.innerHTML=`<label class="field-label" for="surface-style">${t('texture.surface')}</label><select id="surface-style"><option value="terrain">${t('ui.terrain')}</option><option value="region">${t('ui.regions')}</option><option value="texture" disabled>${t('texture.original')}</option></select><button id="load-textures">${t('texture.load')}</button><input id="local-textures-file" type="file" accept=".bin" hidden/><p id="texture-status" class="control-note" role="status">${t('texture.unavailable')}</p><label class="field-label" for="relief-preset">${t('texture.relief')}</label><select id="relief-preset"><option value="0">${t('texture.flat')}</option>${[1,10,25,50,100].map(n=>`<option value="${n}" ${n===1?'selected':''}>${n}×</option>`).join('')}<option value="custom">${t('texture.custom')}</option></select><input id="relief-custom" type="range" min="0" max="100" step="1" value="1" hidden aria-label="${t('texture.relief')}"/><output id="relief-value">1×</output><label class="field-label" for="texture-filter">${t('texture.filter')}</label><select id="texture-filter"><option value="nearest">${t('texture.nearest')}</option><option value="linear">${t('texture.linear')}</option></select><label class="switch-row"><span>${t('texture.shading')}</span><input id="relief-shading" type="checkbox"/></label><p class="control-note">${t('texture.note')}</p>`;
 document.querySelector('.controls .panel-heading')!.after(host);const get=<T extends HTMLElement>(id:string)=>host.querySelector<T>(`#${id}`)!;
 let ticket=0;
 const label=document.querySelector<HTMLElement>('label[for=color-layer]')!;const syncLabel=()=>label.textContent=t(style.value==='texture'?'texture.overlay':'ui.color');
 const style=get<HTMLSelectElement>('surface-style'),filter=get<HTMLSelectElement>('texture-filter'),file=get<HTMLInputElement>('local-textures-file'),status=get('texture-status');
 get('load-textures').onclick=()=>file.click();const loadFile=async(f:File)=>{const request=++ticket;let pending:Awaited<ReturnType<typeof decodeTextures>>|null=null;try{if(f.size>64_000_000)throw new Error('Texture pack too large');const pack=await decodeTextures(await f.arrayBuffer(),viewer.mesh,viewer.meta);pending=pack;if(!current()||request!==ticket){pack.image.close();pending=null;return;}viewer.loadTextures(pack);loadedAsset("textures",f.size);pending=null;viewer.setTextureFiltering(filter.value==='linear');style.querySelector<HTMLOptionElement>('[value=texture]')!.disabled=false;style.value='texture';viewer.setSurfaceStyle('texture');syncLabel();status.textContent=t('texture.loaded',{count:pack.resources.size});}catch(e){pending?.image.close();if(current()&&request===ticket)status.textContent=t('texture.error',{reason:String(e instanceof Error?e.message:e)});throw e;}finally{if(request===ticket)file.value='';}};file.onchange=async()=>{const f=file.files?.[0];if(f)try{await loadFile(f);}catch{}};workspaceLoader.register('textures',async files=>loadFile(files[0]));
 style.onchange=()=>{syncLabel();viewer.setSurfaceStyle(style.value as 'terrain'|'region'|'texture');const layer=document.getElementById('color-layer') as HTMLSelectElement;layer.value=style.value==='region'?'region':'terrain';layer.dispatchEvent(new Event('change'));};filter.onchange=()=>viewer.setTextureFiltering(filter.value==='linear');get<HTMLInputElement>('relief-shading').onchange=e=>viewer.setReliefShading((e.target as HTMLInputElement).checked);
 const preset=get<HTMLSelectElement>('relief-preset'),slider=get<HTMLInputElement>('relief-custom');const relief=(n:number)=>{viewer.setRelief(n);get('relief-value').textContent=`${formatNumber(n,0)}×`;};preset.onchange=()=>{slider.hidden=preset.value!=='custom';relief(preset.value==='custom'?Number(slider.value):Number(preset.value));};slider.oninput=()=>relief(Number(slider.value));
 return {inspect(source:number,detail:HTMLElement){const section=document.createElement('details');section.className='texture-inspector';const title=document.createElement('summary');title.textContent=t('texture.inspector');section.append(title);const a=viewer.mesh.attributes(source),pack=viewer.texturePack,r=a.texture===null?undefined:pack?.resources.get(a.texture),p=pack?.records.get(`${a.section}/${a.mesh}/${a.triangle}`);const note=document.createElement('p');if(a.origin)note.textContent=t('texture.synthetic');else if(!r||p===undefined||!pack)note.textContent=t('texture.unavailable');else{const raw=Array.from({length:3},(_,j)=>[pack.uv.getUint8(p+8+j*2),pack.uv.getUint8(p+9+j*2)]),list=document.createElement('dl');list.className='property-list';for(const [label,value]of [[t('texture.resource'),`${r.id} · ${r.name}.tex`],[t('texture.dimensions'),`${r.width} × ${r.height}`],[t('texture.raw'),raw.map(v=>v.join('/')).join(' · ')],[t('texture.atlas'),raw.map(([u,v])=>`${formatNumber((r.x+((u-r.u_offset)%r.width+r.width)%r.width)/pack.metadata.atlas.width,5)}/${formatNumber((r.y+((v-r.v_offset)%r.height+r.height)%r.height)/pack.metadata.atlas.height,5)}`).join(' · ')],[t('texture.filter'),t(filter.value==='linear'?'texture.linear':'texture.nearest')]]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);list.append(row);}section.append(list);const advanced=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('p');summary.textContent=t('texture.format');body.className='control-note';body.textContent=JSON.stringify(r.format)+((r as typeof r&{frame_count?:number}).frame_count?' · '+t('texture.static'):'');advanced.append(summary,body);section.append(advanced);}section.append(note);detail.append(section);}};
}
