// SPDX-License-Identifier: GPL-3.0-only
import '../styles/user-mapping.css';
import {appStore} from '../app/state';
import {clearNavigation,registerNavigation,setNavigationSelection} from '../app/navigation';
import {ResourceScope} from '../app/resources';
import {userStateStorage} from '../app/userState';
import {createFeature,deleteLayer,editFeature,exportGaiaJSON,featureMeasurements,geographicVertex,importGaiaJSON,mergeMapping,moveFeature,reorderLayer,validateGeometry,vertexGeographic,MAPPING_LIMITS} from '../app/userMapping';
import type {GameVertex,GeometryType,UserFeature,UserLayer} from '../app/userMapping';
import {compileMapping} from '../viewer/userMappingOverlay';
import {screenGeographic} from '../navigation/scale';
import {formatNumber,onLocaleChange,t} from '../i18n';
import type {GaiaViewer} from '../viewer/GaiaViewer';
import type {MapId} from '../data/nativeMaps';

type Tool='select'|GeometryType|'edit'|'move'|'add';
export function mountUserMapping(getViewer:()=>GaiaViewer|undefined,switchMap:(id:MapId)=>Promise<void>){
 const scope=new ResourceScope(),storage=userStateStorage(),drawing=document.createElement('details'),layers=document.createElement('details'),card=document.createElement('section'),dialog=document.createElement('dialog');
 drawing.id='user-drawing';layers.id='user-layers';card.id='user-feature-card';dialog.id='user-layer-dialog';card.hidden=true;
 const title=(root:HTMLElement,key:string)=>{const s=document.createElement('summary');s.textContent=t('user26.'+key);root.append(s);};title(drawing,'title');title(layers,'layers');
 document.getElementById('app-group-explore')!.append(drawing);document.getElementById('app-group-layers')!.append(layers);document.getElementById('integrated-inspector')!.append(card);document.body.append(dialog);
 scope.own(()=>{drawing.remove();layers.remove();card.remove();dialog.remove();});
 const button=(key:string,id:string,fn:()=>void)=>{const b=document.createElement('button');b.id=id;b.type='button';b.textContent=t('user26.'+key);b.onclick=fn;return b;};
 const note=(key:string)=>{const p=document.createElement('p');p.className='control-note';p.textContent=t('user26.'+key);return p;};
 const actions=(parent:HTMLElement)=>{const a=document.createElement('div');a.className='user-actions';parent.append(a);return a;};
 const layerMemory=note('memory');layerMemory.setAttribute('role','status');layers.append(layerMemory);const layerStatus=document.createElement('p');layerStatus.id='user-layers-status';layerStatus.setAttribute('role','status');layers.append(layerStatus);
 const status=document.createElement('p'),warning=document.createElement('p'),unavailable=note('unavailable');status.id='user-mapping-status';status.setAttribute('role','status');warning.id='user-storage-warning';warning.setAttribute('role','status');drawing.append(note('local'),note('help'),unavailable,status,warning);
 const tools=actions(drawing),toolButtons=new Map<Tool,HTMLButtonElement>();let tool:Tool='select',draft:GameVertex[]=[],layerId=storage.state.userLayers[0]?.id??'',vertexIndex=0,preview:UserFeature|null=null,mappingKey='',inspectorKey='',disposed=false;
 const available=()=>!!getViewer()&&appStore.state.map.id==='WM0'&&appStore.state.explorer.phase==='idle'&&appStore.state.analysis.tool==='none';
 const selected=()=>appStore.state.selection?.kind==='user-feature'?storage.state.userFeatures.find(f=>f.id===appStore.state.selection!.id):undefined;
 const message=(key:string,reason?:unknown)=>{status.textContent=layerStatus.textContent=t('user26.'+key,reason?{reason:reason instanceof Error?reason.message:String(reason)}:{});};
 function attempt(fn:()=>void){try{fn();message('saved');}catch(e){message('error',e);}}
 function render(){const v=getViewer();if(!v)return;const state=storage.state,data={userLayers:state.userLayers,userFeatures:preview?state.userFeatures.map(f=>f.id===preview!.id?preview!:f):state.userFeatures};v.setUserMapping(compileMapping(data,selected()?.id??null,draft,tool==='Polygon'));}
 function setTool(next:Tool){tool=next;draft=[];preview=null;for(const [id,b]of toolButtons){b.setAttribute('aria-pressed',String(id===next));}getViewer()?.cancelMotion();if(next!=='select')appStore.dispatch({type:'analysis',tool:'none'});render();status.textContent=t('user26.active',{tool:t('user26.'+({select:'select',edit:'edit',move:'move',add:'addVertex'}[next as 'select'|'edit'|'move'|'add']??next)),count:0});drawing.dataset.tool=tool;getViewer()?.renderer.domElement.parentElement?.classList.toggle('user-drawing-active',next!=='select');if(next!=='select'&&innerWidth<1100){document.getElementById('integrated-panel')?.classList.remove('open');document.getElementById('integrated-inspector')?.classList.remove('open');document.getElementById('app-menu')?.setAttribute('aria-expanded','false');document.getElementById('toggle-inspector')?.setAttribute('aria-expanded','false');}}
 for(const value of ['select','Point','Polyline','Polygon'] as const){const b=button(value,'draw-'+value,()=>setTool(value));toolButtons.set(value,b);tools.append(b);}
 const layerSelect=document.createElement('select'),layerLabel=document.createElement('label');layerSelect.id='draw-layer';layerLabel.htmlFor=layerSelect.id;layerLabel.textContent=t('user26.layer');layerSelect.onchange=()=>layerId=layerSelect.value;drawing.append(layerLabel,layerSelect);
 const finish=button('finish','draw-finish',()=>finishDrawing()),cancel=button('cancel','draw-cancel',()=>setTool('select'));const ends=actions(drawing);ends.append(finish,cancel);
 const layerList=document.createElement('div'),layerActions=actions(layers);layerList.id='user-layer-list';layers.append(layerList,note('importHelp'));
 layerActions.append(button('newLayer','user-layer-create',()=>nameDialog(null)));
 const exchange=actions(layers),file=document.createElement('input');file.type='file';file.accept='.gaiagis.json,application/json';file.id='user-gaiajson-file';file.hidden=true;layers.append(file);
 exchange.append(button('export','user-export',()=>attempt(()=>{const blob=new Blob([exportGaiaJSON(storage.state)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='my-layers.gaiagis.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})),button('import','user-import',()=>file.click()));
 file.onchange=()=>{const chosen=file.files?.[0];if(!chosen)return;if(chosen.size>MAPPING_LIMITS.bytes){message('error','file exceeds 4 MiB');file.value='';return;}void chosen.text().then(text=>{if(disposed)return;try{storage.update(s=>mergeMapping(s,importGaiaJSON(text)));message('imported');}catch(e){message('error',e);}}).catch(e=>message('error',e)).finally(()=>file.value='');};
 function confirm(key:string,fn:()=>void,count=0){dialog.replaceChildren();const p=document.createElement('p');p.textContent=t('user26.'+key,{count});const a=actions(dialog);a.append(button('cancel','user-confirm-cancel',()=>dialog.close()),button('delete','user-confirm-delete',()=>{dialog.close();attempt(fn);}));dialog.prepend(p);dialog.showModal();document.getElementById('user-confirm-cancel')?.focus();}
 function nameDialog(layer:UserLayer|null){dialog.replaceChildren();const label=document.createElement('label'),input=document.createElement('input');input.id='user-layer-name';input.maxLength=120;input.value=layer?.name??t('user26.layers');label.htmlFor=input.id;label.textContent=t('user26.name');dialog.append(label,input);actions(dialog).append(button('cancel','user-name-cancel',()=>dialog.close()),button('save','user-name-save',()=>attempt(()=>{storage.update(s=>{const name=input.value.trim();if(!name)throw Error('name required');if(layer)s.userLayers.find(l=>l.id===layer.id)!.name=name;else{s.userLayers.sort((a,b)=>a.order-b.order).forEach((l,order)=>l.order=order);const id=crypto.randomUUID();s.userLayers.push({id,name,visible:true,opacity:1,order:s.userLayers.length});layerId=id;}});dialog.close();})));dialog.showModal();input.focus();}
 function finishDrawing(){if(tool!=='Polyline'&&tool!=='Polygon')return;attempt(()=>{const f=createFeature(layerId,tool as GeometryType,draft,t('user26.'+tool));storage.update(s=>s.userFeatures.push(f));setTool('select');selectFeature(f.id);});}
 async function navigate(id:string,fly=false){if(appStore.state.explorer.phase!=='idle')return;if(appStore.state.map.id!=='WM0')await switchMap('WM0');if(disposed)return;selectFeature(id);const f=storage.state.userFeatures.find(f=>f.id===id),p=f&&vertexGeographic(f.geometry.vertices[0]);if(fly&&p)getViewer()?.flyToLocation(p[0],p[1]);}
 function selectFeature(id:string){const f=storage.state.userFeatures.find(f=>f.id===id);if(!f||appStore.state.map.id!=='WM0')return;setNavigationSelection(null);getViewer()?.clearSelection();vertexIndex=0;appStore.dispatch({type:'select',selection:{kind:'user-feature',id,mapId:'WM0',geographicPoint:vertexGeographic(f.geometry.vertices[0])}});render();}
 function drawLayers(){layerList.replaceChildren();layerSelect.replaceChildren();for(const layer of [...storage.state.userLayers].sort((a,b)=>a.order-b.order)){const option=document.createElement('option');option.value=layer.id;option.textContent=layer.name;option.dataset.userText='';layerSelect.append(option);const row=document.createElement('div'),head=document.createElement('div'),visible=document.createElement('input'),name=document.createElement('strong');row.className='user-layer';row.dataset.layerId=layer.id;head.className='user-layer-head';visible.type='checkbox';visible.checked=layer.visible;visible.setAttribute('aria-label',t('user26.visible')+' '+layer.name);visible.id='user-visible-'+layer.id;visible.onchange=()=>attempt(()=>storage.update(s=>s.userLayers.find(l=>l.id===layer.id)!.visible=visible.checked));name.textContent=layer.name;name.dataset.userText='';head.append(visible,name);row.append(head);
  const range=document.createElement('input');range.type='range';range.min='0';range.max='1';range.step='.05';range.value=String(layer.opacity);range.setAttribute('aria-label',t('user26.opacity')+' '+layer.name);range.id='user-opacity-'+layer.id;range.onchange=()=>attempt(()=>storage.update(s=>s.userLayers.find(l=>l.id===layer.id)!.opacity=Number(range.value)));row.append(range);const a=actions(row);a.append(button('rename','user-rename-'+layer.id,()=>nameDialog(layer)),button('up','user-up-'+layer.id,()=>attempt(()=>storage.update(s=>reorderLayer(s,layer.id,-1)))),button('down','user-down-'+layer.id,()=>attempt(()=>storage.update(s=>reorderLayer(s,layer.id,1)))),button('delete','user-delete-layer-'+layer.id,()=>{const count=storage.state.userFeatures.filter(f=>f.layerId===layer.id).length,fn=()=>storage.update(s=>deleteLayer(s,layer.id));if(count)confirm('confirmLayer',fn,count);else attempt(fn);}));const list=document.createElement('div');list.className='user-feature-list';for(const f of storage.state.userFeatures.filter(f=>f.layerId===layer.id)){const b=button('select','user-feature-'+f.id,()=>void navigate(f.id));b.textContent=f.name+' · '+t('user26.'+f.geometryType);b.dataset.userText='';b.dataset.featureId=f.id;list.append(b);}row.append(list);layerList.append(row);
 }if(!storage.state.userLayers.some(l=>l.id===layerId))layerId=storage.state.userLayers[0]?.id??'';layerSelect.value=layerId;if(!storage.state.userFeatures.length)layerList.append(note('empty'));layers.dataset.features=String(storage.state.userFeatures.length);layers.dataset.vertices=String(storage.state.userFeatures.reduce((n,f)=>n+f.geometry.vertices.length,0));}
 function drawInspector(force=false){const f=selected(),key=JSON.stringify([f,storage.state.userLayers]);card.hidden=!f;if(!force&&key===inspectorKey)return;inspectorKey=key;card.replaceChildren();if(!f)return;card.dataset.featureId=f.id;const h=document.createElement('h2');h.textContent=t('user26.created')+' · '+t('user26.'+f.geometryType);card.append(h,note('local'));if(storage.status==='memory')card.append(note('memory'));const m=featureMeasurements(f),dl=document.createElement('dl');dl.className='property-list';for(const [key,value]of [['vertices',String(f.geometry.vertices.length)],['length',formatNumber(m.length/1000,3)+' km'],['area',formatNumber(m.area/1e6,5)+' km²'],['createdAt',new Date(f.createdAt).toLocaleString()],['updatedAt',new Date(f.updatedAt).toLocaleString()]]){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t('user26.'+key);dd.textContent=value;row.append(dt,dd);dl.append(row);}card.append(dl,note('measure'));
  const form=document.createElement('form');form.id='user-feature-form';const field=(key:string,kind='text',value='')=>{const label=document.createElement('label'),input=key==='note'?document.createElement('textarea'):document.createElement('input');input.id='user-field-'+key;if(input instanceof HTMLInputElement)input.type=kind;input.value=value;label.htmlFor=input.id;label.textContent=t('user26.'+key);form.append(label,input);return input;};
  const name=field('name','text',f.name),noteInput=field('note','text',f.note),tags=field('tags','text',f.tags.join(', ')),color=field('color','color',f.style.color),size=field('size','number',String(f.style.pointSize)),fill=field('fill','number',String(f.style.fillOpacity));name.maxLength=120;noteInput.maxLength=1000;tags.maxLength=264;(size as HTMLInputElement).min='3';(size as HTMLInputElement).max='18';(fill as HTMLInputElement).min='0';(fill as HTMLInputElement).max='.6';(fill as HTMLInputElement).step='.01';const label=document.createElement('label'),select=document.createElement('select');select.id='user-field-layer';label.htmlFor=select.id;label.textContent=t('user26.layer');for(const l of storage.state.userLayers){const o=document.createElement('option');o.value=l.id;o.textContent=l.name;o.dataset.userText='';select.append(o);}select.value=f.layerId;form.append(label,select);const save=button('save','user-feature-save',()=>{});save.type='submit';form.append(save);form.onsubmit=e=>{e.preventDefault();attempt(()=>storage.update(s=>editFeature(s,f.id,{name:name.value.trim(),note:noteInput.value,tags:[...new Set(tags.value.split(',').map(t=>t.trim()).filter(Boolean))],style:{color:color.value,pointSize:Number(size.value),fillOpacity:Number(fill.value)},layerId:select.value})));};card.append(form);
  const a=actions(card);a.append(button('edit','user-edit',()=>setTool('edit')),button('move','user-move',()=>setTool('move')),button('fly','user-fly',()=>void navigate(f.id,true)),button('duplicate','user-duplicate',()=>attempt(()=>{const copy=structuredClone(f);copy.id=crypto.randomUUID();copy.createdAt=copy.updatedAt=Date.now();storage.update(s=>s.userFeatures.push(copy));selectFeature(copy.id);})),button('delete','user-delete-feature',()=>confirm('confirmFeature',()=>{setTool('select');storage.update(s=>s.userFeatures=s.userFeatures.filter(row=>row.id!==f.id));appStore.dispatch({type:'select',selection:null});})));card.append(note('editHelp'));const vertices=document.createElement('div');vertices.id='user-vertices';f.geometry.vertices.forEach((v,i)=>{const b=button('select','user-vertex-'+i,()=>{vertexIndex=i;drawInspector(true);});b.textContent=(i+1)+': '+formatNumber(v.game_east,2)+' / '+formatNumber(v.game_north,2);b.dataset.userText='';b.setAttribute('aria-pressed',String(vertexIndex===i));vertices.append(b);});card.append(vertices);const va=actions(card),add=button('addVertex','user-add-vertex',()=>setTool('add')),remove=button('delete','user-remove-vertex',()=>attempt(()=>storage.update(s=>{const vertices=f.geometry.vertices.filter((_,i)=>i!==vertexIndex);editFeature(s,f.id,{geometry:validateGeometry(f.geometryType,{...f.geometry,vertices})});vertexIndex=Math.max(0,vertexIndex-1);})));add.disabled=f.geometryType==='Point';remove.disabled=f.geometry.vertices.length<=(f.geometryType==='Point'?1:f.geometryType==='Polyline'?2:3);va.append(add,remove);
  for(const id of ['user-edit','user-move','user-add-vertex','user-fly']){const b=document.getElementById(id) as HTMLButtonElement;b.disabled||=!available();}
 }
 function refresh(){const key=JSON.stringify([storage.state.userLayers,storage.state.userFeatures]);if(key!==mappingKey){mappingKey=key;drawLayers();render();const state=storage.state;registerNavigation('user-mapping',state.userFeatures.map(f=>{const layer=state.userLayers.find(l=>l.id===f.layerId)!,point=f.geometryType==='Point';return {id:f.id,kind:'user-feature',mapId:'WM0',name:f.name,aliases:f.tags,target:{kind:'user-feature',id:f.id,mapId:'WM0'},anchor:point&&layer.visible&&layer.opacity>0?vertexGeographic(f.geometry.vertices[0]):undefined,precision:point?'user_created':undefined,group:'user',canTour:point,navigate:()=>void navigate(f.id,true)};}));if(appStore.state.selection?.kind==='user-feature'){const f=selected();if(!f)appStore.dispatch({type:'select',selection:null});else{const geographicPoint=vertexGeographic(f.geometry.vertices[0]);if(JSON.stringify(appStore.state.selection.geographicPoint)!==JSON.stringify(geographicPoint))appStore.dispatch({type:'select',selection:{kind:'user-feature',id:f.id,mapId:'WM0',geographicPoint}});}}}drawInspector();warning.hidden=layerMemory.hidden=storage.status!=='memory';warning.textContent=t('user26.memory');updateAvailability();}
 function updateAvailability(){const enabled=available();unavailable.hidden=enabled;for(const [key,b]of toolButtons)b.disabled=key!=='select'&&(!enabled||!layerId);finish.disabled=!enabled||!['Polyline','Polygon'].includes(tool)||draft.length<(tool==='Polyline'?2:3);if(!enabled&&tool!=='select')setTool('select');if(getViewer()&&appStore.state.map.id!=='WM0')getViewer()!.userMapping.objects.forEach(o=>o.visible=false);}
 const v=getViewer();let drag:{pointer:number;startX:number;startY:number;origin:GameVertex|null;feature:UserFeature|null;vertex:number;active:boolean}|null=null,lastClick={time:0,x:0,y:0};
 const canvas=v?.renderer.domElement;let suppressMarkerClick=false;
 const coordinate=(e:PointerEvent)=>{if(!v||!canvas)return null;const r=canvas.getBoundingClientRect(),p=screenGeographic(v.overviewBridge.camera,v.projectionId,v.context,e.clientX-r.left,e.clientY-r.top,r.width,r.height,v.viewState().center);if(!p)return null;try{return geographicVertex(p);}catch{return null;}};
 const hit=(e:PointerEvent)=>{if(!v||!canvas)return null;const r=canvas.getBoundingClientRect();return v.userMapping.hit(e.clientX-r.left,e.clientY-r.top,r.width,r.height,v.overviewBridge.camera,e.pointerType==='touch'?22:14);};
 const consume=(e:Event)=>{e.preventDefault();e.stopImmediatePropagation();};
 function restoreControls(){if(v&&!v.captureExplorer)v.overviewBridge.controls.enabled=true;}
 if(canvas&&v){const down=(e:PointerEvent)=>{if(!(e.target instanceof Element)||!e.target.closest('canvas,.location-marker'))return;suppressMarkerClick=false;const selectingCompare=tool==='select'&&appStore.state.map.id==='WM0'&&appStore.state.explorer.phase==='idle'&&appStore.state.analysis.tool==='compare';if((!available()&&!selectingCompare)||v.isMorphing||e.button!==0)return;if(drag){consume(e);return;}const target=hit(e),editing=['edit','move'].includes(tool),own=tool!=='select'||!!target?.id;if(!own)return;suppressMarkerClick=true;consume(e);v.cancelMotion();v.overviewBridge.controls.enabled=false;canvas.setPointerCapture(e.pointerId);drag={pointer:e.pointerId,startX:e.clientX,startY:e.clientY,origin:coordinate(e),feature:editing&&target?.id===selected()?.id?structuredClone(selected()!):null,vertex:target?.vertex??-1,active:own};if(target?.id&&tool==='select')selectFeature(target.id);};
  const move=(e:PointerEvent)=>{if(!drag||drag.pointer!==e.pointerId)return;consume(e);const point=coordinate(e),f=drag.feature;if(!point||!f)return;try{if(tool==='move'&&drag.origin){let east=point.game_east-drag.origin.game_east;east-=294912*Math.round(east/294912);preview={...f,geometry:moveFeature(f,east,point.game_north-drag.origin.game_north)};}else if(tool==='edit'&&(drag.vertex>=0||f.geometryType==='Point')){const vertices=structuredClone(f.geometry.vertices);vertices[f.geometryType==='Point'?0:drag.vertex]=point;preview={...f,geometry:{...f.geometry,vertices}};}render();}catch(e){message('error',e);}};
  const up=(e:PointerEvent)=>{if(!drag||drag.pointer!==e.pointerId)return;consume(e);const current=drag;drag=null;try{if(!current.active)return;if(preview){const f=preview;attempt(()=>storage.update(s=>editFeature(s,f.id,{geometry:validateGeometry(f.geometryType,f.geometry)})));preview=null;render();}else if(Math.hypot(e.clientX-current.startX,e.clientY-current.startY)<12){const point=coordinate(e);if(point){if(tool==='Point')attempt(()=>{const f=createFeature(layerId,'Point',[point],t('user26.Point'));storage.update(s=>s.userFeatures.push(f));selectFeature(f.id);});else if(tool==='Polyline'||tool==='Polygon'){const target=hit(e),now=performance.now(),double=now-lastClick.time<350&&Math.hypot(e.clientX-lastClick.x,e.clientY-lastClick.y)<5;if(tool==='Polygon'&&draft.length>=3&&target?.id===''&&target.vertex===0)finishDrawing();else if(double&&draft.length>=(tool==='Polyline'?2:3))finishDrawing();else{if(draft.length>=MAPPING_LIMITS.perFeature){message('error','maximum 512 vertices per feature');return;}draft.push(point);lastClick={time:now,x:e.clientX,y:e.clientY};render();status.textContent=t('user26.active',{tool:t('user26.'+tool),count:draft.length});updateAvailability();}}else if(tool==='add'&&selected())attempt(()=>{const f=selected()!,vertices=structuredClone(f.geometry.vertices);vertices.splice(vertexIndex+1,0,point);storage.update(s=>editFeature(s,f.id,{geometry:validateGeometry(f.geometryType,{...f.geometry,vertices})}));setTool('edit');});}}}finally{if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);restoreControls();}};
  const cancelPointer=(e:PointerEvent)=>{if(drag?.pointer!==e.pointerId)return;consume(e);drag=null;preview=null;render();restoreControls();};const inputRoot=canvas.parentElement!;scope.listen(inputRoot,'pointerdown',down as EventListener,{capture:true});scope.listen(inputRoot,'pointermove',move as EventListener,{capture:true});scope.listen(inputRoot,'pointerup',up as EventListener,{capture:true});scope.listen(inputRoot,'pointercancel',cancelPointer as EventListener,{capture:true});scope.listen(inputRoot,'click',e=>{if(suppressMarkerClick&&e.target instanceof Element&&e.target.closest('.location-marker')){consume(e);suppressMarkerClick=false;}},{capture:true});const previous=v.onUserFeature;v.onUserFeature=id=>selectFeature(id);scope.own(()=>{v.onUserFeature=previous;v.renderer.domElement.parentElement?.classList.remove('user-drawing-active');restoreControls();v.setUserMapping(compileMapping({userLayers:[],userFeatures:[]}));});
 }
 scope.listen(document,'keydown',((e:KeyboardEvent)=>{if(e.key==='Escape'&&(tool!=='select'||drag)){if(drag)drag.active=false;restoreControls();setTool('select');}else if(e.key==='Enter'&&['Polyline','Polygon'].includes(tool)&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();finishDrawing();}}) as EventListener,{capture:true});
 scope.own(storage.subscribe(refresh));scope.own(appStore.subscribe(()=>{updateAvailability();drawInspector();const selection=selected()?.id??null;if(drawing.dataset.selected!==(selection??'')){drawing.dataset.selected=selection??'';render();}}));scope.own(onLocaleChange(()=>{drawLayers();drawInspector(true);refresh();}));scope.own(()=>{clearNavigation('user-mapping');document.dispatchEvent(new Event('gaiagis-navigation'));});refresh();setTool('select');
 return {dispose(){disposed=true;scope.dispose();}};
}
