// SPDX-License-Identifier: GPL-3.0-only
import {appStore,capabilities} from '../app/state';
import {assetFiles} from '../app/workspace';
import {workspaceConnection,onWorkspaceConnection,DEFAULT_WORKSPACE} from '../app/workspaceUX';
import {localAdvertised} from '../app/localWorkspace';
import {t,onLocaleChange} from '../i18n';
export function mountWorkspaceCard(parent:HTMLElement,list:HTMLElement){
 const card=document.createElement('section');card.id='workspace-connection';card.className='app-card workspace-status-card';
 const title=document.createElement('h2'),summary=document.createElement('dl'),hint=document.createElement('p'),resources=document.createElement('h3'),help=document.createElement('details'),helpTitle=document.createElement('summary');summary.className='property-list';hint.className='control-note';help.id='workspace-help';help.append(helpTitle);
 const guidance=document.createElement('p'),raw=document.createElement('p'),generate=document.createElement('p'),command=document.createElement('pre'),location=document.createElement('p'),old=document.createElement('p'),contents=document.createElement('p');command.textContent='python -m gaiagis.local --source "YOUR_FF7_INSTALLATION"';help.append(guidance,raw,generate,command,location,old,contents);const inventory=document.createElement('details'),inventoryTitle=document.createElement('summary');inventory.id='workspace-resource-details';inventory.append(inventoryTitle,resources,list);card.append(title,summary,hint,inventory,help);parent.prepend(card);
 const keys:Record<string,string>={geometry:'shell.geometry',locations:'ui.locations',encounters:'ui.encounters',events:'ui.events',routing:'routing.title',textures:'shell.textures',WM2:'map.WM2',WM3:'map.WM3','textures-WM2':'shell.textureWM2','textures-WM3':'shell.textureWM3',transitions:'map.transitions',explorer:'shell.characters',presentation:'present.title',atlas:'atlas.title','field-context':'field.title','field-walkmesh':'field.walkmesh'};
 const refresh=()=>{const s=appStore.state,c=workspaceConnection,connected=capabilities(s).canInspectSurface;card.dataset.connected=String(connected);card.dataset.source=c.source;title.textContent=t(c.loading?'shell.loading':connected?'shell.connected':'shell.disconnected');summary.replaceChildren();const row=(key:string,value:string)=>{const r=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=t(key);dd.textContent=value;r.append(dt,dd);summary.append(r);};row('shell.source',t(c.source==='auto'?'shell.auto':c.source==='manual'||connected?'shell.manual':'shell.public'));if(c.source==='auto'&&localAdvertised())row('shell.path',c.localPath??DEFAULT_WORKSPACE);else if(c.source==='manual'&&c.folder)row('shell.path',c.folder);
  hint.textContent=t(connected?'shell.assetsHint':'shell.publicHint');inventoryTitle.textContent=t('shell.datasets');resources.hidden=false;resources.textContent=t('shell.manifest')+': '+t(c.manifest==='valid'?'shell.valid':'shell.absent');list.replaceChildren();for(const id of Object.keys(assetFiles)){const a=s.data.assets[id as keyof typeof s.data.assets],r=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');r.dataset.asset=id;dt.textContent=t(keys[id]);dd.textContent=t('workspace.'+(a?.status??(id==='geometry'?'missing':'optional')));if(a?.reason)dd.title=t(a.reason);r.append(dt,dd);list.append(r);}
  helpTitle.textContent=t('shell.help');guidance.textContent=t('shell.pick');raw.textContent=t('shell.raw');generate.textContent=t('shell.generate');location.textContent=t('shell.defaultPath');old.textContent=t('shell.oldPath');contents.textContent=t('shell.contents');
 };const unsubscribe=appStore.subscribe(refresh),connection=onWorkspaceConnection(refresh),language=onLocaleChange(refresh);refresh();return()=>{unsubscribe();connection();language();card.remove();};
}
