// SPDX-License-Identifier: GPL-3.0-only
// Actual local/public acceptance; all evidence is ignored and workspace-local.
import {chromium} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=root+'output/v2_3/browser';
mkdirSync(out+'/tmp',{recursive:true});for(const k of ['TEMP','TMP','TMPDIR'])process.env[k]=out+'/tmp';
const local=process.env.GAIAGIS_QA_URL??'http://127.0.0.1:5183',publicURL=process.env.GAIAGIS_PUBLIC_QA_URL??'http://127.0.0.1:5175';
const report={checks:{},metrics:{},errors:[],external:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const check=(id,value)=>{report.checks[id]=!!value;if(!value)throw Error(id);};let current;
async function tab(p,id){if(await p.locator('#app-menu').isVisible()&&!await p.locator('#integrated-panel').evaluate(e=>e.classList.contains('open')))await p.locator('#app-menu').click();await p.locator('#app-tab-'+id).click();}
async function close(p){if(await p.locator('#integrated-close').isVisible()&&await p.locator('#integrated-panel').evaluate(e=>e.classList.contains('open')))await p.locator('#integrated-close').click();}
async function page(base,width=1440,reduced='reduce'){const ctx=await browser.newContext({viewport:{width,height:900},hasTouch:true,reducedMotion:reduced});const p=await ctx.newPage();current=p;p.on('pageerror',e=>report.errors.push(String(e)));p.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))report.external.push(r.url());});const start=performance.now();await p.goto(base+'/?lang=en');await p.waitForSelector('#discovery',{state:'attached'});if(base===local)await p.waitForFunction(()=>document.getElementById('local-workspace-indicator')?.textContent?.includes('loaded automatically'),{},{timeout:60000});if(await p.locator('#gaia-intro').isVisible())await p.locator('#gaia-intro button').first().click();report.metrics['ready_'+base+'_'+width]=performance.now()-start;return p;}
async function search(p,name,id){await tab(p,'explore');await p.locator('#location-search').fill(name);await p.locator('[data-navigation-id="atlas:'+id+'"]').click();await p.waitForFunction(id=>document.getElementById('atlas-card')?.dataset.entity===id,id);await close(p);}
async function bookmark(p,name){await p.locator('#bookmark-selection').click();await p.locator('#bookmark-name').fill(name);await p.locator('#bookmark-note').fill('Local navigation QA');await p.locator('#bookmark-save').click();await p.waitForSelector('#user-state-dialog',{state:'hidden'});}
const state=p=>p.evaluate(()=>JSON.parse(localStorage.getItem('gaiagis.user-state')));
async function details(p,id){await p.locator('#'+id).evaluate(e=>e.open=true);}
try{
 const p=await page(local);check('local_auto_workspace',(await p.locator('#local-workspace-indicator').textContent()).includes('loaded automatically'));
 await search(p,'Midgar','midgar');await bookmark(p,'Midgar');check('A_identity_bookmark',(await state(p)).bookmarks[0].target.id==='midgar');
 await search(p,'Kalm','kalm');await tab(p,'explore');await details(p,'discovery-recent');await p.locator('#recent-atlas-midgar').click();await p.waitForFunction(()=>document.getElementById('atlas-card')?.dataset.entity==='midgar');await close(p);check('A_recent_return',true);
 await p.locator('#nearby-selection').click();await tab(p,'explore');await details(p,'discovery-nearby');check('A_nearby_results',await p.locator('#nearby-results button').count()>1);report.metrics.nearbyEntities=Number(await p.locator('#discovery').getAttribute('data-nearby-entities'));report.metrics.nearbyQueryMs=Number(await p.locator('#discovery').getAttribute('data-nearby-ms'));
 check('A_nearby_first_zero',Number(await p.locator('#nearby-results button').first().getAttribute('data-distance'))<1);await p.locator('#nearby-radius').selectOption('50');check('A_radius_filter',await p.locator('#nearby-results button').evaluateAll(rows=>rows.every(r=>Number(r.dataset.distance)<=50000)));
 await close(p);await p.locator('#share-selection').click();const link=await p.locator('#share-link').inputValue();check('A_share_public_id',new URL(link).searchParams.get('atlas')==='midgar');check('A_share_no_private_fields',![...new URL(link).searchParams.keys()].some(k=>/lat|lon|xyz|hash|path|triangle|node|camera|bookmark/i.test(k)));report.metrics.shareBytes=link.length;
 await p.goto(link);await p.waitForSelector('#discovery',{state:'attached'});await p.waitForFunction(()=>document.getElementById('atlas-card')?.dataset.entity==='midgar');check('A_deep_link_resolved',await p.locator('#atlas-fly').count()===1);check('A_bookmark_persistence',(await state(p)).bookmarks.length===1);
 await search(p,'Kalm','kalm');await bookmark(p,'Kalm');await search(p,'Junon','junon');await bookmark(p,'Junon');await tab(p,'explore');await details(p,'discovery-bookmarks');await p.locator('#bookmark-list .saved-row').first().locator('button[id^="bookmark-edit-"]').click();await p.locator('#bookmark-name').fill('Midgar saved');await p.locator('#bookmark-save').click();check('bookmark_rename',(await state(p)).bookmarks[0].name==='Midgar saved');
 await details(p,'discovery-tours');await p.locator('#tour-from-bookmarks').click();check('B_draft_three',await p.locator('#tour-draft .saved-row').count()===3);await p.locator('#save-tour').click();await p.locator('#tour-name').fill('Three cities');await p.locator('#tour-save').click();await p.locator('#tour-list button[id^="tour-play-"]').click();check('B_tour_play',await p.locator('#discovery-tours').getAttribute('data-phase')==='playing');await p.locator('#tour-pause').click();check('B_tour_pause',await p.locator('#discovery-tours').getAttribute('data-phase')==='paused');const paused=await p.locator('#discovery-tours').getAttribute('data-index');await p.waitForTimeout(700);check('B_pause_stable',paused===await p.locator('#discovery-tours').getAttribute('data-index'));await p.locator('#tour-next').click();check('B_next',await p.locator('#atlas-card').getAttribute('data-entity')==='kalm');await p.locator('#tour-previous').click();check('B_previous',await p.locator('#atlas-card').getAttribute('data-entity')==='midgar');await p.locator('#tour-next').click();await p.locator('#tour-next').click();await p.locator('#tour-next').click();await p.waitForTimeout(700);check('B_finish_restore',await p.locator('#discovery-tours').getAttribute('data-phase')==='finished'&&await p.locator('#app').getAttribute('data-morphing')==='false');
 await tab(p,'view');await p.locator('#projection').selectOption('mercator');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');await tab(p,'explore');await details(p,'discovery-bookmarks');await p.locator('#save-view').click();await p.locator('#bookmark-name').fill('Mercator view');await p.locator('#bookmark-save').click();check('view_bookmark_local_camera',(await state(p)).bookmarks.at(-1).view.camera.position.length===3);await tab(p,'view');await p.locator('#projection').selectOption('globe');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');await tab(p,'explore');await p.locator('#bookmark-list button[id^="bookmark-open-"]').filter({hasText:'Mercator view'}).click();await p.waitForFunction(()=>document.getElementById('app').dataset.projection==='mercator'&&document.getElementById('app').dataset.morphing==='false');check('view_bookmark_restore',true);
 await search(p,'Midgar','midgar');await p.locator('#selection-context button').filter({hasText:'Set as route start'}).click();await search(p,'Kalm','kalm');await p.locator('#selection-context button').filter({hasText:'Set as route destination'}).click();await tab(p,'analysis');await details(p,'analysis-routing');await p.locator('#find-route').click();await p.waitForFunction(()=>Number(document.getElementById('analysis-panel').dataset.routeNodes)>1);const routeBefore=await p.locator('#route-result').textContent(),nodes=await p.locator('#analysis-panel').getAttribute('data-route-nodes');await details(p,'discovery-route');await p.locator('#route-play').click();await p.waitForTimeout(500);check('C_route_progress',Number(await p.locator('#discovery-route').getAttribute('data-progress'))>0);await p.locator('#route-follow').check();await p.locator('#route-pause').click();const progress=await p.locator('#discovery-route').getAttribute('data-progress');await p.waitForTimeout(400);check('C_route_pause',progress===await p.locator('#discovery-route').getAttribute('data-progress'));await p.locator('#route-speed').selectOption('4');await p.locator('#route-play').click();await tab(p,'view');await p.locator('#projection').selectOption('equal-earth');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');await tab(p,'analysis');await p.locator('#route-stop').click();check('C_solver_result_unchanged',routeBefore===await p.locator('#route-result').textContent()&&nodes===await p.locator('#analysis-panel').getAttribute('data-route-nodes'));check('C_route_stop',await p.locator('#discovery-route').getAttribute('data-phase')==='idle');
 await tab(p,'layers');await p.locator('#color-layer').selectOption('traversal');await details(p,'discovery-opacity');await p.locator('#opacity-traversal').fill('0.4');await p.locator('#opacity-traversal').dispatchEvent('input');check('D_opacity_persisted',(await state(p)).preferences.opacity.traversal===.4);await tab(p,'view');await p.locator('#surface-style').selectOption('texture');await tab(p,'analysis');await details(p,'analysis-compare');await p.locator('#compare-projections').check();check('D_compare',await p.locator('.comparison-layout canvas').count()===2);await tab(p,'layers');await p.locator('#reset-layers').click();check('D_layers_reset',(await state(p)).preferences.opacity.traversal===1);check('D_legend_consolidated',await p.locator('#discovery-legend #terrain-legend').count()===1);await tab(p,'analysis');await p.locator('#compare-projections').uncheck();
 await tab(p,'view');await p.locator('#projection').selectOption('mercator');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');await p.waitForSelector('#local-scale:not([hidden])');const eq=Number(await p.locator('#local-scale').getAttribute('data-metres-per-pixel'));await close(p);const box=await p.locator('.viewport canvas').boundingBox();await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2,box.y+box.height/2+170,{steps:12});await p.mouse.up();await p.waitForTimeout(500);const high=Number(await p.locator('#local-scale').getAttribute('data-metres-per-pixel'));check('E_Mercator_latitude_updates',high>0&&Math.abs(high-eq)>eq*.1);report.metrics.scaleMercatorHigh=high;
 await tab(p,'analysis');await details(p,'analysis-measurement');
 await tab(p,'view');await p.locator('#projection').selectOption('equal-earth');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');await p.waitForSelector('#local-scale:not([hidden])');check('E_equal_earth_scale',Number(await p.locator('#local-scale').getAttribute('data-metres-per-pixel'))>0);await p.locator('#projection').selectOption('globe');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');await p.waitForSelector('#local-scale:not([hidden])');check('E_globe_scale',true);report.metrics.scaleMercatorEquator=eq;
 await search(p,'Gold Saucer','gold-saucer');check('unresolved_no_nearby',await p.locator('#nearby-selection').isHidden());check('unresolved_no_fake_fly',await p.locator('#atlas-fly').count()===0);await bookmark(p,'Unresolved card');check('unresolved_bookmark',true);
 await tab(p,'map');await p.locator('#map-selector').selectOption('WM2');await p.waitForSelector('.native-viewport canvas');await tab(p,'explore');await details(p,'discovery-nearby');check('WM2_nearby_unavailable',await p.locator('#nearby-center').isDisabled());check('WM2_scale_hidden',await p.locator('#local-scale').isHidden());await details(p,'discovery-bookmarks');await p.locator('#save-view').click();await p.locator('#bookmark-name').fill('Native view');await p.locator('#bookmark-save').click();check('native_view_bookmark',(await state(p)).bookmarks.at(-1).view.mapId==='WM2');await tab(p,'map');await p.locator('#map-selector').selectOption('WM3');await p.waitForSelector('.native-viewport canvas');check('WM3_render',true);await p.locator('#map-selector').selectOption('WM0');
 await search(p,'Kalm','kalm');await p.locator('#selection-context button').filter({hasText:'Explore from verified entrance'}).click();await p.waitForFunction(()=>document.getElementById('explorer-panel').dataset.state==='active');check('explorer_discovery_suspended',await p.locator('#discovery').isHidden());await p.locator('#explorer-hud-exit').click();check('explorer_restores_discovery',!await p.locator('#discovery').isHidden());
 await tab(p,'explore');await p.locator('#location-search').fill('WM0');await p.locator('#location-results button').filter({hasText:'WM0 →'}).first().click();await close(p);await bookmark(p,'Transition');check('transition_bookmark',(await state(p)).bookmarks.at(-1).target.kind==='transition');check('transition_inspector',await p.locator('#selection-details').innerText().then(s=>s.includes('WM0')));
 await p.locator('#bookmark-selection').click();await p.locator('#bookmark-name').fill('Nearby');await p.locator('#bookmark-save').click();await p.locator('#about-button').click();await p.locator('#language').selectOption('zh-CN');await p.locator('#close-about').click();await tab(p,'explore');await details(p,'discovery-bookmarks');check('user_names_not_translated',await p.locator('#bookmark-list button[id^=bookmark-open-]').filter({hasText:/^Nearby$/}).count()===1);await p.locator('#about-button').click();await p.locator('#language').selectOption('en');await p.locator('#close-about').click();
 report.metrics.storageBytes=await p.locator('#discovery').getAttribute('data-storage-bytes');report.metrics.heap=await p.evaluate(()=>performance.memory?.usedJSHeapSize??null);await p.screenshot({path:out+'/desktop.png'});
 await tab(p,'data');await p.locator('#clear-user-group').selectOption('recent');await p.locator('#clear-user-data').click();check('clear_second_confirmation',await p.locator('#user-state-dialog').isVisible());await p.locator('#clear-cancel').click();check('clear_cancel_keeps_data',(await state(p)).recent.length>0);await p.locator('#clear-user-data').click();await p.locator('#clear-confirm').click();check('clear_recent_only',(await state(p)).recent.length===0&&(await state(p)).bookmarks.length>0);
 for(const width of [390,320]){const m=await page(local,width);await search(m,'Midgar','midgar');await bookmark(m,'Touch Midgar');await tab(m,'explore');await details(m,'discovery-recent');check('mobile_recent_'+width,await m.locator('#recent-list button').count()>0);await details(m,'discovery-nearby');await m.locator('#nearby-center').tap();check('mobile_nearby_'+width,await m.locator('#nearby-results button').count()>0);await details(m,'discovery-tours');await m.locator('#tour-from-bookmarks').tap();await m.locator('#save-tour').tap();await m.locator('#tour-save').tap();await m.locator('#tour-list button[id^="tour-play-"]').first().tap();await m.locator('#tour-pause').tap();await m.locator('#tour-stop').tap();check('mobile_tour_'+width,true);await search(m,'Midgar','midgar');await m.locator('#selection-context button').filter({hasText:'Set as route start'}).tap();await search(m,'Kalm','kalm');await m.locator('#selection-context button').filter({hasText:'Set as route destination'}).tap();await tab(m,'analysis');await details(m,'analysis-routing');await m.locator('#find-route').tap();await m.waitForFunction(()=>Number(document.getElementById('analysis-panel').dataset.routeNodes)>1);await details(m,'discovery-route');await m.locator('#route-play').tap();await m.waitForTimeout(300);await m.locator('#route-pause').tap();check('mobile_route_'+width,Number(await m.locator('#discovery-route').getAttribute('data-progress'))>0);await m.locator('#route-stop').tap();await tab(m,'layers');await details(m,'discovery-opacity');await m.locator('#opacity-terrain').tap({position:{x:40,y:18}});check('mobile_opacity_'+width,(await state(m)).preferences.opacity.terrain<1);check('mobile_no_overflow_'+width,await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.screenshot({path:out+'/mobile-'+width+'.png'});await m.close();}
 const pub=await page(publicURL);await search(pub,'Midgar','midgar');await bookmark(pub,'Public Midgar');check('public_no_spatial_fly',await pub.locator('#atlas-fly').count()===0);await tab(pub,'explore');await details(pub,'discovery-tours');await pub.locator('#tour-from-bookmarks').click();await pub.locator('#save-tour').click();await pub.locator('#tour-save').click();await pub.locator('#tour-list button[id^="tour-play-"]').first().click();check('public_tour_information',await pub.locator('#atlas-card').getAttribute('data-entity')==='midgar'&&await pub.locator('#atlas-fly').count()===0);await pub.locator('#tour-stop').click();await pub.goto(publicURL+'/?place=midgar');await pub.waitForFunction(()=>document.getElementById('atlas-card')?.dataset.entity==='midgar');check('public_place_deep_link',await pub.locator('#atlas-fly').count()===0);await pub.goto(publicURL+'/?atlas=stale-id');await pub.waitForSelector('#discovery',{state:'attached'});check('stale_link_graceful',await pub.locator('#discovery').count()===1);
 for(const lang of ['en','zh-CN','zh-TW','ja','ko']){await pub.goto(publicURL+'/?lang='+lang);await pub.waitForSelector('#discovery',{state:'attached'});check('locale_'+lang,await pub.evaluate(()=>document.documentElement.lang)===lang&&!await pub.locator('#discovery').innerText().then(s=>s.includes('nav23.')));}
 await pub.context().setOffline(true);await tab(pub,'explore');await pub.locator('#location-search').fill('Midgar');await pub.locator('[data-navigation-id="atlas:midgar"]').click();check('public_offline_search',await pub.locator('#atlas-card').getAttribute('data-entity')==='midgar');check('no_automatic_external_requests',report.external.length===0);check('no_page_errors',report.errors.length===0);
}catch(error){report.failure=String(error);process.exitCode=1;if(current)await current.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
