// SPDX-License-Identifier: GPL-3.0-only
// Local integration QA. No derived assets or screenshots belong in public Git.
import {chromium} from '@playwright/test';
import {mkdirSync,existsSync,readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=root+'output/v2_0/browser-qa';
mkdirSync(out+'/tmp',{recursive:true});for(const key of ['TEMP','TMP','TMPDIR'])process.env[key]=out+'/tmp';
const base=process.env.GAIAGIS_QA_URL??'http://127.0.0.1:5173',workspace=root+'output/v2_0/workspace',manifest=workspace+'/gaia-workspace.json';
const real=process.env.GAIAGIS_QA_SOURCE_ONLY!=='1'&&existsSync(manifest),report={checks:{},metrics:{},errors:[],realSourceEnabled:real};
const check=(id,value)=>{report.checks[id]=!!value;if(!value)throw Error(id);},browser=await chromium.launch({executablePath:process.env.GAIAGIS_CHROME??'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const pages=[];
async function page(width=1440){const p=await browser.newPage({viewport:{width,height:1000},hasTouch:true,reducedMotion:'reduce'});pages.push(p);p.on('pageerror',e=>report.errors.push(String(e)));const begin=performance.now();await p.goto(base+'/?lang=en');await p.waitForSelector('#integrated-panel',{state:'attached'});report.metrics['startup_'+width]=performance.now()-begin;if(await p.locator('#gaia-intro').count()){check('intro_aria',await p.locator('#gaia-intro').getAttribute('role')==='dialog');await p.locator('#gaia-intro button').first().click();}return p;}
async function tab(p,id){if(await p.locator('#app-menu').isVisible()&&!(await p.locator('#integrated-panel').getAttribute('class')).includes('open'))await p.locator('#app-menu').click();await p.locator('#app-tab-'+id).click();}
async function close(p){if(await p.locator('#integrated-close').isVisible())await p.locator('#integrated-close').click();}
async function load(p,folder=false){await tab(p,'data');const start=performance.now();if(folder)await p.locator('#workspace-directory').setInputFiles(workspace);else {const names=JSON.parse(readFileSync(manifest,'utf8')).assets.map(a=>a.filename);await p.locator('#workspace-files').setInputFiles([manifest,...names.map(n=>workspace+'/'+n)]);}await p.waitForFunction(()=>document.getElementById('workspace-status')?.textContent==='Loaded',{},{timeout:60000});check('workspace_'+(folder?'folder':'files'),!(await p.locator('#workspace-assets').innerText()).match(/Corrupt|Incompatible|Missing|Unsupported/));report.metrics['workspace_'+(folder?'folder':'files')]=performance.now()-start;await close(p);}
async function projection(p,id){await tab(p,'view');const begin=performance.now();await p.locator('#projection').selectOption(id);await p.waitForFunction(id=>document.getElementById('app').dataset.projection===id&&document.getElementById('app').dataset.morphing==='false',id);report.metrics['projection_'+id]=performance.now()-begin;}
async function search(p,q){await tab(p,'explore');await p.locator('#location-search').fill(q);await p.locator('#location-results button').first().click();await close(p);}
try{
 const p=await page();check('six_tabs',await p.locator('#integrated-panel [role=tab]').count()===6);check('one_primary_one_inspector',await p.locator('#integrated-panel').count()===1&&await p.locator('#integrated-inspector').count()===1);
 check('initial_map_controls_integrated',await p.locator('#app-group-map #map-selector').count()===1);check('initial_explorer_controls_integrated',await p.locator('#app-group-explore #explorer-launch').count()===1||await p.locator('#app-group-explore #explorer-panel').count()===1);await tab(p,'data');check('diagnostics_no_paths',!/[A-Z]:[\\/]|Users[\\/]|file:\/\//i.test(await p.locator('#workspace-assets').innerText()+await p.locator('#app-group-data pre').innerText()));
 await p.locator('#app-tab-data').focus();await p.keyboard.press('Home');check('keyboard_tab_home',await p.locator('#app-tab-explore').getAttribute('aria-selected')==='true');await p.keyboard.press('End');check('keyboard_tab_end',await p.locator('#app-tab-data').getAttribute('aria-selected')==='true');
 if(real){
  await load(p);
  await search(p,'Midgar');check('A_location',await p.locator('#selection-details').getAttribute('data-location')==='midgar');await p.locator('#selection-context button').filter({hasText:'Measure from here'}).click();check('A_context_measure',await p.locator('#analysis-measurement').getAttribute('data-points')==='1');await p.locator('#measure-finish').click();await p.locator('#selection-context button').filter({hasText:'Set as route start'}).click();await search(p,'Kalm');await p.locator('#selection-context button').filter({hasText:'Set as route destination'}).click();await p.locator('#analysis-routing').evaluate(e=>e.open=true);await p.locator('#find-route').click();await p.waitForFunction(()=>Number(document.getElementById('analysis-panel')?.dataset.queryMs??0)>0);report.metrics.routeMs=Number(await p.locator('#analysis-panel').getAttribute('data-query-ms'));check('A_route',Number(await p.locator('#analysis-panel').getAttribute('data-route-nodes'))>0);await p.locator('#route-result').click();check('route_selection',await p.locator('#tool-inspector').isVisible());
  await projection(p,'equal-earth');await tab(p,'analysis');await p.locator('#analysis-compare').evaluate(e=>e.open=true);await p.locator('#compare-projection-b').selectOption('mercator');const start=performance.now();await p.locator('#compare-projections').check();check('A_compare',await p.locator('canvas').count()===2);report.metrics.compareMs=performance.now()-start;await p.locator('#compare-projections').uncheck();check('compare_cleanup',await p.locator('canvas').count()===1);await projection(p,'globe');await search(p,'Kalm');await p.locator('#selection-context button').filter({hasText:'Explore from verified entrance'}).click();await p.waitForFunction(()=>document.getElementById('explorer-panel').dataset.state==='active');check('Explorer_selection',await p.locator('#integrated-inspector').getAttribute('data-selection')==='explorer');check('A_Explorer_HUD',await p.locator('#explorer-hud-exit').isVisible());await p.locator('#explorer-hud-exit').click();check('A_exit',await p.locator('#explorer-pad').isHidden());check('Explorer_selection_restored',await p.locator('#integrated-inspector').getAttribute('data-selection')==='location');
  // Transition provenance opens its target map without inventing a geographic transform.
  await tab(p,'map');const transitions=p.locator('#app-group-map details').filter({has:p.locator('summary')}).first();await transitions.evaluate(e=>e.open=true);const toWM2=p.locator('#app-group-map details div').filter({hasText:'WM2'}).filter({has:p.locator('button')}).first();await toWM2.locator('button').last().click();await p.waitForSelector('.native-viewport canvas');check('B_transition_to_WM2',await p.locator('#map-selector').inputValue()==='WM2');await tab(p,'layers');await p.locator('#native-layer').selectOption('texture');check('B_native_texture',await p.locator('#native-layer').inputValue()==='texture');await tab(p,'analysis');check('native_global_analysis_hidden',await p.locator('#analysis-panel').isHidden());await tab(p,'view');check('native_view_controls',await p.locator('#native-view').isVisible()&&await p.locator('#projection').isHidden());await tab(p,'explore');await p.locator('#explorer-panel').evaluate(e=>e.open=true);await p.locator('#explorer-start').click();const box=await p.locator('.native-viewport canvas').boundingBox();await p.mouse.click(box.x+box.width/2,box.y+box.height/2);await p.waitForFunction(()=>document.getElementById('explorer-panel').dataset.state==='active');check('B_Submarine_preview',await p.locator('#explorer-pad').isVisible());await p.locator('#explorer-hud-exit').click();await tab(p,'map');await p.locator('#native-return').click();check('B_return_WM0',await p.locator('#app').isVisible());
  await projection(p,'equal-earth');await tab(p,'analysis');await p.locator('#analysis-projection').evaluate(e=>e.open=true);await p.locator('#show-tissot').check();await p.locator('#distortion-lon').fill('30');await p.locator('#distortion-lat').fill('40');await p.locator('#distortion-probe').click();check('C_equal_area',Math.abs(Number(await p.locator('#analysis-projection').getAttribute('data-area-scale'))-1)<.005);await p.locator('#show-tissot').uncheck();await p.locator('#analysis-measurement').evaluate(e=>e.open=true);await p.locator('#measure-clear').click();await p.locator('#measure-type').selectOption('area');for(const [x,y]of [[0,0],[10,0],[0,10]]){await p.locator('#measure-lon').fill(String(x));await p.locator('#measure-lat').fill(String(y));await p.locator('#measure-add').click();}check('C_area',Number(await p.locator('#analysis-measurement').getAttribute('data-area'))>0);await p.locator('#measurement-result').click();check('measurement_selection',await p.locator('#integrated-inspector').getAttribute('data-selection')==='measurement'&&await p.locator('#tool-inspector').isVisible());await p.locator('#measure-clear').click();check('measurement_selection_cleared',await p.locator('#integrated-inspector').getAttribute('data-selection')==='none');await tab(p,'view');await p.locator('#surface-style').selectOption('texture');check('C_texture_return',await p.locator('#surface-style').inputValue()==='texture');
  const ids=await p.locator('#projection option').evaluateAll(o=>o.map(x=>x.value));check('thirteen_views',ids.length===13);for(const id of ids){await projection(p,id);check('projection_'+id,await p.locator('#app').getAttribute('data-projection')===id);}await projection(p,'equal-earth');await tab(p,'layers');await p.locator('#graticule-spacing').selectOption('15');await tab(p,'data');check('data_diagnostics_private',!/[A-Z]:[\\/]|Users[\\/]|file:\/\//i.test(await p.locator('#app-group-data pre').innerText()));
  await p.reload();await p.waitForSelector('#integrated-panel',{state:'attached'});if(base.includes('5175'))await load(p);else await p.waitForFunction(()=>document.getElementById('app')?.dataset.ready==='true');check('panel_persisted',await p.locator('#app-tab-data').getAttribute('aria-selected')==='true');await p.waitForFunction(()=>document.getElementById('app').dataset.projection==='equal-earth');check('projection_persisted',await p.locator('#projection').inputValue()==='equal-earth');check('grid_persisted',await p.locator('#graticule-spacing').inputValue()==='15');
  for(const width of [390,320]){
   const m=await page(width);await load(m,width===320);await search(m,'Midgar');check('D_'+width+'_Inspector',await m.locator('#integrated-inspector').isVisible());await m.locator('#selection-context button').filter({hasText:'Measure from here'}).click();check('D_'+width+'_measure',await m.locator('#analysis-measurement').getAttribute('data-points')==='1');await m.locator('#measure-finish').click();await close(m);await m.locator('#selection-context button').filter({hasText:'Explore from verified entrance'}).click();await m.waitForFunction(()=>document.getElementById('explorer-panel').dataset.state==='active');check('D_'+width+'_touch',await m.locator('#explorer-pad').isVisible());await m.locator('#explorer-hud-exit').tap();check('D_'+width+'_exit',await m.locator('#explorer-pad').isHidden());await tab(m,'analysis');await m.locator('#analysis-compare').evaluate(e=>e.open=true);await m.locator('#compare-projections').check();await close(m);const rects=await m.locator('canvas').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};}));check('mobile_compare_'+width,rects.length===2&&Math.abs(rects[0].x-rects[1].x)<2&&rects[1].y>rects[0].y);await tab(m,'analysis');await m.locator('#compare-projections').uncheck();await m.keyboard.press('Escape');check('mobile_focus_'+width,await m.locator('#app-menu').evaluate(e=>document.activeElement===e));check('mobile_no_overflow_'+width,await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.screenshot({path:out+'/mobile-'+width+'.png'});await m.close();
  }
 await p.locator('#local-dataset-files').setInputFiles([workspace+'/gaia-meta.json',workspace+'/gaia-mesh.bin']);await p.waitForFunction(()=>document.getElementById('workspace-assets')?.textContent.includes('geometryLoaded')&&document.getElementById('workspace-assets')?.textContent.includes('explorerOptional'));check('base_replacement_clears_source_bound_assets',!(await p.locator('#workspace-assets').innerText()).match(/locations\s+Loaded|routing\s+Loaded|WM2\s+Loaded/)&&await p.locator('canvas').count()===1);check('base_replacement_clears_selection',await p.locator('#integrated-inspector').getAttribute('data-selection')==='none');
 }else {check('source_only_no_auto_assets',!(await p.locator('#workspace-assets').innerText()).includes('Loaded'));check('source_only_local_loader',await p.locator('#workspace-files').count()===1);}
 await p.context().grantPermissions(['clipboard-read','clipboard-write']);await tab(p,'data');await p.locator('#app-group-data details').evaluate(e=>e.open=true);await p.locator('#copy-diagnostics').click();const copied=await p.evaluate(()=>navigator.clipboard.readText());check('copy_diagnostics_private',JSON.parse(copied).privateContentIncluded===false&&!/[A-Z]:[\\/]|Users[\\/]/i.test(copied));
 await p.locator('#about-button').click();for(const id of ['en','zh-CN','zh-TW','ja','ko']){await p.locator('#language').selectOption(id);check('locale_'+id,await p.locator('html').getAttribute('lang')===id);}await p.locator('#close-about').click();check('no_page_errors',report.errors.length===0);await p.screenshot({path:out+'/desktop.png'});
}catch(e){report.failure=String(e);throw e;}finally{writeFileSync(out+(real?'/report.json':'/source-only.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
