// SPDX-License-Identifier: GPL-3.0-only
// Real assets, screenshots and reports are private ignored workspace outputs.
import {chromium} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=root+'output/v1_9/browser-qa';mkdirSync(out+'/screenshots',{recursive:true});mkdirSync(out+'/tmp',{recursive:true});for(const k of ['TEMP','TMP','TMPDIR'])process.env[k]=out+'/tmp';
const report={checks:{},metrics:{},errors:[]},check=(k,v)=>{report.checks[k]=!!v;if(!v)throw Error(k);};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,reducedMotion:'reduce'}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
try{
 await page.goto('http://127.0.0.1:5173/?lang=en');await page.waitForFunction(()=>document.getElementById('app').dataset.ready==='true');await page.evaluate(async()=>{const url=performance.getEntriesByType('resource').find(r=>r.name.includes('/src/explorer/controller.ts')).name;window.__e=(await import(url)).activeExplorer;});await page.locator('#explorer-panel>summary').click();
 check('optional_unavailable',(await page.locator('#explorer-panel').innerText()).includes('Explorer data unavailable'));await page.locator('#explorer-file').setInputFiles(root+'output/v1_9/gaia-explorer.bin');await page.waitForFunction(()=>!!window.__e.pack);report.metrics.load=await page.evaluate(()=>window.__e.diagnostics);
 const cases=[['foot','cloud',0],['foot','tifa',0],['foot','cid',0],['buggy','buggy',0],['tiny-bronco','tiny-bronco',4],['chocobo-yellow','chocobo',0],['chocobo-green','chocobo',2],['chocobo-blue','chocobo',4],['chocobo-black','chocobo',2],['chocobo-gold','chocobo',3],['highwind','highwind',3]];
 for(const [profile,model,terrain]of cases){await page.evaluate(()=>window.__e.exit());await page.locator('#explorer-mode').selectOption(profile);if(profile==='foot')await page.locator('#explorer-model').selectOption(model);await page.locator('#explorer-start').click();
  const placed=await page.evaluate(terrain=>{const e=window.__e;for(let i=0;i<e.surface.count;i++){if(e.surface.attrs(i).terrain!==terrain)continue;if(e.place(i,[1/3,1/3,1/3]))return true;}return false;},terrain);check(profile+'_'+model+'_place',placed);await page.waitForTimeout(250);
  check(profile+'_'+model+'_original',await page.evaluate(model=>window.__e.model.model.id===model,model));check(profile+'_'+model+'_frame',await page.evaluate(()=>window.__e.state.runtimeClaim===false&&Number.isFinite(window.__e.state.rawInterpolatedHeight)));
  report.metrics[profile+'_'+model]=await page.evaluate(async()=>{const e=window.__e,{Box3,Vector3}=await import('/node_modules/three/build/three.module.js'),box=new Box3().setFromObject(e.model.object);return {model:e.model.model.hrc,box:box.getSize(new Vector3()).toArray(),state:e.state,diagnostics:e.diagnostics};});
  await page.evaluate(()=>document.activeElement?.blur());const before=await page.evaluate(()=>[window.__e.state.nativeX,window.__e.state.nativeZ]);await page.keyboard.down('w');await page.waitForTimeout(300);await page.keyboard.up('w');check(profile+'_'+model+'_real_keyboard',await page.evaluate(before=>Math.hypot(window.__e.state.nativeX-before[0],window.__e.state.nativeZ-before[1])>0,before));report.metrics[profile+'_'+model].animationAfter=await page.evaluate(()=>window.__e.state.animationState);await page.screenshot({path:out+'/screenshots/'+profile+'-'+model+'.png'});
 }

 await page.evaluate(()=>window.__e.exit());
 const packHash=await page.evaluate(()=>window.__e.pack.sha256),bad=Buffer.from(readFileSync(root+'output/v1_9/gaia-explorer.bin'));bad[bad.length-1]^=1;
 await page.locator('#explorer-file').setInputFiles({name:'corrupt.bin',mimeType:'application/octet-stream',buffer:bad});await page.waitForTimeout(200);check('corruption_preserves_pack',await page.evaluate(hash=>window.__e.pack.sha256===hash,packHash));
 for(const kind of ['source','requiredModel','extent']){
  const original=readFileSync(root+'output/v1_9/gaia-explorer.bin'),n=original.readUInt32LE(12),header=JSON.parse(original.subarray(16,16+n)),start=16+Math.ceil(n/4)*4;
  if(kind==='source'){header.sources['wm0.map']='0'.repeat(64);header.surfaces[0].source_sha256=header.sources['wm0.map'];}if(kind==='requiredModel')header.models[0].id='missing-cloud';if(kind==='extent')header.surfaces[0].extent[0]*=2;
  const meta=Buffer.from(JSON.stringify(header)),offset=16+Math.ceil(meta.length/4)*4,buffer=Buffer.alloc(offset+original.length-start);original.copy(buffer,0,0,16);buffer.writeUInt32LE(meta.length,12);meta.copy(buffer,16);original.copy(buffer,offset,start,original.length-32);const {createHash}=await import('node:crypto');createHash('sha256').update(buffer.subarray(0,-32)).digest().copy(buffer,buffer.length-32);
  await page.locator('#explorer-file').setInputFiles({name:kind+'.bin',mimeType:'application/octet-stream',buffer});await page.waitForTimeout(1200);check(kind+'_pack_preserved',await page.evaluate(hash=>window.__e.pack.sha256===hash,packHash));
 }
 // Every overview projection returns intact after Explorer temporarily selects Globe.
 for(const projection of await page.locator('#projection option').evaluateAll(options=>options.map(o=>o.value))){
  await page.locator('#projection').selectOption(projection);await page.waitForTimeout(150);const overview=await page.evaluate(()=>{const v=window.__e.getWM0(),b=v.overviewBridge;if(v.projectionId!=='globe'){b.camera.zoom=1.5;b.camera.position.x=.2;b.controls.target.x=.2;b.camera.updateProjectionMatrix();b.controls.update();}return {position:b.camera.position.toArray(),target:b.controls.target.toArray(),zoom:b.camera.zoom};});await page.locator('#explorer-mode').selectOption('foot');await page.locator('#explorer-start').click();check(projection+'_locked',await page.locator('#projection').isDisabled());
  const placed=await page.evaluate(()=>{const e=window.__e;for(let i=0;i<e.surface.count;i++)if(e.surface.attrs(i).terrain===0&&e.place(i,[1/3,1/3,1/3]))return true;return false;});check(projection+'_place',placed);await page.evaluate(()=>window.__e.exit());await page.waitForTimeout(1300);check(projection+'_return',await page.evaluate(p=>window.__e.getWM0().projectionId===p,projection));check(projection+'_controls',await page.locator('#projection').isEnabled());check(projection+'_camera_restore',await page.evaluate(old=>{const b=window.__e.getWM0().overviewBridge;return b.camera.position.toArray().every((x,i)=>Math.abs(x-old.position[i])<1e-6)&&b.controls.target.toArray().every((x,i)=>Math.abs(x-old.target[i])<1e-6)&&Math.abs(b.camera.zoom-old.zoom)<1e-6;},overview));
 }
 await page.locator('#projection').selectOption('globe');await page.locator('#explorer-mode').selectOption('highwind');await page.locator('#explorer-start').click();await page.waitForTimeout(200);
 // Actual renderer raycast, without calling the placement method directly.
 check('globe_actual_ray_drop',await page.evaluate(async()=>{const e=window.__e,v=e.viewer,{Vector3}=await import('/node_modules/three/build/three.module.js'),r=v.renderer.domElement.getBoundingClientRect();v.camera.updateMatrixWorld();for(let face=0;face<v.display.renderToSource.length;face++){if(v.display.renderToSource[face]>=e.surface.count)continue;const q=new Vector3();for(let j=0;j<3;j++)q.add(new Vector3().fromArray(v.frame.positions,face*9+j*3));q.multiplyScalar(1/3);if(q.dot(v.camera.position)<=0)continue;q.project(v.camera);if(Math.abs(q.x)>.8||Math.abs(q.y)>.8)continue;v.pick(r.left+(q.x+1)*r.width/2,r.top+(1-q.y)*r.height/2);if(e.state)return e.state.barycentricPosition.every(x=>x>=0); }return false;}));
 check('air_no_terrain_gate',await page.evaluate(()=>{const e=window.__e,s=e.state;s.nativeX=294910;s.heading=Math.PI/2;e.keys.add('w');e.frame(.05);e.keys.clear();return s.nativeX<1000&&s.airborne;}));
 check('sea_landing_blocked',await page.evaluate(()=>{const e=window.__e;for(let i=0;i<e.surface.count;i++)if(e.surface.attrs(i).terrain===3){e.place(i,[1/3,1/3,1/3]);if(!e.toggleFlight())return e.state.airborne;}return false;}));
 check('grass_land_takeoff',await page.evaluate(()=>{const e=window.__e;for(let i=0;i<e.surface.count;i++)if(e.surface.attrs(i).terrain===0){e.place(i,[1/3,1/3,1/3]);if(e.toggleFlight())return !e.state.airborne&&e.toggleFlight()&&e.state.airborne;}return false;}));
 check('incompatible_change_no_teleport',await page.evaluate(()=>{const e=window.__e;for(let i=0;i<e.surface.count;i++)if(e.surface.attrs(i).terrain===3){e.place(i,[1/3,1/3,1/3]);const s=JSON.stringify(e.state);return !e.change('foot')&&JSON.stringify(e.state)===s;}return false;}));
 await page.evaluate(()=>window.__e.exit());
 // Real source edge crossing and E/W seam use the public walker, never nearest faces.
 check('real_source_ew_seam',await page.evaluate(async()=>{const e=window.__e,s=e.pack.surface('WM0'),{locate,advance}=await import('/src/explorer/walker.ts');for(let i=0;i<s.count;i++)for(const [slot,n]of s.neighbors(i).entries()){if(n<0)continue;const a=s.points(i),b=s.points(n);if(Math.abs(a.reduce((v,p)=>v+p[0]/3,0)-b.reduce((v,p)=>v+p[0]/3,0))<294912/2)continue;const edge=[[1,2],[2,0],[0,1]][slot],bc=[.02,.02,.02];bc[edge[0]]=.49;bc[edge[1]]=.49;const start=locate(s,i,bc),x=(a[edge[0]][0]+a[edge[1]][0])/2,z=(a[edge[0]][1]+a[edge[1]][1])/2,r=advance(s,start,(x-start.nativeX)*2,(z-start.nativeZ)*2,'chocobo-gold');if(!r.blocked&&r.state.sourceTriangleId===n)return true;}return false;}));
 // Native maps: manual placement, bounded geometry preview and original assets.
 for(const id of ['WM2','WM3']){
  await page.locator('#map-selector').selectOption(id);await page.locator('#native-map-file').setInputFiles(root+`output/v1_8/data/gaia-map-${id}.bin`);await page.waitForSelector('.native-viewport canvas');await page.locator('#native-texture-file').setInputFiles(root+`output/v1_8/data/gaia-textures-${id}.bin`);await page.waitForTimeout(300);await page.locator('#native-view').selectOption('topdown');await page.locator('#explorer-start').click();
  check(id+'_native_preview',await page.evaluate(id=>window.__e.surface.header.mapId===id&&window.__e.profile===(id==='WM2'?'submarine-native':'glacier-native'),id));
  check(id+'_place',await page.evaluate(()=>window.__e.place(Math.floor(window.__e.surface.count/2),[1/3,1/3,1/3])));await page.evaluate(()=>document.activeElement?.blur());const before=await page.evaluate(()=>window.__e.state.nativeZ);await page.keyboard.down('w');await page.waitForTimeout(250);await page.keyboard.up('w');check(id+'_movement',await page.evaluate(z=>window.__e.state.nativeZ!==z,before));
  check(id+'_camera_texture',await page.evaluate(()=>window.__e.viewer.pack&&window.__e.viewer.camera.position.toArray().every(Number.isFinite)&&window.__e.model.model.id===(window.__e.profile==='submarine-native'?'submarine':document.getElementById('explorer-model').value)));
  if(id==='WM2'){const altitude=await page.evaluate(()=>window.__e.state.flightAltitude);await page.keyboard.down('q');await page.waitForTimeout(200);await page.keyboard.up('q');check('submarine_vertical_preview',await page.evaluate(a=>window.__e.state.flightAltitude>a,altitude));}
  report.metrics[id]=await page.evaluate(()=>({state:window.__e.state,diagnostics:window.__e.diagnostics,render:window.__e.viewer.diagnostics}));await page.screenshot({path:out+`/screenshots/${id}-explorer.png`});
  await page.evaluate(()=>window.__e.exit());check(id+'_topdown_restored',await page.evaluate(()=>window.__e.getNative().topdown));await page.locator('#explorer-start').click();await page.evaluate(()=>window.__e.place(Math.floor(window.__e.surface.count/2),[1/3,1/3,1/3]));await page.locator('#map-selector').selectOption('WM0');check(id+'_transition_stops',await page.evaluate(()=>!window.__e.state&&!window.__e.armed));
 }
 for(const width of [390,320]){
  await page.setViewportSize({width,height:844});await page.locator('#explorer-panel').evaluate(el=>el.open=true);await page.locator('#explorer-mode').selectOption('foot');await page.locator('#explorer-start').click();check('mobile_'+width+'_place',await page.evaluate(()=>{const e=window.__e;for(let i=0;i<e.surface.count;i++)if(e.surface.attrs(i).terrain===0&&e.place(i,[1/3,1/3,1/3]))return true;return false;}));await page.waitForTimeout(250);
  check('mobile_'+width+'_no_overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const button=page.locator('#explorer-pad [data-key=w]'),box=await button.boundingBox(),before=await page.evaluate(()=>window.__e.state.nativeZ);
  const client=await context.newCDPSession(page);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+box.width/2,y:box.y+box.height/2}]});await page.waitForTimeout(250);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('mobile_'+width+'_touch_move',await page.evaluate(z=>window.__e.state.nativeZ!==z,before));
  const canvas=await page.locator('#app canvas').first().boundingBox(),yaw=await page.evaluate(()=>window.__e.yaw);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:canvas.x+canvas.width*.7,y:canvas.y+canvas.height*.65}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:canvas.x+canvas.width*.8,y:canvas.y+canvas.height*.65}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('mobile_'+width+'_camera_drag',await page.evaluate(y=>window.__e.yaw!==y,yaw));await client.detach();
  await page.locator('#explorer-panel').evaluate(el=>el.open=true);await page.locator('#explorer-mode').selectOption('buggy');check('mobile_'+width+'_change',await page.evaluate(()=>window.__e.state.explorerType==='buggy'));await page.locator('#explorer-panel').evaluate(el=>el.open=false);await page.screenshot({path:out+`/screenshots/mobile-${width}.png`});await page.locator('#explorer-panel').evaluate(el=>el.open=true);await page.locator('#explorer-exit').click();check('mobile_'+width+'_gpu_cleanup',await page.evaluate(()=>window.__e.model===null&&window.__e.diagnostics.modelDrawCalls===0));
 }
 for(const lang of ['en','zh-CN','zh-TW','ja','ko']){await page.evaluate(async lang=>(await import('/src/i18n/index.ts')).setLocale(lang),lang);check('locale_'+lang,await page.locator('#explorer-panel>summary').textContent()!=='explore.title');}

 await page.setViewportSize({width:1440,height:1000});await page.locator('#explorer-panel').evaluate(el=>el.open=true);await page.locator('#map-selector').selectOption('WM0');await page.locator('#explorer-mode').selectOption('foot');await page.locator('#explorer-start').click();await page.evaluate(()=>{const e=window.__e;for(let i=0;i<e.surface.count;i++)if(e.surface.attrs(i).terrain===0&&e.place(i,[1/3,1/3,1/3]))return;});await page.waitForTimeout(700);report.metrics.finalWM0=await page.evaluate(()=>({fps:Number(document.getElementById('app').dataset.fps),drawCalls:Number(document.getElementById('app').dataset.drawCalls),diagnostics:window.__e.diagnostics}));await page.evaluate(()=>window.__e.exit());
 const production=await context.newPage(),requests=[];production.on('request',r=>requests.push(r.url()));production.on('pageerror',e=>report.errors.push(String(e)));await production.goto('http://127.0.0.1:5175/?lang=en');await production.waitForSelector('#open-local-data');check('production_no_auto_derived',requests.every(x=>!/gaia-(explorer|mesh|meta|map|textures|events|poi|encounters|routing)/i.test(x)));await production.locator('#local-dataset-files').setInputFiles([root+'web/public/data/gaia-meta.json',root+'web/public/data/gaia-mesh.bin']);await production.waitForFunction(()=>document.getElementById('app').dataset.ready==='true');check('production_local_geometry',await production.locator('canvas').count()===1);await production.locator('#explorer-panel').evaluate(el=>el.open=true);await production.locator('#explorer-file').setInputFiles(root+'output/v1_9/gaia-explorer.bin');await production.waitForFunction(()=>!document.getElementById('explorer-start').disabled);check('production_optional_pack',await production.locator('#explorer-start').isEnabled());await production.locator('#explorer-mode').selectOption('highwind');await production.locator('#explorer-start').click();const rect=await production.locator('#app canvas').first().boundingBox();await production.mouse.click(rect.x+rect.width/2,rect.y+rect.height/2);await production.waitForFunction(()=>document.getElementById('explorer-panel').dataset.state==='active');check('production_actual_drop',await production.locator('#explorer-pad').isVisible());await production.locator('#explorer-exit').click();check('production_return_cleanup',await production.locator('#explorer-pad').isHidden());check('production_no_asset_requests',requests.every(x=>!/gaia-(explorer|mesh|meta|map|textures|events|poi|encounters|routing)/i.test(x)));await production.close();
 check('no_errors',report.errors.length===0);
}finally{await browser.close();writeFileSync(out+'/results.json',JSON.stringify(report,null,2));console.log(JSON.stringify({checks:Object.keys(report.checks).length,passed:Object.values(report.checks).filter(Boolean).length,errors:report.errors,metrics:report.metrics},null,2));}
