// SPDX-License-Identifier: GPL-3.0-only
// Real-source local QA. Every profile, output and screenshot stays ignored.
import {chromium} from '@playwright/test';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=`${root}output/v1_5/browser-qa`;
mkdirSync(`${out}/tmp`,{recursive:true});mkdirSync(`${out}/screenshots`,{recursive:true});for(const k of ['TMP','TEMP','TMPDIR'])process.env[k]=`${out}/tmp`;
const projections=['globe','equirectangular','mercator','mollweide','orthographic','equal-earth','winkel-tripel','robinson','natural-earth','sinusoidal','gall-peters','laea','aeqd'];
const result={checks:{},errors:[],metrics:{},routes:{},screenshots:[]};const check=(key,value)=>{result.checks[key]=!!value;if(!value)throw new Error(key);};
const browser=await chromium.launch({executablePath:process.env.GAIA_BROWSER_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});
const ready=async p=>{await p.locator('#loading').waitFor({state:'hidden',timeout:60000});await p.waitForFunction(()=>document.getElementById('routing-status').textContent.includes('142,586')&&document.querySelectorAll('.location-marker:not(.event-marker)').length===34);};
const watch=p=>p.on('pageerror',e=>result.errors.push(String(e)));
async function hook(p){await p.evaluate(async()=>{const url=performance.getEntriesByType('resource').find(e=>e.name.includes('/src/viewer/GaiaViewer.ts'))?.name;const {GaiaViewer}=await import(url||'/src/viewer/GaiaViewer.ts');const old=GaiaViewer.prototype.setColorLayer;GaiaViewer.prototype.setColorLayer=function(layer){window.__qaViewer=this;return old.call(this,layer);};document.getElementById('color-layer').dispatchEvent(new Event('change'));GaiaViewer.prototype.setColorLayer=old;window.__qaGeometry=window.__qaViewer.surface.geometry;});}
const mode=async(p,id)=>{await p.locator('#projection').selectOption(id);await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');};
const shot=async(p,name)=>{await p.screenshot({path:`${out}/screenshots/${name}.png`,fullPage:true});result.screenshots.push(name);};
async function triangleTap(p,key,mobile=false){const q=await p.evaluate(()=>{const v=window.__qaViewer,rect=v.renderer.domElement.getBoundingClientRect(),positions=v.frame.positions,mask=v.frame.mask;for(let face=0;face<v.display.renderToSource.length;face+=17){const source=v.display.renderToSource[face];if(source>=v.mesh.sourceTriangleCount||Math.min(...mask.slice(face*3,face*3+3))<.3)continue;const point=v.surface.position.clone().set(0,0,0);for(let j=0;j<3;j++){const i=face*9+j*3;point.x+=positions[i]/3;point.y+=positions[i+1]/3;point.z+=positions[i+2]/3;}point.project(v.camera);const x=(point.x+1)*rect.width/2,y=(1-point.y)*rect.height/2;if(x>70&&x<rect.width-90&&y>210&&y<rect.height-120&&!v.locations.nearest(x+rect.x,y+rect.y)){return {x:x+rect.x,y:y+rect.y};}}return null;});check(`${key}_pick_candidate`,!!q);if(mobile)await p.touchscreen.tap(q.x,q.y);else await p.mouse.click(q.x,q.y);check(`${key}_actual_triangle_pick`,await p.locator('#selection-details').getAttribute('data-source-triangle')!==null);check(`${key}_inspector_lineage`,await p.evaluate(()=>{const source=Number(document.getElementById('selection-details').dataset.sourceTriangle),a=window.__qaViewer.mesh.attributes(source);return Number.isInteger(source)&&source<window.__qaViewer.mesh.sourceTriangleCount&&a.map===0&&a.origin===0;}));await p.locator('#clear-selection').click();}
async function route(p,pair,mode){await p.locator('#route-mode').selectOption(mode);await p.locator('#route-from').fill(pair.from);await p.locator('#route-to').fill(pair.to);await p.locator('#find-route').click();await p.waitForFunction(()=>{const s=document.getElementById('route-result').textContent;return s.includes('Reference-sphere distance')||s.includes('No static route');});return {text:await p.locator('#route-result').innerText(),...(await p.locator('#analysis-panel').evaluate(e=>({...e.dataset})))};}
try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}}),p=await ctx.newPage();watch(p);const begin=Date.now();await p.goto('http://127.0.0.1:5173/?lang=en');await ready(p);result.metrics.readyMs=Date.now()-begin;await hook(p);check('13_options',await p.locator('#projection option').count()===13);await p.waitForTimeout(1200);result.metrics.baseFps=Number(await p.locator('#app').getAttribute('data-fps'));result.metrics.baseCalls=Number(await p.locator('#app').getAttribute('data-draw-calls'));
 // Find real source endpoints across all entrances; never fabricate a spatial pair.
 result.routes=await p.evaluate(async()=>{const {parseRouting,connectedComponents,entranceEndpoints,routeProfiles,findRoute}=await import('/src/data/routing.ts');const g=parseRouting(await (await fetch('/data/gaia-routing.bin')).arrayBuffer()),poi=await (await fetch('/data/gaia-poi.json')).json(),rows={};for(const mode of routeProfiles){const c=connectedComponents(g,mode.id),pairs=[];for(let i=0;i<poi.locations.length;i++)for(let j=i+1;j<poi.locations.length;j++){const a=poi.locations[i],b=poi.locations[j],starts=entranceEndpoints(g,poi.entrances.filter(e=>e.location_id===a.id)),targets=entranceEndpoints(g,poi.entrances.filter(e=>e.location_id===b.id));if(!starts.some(s=>c.labels[s.node]>=0&&targets.some(t=>c.labels[t.node]===c.labels[s.node])))continue;const path=findRoute(g,c.labels,starts,targets);if(path&&path.nodes.length>1)pairs.push({from:a.display_name,to:b.display_name,...path});if(pairs.length>=3)break;}rows[mode.id]={components:c.components.length,pairs:pairs.slice(0,3)};}return rows;});
 writeFileSync(`${out}/route-candidates.json`,JSON.stringify(result.routes,null,2));
 await p.locator('#open-analysis').click();
 const foot=result.routes.foot.pairs[0];check('real_foot_pair',!!foot);result.metrics.foot=await route(p,foot,'foot');check('foot_route_ids',result.metrics.foot.text.includes(foot.startEntrance)&&result.metrics.foot.text.includes(foot.targetEntrance));check('all_component_rows',await p.locator('#route-components li').count()===result.routes.foot.components);check('reachable_list',await p.locator('#reachable-locations li').count()>1);check('start_target_distinction',await p.locator('.analysis-start').count()===1&&await p.locator('.analysis-target').count()===1);
 await p.locator('#analysis-close').click();await p.locator('#location-search').fill(foot.from);await p.locator('#location-search').press('Enter');await p.waitForTimeout(1000);check('location_search_intact',await p.locator('#selection-details').getAttribute('data-location')!==null);await p.locator('#clear-selection').click();await p.locator('#open-analysis').click();
 for(const m of ['buggy','chocobo-yellow','chocobo-green','chocobo-blue','chocobo-black','chocobo-gold','tiny-bronco','submarine-surface']){const pair=result.routes[m].pairs[0];if(pair){result.metrics[m]=await route(p,pair,m);check(`${m}_real_route`,result.metrics[m].text.includes('Reference-sphere distance'));}else{result.metrics[m]={...await route(p,foot,m),real_pair:'No eligible resolved Location pair; synthetic solver tests cover movement occupancy.'};check(`${m}_real_incompatible_entrances`,result.metrics[m].text.includes('No static route'));}}
 result.metrics.seam=await p.evaluate(async()=>{const {parseRouting,connectedComponents,findRoute}=await import('/src/data/routing.ts'),g=parseRouting(await (await fetch('/data/gaia-routing.bin')).arrayBuffer()),v=window.__qaViewer,labels=connectedComponents(g,'chocobo-gold').labels;const longitude=t=>{const a=[0,1,2].map(j=>v.mesh.geographic[v.mesh.indices[t*3+j]*3]);return a.reduce((s,l)=>s+l+360*Math.round((a[0]-l)/360),0)/3;};for(let a=0;a<g.count;a++)if(labels[a]>=0)for(let j=g.offsets[a];j<g.offsets[a+1];j++){const b=g.neighbors[j];if(labels[b]>=0&&Math.abs(longitude(a)-longitude(b))>300){const route=findRoute(g,labels,[{node:a,entrance:'source-triangle-diagnostic-a'}],[{node:b,entrance:'source-triangle-diagnostic-b'}]);return {nodes:route.nodes,distance:route.distance,longitudes:[longitude(a),longitude(b)],endpoint_kind:'exact source triangles; not fabricated Location entrances'};}}return null;});check('real_ew_seam_route',result.metrics.seam?.nodes.length===2&&result.metrics.seam.distance<500000);
 result.metrics.noRoute=await route(p,{from:'Midgar',to:'Wutai'},'foot');check('real_no_route',result.metrics.noRoute.text.includes('No static route'));await route(p,foot,'foot');await p.locator('#analysis-close').click();
 for(const id of projections){await mode(p,id);check(`${id}_same_mesh`,await p.evaluate(()=>window.__qaViewer.surface.geometry===window.__qaGeometry));check(`${id}_route_finite`,await p.evaluate(()=>{const v=window.__qaViewer;return v.route.line.visible&&Array.from(v.route.line.geometry.getAttribute('position').array).every(Number.isFinite);}));check(`${id}_corridor_identity`,await p.evaluate(()=>window.__qaViewer.corridor.size>1));
  await p.locator('#color-layer').selectOption('traversal');await p.locator('#movement-mode').selectOption('chocobo-gold');check(`${id}_traversal`,(await p.locator('#legend-title').innerText()).includes('Gold Chocobo'));await p.locator('#color-layer').selectOption('encounter');await p.locator('#chocobo-tracks').check();await p.locator('#chocobo-tracks').uncheck();await p.locator('#color-layer').selectOption('terrain');
  check(`${id}_markers_formula`,await p.evaluate(async()=>{const {markerPosition}=await import('/src/viewer/locations.ts');const v=window.__qaViewer;return v.locations.markers.every(m=>m.current.every((x,i)=>Math.abs(x-markerPosition(m.location,v.projectionId,v.context)[i])<1e-6));}));
  await p.locator('#events-toggle').check();await p.locator('#event-list').selectOption({index:1});await p.waitForTimeout(1100);check(`${id}_event_inspector`,await p.locator('#selection-details').getAttribute('data-event')!==null);await p.locator('#clear-selection').click();await p.locator('#events-toggle').uncheck();
  check(`${id}_surface_available`,await p.evaluate(()=>{const v=window.__qaViewer,p=v.surface.geometry.getAttribute('position').array;return v.display.renderToSource.length>0&&Array.from(p).every(Number.isFinite);}));
  await triangleTap(p,id);
  if(['equal-earth','winkel-tripel','robinson','natural-earth','laea','aeqd'].includes(id))await shot(p,id);
 }
 // Interrupted morph and azimuthal drag/hemisphere center use existing camera.
 await p.locator('#projection').selectOption('globe');await p.waitForTimeout(150);await p.locator('#projection').selectOption('equal-earth');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');check('interrupted_route_finite',await p.evaluate(()=>Array.from(window.__qaViewer.route.line.geometry.getAttribute('position').array).every(Number.isFinite)));
 for(const id of ['laea','aeqd']){await mode(p,id);const old=await p.evaluate(()=>window.__qaViewer.context.centerLon);const b=await p.locator('canvas').boundingBox();await p.mouse.move(b.x+b.width*.55,b.y+b.height*.6);await p.mouse.down();await p.mouse.move(b.x+b.width*.55+80,b.y+b.height*.6+20,{steps:8});await p.mouse.up();check(`${id}_center_drag`,await p.evaluate(old=>window.__qaViewer.context.centerLon!==old,old));}
 await mode(p,'globe');await p.waitForTimeout(1500);result.metrics.routeFps=Number(await p.locator('#app').getAttribute('data-fps'));result.metrics.routeCalls=Number(await p.locator('#app').getAttribute('data-draw-calls'));check('route_only_one_drawcall',result.metrics.routeCalls<=result.metrics.baseCalls+1);
 await p.locator('#open-analysis').click();await p.locator('#clear-analysis').click();check('clear_route',await p.evaluate(()=>!window.__qaViewer.route.line.visible&&!window.__qaViewer.reachable));check('clear_component_summary',(await p.locator('#route-components summary').innerText()).includes('0'));check('analysis_legend',(await p.locator('#analysis-panel').innerText()).includes('Gold: route corridor.'));check('clear_route_metadata',await p.locator('#analysis-panel').getAttribute('data-route-nodes')==='0');await p.locator('#analysis-close').click();
 const countBefore=await p.locator('canvas').count();await p.evaluate(async()=>{const url=performance.getEntriesByType('resource').find(e=>e.name.includes('/src/i18n/index.ts'))?.name;const {t}=await import(url||'/src/i18n/index.ts');for(let i=0;i<21000;i++)t('message.regionCenter',{name:'synthetic-cache-test-'+i,lat:i,lon:i});});for(const [lang,expected]of [['zh-CN','显示'],['zh-TW','顯示'],['ja','表示'],['ko','표시'],['en','Display']]){await p.locator('#about-button').click();await p.locator('#language').selectOption(lang);check(`${lang}_instant`,await p.locator('#mobile-display').textContent()===expected);check(`${lang}_html_lang`,await p.locator('html').getAttribute('lang')===lang);check(`${lang}_canvas_aria`,(await p.locator('canvas').getAttribute('aria-label')).length>10);await p.locator('#close-about').click();check(`${lang}_geometry_not_reloaded`,await p.locator('canvas').count()===countBefore&&await p.evaluate(()=>window.__qaViewer.surface.geometry===window.__qaGeometry));}await p.locator('#about-button').click();await p.locator('#language').selectOption('ja');await p.locator('#close-about').click();await p.goto('http://127.0.0.1:5173/');await ready(p);check('locale_saved_without_url',await p.locator('html').getAttribute('lang')==='ja');await p.goto('http://127.0.0.1:5173/?lang=ko');await ready(p);check('locale_url_overrides_saved',await p.locator('html').getAttribute('lang')==='ko');await ctx.close();
 for(const width of [390,320])for(const lang of ['en','zh-CN','ja']){const ctx=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await ctx.newPage();watch(p);await p.goto(`http://127.0.0.1:5173/?lang=${lang}`);await ready(p);await hook(p);await p.locator('#open-analysis').tap();await p.locator('#route-from').fill(foot.from);await p.locator('#route-to').fill(foot.to);await p.locator('#find-route').tap();await p.waitForFunction(()=>Number(document.getElementById('analysis-panel').dataset.routeNodes)>1);check(`${width}_${lang}_route`,Number(await p.locator('#analysis-panel').getAttribute('data-route-nodes'))>1);await shot(p,`analysis-${width}-${lang}`);check(`${width}_${lang}_overflow`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#analysis-close').tap();await mode(p,'equal-earth');await p.locator('#mobile-display').tap();await p.locator('#color-layer').selectOption('traversal');await p.locator('#movement-mode').selectOption('buggy');check(`${width}_${lang}_selector`,await p.locator('#movement-mode').isVisible());await shot(p,`display-${width}-${lang}`);await p.locator('#mobile-display').tap();await p.locator('#about-button').tap();check(`${width}_${lang}_lang_available`,await p.locator('#language').isVisible());await p.locator('#close-about').tap();await ctx.close();}
 // Optional missing/corrupt data retain geometry + locations + events + encounters.
 {const ctx=await browser.newContext(),p=await ctx.newPage();watch(p);await p.route('**/data/gaia-routing.bin',r=>r.fulfill({status:404,body:''}));await p.goto('http://127.0.0.1:5173/?lang=en');await p.locator('#loading').waitFor({state:'hidden'});await p.waitForTimeout(300);check('missing_routing_optional',(await p.locator('#routing-status').innerText()).includes('unavailable'));check('old_layers_intact',await p.locator('.location-marker:not(.event-marker)').count()===34&&await p.locator('.event-marker').count()===177);await p.locator('#routing-file').setInputFiles({name:'gaia-routing.bin',mimeType:'application/octet-stream',buffer:Buffer.from('corrupt')});await p.waitForTimeout(100);check('corrupt_rejected',await p.locator('#routing-status').getAttribute('title')!==null);check('corrupt_geometry_retained',await p.locator('canvas').count()===1);await ctx.close();}
 {const ctx=await browser.newContext(),p=await ctx.newPage(),requests=[];watch(p);p.on('request',q=>requests.push({method:q.method(),url:q.url()}));await p.goto('http://127.0.0.1:5175/?lang=en');await p.locator('#local-dataset-files').setInputFiles([`${root}web/public/data/gaia-meta.json`,`${root}web/public/data/gaia-mesh.bin`]);await p.locator('#loading').waitFor({state:'hidden'});check('release_routing_optional',(await p.locator('#routing-status').innerText()).includes('unavailable'));await p.locator('#local-poi-file').setInputFiles(`${root}web/public/data/gaia-poi.json`);await p.locator('#routing-file').setInputFiles(`${root}web/public/data/gaia-routing.bin`);await ready(p);await p.locator('#open-analysis').click();const path=await route(p,foot,'foot');check('release_local_worker_route',path.text.includes('Reference-sphere distance'));await p.locator('#analysis-close').click();await mode(p,'laea');check('release_13_projections',await p.locator('#projection option').count()===13);check('release_no_data_request_or_upload',requests.every(q=>q.method==='GET'&&!q.url.includes('/data/')));await ctx.close();}
 check('no_browser_errors',result.errors.length===0);
}catch(error){result.failure=String(error);throw error;}finally{writeFileSync(`${out}/results.json`,JSON.stringify(result,null,2));await browser.close();}
console.log(`${Object.keys(result.checks).length} v1.5 browser checks passed`);
