// SPDX-License-Identifier: GPL-3.0-only
// Private original-asset evidence only; no screenshots or datasets enter Git.
import {chromium} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=root+'output/v2_1/browser';mkdirSync(out+'/tmp',{recursive:true});for(const k of ['TEMP','TMP','TMPDIR'])process.env[k]=out+'/tmp';
const report={checks:{},metrics:{},errors:[]},check=(k,v)=>{report.checks[k]=!!v;if(!v)throw Error(k);};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const ctx=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,reducedMotion:'reduce'}),p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(String(e)));
const manifest=JSON.parse(readFileSync(root+'output/local-workspace/gaia-workspace.json'));const files=[root+'output/local-workspace/gaia-workspace.json',...manifest.assets.map(a=>root+'output/local-workspace/'+a.filename)];
async function tab(id){if(await p.locator('#app-menu').isVisible()&&!await p.locator('#integrated-panel').evaluate(e=>e.classList.contains('open')))await p.locator('#app-menu').click();await p.locator('#app-tab-'+id).click();}
try{
 await p.goto('http://127.0.0.1:5173/?lang=en');await p.waitForSelector('#workspace-files',{state:'attached'});await p.locator('#workspace-files').setInputFiles(files);await p.waitForFunction(()=>document.querySelectorAll('#workspace-assets dd').length===13&&[...document.querySelectorAll('#workspace-assets dd')].every(e=>e.textContent==='Loaded'),{},{timeout:60000});await p.evaluate(async()=>{const find=s=>performance.getEntriesByType('resource').find(r=>r.name.includes(s)).name;window.e=(await import(find('/src/explorer/controller.ts'))).activeExplorer;window.prefs=await import(find('/src/app/presentation.ts'));window.lang=await import(find('/src/i18n/index.ts'));});
 await tab('view');await p.locator('#presentation-settings').evaluate(e=>e.open=true);check('default_ff7',await p.locator('html').getAttribute('data-theme')==='ff7');await p.locator('#presentation-theme').selectOption('scientific');check('scientific',await p.locator('html').getAttribute('data-theme')==='scientific');await p.locator('#presentation-theme').selectOption('ff7');
 await p.waitForFunction(()=>!document.getElementById('presentation-sounds').disabled,{},{timeout:10000});report.metrics.audioDebug=await p.evaluate(async()=>({state:window.prefs.uiSounds.available,html:document.getElementById('presentation-sounds').outerHTML,assets:document.getElementById('workspace-assets').textContent}));check('audio_ready',await p.locator('#presentation-sounds').isEnabled());await p.locator('#presentation-sounds').check();await p.locator('#presentation-volume').fill('20');await p.locator('#presentation-volume').dispatchEvent('input');check('audio_gesture',await p.evaluate(async()=>{const m=window.prefs;return m.uiSounds.unlocked&&m.uiSounds.available&&m.presentation.volume===.2;}));
 await tab('explore');await p.locator('#explorer-panel').evaluate(e=>e.open=true);
 const start=async()=>{await p.evaluate(async()=>{const e=window.e;await e.arm();for(let i=0;i<e.surface.count;i++)if(e.surface.attrs(i).terrain===0&&e.place(i,[1/3,1/3,1/3])){window.qaTriangle=i;return;}throw Error('No valid grass case');});};await start();
 report.metrics.anchor=await p.evaluate(()=>({triangle:window.qaTriangle,state:window.e.state}));
 for(const id of ['cloud','barret','tifa','aerith','red-xiii','yuffie','cait-sith','vincent','cid']){
  const before=await p.evaluate(()=>[window.e.state.nativeX,window.e.state.nativeZ,window.e.state.sourceTriangleId,window.e.state.heading]);await p.locator('#explorer-model').selectOption(id);await p.waitForTimeout(250);check(id+'_identity',await p.evaluate(id=>window.e.model.model.id===id,id));check(id+'_same_position',await p.evaluate(b=>JSON.stringify(b)===JSON.stringify([window.e.state.nativeX,window.e.state.nativeZ,window.e.state.sourceTriangleId,window.e.state.heading]),before));
  check(id+'_shadow',await p.evaluate(()=>window.e.shadow.object.visible&&window.e.diagnostics.shadowDrawCalls===1));
  report.metrics[id]=await p.evaluate(async()=>{const e=window.e,{Box3,Vector3}=await import('/node_modules/three/build/three.module.js');return {diagnostics:{...e.diagnostics},source:e.model.model.hrc,kind:e.model.model.sourceKind,scale:e.model.displayScale,groundOffset:e.model.groundOffset,size:e.model.size,box:new Box3().setFromObject(e.model.object).getSize(new Vector3()).toArray()};});
  await p.screenshot({path:out+'/'+id+'.png'});await p.evaluate(()=>document.activeElement?.blur());await p.keyboard.down('w');await p.waitForTimeout(120);check(id+'_source_move_animation',await p.evaluate(()=>window.e.state.animationState===1));await p.keyboard.up('w');await p.evaluate(()=>{window.e.place(window.qaTriangle,[1/3,1/3,1/3]);});
 }
 await p.locator('#explorer-model').selectOption('cloud');const origin=await p.evaluate(()=>[window.e.state.nativeX,window.e.state.nativeZ]);await p.locator('#explorer-model').selectOption('buggy');check('party_to_buggy',await p.evaluate(()=>window.e.profile==='buggy'));await p.locator('#explorer-model').selectOption('aerith');check('buggy_to_party',await p.evaluate(b=>window.e.profile==='foot'&&window.e.model.model.id==='aerith'&&JSON.stringify(b)===JSON.stringify([window.e.state.nativeX,window.e.state.nativeZ]),origin));
 for(const mode of ['chocobo-yellow','chocobo-green','chocobo-blue','chocobo-black','chocobo-gold','highwind']){await p.locator('#explorer-model').selectOption(mode);await p.waitForTimeout(100);check('regression_'+mode,await p.evaluate(mode=>window.e.profile===mode&&window.e.model.model.id===(mode.startsWith('chocobo')?'chocobo':mode),mode));}await p.locator('#explorer-model').selectOption('cloud');
 check('bronco_water_case',await p.evaluate(()=>{const e=window.e;e.selectVisual('chocobo-gold');for(let i=0;i<e.surface.count;i++)if(e.surface.attrs(i).terrain===6&&e.place(i,[1/3,1/3,1/3]))return e.selectVisual('tiny-bronco')&&e.model.model.id==='tiny-bronco';return false;}));await p.evaluate(()=>{window.e.selectVisual('chocobo-gold');window.e.place(window.qaTriangle,[1/3,1/3,1/3]);window.e.selectVisual('cloud');});
 for(const preset of ['flat','debug','original']){await tab('view');await p.locator('#presentation-settings').evaluate(e=>e.open=true);await p.locator('#presentation-lighting').selectOption(preset);check('lighting_'+preset,await p.evaluate(v=>window.e.model.lights[0].uniforms.modelAmbient.value===v,preset==='flat'?1:preset==='debug'?1.25:.6));}
 await tab('explore');await p.locator('#explorer-panel').evaluate(e=>e.open=true);await p.locator('#explorer-exit').click();check('shadow_cleanup',await p.evaluate(()=>window.e.shadow===null&&window.e.model===null));
 const current=readFileSync(root+'output/local-workspace/gaia-explorer.bin');await p.locator('#explorer-file').setInputFiles(root+'output/v2_1/baseline-explorer.bin');await p.waitForFunction(()=>window.e.pack.header.models.length===8);check('old_pack_missing_disabled',await p.locator('#explorer-model option[value=aerith]').isDisabled());await p.locator('#explorer-file').setInputFiles({name:'gaia-explorer.bin',mimeType:'application/octet-stream',buffer:current});await p.waitForFunction(()=>window.e.pack.header.models.length===14);
 for(const width of [390,320]){await p.setViewportSize({width,height:844});await tab('view');await p.locator('#presentation-settings').evaluate(e=>e.open=true);await p.locator('#presentation-theme').selectOption('scientific');await p.locator('#presentation-theme').selectOption('ff7');check('mobile_theme_'+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await tab('explore');await p.locator('#explorer-panel').evaluate(e=>e.open=true);await start();await tab('explore');await p.locator('#explorer-panel').evaluate(e=>e.open=true);await p.locator('#explorer-model').selectOption('vincent');check('mobile_party_'+width,await p.evaluate(()=>window.e.model.model.id==='vincent'&&document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:out+'/mobile-'+width+'.png'});await p.locator('#explorer-exit').click();}
 for(const lang of ['en','zh-CN','zh-TW','ja','ko']){await p.evaluate(async lang=>window.lang.setLocale(lang),lang);check('locale_'+lang,await p.locator('#explorer-model option[value=aerith]').textContent()!=='party.aerith');}
 await p.setViewportSize({width:1440,height:1000});await p.evaluate(async()=>window.lang.setLocale('en'));for(const id of ['WM2','WM3']){await tab('map');await p.locator('#map-selector').selectOption(id);await p.waitForSelector('.native-viewport canvas');await tab('explore');await p.locator('#explorer-panel').evaluate(e=>e.open=true);await p.evaluate(async()=>{await window.e.arm();if(!window.e.surface)throw Error(document.getElementById('explorer-panel').textContent);});check(id+'_native_place',await p.evaluate(()=>window.e.place(Math.floor(window.e.surface.count/2),[1/3,1/3,1/3])));await p.waitForTimeout(500);check(id+'_shadow',await p.evaluate(()=>!!window.e.shadow));await p.screenshot({path:out+'/'+id+'.png'});await p.locator('#explorer-exit').click();}
 const local=await ctx.newPage();local.on('pageerror',e=>report.errors.push(String(e)));let pickers=0;local.on('filechooser',()=>pickers++);await local.goto('http://127.0.0.1:5180/?lang=en');await local.waitForFunction(()=>document.getElementById('local-workspace-indicator')?.textContent?.includes('Workspace loaded automatically'),{},{timeout:60000});check('launcher_no_picker',pickers===0);check('all_13_components',(await local.locator('#workspace-assets dd').allTextContents()).every(s=>s==='Loaded')&&await local.locator('#workspace-assets dd').count()===13);await local.close();
 check('no_page_errors',report.errors.length===0);
}catch(e){report.failure=String(e);process.exitCode=1;}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
