// SPDX-License-Identifier: GPL-3.0-only
import {chromium} from '@playwright/test';
import {mkdirSync,writeFileSync,readdirSync,readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=root+'output/v2_4/browser';mkdirSync(out+'/tmp',{recursive:true});for(const k of ['TEMP','TMP','TMPDIR'])process.env[k]=out+'/tmp';
const local='http://127.0.0.1:5183',pub='http://127.0.0.1:5175',report={checks:{},errors:[],external:[],metrics:{}};
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});let current;
const check=(id,v)=>{report.checks[id]=!!v;if(!v)throw Error(id);};
async function page(base,width=1440,height=900){const p=await b.newPage({viewport:{width,height},hasTouch:true,reducedMotion:'reduce'});current=p;p.on('pageerror',e=>report.errors.push(String(e)));p.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))report.external.push(r.url());});await p.goto(base+'/?lang=en');await p.waitForSelector('#discovery',{state:'attached'});if(base===local)await p.waitForFunction(()=>document.getElementById('workspace-connection')?.dataset.connected==='true'&&document.getElementById('local-workspace-indicator')?.textContent.includes('loaded automatically'),{},{timeout:60000});if(await p.locator('#gaia-intro').isVisible())await p.locator('#gaia-intro button').first().click();return p;}
async function tab(p,id){if(!await p.locator('#integrated-panel').evaluate(e=>e.classList.contains('open')))await p.locator('#app-menu').click();await p.locator('#app-tab-'+id).click();}
async function search(p,name,id){await tab(p,'explore');await p.locator('#location-search').fill(name);await p.locator('[data-navigation-id="atlas:'+id+'"]').click();await p.waitForFunction(id=>document.getElementById('atlas-card')?.dataset.entity===id,id);}
async function bounds(p,id){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const data=await p.evaluate(()=>{const ids=['integrated-panel','integrated-inspector','viewport'],r={width:innerWidth,height:innerHeight,pageWidth:document.documentElement.scrollWidth,pageHeight:document.documentElement.scrollHeight};r.boxes=ids.map(id=>{const original=document.getElementById(id),e=id==='viewport'&&original.getBoundingClientRect().width===0?document.querySelector('.native-viewport'):original,b=e.getBoundingClientRect();return{id,visible:b.width>0&&b.height>0,left:b.left,top:b.top,right:b.right,bottom:b.bottom,width:b.width,height:b.height,scrollWidth:e.scrollWidth,clientWidth:e.clientWidth};});return r;});report.metrics[id]=data;check(id+'_viewport',data.pageWidth<=data.width&&data.pageHeight<=data.height&&data.boxes.every(r=>!r.visible||(r.left>=0&&r.top>=0&&r.right<=data.width+.5&&r.bottom<=data.height+.5)));check(id+'_content_width',data.boxes.filter(r=>r.id!=='viewport').every(r=>!r.visible||r.scrollWidth<=r.clientWidth+1));check(id+'_map_usable',data.boxes[2].width>=Math.min(280,data.width)&&data.boxes[2].height>=100);}
try{
 const p=await page(local);await tab(p,'data');check('auto_connected',await p.locator('#workspace-connection').getAttribute('data-source')==='auto');check('canonical_local_path',(await p.locator('#workspace-connection').innerText()).includes('output\\local-workspace'));check('manifest_validated',(await p.locator('#workspace-connection').innerText()).includes('Validated'));check('all_resources_loaded',await p.locator('#workspace-assets dd').evaluateAll(a=>a.length===14&&a.every(e=>e.textContent==='Loaded')));check('automatic_no_manual_guess',!await p.locator('#manual-loading').evaluate(e=>e.open));
 check('no_path_in_user_storage',await p.evaluate(()=>Object.values(localStorage).every(v=>!String(v).includes('D:\\Project'))));check('no_path_in_diagnostics',!await p.locator('#copy-diagnostics').evaluate(e=>e.parentElement.querySelector('pre').textContent.includes('D:')));
 await p.locator('#workspace-help').evaluate(e=>e.open=true);check('folder_help',(await p.locator('#workspace-help').innerText()).includes('not your FF7 installation'));check('launcher_help',(await p.locator('#workspace-help').innerText()).includes('python -m gaiagis.local'));await bounds(p,'desktop_data');
 await search(p,'Midgar','midgar');await p.locator('#atlas-card details').evaluateAll(a=>a.forEach(e=>e.open=true));await tab(p,'analysis');await p.locator('#analysis-panel details').evaluateAll(a=>a.forEach(e=>e.open=true));await bounds(p,'desktop_both');check('inspector_auto_open',await p.locator('#integrated-inspector').isVisible());await p.locator('#collapse-inspector').click();check('inspector_collapse',!await p.locator('#integrated-inspector').isVisible());await p.locator('#toggle-inspector').click();await bounds(p,'desktop_reopen');
 const themes=await p.evaluate(()=>({header:getComputedStyle(document.querySelector('.topbar')).backgroundImage,left:getComputedStyle(document.getElementById('integrated-panel')).backgroundImage,right:getComputedStyle(document.getElementById('integrated-inspector')).backgroundImage,info:getComputedStyle(document.getElementById('info-panel')).backgroundImage}));check('unified_window_tokens',themes.header===themes.left&&themes.left===themes.right&&themes.info==='none');await p.screenshot({path:out+'/desktop-both.png'});
 await tab(p,'view');await p.locator('#projection').selectOption('mercator');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');await bounds(p,'mercator');await p.locator('#presentation-settings').evaluate(e=>e.open=true);await p.locator('#presentation-theme').selectOption('scientific');check('scientific_explicit',await p.evaluate(()=>document.documentElement.dataset.theme)==='scientific');await bounds(p,'scientific');await p.screenshot({path:out+'/scientific.png'});await p.locator('#presentation-theme').selectOption('ff7');await p.locator('#projection').selectOption('globe');await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');
 for(const map of ['WM2','WM3']){await tab(p,'map');await p.locator('#map-selector').selectOption(map);await p.waitForSelector('.native-viewport canvas');await tab(p,'data');check(map+'_available',await p.locator('[data-asset="'+map+'"] dd').textContent()==='Loaded');await bounds(p,map);await p.screenshot({path:out+'/'+map+'.png'});}await tab(p,'map');await p.locator('#map-selector').selectOption('WM0');await search(p,'Kalm','kalm');await p.locator('#selection-context button').filter({hasText:'Explore from verified entrance'}).click();await p.waitForFunction(()=>document.getElementById('explorer-panel').dataset.state==='active');check('explorer_active',true);await bounds(p,'explorer');await p.locator('#explorer-hud-exit').click();
 for(const [w,h]of [[1440,420],[1024,600],[390,844],[320,568]]){await p.setViewportSize({width:w,height:h});await tab(p,'data');await bounds(p,'data_'+w+'x'+h);await p.screenshot({path:out+'/data-'+w+'x'+h+'.png'});await search(p,'Midgar','midgar');await p.locator('#atlas-card details').evaluateAll(a=>a.forEach(e=>e.open=true));if(w>=1100)await tab(p,'analysis');await bounds(p,'inspector_'+w+'x'+h);await p.screenshot({path:out+'/inspector-'+w+'x'+h+'.png'});}
 const s=await page(pub);await tab(s,'data');check('public_disconnected',await s.locator('#workspace-connection').getAttribute('data-connected')==='false');check('public_source_only',await s.locator('#workspace-connection').getAttribute('data-source')==='public');check('public_no_path',!(await s.locator('#workspace-connection').innerText()).includes('D:'));check('manual_guidance',(await s.locator('#app-group-data').innerText()).includes('GaiaGIS-generated workspace'));
 await s.locator('#workspace-files').setInputFiles({name:'wm0.map',mimeType:'application/octet-stream',buffer:Buffer.from('raw')});check('raw_folder_error',(await s.locator('#workspace-status').textContent()).includes('No gaia-workspace.json'));await s.locator('#workspace-files').setInputFiles({name:'gaia-workspace.json',mimeType:'application/json',buffer:Buffer.from('{')});await s.waitForFunction(()=>document.getElementById('workspace-status')?.textContent.includes('invalid or unsupported'));check('malformed_manifest_error',(await s.locator('#workspace-status').textContent()).includes('invalid or unsupported'));
 const ws=root+'output/local-workspace/',names=readdirSync(ws).filter(n=>n==='gaia-workspace.json'||/^gaia-/.test(n));await s.locator('#workspace-files').setInputFiles(names.filter(n=>n!=='gaia-mesh.bin').map(n=>ws+n));await s.waitForFunction(()=>document.getElementById('workspace-status')?.textContent.includes('gaia-mesh.bin'));check('missing_core_error',(await s.locator('#workspace-status').textContent()).includes('gaia-mesh.bin'));await s.locator('#workspace-files').setInputFiles(names.map(n=>ws+n));await s.waitForFunction(()=>document.getElementById('workspace-status')?.textContent==='Loaded',{},{timeout:60000});check('manual_connected',await s.locator('#workspace-connection').getAttribute('data-source')==='manual'&&await s.locator('#workspace-connection').getAttribute('data-connected')==='true');check('manual_all_resources',await s.locator('#workspace-assets dd').evaluateAll(a=>a.every(e=>e.textContent==='Loaded')));await bounds(s,'manual_import');
 const core=['gaia-workspace.json','gaia-meta.json','gaia-mesh.bin'].map(name=>({name,mimeType:'application/octet-stream',buffer:readFileSync(ws+name)}));core[2].buffer=Buffer.from(core[2].buffer);core[2].buffer[0]^=1;await s.locator('#workspace-files').setInputFiles(core);await s.waitForFunction(()=>document.getElementById('workspace-status')?.textContent.includes('checksum'));check('corrupt_import_retains_connection',await s.locator('#workspace-connection').getAttribute('data-connected')==='true');check('corrupt_import_retains_resources',await s.locator('#workspace-assets dd').evaluateAll(a=>a.every(e=>e.textContent==='Loaded')));
 const folderFiles=['gaia-workspace.json','gaia-meta.json','gaia-mesh.bin'].map(name=>({name,data:readFileSync(ws+name).toString('base64')}));await s.evaluate(files=>{window.showDirectoryPicker=async()=>({name:'generated-workspace',kind:'directory',async *values(){for(const f of files)yield {kind:'file',name:f.name,getFile:async()=>new File([Uint8Array.from(atob(f.data),c=>c.charCodeAt(0))],f.name)};}});},folderFiles);await s.locator('#load-workspace-folder').click();await s.waitForFunction(()=>document.getElementById('workspace-status')?.textContent.includes('Unavailable or rejected'),{},{timeout:60000});check('manual_folder_name',(await s.locator('#workspace-connection').innerText()).includes('generated-workspace'));check('missing_optional_explained',(await s.locator('#workspace-status').textContent()).includes('textures'));check('partial_workspace_keeps_geometry',await s.locator('#workspace-connection').getAttribute('data-connected')==='true');
 for(const lang of ['en','zh-CN','zh-TW','ja','ko']){const q=await page(pub);await q.goto(pub+'/?lang='+lang);await q.waitForSelector('#workspace-connection',{state:'attached'});await tab(q,'data');check('locale_'+lang,!await q.locator('#workspace-connection').innerText().then(t=>t.includes('shell.')));await bounds(q,'public_'+lang);await q.close();}
 check('no_page_errors',report.errors.length===0);check('no_automatic_external_requests',report.external.length===0);
}catch(e){report.failure=String(e);process.exitCode=1;if(current)await current.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:Object.values(report.checks).filter(Boolean).length,total:Object.keys(report.checks).length,failure:report.failure,errors:report.errors,external:report.external}));await b.close();}
