// SPDX-License-Identifier: GPL-3.0-only
import {chromium,devices} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url));
const output=process.env.GAIA_QA_OUTPUT||`${root}output/web_release_v1/qa`,screens=`${output}/screenshots`;
mkdirSync(output,{recursive:true});mkdirSync(screens,{recursive:true});
mkdirSync(`${output}/tmp`,{recursive:true});
for(const key of ['TEMP','TMP','TMPDIR'])process.env[key]=`${output}/tmp`;
const executable=process.env.GAIA_BROWSER_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe';
const context=await chromium.launchPersistentContext(`${output}/browser-profile`,{executablePath:executable,headless:true,viewport:{width:1440,height:1000},deviceScaleFactor:1,args:['--disable-background-networking','--no-first-run']});
const page=context.pages()[0],errors=[];
page.on('pageerror',error=>errors.push(String(error)));
page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});
const results={checks:{},screenshots:[],metrics:{},browser:await context.browser()?.version(),mode:'Headless Chrome, isolated workspace profile'};
try{
  await page.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});
  await page.locator('#loading').waitFor({state:'hidden',timeout:30000});
  await page.waitForFunction(()=>Number(document.querySelector('#app').dataset.fps)>0);
  await page.waitForTimeout(2200);
  const samples=[];
  await page.locator('#auto-rotate').check();
  for(let i=0;i<12;i++){await page.waitForTimeout(250);samples.push(Number(await page.locator('#app').getAttribute('data-fps')));}
  await page.locator('#auto-rotate').uncheck();await page.locator('#reset-view').click();await page.waitForTimeout(400);
  results.metrics.globe_fps={samples,average:samples.reduce((a,b)=>a+b,0)/samples.length,minimum:Math.min(...samples),maximum:Math.max(...samples)};
  results.metrics.gpu=await page.evaluate(()=>{const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl2');const ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),dpr:devicePixelRatio};});
  const shot=async name=>{await page.screenshot({path:`${screens}/${name}.png`,fullPage:true});results.screenshots.push(`${name}.png`);};
  await shot('globe');results.checks.initial_globe=true;
  if(!(await page.locator('#graticule').isChecked()))throw new Error('Direction grid should start enabled');
  if(await page.locator('#graticule-labels span:visible').count()<3)throw new Error('Expected visible hemisphere coordinate labels');
  await page.locator('#toggle-graticule').click();await page.waitForTimeout(150);
  if(await page.locator('#graticule').isChecked()||await page.locator('#graticule-labels span:visible').count())throw new Error('Grid toolbar toggle did not hide labels');
  await page.locator('#toggle-graticule').click();await page.waitForTimeout(150);
  if(!(await page.locator('#graticule').isChecked()))throw new Error('Toolbar and sidebar grid controls are not synchronized');
  results.checks.labeled_graticule_toolbar=true;
  const canvas=page.locator('canvas');let box=await canvas.boundingBox();
  await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.64,box.y+box.height*.57,{steps:15});await page.mouse.up();
  await page.mouse.wheel(0,-200);await page.waitForTimeout(300);
  results.checks.globe_drag_zoom=true;
  await page.locator('#north-up').click();await page.waitForTimeout(250);
  if(!(await page.locator('#view-center').innerText()).includes('Equator 0°'))throw new Error('North-up button did not return to an equatorial view');
  results.checks.north_up_readout=true;
  await page.locator('#reset-view').click();await page.waitForTimeout(500);
  const withDepth=await canvas.screenshot();await page.locator('#globe-depth').uncheck();await page.waitForTimeout(150);
  if(withDepth.equals(await canvas.screenshot()))throw new Error('Globe depth toggle did not change rendered shading');
  await page.locator('#globe-depth').check();results.checks.optional_globe_depth=true;
  box=await canvas.boundingBox();await page.mouse.click(box.x+box.width*.5,box.y+box.height*.5);
  await page.locator('#selection-details').waitFor({state:'visible'});
  results.checks.source_picking=await page.locator('#selection-details').getAttribute('data-origin')==='0';
  if(!results.checks.source_picking)throw new Error('Expected FF7 source face at initial view center');
  await page.locator('#triangle-grid').check();await page.locator('#graticule').check();await page.waitForTimeout(200);await shot('globe-grid');
  results.checks.grid_graticule=true;
  await page.locator('#triangle-grid').uncheck();await page.locator('#clear-selection').click();
  await page.locator('#terrain').uncheck();await page.waitForTimeout(100);await page.locator('#terrain').check();
  await page.locator('#cap-distinction').check();await page.waitForTimeout(100);await page.locator('#cap-distinction').uncheck();
  results.checks.terrain_cap_toggles=true;
  for(const id of ['equirectangular','mercator','mollweide','orthographic']){
    const started=Date.now();await page.locator('#projection').selectOption(id);
    await page.waitForFunction(()=>document.querySelector('#app').dataset.morphing==='false');
    if(Date.now()-started<800)throw new Error('Projection transition jumped without animation');
    results.checks[`projection_${id}`]=true;
    await page.waitForTimeout(200);await shot(id);
  }
  box=await canvas.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.69,box.y+box.height*.56,{steps:12});await page.mouse.up();await page.waitForTimeout(200);await shot('orthographic-rotated');
  results.checks.orthographic_drag=true;
  await page.locator('#projection').selectOption('equirectangular');await page.waitForFunction(()=>document.querySelector('#app').dataset.morphing==='false');
  box=await canvas.boundingBox();const aspect=box.width/box.height,halfHeight=Math.max(Math.PI/2,Math.PI/aspect)*1.14;
  await page.mouse.click(box.x+box.width*.5,box.y+box.height*.5-(85*Math.PI/180)/halfHeight*box.height/2);
  await page.locator('#selection-details').waitFor({state:'visible'});
  if(await page.locator('#selection-details').getAttribute('data-origin')==='0')throw new Error('Expected synthetic polar face at 85 degrees');
  if(!(await page.locator('#selection-details').innerText()).includes('No FF7 source'))throw new Error('Synthetic selection lacks null-lineage explanation');
  results.checks.synthetic_picking=true;await shot('polar-cap-inspector');
  // Responsive + real tap path in a touch-enabled browser context.
  const mobile=await context.browser().newContext({...devices['iPhone 13'],viewport:{width:390,height:844}});
  const mobilePage=await mobile.newPage();mobilePage.on('pageerror',e=>errors.push(String(e)));
  await mobilePage.goto('http://127.0.0.1:5173/',{waitUntil:'networkidle'});await mobilePage.locator('#loading').waitFor({state:'hidden',timeout:30000});
  await mobilePage.waitForTimeout(800);
  if(await mobilePage.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw new Error('Mobile horizontal overflow');
  await mobilePage.locator('#toggle-graticule').tap();await mobilePage.waitForTimeout(150);
  if(await mobilePage.locator('#graticule').isChecked())throw new Error('Mobile graticule toggle failed');
  await mobilePage.locator('#toggle-graticule').tap();results.checks.mobile_grid_toolbar=true;
  const mobileCanvas=await mobilePage.locator('canvas').boundingBox();await mobilePage.touchscreen.tap(mobileCanvas.x+mobileCanvas.width/2,mobileCanvas.y+mobileCanvas.height/2);
  await mobilePage.locator('#selection-details').waitFor({state:'visible'});
  await mobilePage.screenshot({path:`${screens}/mobile.png`,fullPage:true});results.screenshots.push('mobile.png');
  results.checks.mobile_tap_layout=true;results.metrics.mobile_fps=await mobilePage.locator('#app').getAttribute('data-fps');
  await mobile.close();
  results.errors=errors;if(errors.length)throw new Error(errors.join('\n'));
  results.success=true;
}catch(error){results.success=false;results.failure=String(error);await page.screenshot({path:`${output}/failure.png`}).catch(()=>{});}
writeFileSync(`${output}/browser-results.json`,JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify(results,null,2));await context.close();
if(!results.success)process.exitCode=1;
