// SPDX-License-Identifier: GPL-3.0-only
// Real local-source QA; screenshots, profiles, output and data remain private.
import {chromium} from '@playwright/test';
import {mkdirSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=`${root}output/v1_6/browser-qa`;
mkdirSync(`${out}/tmp`,{recursive:true});mkdirSync(`${out}/screenshots`,{recursive:true});for(const k of ['TMP','TEMP','TMPDIR'])process.env[k]=`${out}/tmp`;
const result={checks:{},errors:[],metrics:{},screenshots:[]},check=(key,value)=>{result.checks[key]=!!value;if(!value)throw new Error(key);};
const browser=await chromium.launch({executablePath:process.env.GAIA_BROWSER_EXECUTABLE||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-networking','--no-first-run']});
const watch=p=>p.on('pageerror',e=>result.errors.push(String(e))),ready=async p=>{await p.locator('#loading').waitFor({state:'hidden',timeout:60000});await p.waitForFunction(()=>document.querySelectorAll('.location-marker:not(.event-marker)').length===34&&document.getElementById('routing-status').textContent.includes('142,586'));};
const shot=async(p,name)=>{await p.screenshot({path:`${out}/screenshots/${name}.png`,fullPage:true});result.screenshots.push(name);};
const hook=async p=>p.evaluate(async()=>{const url=performance.getEntriesByType('resource').find(e=>e.name.includes('/src/viewer/GaiaViewer.ts'))?.name;const {GaiaViewer}=await import(url||'/src/viewer/GaiaViewer.ts'),old=GaiaViewer.prototype.setColorLayer;GaiaViewer.prototype.setColorLayer=function(layer){window.__qaViewer=this;return old.call(this,layer);};document.getElementById('color-layer').dispatchEvent(new Event('change'));GaiaViewer.prototype.setColorLayer=old;window.__qaGeometry=window.__qaViewer.surface.geometry;});
const mode=async(p,id)=>{await p.locator('#projection').selectOption(id);await p.waitForFunction(()=>document.getElementById('app').dataset.morphing==='false');await p.waitForTimeout(260);};
const group=async(p,id)=>{if(!await p.locator('#analysis-panel').isVisible())await p.locator('#open-analysis').click();if(!await p.locator(`#${id}`).evaluate(e=>e.open))await p.locator(`#${id}>summary`).click();};
const coordinate=async(p,prefix,lon,lat)=>{await p.locator(`#${prefix}-lon`).fill(String(lon));await p.locator(`#${prefix}-lat`).fill(String(lat));await p.locator(`#${prefix}-${prefix==='measure'?'add':'probe'}`).click();};
const hide=async p=>{if(await p.locator('#analysis-panel').isVisible())await p.locator('#analysis-close').click();};
try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),p=await ctx.newPage();watch(p);const begin=Date.now();await p.goto('http://127.0.0.1:5173/?lang=en');await ready(p);await hook(p);result.metrics.loadMs=Date.now()-begin;await p.waitForTimeout(1100);result.metrics.baseCalls=Number(await p.locator('#app').getAttribute('data-draw-calls'));result.metrics.baseFps=Number(await p.locator('#app').getAttribute('data-fps'));
 const ids=await p.locator('#projection option').evaluateAll(o=>o.map(e=>e.value));check('13_projections',ids.length===13);check('default_auto',await p.locator('#graticule-spacing').inputValue()==='auto');check('11_grid_choices',await p.locator('#graticule-spacing option').count()===11);
 await group(p,'analysis-measurement');await coordinate(p,'measure',0,0);await coordinate(p,'measure',1,0);const one=Number(await p.locator('#analysis-measurement').getAttribute('data-distance'));check('equatorial_one_degree',Math.abs(one-111195.0802335329)<1e-6);await p.locator('#measure-clear').click();await p.locator('#measure-type').selectOption('area');for(const point of [[179,-10],[-179,-10],[-179,10],[179,10]])await coordinate(p,'measure',...point);const area=await p.locator('#analysis-measurement').getAttribute('data-area'),distance=await p.locator('#analysis-measurement').getAttribute('data-distance');check('seam_area_result',Number(area)>0);await p.locator('#measure-finish').click();await hide(p);
 for(const id of ids){await mode(p,id);check(`${id}_same_geometry`,await p.evaluate(()=>window.__qaViewer.surface.geometry===window.__qaGeometry));check(`${id}_measurement_invariance`,await p.locator('#analysis-measurement').getAttribute('data-area')===area&&await p.locator('#analysis-measurement').getAttribute('data-distance')===distance);check(`${id}_measurement_finite`,await p.evaluate(()=>Array.from(window.__qaViewer.measurement.line.geometry.getAttribute('position').array).every(Number.isFinite)));check(`${id}_grid_finite`,await p.evaluate(()=>window.__qaViewer.gridFrame.positions.every(Number.isFinite)));check(`${id}_candidate`,await p.evaluate(()=>[90,60,45,30,20,15,10,5,2,1,.5,.25,.1].includes(window.__qaViewer.diagnostics.gridInterval)));await group(p,'analysis-projection');await p.locator('#show-tissot').check();await coordinate(p,'distortion',20,40);check(`${id}_distortion_scope`,id==='globe'?await p.locator('#distortion-metrics').innerText().then(t=>t.includes('Unavailable')):Number(await p.locator('#analysis-projection').getAttribute('data-area-scale'))>0);if(['equal-earth','mollweide','sinusoidal','gall-peters','laea'].includes(id))check(`${id}_equal_area`,Math.abs(Number(await p.locator('#analysis-projection').getAttribute('data-area-scale'))-1)<1e-5);check(`${id}_tissot_finite`,await p.evaluate(()=>window.__qaViewer.tissot.line.geometry.getAttribute('position').array.every(Number.isFinite)));await hide(p);if(['equal-earth','mercator','winkel-tripel','orthographic','laea'].includes(id))await shot(p,`${id}-grid-tissot-measurement`);}
 await mode(p,'equal-earth');const idle=await p.evaluate(()=>window.__qaViewer.diagnostics.gridRegenerations);await p.waitForTimeout(900);check('idle_grid_no_rebuild',await p.evaluate(n=>window.__qaViewer.diagnostics.gridRegenerations===n,idle));const interval=await p.evaluate(()=>window.__qaViewer.diagnostics.gridInterval);for(let i=0;i<7;i++)await p.locator('#zoom-in').click();await p.waitForTimeout(500);check('zoom_adapts_grid',await p.evaluate(n=>window.__qaViewer.diagnostics.gridInterval<n,interval));await p.locator('#reset-view').click();await p.waitForTimeout(500);
 for(const value of ['90','45','30','15','10','5','2','1','0.5']){await p.locator('#graticule-spacing').selectOption(value);await p.waitForTimeout(250);check(`fixed_${value}`,await p.evaluate(n=>window.__qaViewer.diagnostics.gridInterval===n,Number(value)));}await p.locator('#graticule-spacing').selectOption('off');check('off_grid',await p.evaluate(()=>!window.__qaViewer.graticule.visible));await p.locator('#toggle-graticule').click();await p.waitForFunction(()=>document.getElementById('graticule-spacing').value==='auto');check('legacy_toggle_auto',await p.locator('#graticule-spacing').inputValue()==='auto');
 // A real surface tap in measurement mode follows the canonical rendered hit.
 await group(p,'analysis-measurement');await p.locator('#measure-clear').click();await p.locator('#measure-type').selectOption('distance');await p.locator('#measure-start').click();await hide(p);await p.evaluate(()=>window.__qaViewer.focusLocation(20,20));const rect=await p.locator('#viewport canvas').boundingBox();await p.mouse.click(rect.x+rect.width*.55,rect.y+rect.height*.6);check('surface_click_measurement',Number(await p.locator('#analysis-measurement').getAttribute('data-points'))===1);await group(p,'analysis-measurement');await coordinate(p,'measure',30,30);await p.locator('#measure-finish').click();await group(p,'analysis-compare');await p.locator('#compare-projection-b').selectOption('mercator');await p.locator('#compare-projections').check();await hide(p);await p.waitForTimeout(500);check('compare_two_canvases',await p.locator('canvas').count()===2);check('compare_single_source',await p.evaluate(()=>window.__qaViewer.comparison.display===window.__qaViewer.display));check('compare_shared_color',await p.evaluate(()=>window.__qaViewer.comparison.surface.geometry.getAttribute('color')===window.__qaViewer.surface.geometry.getAttribute('color')));check('compare_measurement',await p.evaluate(()=>window.__qaViewer.comparison.measurement.geo===window.__qaViewer.measurement.geo));
 await p.evaluate(()=>window.__qaViewer.flyToLocation(179,35));await p.waitForTimeout(300);check('compare_linked_center',await p.evaluate(()=>{const v=window.__qaViewer,c=v.viewState().center,b=document.getElementById('comparison-viewport').dataset.center.split(',').map(Number);return Math.abs(c[0]-179)<1e-4&&Math.abs(c[1]-35)<1e-4&&Math.abs(b[0]-c[0])<1e-8&&Math.abs(b[1]-c[1])<1e-8;}));await p.locator('#zoom-in').click();await p.waitForTimeout(250);check('compare_linked_zoom',await p.evaluate(()=>Math.abs(window.__qaViewer.viewState().zoom-Number(document.getElementById('comparison-viewport').dataset.zoom))<1e-8));
 await mode(p,'laea');check('compare_projection_preserves_center',await p.evaluate(()=>Math.abs(window.__qaViewer.context.centerLon-179)<1e-4&&Math.abs(window.__qaViewer.context.centerLat-35)<1e-4));await mode(p,'equal-earth');await p.evaluate(()=>window.__qaViewer.focusLocation(20,20));await p.locator('#location-search').fill('Midgar');await p.locator('#location-search').press('Enter');await p.waitForTimeout(300);check('compare_location_selection',await p.evaluate(()=>window.__qaViewer.locations.selected===window.__qaViewer.comparison.locations.selected&&!!window.__qaViewer.locations.selected));await p.locator('#clear-selection').click();
 await group(p,'analysis-compare');await p.locator('#compare-traversal').click();check('four_traversal_classes',await p.evaluate(()=>JSON.parse(document.getElementById('comparison-results').dataset.counts).reduce((a,b)=>a+b,0)===window.__qaViewer.mesh.sourceTriangleCount));check('comparison_surface_identity',await p.evaluate(()=>window.__qaViewer.surface.geometry===window.__qaGeometry));await p.locator('#route-from').fill('Midgar');await p.locator('#route-to').fill('Kalm');await p.locator('#compare-reachable').click();await p.waitForFunction(()=>document.getElementById('comparison-results').dataset.counts!==undefined&&document.getElementById('comparison-results').textContent.includes('source triangles'));check('reachability_four_classes',await p.evaluate(()=>window.__qaViewer.comparisonFlags?.length===window.__qaViewer.mesh.sourceTriangleCount));await p.locator('#compare-routes').click();await p.waitForFunction(()=>document.querySelectorAll('.compared-route').length===9);check('nine_routes',await p.locator('.compared-route').count()===9);const available=p.locator('[data-route-overlay]');const n=await available.count();check('real_route_exists',n>0);for(let i=0;i<Math.min(3,n);i++)await available.nth(i).check({force:true});if(n>3)await available.nth(3).click({force:true});check('three_route_limit',await p.locator('[data-route-overlay]:checked').count()<=3);check('compare_route_mirror',await p.evaluate(()=>window.__qaViewer.comparedRoutes.every((o,i)=>o.geo===window.__qaViewer.comparison.comparedRoutes[i].geo)));await hide(p);await p.waitForTimeout(1200);await shot(p,'projection-comparison-route');result.metrics.compareFps=Number(await p.locator('#app').getAttribute('data-fps'));result.metrics.mainCalls=Number(await p.locator('#app').getAttribute('data-draw-calls'));result.metrics.diagnostics=await p.evaluate(()=>({...window.__qaViewer.diagnostics}));check('compare_finite_buffers',await p.evaluate(()=>window.__qaViewer.comparison.surface.geometry.getAttribute('position').array.every(Number.isFinite)));

 // Each secondary viewport owns only reusable display buffers and its own pixel-aware grid.
 await group(p,'analysis-compare');await p.evaluate(()=>window.__qaBPosition=window.__qaViewer.comparison.surface.geometry.getAttribute('position').array);
 for(const id of ids){await p.locator('#compare-projection-b').selectOption(id);await p.waitForTimeout(300);check(`compare_B_${id}_finite`,await p.evaluate(()=>window.__qaViewer.comparison.surface.geometry.getAttribute('position').array.every(Number.isFinite)));check(`compare_B_${id}_buffer_reuse`,await p.evaluate(()=>window.__qaBPosition===window.__qaViewer.comparison.surface.geometry.getAttribute('position').array));check(`compare_B_${id}_grid`,await p.evaluate(()=>[90,60,45,30,20,15,10,5,2,1,.5,.25,.1].includes(window.__qaViewer.comparison.gridInterval)));}
 check('all_route_results_core_parity',await p.evaluate(async()=>{const {parseRouting,connectedComponents,findRoute,entranceEndpoints,routeProfiles}=await import('/src/data/routing.ts'),graph=parseRouting(await(await fetch('/data/gaia-routing.bin')).arrayBuffer()),poi=await(await fetch('/data/gaia-poi.json')).json();const endpoints=name=>entranceEndpoints(graph,poi.entrances.filter(e=>e.location_id===poi.locations.find(l=>l.display_name===name).id));return routeProfiles.every(mode=>{const path=findRoute(graph,connectedComponents(graph,mode.id).labels,endpoints('Midgar'),endpoints('Kalm')),values=[...document.querySelectorAll(`.compared-route[data-mode="${mode.id}"] dd`)].map(e=>e.textContent);return path?Number(values[1])===path.nodes.length&&values[2]===`${path.startEntrance} → ${path.targetEntrance}`&&Math.abs(Number(values[3].replaceAll(',',''))-path.distance/1000)<.0051&&Number(values[4])===path.component:Number(values[1])===0;});}));
 result.metrics.measurementKernel=await p.evaluate(async()=>{const {measureDistance,measureArea}=await import('/src/analysis/sphere.ts'),points=[[179,-10,0],[-179,-10,0],[-179,10,0],[179,10,0]],start=performance.now();for(let i=0;i<1000;i++){measureDistance(points);measureArea(points);}return {iterations:1000,totalMs:performance.now()-start};});
await group(p,'analysis-compare');await p.locator('#compare-clear').click();await p.locator('#compare-projections').uncheck();check('compare_cleanup_canvas',await p.locator('canvas').count()===1);check('compare_cleanup_owner',await p.evaluate(()=>!window.__qaViewer.comparison&&!window.__qaViewer.compareLayout&&window.__qaViewer.surface.geometry===window.__qaGeometry));check('comparison_clear',await p.evaluate(()=>!window.__qaViewer.comparisonFlags&&window.__qaViewer.comparedRoutes.every(o=>!o.line.visible)));await hide(p);
 for(const lang of ['en','zh-CN','zh-TW','ja','ko']){await p.locator('#about-button').click();await p.locator('#language').selectOption(lang);await p.locator('#close-about').click();await group(p,'analysis-measurement');check(`${lang}_measurement_i18n`,!(await p.locator('#analysis-measurement').innerText()).includes('measure.')&&await p.locator('#analysis-measurement').getAttribute('data-distance')!==null);await group(p,'analysis-projection');check(`${lang}_metrics_i18n`,!(await p.locator('#distortion-metrics').innerText()).includes('distortion.'));await group(p,'analysis-compare');check(`${lang}_compare_i18n`,!(await p.locator('#compare-routes').innerText()).includes('compare.'));await hide(p);}await ctx.close();
 for(const width of [390,320])for(const lang of ['en','zh-CN','ja']){const ctx=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await ctx.newPage();watch(p);await p.goto(`http://127.0.0.1:5173/?lang=${lang}`);await ready(p);await hook(p);await mode(p,'equal-earth');await p.locator('#mobile-display').tap();await p.locator('#graticule-spacing').selectOption('5');check(`${width}_${lang}_grid`,await p.locator('#graticule-spacing').inputValue()==='5');await p.locator('#mobile-display').tap();await group(p,'analysis-measurement');await coordinate(p,'measure',0,0);await coordinate(p,'measure',1,0);check(`${width}_${lang}_distance`,Number(await p.locator('#analysis-measurement').getAttribute('data-distance'))>111000);await group(p,'analysis-projection');await p.locator('#show-tissot').check();await coordinate(p,'distortion',30,40);check(`${width}_${lang}_distortion`,Math.abs(Number(await p.locator('#analysis-projection').getAttribute('data-area-scale'))-1)<1e-5);await group(p,'analysis-compare');await p.locator('#compare-projections').check();await p.locator('#route-from').fill('Midgar');await p.locator('#route-to').fill('Kalm');await p.locator('#compare-routes').tap();await p.waitForFunction(()=>document.querySelectorAll('.compared-route').length===9);check(`${width}_${lang}_route_comparison`,await p.locator('.compared-route').count()===9);check(`${width}_${lang}_no_overflow`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&[...document.querySelectorAll('.analysis-panel')].every(e=>e.scrollWidth<=e.clientWidth+1)));await shot(p,`mobile-panel-${width}-${lang}`);await hide(p);check(`${width}_${lang}_vertical_split`,await p.evaluate(()=>{const a=document.getElementById('viewport').getBoundingClientRect(),b=document.getElementById('comparison-viewport').getBoundingClientRect();return Math.abs(a.width-b.width)<1&&b.top>=a.bottom-1;}));await shot(p,`mobile-comparison-${width}-${lang}`);await group(p,'analysis-compare');await p.locator('#compare-projections').uncheck();await ctx.close();}

 {const ctx=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),p=await ctx.newPage(),requests=[];watch(p);p.on('request',q=>requests.push({method:q.method(),url:q.url()}));await p.goto('http://127.0.0.1:5175/?lang=en');await p.locator('#open-local-data').waitFor({state:'visible'});check('release_initial_local_chooser',await p.locator('#open-local-data').isVisible());await p.locator('#local-dataset-files').setInputFiles([`${root}web/public/data/gaia-meta.json`,`${root}web/public/data/gaia-mesh.bin`]);await p.locator('#loading').waitFor({state:'hidden'});await group(p,'analysis-measurement');await coordinate(p,'measure',0,0);await coordinate(p,'measure',1,0);check('release_local_measurement',Number(await p.locator('#analysis-measurement').getAttribute('data-distance'))>111000);await group(p,'analysis-projection');await mode(p,'equal-earth');await coordinate(p,'distortion',30,40);check('release_distortion',Math.abs(Number(await p.locator('#analysis-projection').getAttribute('data-area-scale'))-1)<1e-5);await group(p,'analysis-compare');await p.locator('#compare-projections').check();check('release_projection_compare',await p.locator('canvas').count()===2);await p.locator('#compare-routes').click();check('release_missing_routing',(await p.locator('#comparison-results').innerText()).includes('unavailable'));await p.locator('#local-poi-file').setInputFiles(`${root}web/public/data/gaia-poi.json`);await p.locator('#routing-file').setInputFiles(`${root}web/public/data/gaia-routing.bin`);await p.waitForFunction(()=>document.getElementById('routing-status').textContent.includes('142,586'));await p.locator('#route-from').fill('Midgar');await p.locator('#route-to').fill('Kalm');await p.locator('#compare-routes').click();await p.waitForFunction(()=>document.querySelectorAll('.compared-route').length===9);check('release_local_route_compare',await p.locator('.compared-route').count()===9);check('release_no_data_request_or_upload',requests.every(q=>q.method==='GET'&&!q.url.includes('/data/')));await ctx.close();}
 check('no_browser_errors',result.errors.length===0);
}catch(e){result.failure=String(e);throw e;}finally{writeFileSync(`${out}/results.json`,JSON.stringify(result,null,2));await browser.close();}
console.log(`${Object.keys(result.checks).length} v1.6 browser checks passed`);
