// SPDX-License-Identifier: GPL-3.0-only
// Real-source results/screenshots are local and ignored.
import {chromium} from '@playwright/test';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=root+'output/v1_8/browser-qa';
mkdirSync(out+'/screenshots',{recursive:true});mkdirSync(out+'/tmp',{recursive:true});for(const key of ['TEMP','TMP','TMPDIR'])process.env[key]=out+'/tmp';
const report={checks:{},metrics:{},errors:[]},check=(key,value)=>{report.checks[key]=!!value;if(!value)throw Error(key);};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const c=await browser.newContext({viewport:{width:1440,height:1000},hasTouch:true,reducedMotion:'reduce'}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(String(e)));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
const requests=[];p.on('request',r=>requests.push(r.url()));
try{
 await p.goto('http://127.0.0.1:5173/?lang=en');await p.waitForFunction(()=>document.getElementById('app').dataset.ready==='true');
 await p.evaluate(async()=>{const url=performance.getEntriesByType('resource').find(r=>r.name.includes('/src/viewer/NativeViewer.ts')).name;const {NativeViewer}=await import(url),original=NativeViewer.prototype.setView;NativeViewer.prototype.setView=function(...args){window.__native=this;return original.apply(this,args);};});
 check('default_wm0',await p.locator('#map-selector').inputValue()==='WM0');check('no_native_auto_fetch',requests.every(u=>!u.includes('gaia-map-WM')&&!u.includes('gaia-textures-WM')));
 for(const id of ['WM2','WM3']){
  await p.locator('#map-selector').selectOption(id);report.metrics[id+'_missing_panel']=await p.locator('.native-panel').innerText();check(id+'_missing_data',report.metrics[id+'_missing_panel'].includes('Map data unavailable'));
  let start=Date.now();await p.locator('#native-map-file').setInputFiles(root+`output/v1_8/data/gaia-map-${id}.bin`);await p.waitForFunction(id=>window.__native?.map.header.mapId===id,id);report.metrics[id+'_geometry_load_ms']=Date.now()-start;
  check(id+'_no_geographic_mapping',await p.evaluate(()=>window.__native.map.header.global_mapping===null));
  check(id+'_triangle_count',await p.evaluate(()=>window.__native.map.sourceTriangleCount)===(id==='WM2'?9967:8268));
  start=Date.now();await p.locator('#native-texture-file').setInputFiles(root+`output/v1_8/data/gaia-textures-${id}.bin`);await p.waitForFunction(()=>!!window.__native.pack);report.metrics[id+'_texture_load_ms']=Date.now()-start;
  check(id+'_texture_isolation',await p.evaluate(id=>window.__native.pack.metadata.mapId===id,id));
  const previous=await p.evaluate(()=>window.__native.pack.metadata.mapId);await p.locator('#native-texture-file').setInputFiles(root+`output/v1_8/data/gaia-textures-${id==='WM2'?'WM3':'WM2'}.bin`);await p.waitForTimeout(150);check(id+'_wrong_texture_preserved',await p.evaluate(id=>window.__native.pack.metadata.mapId===id,previous));
  await p.locator('#native-filter').selectOption('linear');await p.locator('#native-shading').check();
  const types=await p.evaluate(()=>[...new Set(Array.from({length:window.__native.map.sourceTriangleCount},(_,t)=>window.__native.map.attributes(t).terrain))]);
  for(const type of types.slice(0,5)){check(id+'_terrain_'+type+'_source',await p.evaluate(type=>Array.from({length:window.__native.map.sourceTriangleCount},(_,t)=>window.__native.map.attributes(t).terrain).includes(type),type));}
  for(const factor of [0,1,10,25,50,100]){await p.locator('#native-relief').selectOption(String(factor));check(id+'_relief_'+factor,await p.evaluate(f=>window.__native.exaggeration===f,factor));}
  await p.locator('#native-relief').selectOption('1');await p.screenshot({path:out+`/screenshots/${id}-3d.png`});
  await p.locator('#native-view').selectOption('topdown');check(id+'_topdown_height_zero',await p.evaluate(()=>{const a=window.__native.geometry.getAttribute('position').array;return Array.from(a).filter((_,i)=>i%3===1).every(x=>x===0);}));
  const screen=await p.evaluate(async()=>{const {Vector3}=await import('/node_modules/three/build/three.module.js');const v=window.__native;v.controls.update();v.camera.updateMatrixWorld();const pos=v.geometry.getAttribute('position'),t=Math.floor(v.map.sourceTriangleCount/2),q=new Vector3();for(let j=0;j<3;j++)q.add(new Vector3().fromBufferAttribute(pos,t*3+j));q.multiplyScalar(1/3).project(v.camera);const r=v.renderer.domElement.getBoundingClientRect();return [r.left+(q.x+1)*r.width/2,r.top+(1-q.y)*r.height/2];});
  await p.mouse.click(...screen);check(id+'_actual_pick',(await p.locator('#native-inspector').innerText()).includes('Gaia Geographic: Not established'));check(id+'_inspector_map',await p.locator('#native-inspector').getAttribute('data-map-id')===id);
  await p.screenshot({path:out+`/screenshots/${id}-topdown.png`});
  const pickedTypes=await p.evaluate(types=>{const viewer=window.__native,r=viewer.renderer.domElement.getBoundingClientRect(),pos=viewer.geometry.getAttribute('position'),picked=[];for(const terrain of types){let attempts=0;for(let t=0;t<viewer.map.sourceTriangleCount&&attempts<300;t++){if(viewer.map.attributes(t).terrain!==terrain)continue;attempts++;const point=viewer.controls.target.clone().set(0,0,0);for(let j=0;j<3;j++)point.x+=pos.getX(t*3+j)/3,point.y+=pos.getY(t*3+j)/3,point.z+=pos.getZ(t*3+j)/3;point.project(viewer.camera);if(Math.abs(point.x)>1||Math.abs(point.y)>1)continue;const hit=viewer.pick(r.left+(point.x+1)*r.width/2,r.top+(1-point.y)*r.height/2);if(hit!==null&&viewer.map.attributes(hit).terrain===terrain){picked.push(terrain);break;}}}return picked;},types);
  for(const terrain of types)check(id+'_terrain_'+terrain+'_raycast',pickedTypes.includes(terrain));
  await p.locator('#map-transitions-file').setInputFiles(root+'output/v1_8/data/gaia-transitions.json');await p.locator('#map-transitions-toggle').check();check(id+'_transition_list',await p.locator('#map-transition-list button').count()>0);
  if(id==='WM3'){check('glacier_anchored_markers',await p.locator('.native-transition-marker').count()>0);await p.locator('#map-transition-list button').first().click();check('transition_inspector_provenance',(await p.locator('#native-inspector').innerText()).includes('Not simulated'));}
  const old=await p.evaluate(()=>window.__native.map.sha256),bad=Buffer.from(readFileSync(root+`output/v1_8/data/gaia-map-${id}.bin`));bad[bad.length-1]^=1;await p.locator('#native-map-file').setInputFiles({name:'bad.bin',mimeType:'application/octet-stream',buffer:bad});await p.waitForTimeout(200);check(id+'_corruption_preserves',await p.evaluate(hash=>window.__native.map.sha256===hash,old));
  await p.waitForTimeout(600);report.metrics[id+'_renderer']=await p.evaluate(()=>window.__native.diagnostics);
 }
 for(const width of [390,320]){await p.setViewportSize({width,height:844});for(const id of ['WM2','WM3']){const start=Date.now();await p.locator('#map-selector').selectOption(id);await p.waitForFunction(id=>window.__native?.map.header.mapId===id&&!!window.__native.pack,id);report.metrics[id+'_switch_ms_'+width]=Date.now()-start;check(id+'_mobile_'+width+'_no_overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.locator('#native-view').selectOption('topdown');const box=await p.locator('.native-viewport canvas').boundingBox();await p.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);check(id+'_mobile_'+width+'_tap',await p.locator('#native-inspector').getAttribute('data-map-id')===id);await p.locator('#native-view').selectOption('3d');await p.screenshot({path:out+`/screenshots/${id}-mobile-${width}.png`});}}
 await p.locator('#native-return').click();check('return_wm0',await p.locator('#map-selector').inputValue()==='WM0');check('native_canvas_disposed',await p.locator('.native-viewport canvas').count()===0);check('wm0_controls_preserved',await p.locator('#projection').count()===1);
 await p.setViewportSize({width:1440,height:1000});await p.locator('.multimap-bar > details').evaluate(el=>el.open=true);await p.locator('.multimap-bar > details details').first().evaluate(el=>el.open=true);check('nested_provenance_normal_flow',await p.locator('.multimap-bar > details details').first().evaluate(el=>getComputedStyle(el).position==='static'));await p.locator('.multimap-bar > details > section').evaluate(el=>{const box=[...el.children].find(box=>box.querySelector('dd')?.textContent==='FIELD');box.querySelector('button').click();});await p.waitForFunction(()=>document.getElementById('map-selector').value==='WM3');check('field_link_open_native_map',await p.locator('.native-viewport canvas').count()===1);await p.locator('#map-transition-list button').first().click();check('provenance_initially_collapsed',await p.locator('#native-inspector details').evaluate(el=>!el.open));
 for(const language of ['en','zh-CN','zh-TW','ja','ko']){await p.evaluate(async language=>{const i=await import('/src/i18n/index.ts');i.setLocale(language);},language);check('native_locale_'+language,await p.locator('#map-selector option[value=WM3]').textContent()!=='map.WM3');}await p.evaluate(async()=>{const i=await import('/src/i18n/index.ts');i.setLocale('en');});
 const production=await c.newPage(),prodRequests=[];production.on('request',r=>prodRequests.push(r.url()));await production.goto('http://127.0.0.1:5175/?lang=en');await production.locator('#map-selector').selectOption('WM2');await production.locator('#native-map-file').setInputFiles(root+'output/v1_8/data/gaia-map-WM2.bin');await production.waitForSelector('.native-viewport canvas');await production.locator('#native-texture-file').setInputFiles(root+'output/v1_8/data/gaia-textures-WM2.bin');await production.waitForTimeout(400);check('production_native_without_WM0',await production.locator('.native-viewport canvas').count()===1);check('production_no_derived_requests',prodRequests.every(u=>!/gaia-(map|textures|mesh|meta|routing|events|poi|encounters)/i.test(u)));await production.close();
 check('no_errors',report.errors.length===0);
}finally{await browser.close();writeFileSync(out+'/results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
