// SPDX-License-Identifier: GPL-3.0-only
import {chromium} from '@playwright/test';
import {fileURLToPath} from 'node:url';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
const root=fileURLToPath(new URL('../../',import.meta.url)),out=root+'output/v2_5/browser';mkdirSync(out+'/tmp',{recursive:true});for(const k of ['TEMP','TMP','TMPDIR'])process.env[k]=out+'/tmp';
const base=process.env.GAIAGIS_DEV_QA_URL??'http://127.0.0.1:5176',local=process.env.GAIAGIS_LOCAL_QA_URL??'http://127.0.0.1:5184';for(const url of [base,local])if(!['127.0.0.1','localhost'].includes(new URL(url).hostname))throw Error('Private QA requires loopback URLs');const report={checks:{},errors:[],external:[],metrics:{}};const check=(id,v)=>{report.checks[id]=!!v;if(!v)throw Error(id);};
const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await b.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce',recordVideo:{dir:out+'/video',size:{width:960,height:600}}});const p=await context.newPage();p.on('pageerror',e=>report.errors.push(String(e)));p.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))report.external.push(r.url());});
await p.route('**/*',async r=>{const u=new URL(r.request().url());if(u.pathname.startsWith('/__gaiagis_local__/')){const res=await fetch(local+u.pathname);await r.fulfill({status:res.status,contentType:res.headers.get('content-type')??'application/octet-stream',body:Buffer.from(await res.arrayBuffer())});}else if(r.request().resourceType()==='document'&&u.pathname==='/'){const res=await r.fetch();await r.fulfill({response:res,body:(await res.text()).replace('<head>','<head><meta name="gaiagis-local" content="true">')});}else await r.continue();});
async function tab(id){if(!await p.locator('#integrated-panel').evaluate(e=>e.classList.contains('open')))await p.locator('#app-menu').click();await p.locator('#app-tab-'+id).click();}
async function bounds(id){const r=await p.evaluate(()=>{const ids=['integrated-panel','integrated-inspector','viewport'],boxes=ids.map(id=>{const e=document.getElementById(id),b=e.getBoundingClientRect();return {visible:b.width>0&&b.height>0,left:b.left,top:b.top,right:b.right,bottom:b.bottom,width:b.width,height:b.height,scroll:e.scrollWidth,client:e.clientWidth};});return {width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,boxes};});check(id+'_bounded',r.scroll<=r.width&&r.boxes.every(v=>!v.visible||v.left>=0&&v.right<=r.width+.5&&v.top>=0&&v.bottom<=r.height+.5));check(id+'_internal_width',r.boxes.slice(0,2).every(v=>!v.visible||v.scroll<=v.client+1));check(id+'_map_usable',r.boxes[2].width>=280&&r.boxes[2].height>=100);}
try{
 await p.goto(base+'/?lang=en');await p.waitForFunction(()=>document.getElementById('workspace-connection')?.dataset.connected==='true'&&document.getElementById('local-workspace-indicator')?.textContent.includes('loaded automatically'),null,{timeout:60000});if(await p.locator('#gaia-intro').isVisible())await p.locator('#gaia-intro button').first().click();
 await tab('analysis');check('auto_workspace',await p.locator('#workspace-connection').getAttribute('data-source')==='auto');check('route_empty',(await p.locator('#spatial-profile').innerText()).includes('Solve a route first'));
 await p.locator('#route-from').fill('Midgar');await p.locator('#route-to').fill('Kalm');await p.locator('#find-route').click();await p.waitForFunction(()=>Number(document.getElementById('analysis-panel')?.dataset.routeNodes)>1,null,{timeout:30000});await p.waitForFunction(()=>Number(document.getElementById('spatial-analysis')?.dataset.samples)>1);
 const route=await p.locator('#spatial-analysis').getAttribute('data-summary');report.metrics.route=JSON.parse(route);report.metrics.routeMs=await p.locator('#spatial-analysis').getAttribute('data-route-ms');check('profile_finite',Object.values(report.metrics.route.metrics).every(Number.isFinite));check('terrain_conservation',Math.abs(report.metrics.route.terrain.reduce((s,r)=>s+r.percentage,0)-100)<1e-7);check('encounter_conservation',Math.abs(report.metrics.route.exposure.reduce((s,r)=>s+r.percentage,0)-100)<1e-7);check('profile_svg',await p.locator('#spatial-profile svg').count()===1);await p.locator('#profile-sample').focus();await p.keyboard.press('ArrowRight');check('profile_keyboard',Number(await p.locator('#profile-sample').inputValue())>0);
 for(const mode of ['foot','chocobo-yellow','chocobo-black','chocobo-gold']){await p.locator('#route-mode').selectOption(mode);await p.locator('#find-route').click();await p.waitForFunction(()=>Number(document.getElementById('analysis-panel')?.dataset.routeNodes)>1);await p.locator('#service-threshold').fill('1000');await p.locator('#calculate-service').click();await p.waitForFunction(m=>document.getElementById('spatial-network')?.querySelector('.spatial-result')?.dataset.profile===m,mode);check('service_'+mode,Number(await p.locator('#spatial-network .spatial-result').getAttribute('data-visited'))>0);report.metrics[mode]={visited:await p.locator('#spatial-network .spatial-result').getAttribute('data-visited'),ms:await p.locator('#spatial-network .spatial-result').getAttribute('data-elapsed-ms')};}
 await p.locator('#route-mode').selectOption('foot');await p.locator('#find-route').click();await p.waitForFunction(()=>Number(document.getElementById('analysis-panel')?.dataset.routeNodes)>1);await p.locator('#calculate-service').click();await p.waitForFunction(()=>document.getElementById('spatial-network')?.querySelector('.spatial-result')?.dataset.profile==='foot');
 await p.locator('#spatial-slope').check();const cache=await p.evaluate(async()=>{const e=(await import('/src/explorer/controller.ts')).activeExplorer,v=e.getWM0();window.qaViewer=v;window.qaSurface=v.sourceSurfaceAnalysis;window.qaSlope=window.qaSurface.slope.slice();window.qaAspect=window.qaSurface.aspect.slice();return {count:v.sourceSurfaceAnalysis.slope.length,bytes:v.sourceSurfaceAnalysis.bytes,ms:v.sourceSurfaceAnalysis.elapsedMs};});report.metrics.surface=cache;check('source_triangle_count',cache.count===142586);
 for(const mode of ['foot','buggy','tiny-bronco','chocobo-yellow','chocobo-green','chocobo-blue','chocobo-black','chocobo-gold']){await p.locator('#route-mode').selectOption(mode);await p.locator('#calculate-service').click();await p.waitForFunction(m=>document.querySelector('#spatial-network .spatial-result')?.dataset.profile===m,mode);check('all_service_'+mode,Number(await p.locator('#spatial-network .spatial-result').getAttribute('data-visited'))>=0);}await p.locator('#route-mode').selectOption('foot');await p.locator('#route-conditional').check();await p.locator('#calculate-service').click();await p.waitForFunction(()=>document.querySelector('#spatial-network .spatial-result')?.dataset.conditional==='true');check('conditional_policy',true);await p.locator('#route-conditional').uncheck();await p.locator('#find-route').click();await p.waitForFunction(()=>Number(document.getElementById('analysis-panel')?.dataset.routeNodes)>1);await p.locator('#calculate-service').click();await p.waitForFunction(()=>document.querySelector('#spatial-network .spatial-result')?.dataset.profile==='foot');const stable=await p.locator('#spatial-analysis').getAttribute('data-summary');const projections=await p.locator('#projection option').evaluateAll(a=>a.map(e=>e.value));
 for(const id of projections){await tab('view');await p.locator('#projection').selectOption(id);await p.waitForFunction(()=>document.getElementById('app')?.dataset.morphing==='false');await tab('analysis');for(const layer of ['slope','aspect','service-area']){await p.locator('#spatial-'+layer).check();check(id+'_'+layer+'_identity',await p.evaluate(()=>window.qaViewer.sourceSurfaceAnalysis===window.qaSurface&&window.qaSurface.slope.every((v,i)=>Object.is(v,window.qaSlope[i]))&&window.qaSurface.aspect.every((v,i)=>Object.is(v,window.qaAspect[i]))));}check(id+'_profile_invariant',await p.locator('#spatial-analysis').getAttribute('data-summary')===stable);}
 await tab('analysis');await p.locator('#spatial-aspect').check();await tab('analysis');await p.locator('#compare-projections').evaluate(e=>{for(let p=e.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;});await p.locator('#compare-projections').check();await p.waitForSelector('.comparison-layout canvas');check('compare_shared_source',await p.evaluate(()=>window.qaViewer.sourceSurfaceAnalysis===window.qaSurface&&window.qaSurface.slope.every((v,i)=>Object.is(v,window.qaSlope[i]))&&window.qaSurface.aspect.every((v,i)=>Object.is(v,window.qaAspect[i]))));await p.locator('#compare-projections').uncheck();
 await tab('layers');check('registered_opacities',await p.locator('#opacity-slope,#opacity-aspect,#opacity-service-area').count()===3);check('unified_legends',await p.locator('#spatial-legends').count()===1);await p.locator('#opacity-aspect').evaluate(e=>{for(let p=e.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;});await p.locator('#opacity-aspect').focus();await p.keyboard.press('Home');for(let i=0;i<7;i++)await p.keyboard.press('ArrowRight');await p.locator('#reset-layers').click();check('layer_reset',await p.locator('#opacity-aspect').inputValue()==='1'&&!await p.locator('#spatial-aspect').isChecked());
 for(const [w,h]of [[1440,900],[390,844],[320,568]]){await p.setViewportSize({width:w,height:h});await tab('analysis');await bounds('analysis_'+w);await p.screenshot({path:out+'/analysis-'+w+'.png'});}
 await p.setViewportSize({width:1440,height:900});
 for(const map of ['WM2','WM3']){await tab('map');await p.locator('#map-selector').selectOption(map);await p.waitForSelector('.native-viewport canvas');await tab('analysis');check(map+'_spatial_unavailable',await p.locator('#calculate-service').isDisabled()&&await p.locator('#spatial-slope').isDisabled());}await tab('map');await p.locator('#map-selector').selectOption('WM0');
 report.metrics.characters=await p.evaluate(async()=>{const {activeExplorer:e}=await import('/src/explorer/controller.ts');await e.arm();const s=e.surface,{locate,advance}=await import('/src/explorer/walker.ts');let face=-1;for(let i=0;i<s.count;i++){if(s.attrs(i).terrain!==0)continue;const p=s.points(i),x=p.reduce((n,v)=>n+v[0]/3,0),z=p.reduce((n,v)=>n+v[1]/3,0);let trial=locate(s,i,[1/3,1/3,1/3]),ok=true;for(let j=0;j<50;j++){const r=advance(s,trial,0,-18,'foot');trial=r.state;if(r.blocked){ok=false;break;}}if(ok&&Math.abs(trial.nativeZ-z+900)<1e-5){face=i;break;}}if(face<0)throw Error('QA source placement');window.qaFace=face;const rows=[];e.getWM0().onExplorerFrame=()=>{};for(const id of ['cloud','barret','tifa','aerith','red-xiii','yuffie','cait-sith','vincent','cid']){e.keys.clear();e.selectVisual(id);e.armed=true;e.place(face,[1/3,1/3,1/3]);e.seconds=0;const x=e.state.nativeX,z=e.state.nativeZ;e.keys.add('w');for(let i=0;i<50;i++)e.frame(.02);e.keys.clear();e.frame(0);e.model.object.updateMatrixWorld(true);rows.push({id,hrc:e.model.model.hrc,moveClip:e.model.model.clips[e.model.model.sourceKind==='extended_field'?2:1].name,distance:Math.hypot(e.state.nativeX-x,e.state.nativeZ-z),idle:e.state.animationState,finite:e.model.bones.every(b=>b.matrixWorld.elements.every(Number.isFinite))});}return rows;});
 for(const c of report.metrics.characters){check(c.id+'_foot_displacement',Math.abs(c.distance-900)<1e-5);check(c.id+'_finite_idle',c.finite&&c.idle===0);}
 for(const id of ['cloud','barret','tifa','aerith','red-xiii','yuffie','cait-sith','vincent','cid']){await p.evaluate(async id=>{const e=(await import('/src/explorer/controller.ts')).activeExplorer;e.keys.clear();e.selectVisual(id);e.armed=true;e.place(window.qaFace,[1/3,1/3,1/3]);e.getWM0().onExplorerFrame=dt=>e.frame(dt);e.keys.add('w');},id);await p.waitForTimeout(1200);await p.screenshot({path:out+'/run-'+id+'.png'});await p.evaluate(async()=>{const e=(await import('/src/explorer/controller.ts')).activeExplorer;e.keys.clear();});}
 await p.locator('#explorer-hud-exit').click();check('explorer_exit',await p.locator('#explorer-panel').getAttribute('data-state')!=='active');
 for(const lang of ['en','zh-CN','zh-TW','ja','ko']){await p.evaluate(async lang=>(await import('/src/i18n/index.ts')).setLocale(lang),lang);await tab('analysis');check('locale_'+lang,await p.evaluate(async()=>{const {t}=await import('/src/i18n/index.ts');return document.querySelector('#spatial-profile h3')?.textContent===t('sp25.profile')&&document.querySelector('#spatial-profile details p:nth-of-type(2)')?.textContent===t('sp25.method')+': '+t('sp25.routeMethod')&&document.querySelector('#calculate-service')?.textContent===t('sp25.calculate')&&!document.getElementById('spatial-analysis').innerText.includes('sp25.');}));}
 report.metrics.locales=await p.evaluate(async()=>Object.fromEntries(Object.entries((await import('/src/i18n/index.ts')).dictionaries).map(([k,v])=>[k,Object.keys(v).length])));check('no_errors',report.errors.length===0);check('no_external_requests',report.external.length===0);
}catch(e){report.failure=String(e);report.pageState=await p.evaluate(()=>({advertised:document.querySelector('meta[name=gaiagis-local]')?.outerHTML,text:document.body.innerText,errors:[...document.querySelectorAll('[title]')].filter(e=>e.title.includes('Error')).map(e=>e.title)}));process.exitCode=1;await p.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{writeFileSync(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:Object.values(report.checks).filter(Boolean).length,total:Object.keys(report.checks).length,failure:report.failure,errors:report.errors,external:report.external}));await context.close();await b.close();}
