// SPDX-License-Identifier: GPL-3.0-only
import {describe,it,expect} from 'vitest';
import {initialState,reduce,capabilities,features,featureAvailable,AppStore} from '../src/app/state';
import {ResourceScope} from '../src/app/resources';
import {parseManifest,discoverWorkspace,WorkspaceLoader,fileHash,directoryFiles,assetSources} from '../src/app/workspace';
import {registerNavigation,clearNavigation,searchNavigation} from '../src/app/navigation';
import type {WorkspaceManifest} from '../src/app/workspace';
const file=(name:string,body?:string)=>new File([body??(name.endsWith('.json')?'{}':new Uint8Array(16))],name);
const manifest=():WorkspaceManifest=>({schema:'gaiagis-workspace',version:1,tool_version:'synthetic',timestamp_policy:'omitted',sources:{'wm0.map':'a'.repeat(64)},assets:[{filename:'gaia-meta.json',type:'metadata',mapId:'WM0',sha256:'1'.repeat(64),bytes:9,dependencies:[]},{filename:'gaia-mesh.bin',type:'geometry',mapId:'WM0',sha256:'2'.repeat(64),bytes:9,dependencies:['gaia-meta.json']}]});
describe('integrated application state',()=>{
 it('keeps slice identity except updated slice',()=>{const s=initialState(),next=reduce(s,{type:'asset',id:'geometry',asset:{status:'loaded',bytes:10}});expect(next.map).toBe(s.map);expect(s.data.assets.geometry).toBeUndefined();});
 it('separates map, coordinate space and overview view',()=>{const s=reduce(initialState(),{type:'map',id:'WM2'});expect(s.map.coordinateSpace).toBe('WM2Native');expect(s.view.projection).toBe('globe');});
 it.each(['WM0','WM2','WM3'] as const)('invalidates cross-map selection and active modes on %s switch',id=>{let s=initialState();s.selection={kind:'location',mapId:'WM0',id:'synthetic'};s.explorer.phase='active';s.view.compare=true;s=reduce(s,{type:'map',id});expect(s.selection).toBeNull();expect(s.explorer.phase).toBe('idle');expect(s.view.compare).toBe(false);});
 it('rejects a selection in another coordinate space',()=>{expect(reduce(initialState(),{type:'select',selection:{id:'0',kind:'triangle',mapId:'WM2'}}).selection).toBeNull();});
 it.each(['triangle','location','entrance','encounter','event','transition','route','measurement','explorer'] as const)('supports %s selection without copying its data owner',kind=>{const s=reduce(initialState(),{type:'select',selection:{id:'reference',kind,mapId:'WM0'}});expect(s.selection?.kind).toBe(kind);expect(Object.keys(s.selection!)).toEqual(['id','kind','mapId']);});
 it('preserves safe preferences on data replacement and uses registry capabilities',()=>{let s=reduce(initialState(),{type:'preference',preferences:{language:'zh-CN',graticule:'15',surfaceStyle:'texture'}});s=reduce(s,{type:'reset-data'});expect(s.preferences.language).toBe('zh-CN');expect(featureAvailable('routing',s)).toBe(false);expect(featureAvailable('unknown',s)).toBe(false);});
 it('requires actual datasets for route and Explorer capabilities',()=>{let s=initialState();expect(capabilities(s).canExplore).toBe(false);for(const id of ['geometry','routing','locations','explorer'] as const)s=reduce(s,{type:'asset',id,asset:{status:'loaded',bytes:1}});expect(capabilities(s).canRoute).toBe(true);expect(capabilities(s).canExplore).toBe(true);s=reduce(s,{type:'map',id:'WM2'});expect(capabilities(s).canRoute).toBe(false);expect(capabilities(s).canMeasureSphere).toBe(false);});
 it('legacy data remains usable but corrupt data does not',()=>{const s=reduce(initialState(),{type:'asset',id:'geometry',asset:{status:'legacy',bytes:1}});expect(capabilities(s).canProjectGlobally).toBe(true);expect(capabilities(reduce(s,{type:'asset',id:'geometry',asset:{status:'corrupt',bytes:1}})).canProjectGlobally).toBe(false);});
 it('Explorer locks analysis without changing reconstruction view',()=>{const s=reduce(initialState(),{type:'explorer',phase:'active'});expect(s.analysis.tool).toBe('none');expect(s.view.projection).toBe('globe');expect(capabilities(s).canMeasureSphere).toBe(false);});
 it('registry uniquely covers requested features',()=>{expect(new Set(features.map(f=>f.id)).size).toBe(features.length);for(const id of ['locations','encounters','tracks','traversal','events','routing','transitions','measurement','distortion','explorer'])expect(features.some(f=>f.id===id)).toBe(true);});
 it('unsubscribe and idempotent resource cleanup do not leak listeners',()=>{const store=new AppStore();let calls=0;const stop=store.subscribe(()=>calls++);stop();store.dispatch({type:'panel',panel:'data'});expect(calls).toBe(0);const scope=new ResourceScope(),target=new EventTarget();scope.listen(target,'change',()=>calls++);scope.own(()=>calls+=10);target.dispatchEvent(new Event('change'));scope.dispose();scope.dispose();target.dispatchEvent(new Event('change'));expect(calls).toBe(11);});
});
describe('source binding and local discovery',()=>{
 it('rejects mixed source assets before the optional owner adopts',async()=>{const outcomes:string[]=[],loader=new WorkspaceLoader((id,s)=>outcomes.push(id+':'+s.status));let adopted=false;loader.register('geometry',async()=>{});loader.register('locations',async()=>{adopted=true;});await loader.load([file('gaia-meta.json',JSON.stringify({stage1:{source_wm0_sha256:'a'.repeat(64)}})),file('gaia-mesh.bin'),file('gaia-poi.json',JSON.stringify({sources:{'wm0.map':'b'.repeat(64)}}))]);expect(adopted).toBe(false);expect(outcomes).toContain('locations:incompatible');});
 it('preserves uppercase legacy fingerprints without weakening validation',async()=>expect(await assetSources(file('gaia-meta.json',JSON.stringify({stage1:{source_wm0_sha256:'A'.repeat(64)}})))).toEqual({'wm0.map':'A'.repeat(64)}));
 it('rejects malformed source hashes',async()=>{await expect(assetSources(file('gaia-poi.json',JSON.stringify({sources:{'wm0.map':'wrong'}})))).rejects.toThrow();});
 it('blocks an optional asset when its declared dependency is missing',async()=>{const m=manifest(),native=file('gaia-map-WM2.bin'),tex=file('gaia-textures-WM2.bin');m.assets.push({filename:native.name,type:'WM2',mapId:'WM2',sha256:await fileHash(native),bytes:native.size,dependencies:[]},{filename:tex.name,type:'textures-WM2',mapId:'WM2',sha256:await fileHash(tex),bytes:tex.size,dependencies:[native.name]});const p=await discoverWorkspace([file('gaia-workspace.json',JSON.stringify(m)),tex]);expect(p.issues.WM2?.status).toBe('missing');expect(p.issues['textures-WM2']?.status).toBe('incompatible');});
 it('folder discovery reads known root files only, never traverses children',async()=>{let secretRead=false;const directory={kind:'directory' as const,async *values(){yield {kind:'directory' as const,async *values(){secretRead=true;}};yield {kind:'file' as const,name:'private-save.bin',async getFile(){secretRead=true;return file('private-save.bin');}};yield {kind:'file' as const,name:'gaia-mesh.bin',async getFile(){return file('gaia-mesh.bin');}};}};expect((await directoryFiles(directory)).map(f=>f.name)).toEqual(['gaia-mesh.bin']);expect(secretRead).toBe(false);});
 it('late registered cleanup executes once without reviving its scope',()=>{let n=0;const scope=new ResourceScope();scope.dispose();scope.own(()=>n++);scope.dispose();expect(n).toBe(1);});
 it('serializes owner adoption so an obsolete asynchronous load cannot win',async()=>{let release!:()=>void,started!:()=>void;const gate=new Promise<void>(r=>release=r),begin=new Promise<void>(r=>started=r),adopted:string[]=[];const loader=new WorkspaceLoader(()=>{});loader.register('geometry',async files=>{const label=JSON.parse(await files[0].text()).label;if(label==='old'){started();await gate;}adopted.push(label);});const old=loader.load([file('gaia-meta.json','{"label":"old"}'),file('gaia-mesh.bin')]);await begin;const next=loader.load([file('gaia-meta.json','{"label":"new"}'),file('gaia-mesh.bin')]);release();await Promise.all([old,next]);expect(adopted).toEqual(['old','new']);});
 it('ranks locations before entrances and searches verified internal aliases',()=>{const make=(kind:'location'|'entrance',id:string,name:string,aliases:string[])=>({id,kind,name,aliases,mapId:'WM0' as const,navigate:()=>{}});registerNavigation('synthetic',[make('entrance','e','Town',[ 'internal']),make('location','l','Town',[]),make('location','l2','Town South',[])]);expect(searchNavigation('town').map(e=>e.id)).toEqual(['l','e','l2']);expect(searchNavigation('INTERNAL')[0].id).toBe('e');clearNavigation('synthetic');expect(searchNavigation('town')).toEqual([]);});
});
describe('local workspace validation and isolation',()=>{
 it('supports schema independent from application version',()=>expect(parseManifest(manifest()).version).toBe(1));
 it.each(['wrong-schema','wrong-map','path','duplicate','cycle','hash'] )('rejects %s manifest',kind=>{const m=manifest();if(kind==='wrong-schema')m.version=2 as 1;if(kind==='wrong-map')m.assets[0].mapId='WM2';if(kind==='path')m.assets[0].filename='../gaia-meta.json';if(kind==='duplicate')m.assets.push({...m.assets[0]});if(kind==='cycle')m.assets[0].dependencies=['gaia-mesh.bin'];if(kind==='hash')m.assets[0].sha256='invalid';expect(()=>parseManifest(m)).toThrow();});
 it('handles no manifest as legacy without inventing optional data',async()=>{const p=await discoverWorkspace([file('gaia-meta.json'),file('gaia-mesh.bin')]);expect(p.manifest).toBeNull();expect(p.issues.geometry).toBeUndefined();expect(p.issues.routing?.status).toBe('optional');});
 it('rejects duplicate basename rather than silently picking a folder',async()=>{await expect(discoverWorkspace([file('gaia-meta.json'),file('gaia-meta.json')])).rejects.toThrow();});
 it('validates manifest hash/size before adoption',async()=>{const m=manifest(),files=[file('gaia-meta.json'),file('gaia-mesh.bin')];for(const a of m.assets){const f=files.find(f=>f.name===a.filename)!;a.sha256=await fileHash(f);a.bytes=f.size;}expect((await discoverWorkspace([...files,file('gaia-workspace.json',JSON.stringify(m))])).issues.geometry).toBeUndefined();m.assets[1].sha256='f'.repeat(64);expect((await discoverWorkspace([...files,file('gaia-workspace.json',JSON.stringify(m))])).issues.geometry?.status).toBe('corrupt');});
 it('isolates optional corruption and continues later adoption',async()=>{const outcomes:string[]=[],loader=new WorkspaceLoader((id,s)=>outcomes.push(`${id}:${s.status}`));loader.register('geometry',async()=>{});loader.register('locations',async()=>{throw Error('Synthetic corrupt');});loader.register('encounters',async()=>{});await loader.load(['gaia-meta.json','gaia-mesh.bin','gaia-poi.json','gaia-encounters.json'].map(n=>file(n)));expect(outcomes).toContain('locations:corrupt');expect(outcomes).toContain('encounters:legacy');});
 it('cancels obsolete loads before later assets are adopted',async()=>{const outcomes:string[]=[],loader=new WorkspaceLoader((id,s)=>outcomes.push(`${id}:${s.status}`));loader.register('geometry',async()=>loader.cancel());await loader.load([file('gaia-meta.json'),file('gaia-mesh.bin'),file('gaia-poi.json')]);expect(outcomes).not.toContain('locations:loading');});
});
