// SPDX-License-Identifier: GPL-3.0-only
import {describe,it,expect} from 'vitest';
import {geoArea} from 'd3-geo';
import {geoEqualEarthRaw,geoMercatorRaw} from 'd3-geo';
import {geoMollweideRaw,geoCylindricalEqualAreaRaw,geoSinusoidalRaw} from 'd3-geo-projection';
import {REFERENCE_RADIUS as R,centralAngle,measureDistance,measureArea,greatCircle,measurementSegments,validPoint} from '../src/analysis/sphere';
import {GRID_CANDIDATES,chooseInterval,minorInterval,visibleGridBounds,adaptiveGrid} from '../src/analysis/adaptive';
import {distortion,inverseDisplay,tissotFrame,linkedContext} from '../src/analysis/distortion';
import {classifyComparison} from '../src/analysis/comparison';
import {projections} from '../src/projections';
import {projectionIds} from '../src/projections/registry';
import {routeSegments} from '../src/viewer/route';
import {screenGridPolicy} from '../src/viewer/gridPolicy';
import {OrthographicCamera,PerspectiveCamera} from 'three';
import {latitudeLabel,longitudeLabel} from '../src/viewer/navigation';
import {setLocale,locales} from '../src/i18n';
import type {GeoPoint,ProjectionId} from '../src/projections/Projection';
const c={radius:R,mercatorLimit:85.0511287798066,centerLon:0,centerLat:0},rad=Math.PI/180;
describe('reference sphere measurement',()=>{
 it('equator one degree and quarter circumference',()=>{expect(measureDistance([[0,0,0],[1,0,0]]).total).toBeCloseTo(R*rad,7);expect(measureDistance([[0,0,0],[90,0,0]]).total).toBeCloseTo(Math.PI*R/2,7);});
 it('short antimeridian and polar arcs',()=>{expect(centralAngle([179,0,0],[-179,0,0])).toBeCloseTo(2*rad,12);expect(centralAngle([0,89,0],[180,89,0])).toBeCloseTo(2*rad,12);});
 it('sums multi-segment arcs and excludes height',()=>{const d=measureDistance([[0,0,100],[90,0,0],[90,90,10000]]);expect(d.segments.length).toBe(2);expect(d.total).toBeCloseTo(Math.PI*R,7);expect(validPoint([370,5,600])).toEqual([10,5,0]);});
 it('octant area and reversal',()=>{const p:GeoPoint[]=[[0,0,0],[90,0,0],[0,90,0]];expect(measureArea(p).steradians).toBeCloseTo(Math.PI/2,12);expect(measureArea(p).percent).toBeCloseTo(12.5,12);expect(measureArea([...p].reverse()).area).toBeCloseTo(measureArea(p).area,1);});
 it('avoids an antipodal fan diagonal when polygon edges themselves are well-defined',()=>{const p:GeoPoint[]=[[0,0,0],[90,80,0],[180,0,0],[-90,-80,0]];expect(measureArea(p).steradians).toBeCloseTo(2*Math.PI,10);});
 for(const [name,coordinates]of Object.entries({seam:[[179,-10],[-179,-10],[-179,10],[179,10]],pole:[[-120,80],[0,80],[120,80]],concave:[[0,0],[15,0],[8,5],[15,10],[0,10]]}))it(`${name} polygon agrees with independent d3 spherical area`,()=>{const p=coordinates.map(([x,y])=>[x,y,0] as GeoPoint),oracle=geoArea({type:'Polygon',coordinates:[[...coordinates,coordinates[0]]]}),smaller=Math.min(oracle,4*Math.PI-oracle);expect(measureArea(p).steradians).toBeCloseTo(smaller,10);});
 it('rejects intersecting, antipodal, invalid and underspecified polygons',()=>{expect(()=>measureArea([[0,0,0],[10,10,0],[0,10,0],[10,0,0]])).toThrow();expect(()=>measureArea([[0,0,0],[180,0,0],[90,20,0]])).toThrow();expect(()=>measureArea([[0,0,0]])).toThrow();expect(()=>validPoint([0,91,0])).toThrow();expect(()=>greatCircle([0,0,0],[180,0,0])).toThrow();});
 it('rejects repeated spherical vertices, empty/invalid radius and invalid single points',()=>{expect(()=>measureArea([[0,0,0],[10,0,0],[0,10,0],[0,0,0]])).toThrow();expect(()=>measureDistance([[NaN,0,0]])).toThrow();expect(()=>measureArea([[0,0,0],[10,0,0],[0,10,0]],Infinity)).toThrow();expect(()=>measureDistance([],0)).toThrow();});
 it('great-circle samples stay on sphere and seam-safe segments never bridge across world',()=>{const p=greatCircle([170,40,0],[-170,40,0]);expect(p[0][0]).toBeCloseTo(170,10);expect(p.at(-1)![0]).toBeCloseTo(-170,10);expect(p[Math.floor(p.length/2)][1]).toBeGreaterThan(40);const s=routeSegments(p);for(let i=0;i<s.length;i+=6)expect(Math.abs(s[i+3]-s[i])).toBeLessThan(2);});
 it('stored spherical results are projection invariant for all thirteen displays',()=>{const points:GeoPoint[]=[[170,20,0],[-170,20,0],[-170,40,0]],distance=measureDistance(points).total,area=measureArea(points).area;for(const id of projectionIds){const display=measurementSegments(points,true).map(p=>projections[id].project(...p,c));expect(display.every(p=>p.every(Number.isFinite))).toBe(true);expect(measureDistance(points).total).toBe(distance);expect(measureArea(points).area).toBe(area);}});
});
describe('adaptive graticule',()=>{
 it('uses discrete candidates at increasing screen scale',()=>{let last=90;for(const px of [.7,1,2,4,8,16,40,100,300,1000]){const step=chooseInterval(d=>d*px,90);expect(GRID_CANDIDATES).toContain(step);expect(step).toBeLessThanOrEqual(last);last=step;}});
 it('hysteresis holds between sixty and one hundred ninety pixels',()=>{for(const px of [60,80,160,190])expect(chooseInterval(d=>d/10*px,10)).toBe(10);expect(chooseInterval(d=>d*20,10)).not.toBe(10);expect(chooseInterval(d=>d*5,10)).not.toBe(10);});
 it('minor lines remain readable and use integer divisions',()=>{expect(minorInterval(10,d=>d*15)).toBe(2);expect(minorInterval(.1,d=>d*1000)).toBeNull();});
 it('resize and zoom change the conservative visible window',()=>{const a=visibleGridBounds(0,0,10,320,400,5),b=visibleGridBounds(0,0,10,1440,900,5),z=visibleGridBounds(0,0,100,1440,900,5);expect(b.east-b.west).toBeGreaterThan(a.east-a.west);expect(z.east-z.west).toBeLessThan(b.east-b.west);});
 it('generated segments split the antimeridian and distinguish major/minor',()=>{const grid=adaptiveGrid(10,{west:160,east:200,south:-20,north:20},2);expect(grid.kind).toContain(1);for(let i=0;i<grid.geo.length;i+=6){expect(Math.abs(grid.geo[i+3]-grid.geo[i])).toBeLessThanOrEqual(1.01);expect(Math.abs(grid.geo[i])).toBeLessThanOrEqual(180);}});
 it('bounds and density guards reject unsupported spacing',()=>{expect(()=>adaptiveGrid(0,{west:0,east:10,south:0,north:10})).toThrow();const grid=adaptiveGrid(.1,{west:-180,east:180,south:-90,north:90});expect(grid.geo.length).toBeLessThan(1_000_000);});
 it('full-world windows never duplicate a periodic meridian cycle',()=>{const b=visibleGridBounds(179,0,1,1440,900,30);expect(b.east-b.west).toBe(360);});
 it('screen spacing uses actual cameras, zoom and viewport rather than a zoom-to-degree table',()=>{const camera=new OrthographicCamera(-Math.PI,Math.PI,Math.PI/2,-Math.PI/2,.01,100);camera.position.z=8;camera.updateMatrixWorld();const a=screenGridPolicy('equirectangular',c,camera,1200,600,[0,0,0],'auto',90,true);expect(a.interval).toBe(30);expect(a.pixels).toBeCloseTo(100,6);camera.zoom=4;camera.updateProjectionMatrix();const b=screenGridPolicy('equirectangular',c,camera,1200,600,[0,0,0],'auto',a.interval,true);expect(b.interval).toBe(10);expect(b.pixels).toBeCloseTo(133.3333333,5);});
 it('Globe and all azimuthal cameras produce finite adaptive estimates',()=>{const camera=new PerspectiveCamera(45,1.5,.01,100);camera.position.z=3.5;camera.updateMatrixWorld();const g=screenGridPolicy('globe',c,camera,900,600,[0,0,0],'auto',90,true);expect(Number.isFinite(g.pixels)).toBe(true);for(const id of ['orthographic','laea','aeqd'] as ProjectionId[]){const camera=new OrthographicCamera(-3,3,2,-2,.01,100);camera.position.z=8;camera.updateMatrixWorld();const p=screenGridPolicy(id,c,camera,900,600,[0,0,0],'auto',90,true);expect(Number.isFinite(p.pixels)).toBe(true);expect(GRID_CANDIDATES).toContain(p.interval);}});
 it.each(locales)('fractional labels preserve hemisphere and locale number formatting in %s',language=>{setLocale(language,false);expect(latitudeLabel(-.25,2)).toContain('S');expect(longitudeLabel(.5,1)).toContain('E');expect(longitudeLabel(-.5,1)).toContain('W');expect(latitudeLabel(.25,2)).toContain('N');setLocale('en',false);});
});
describe('projection numerical factors',()=>{
 for(const id of ['equal-earth','mollweide','sinusoidal','gall-peters','laea'] as ProjectionId[])it(`${id} area scale is one on a unit reference sphere`,()=>{for(const lon of [-120,-30,0,60,120])for(const lat of [-60,-20,0,40,70]){const m=distortion(id,lon,lat,c);expect(m).not.toBeNull();expect(m!.areaScale).toBeCloseTo(1,6);}});
 it('Mercator is conformal with secant scale and secant squared area',()=>{for(const lat of [0,20,40,60,80]){const m=distortion('mercator',15,lat,c)!;expect(m.maxScale).toBeCloseTo(1/Math.cos(lat*rad),6);expect(m.minScale).toBeCloseTo(m.maxScale,6);expect(m.angularDeformation).toBeLessThan(.0001);expect(m.areaScale).toBeCloseTo(1/Math.cos(lat*rad)**2,5);}});
 it('AEQD center has unit radial and transverse scales',()=>{const rotated={...c,centerLon:30,centerLat:40},m=distortion('aeqd',30,40,rotated)!;expect(m.maxScale).toBeCloseTo(1,6);expect(m.minScale).toBeCloseTo(1,6);expect(m.areaScale).toBeCloseTo(1,6);});
 for(const [id,oracle]of [['equal-earth',geoEqualEarthRaw],['mercator',geoMercatorRaw],['mollweide',geoMollweideRaw],['sinusoidal',geoSinusoidalRaw],['gall-peters',geoCylindricalEqualAreaRaw(Math.PI/4)]] as const)it(`${id} factors agree with independent d3 forward differences`,()=>{const lon=30,lat=40,h=2e-6,[w,e,s,n]=[[lon*rad-h,lat*rad],[lon*rad+h,lat*rad],[lon*rad,lat*rad-h],[lon*rad,lat*rad+h]].map(([x,y])=>oracle(x,y)),a=(e[0]-w[0])/(2*h*Math.cos(lat*rad)),d=(e[1]-w[1])/(2*h*Math.cos(lat*rad)),b=(n[0]-s[0])/(2*h),f=(n[1]-s[1])/(2*h);expect(distortion(id,lon,lat,c)!.areaScale).toBeCloseTo(Math.abs(a*f-b*d),6);});
 it('seams, poles, clipped hemisphere and Globe have unavailable metrics',()=>{expect(distortion('globe',0,0,c)).toBeNull();expect(distortion('equal-earth',180,0,c)).toBeNull();expect(distortion('mercator',0,90,c)).toBeNull();expect(distortion('orthographic',120,0,c)).toBeNull();});
 for(const id of projectionIds.filter(id=>id!=='globe'))it(`${id} bounded display inversion resolves visible points`,()=>{for(const [lon,lat]of [[0,0],[20,30],[-45,-20],[70,10]]){const [x,y]=projections[id].project(lon,lat,0,c),actual=inverseDisplay(id,x,y,c);expect(actual).not.toBeNull();expect(actual![0]).toBeCloseTo(lon,4);expect(actual![1]).toBeCloseTo(lat,4);}});
 it('Tissot buffers are finite, fixed-size and clipped in azimuthal views',()=>{for(const id of projectionIds){const frame=tissotFrame(id,c);expect(frame.mask.length).toBe(55*64);expect(frame.positions.length).toBe(frame.mask.length*3);expect(frame.positions.every(Number.isFinite)).toBe(true);if(id==='globe')expect(frame.mask.every(x=>x===-1)).toBe(true);if(['orthographic','laea','aeqd'].includes(id)){const limit=id==='orthographic'?1:id==='laea'?2:Math.PI;for(let i=0;i<frame.mask.length;i++)if(frame.mask[i]>0)expect(Math.hypot(frame.positions[i*3],frame.positions[i*3+1])).toBeLessThan(limit+1e-6);}}});
});
describe('linked comparison and four classes',()=>{
 it('classifies A-only B-only Both Neither without altering flags',()=>{const a=new Uint8Array([0,1,0,1]),b=new Uint8Array([0,0,1,1]),r=classifyComparison(a,b);expect([...r.flags]).toEqual([0,1,2,3]);expect(r.counts).toEqual([1,1,1,1]);expect([...a]).toEqual([0,1,0,1]);expect(()=>classifyComparison(a,b.slice(1))).toThrow();});
 it('links azimuthal centers and leaves cylindrical origin unchanged',()=>{const p:GeoPoint=[179,40,0];for(const id of ['laea','aeqd','orthographic'] as ProjectionId[]){expect(linkedContext(id,c,p).centerLon).toBe(179);expect(linkedContext(id,c,p).centerLat).toBe(40);}expect(linkedContext('equal-earth',c,p)).toEqual(c);expect(c.centerLon).toBe(0);});
});
