// SPDX-License-Identifier: GPL-3.0-only
import {describe,it,expect,afterEach,vi} from 'vitest';
import {catalog,dictionaries,locales,detectLocale,matchLocale,t,setLocale,formatNumber,onLocaleChange} from '../src/i18n';
import {projectionRegistry} from '../src/projections/registry';
import {routeProfiles} from '../src/data/routing';
afterEach(()=>{setLocale('en',false);vi.unstubAllGlobals();});
describe('five complete UI dictionaries',()=>{
 it('covers every registered projection property/family and analysis movement label',()=>{for(const l of locales){for(const p of Object.values(projectionRegistry))for(const key of [p.translationKey,`family.${p.family}`,`property.${p.property}`])expect(dictionaries[l][key]?.trim()).toBeTruthy();for(const p of routeProfiles)expect(dictionaries[l][`mode.${p.id}`]?.trim()).toBeTruthy();}});
 it('has stable unique keys, parity, nonempty strings and no HTML injection',()=>{expect(new Set(catalog.map(r=>r[0])).size).toBe(catalog.length);for(const l of locales){expect(Object.keys(dictionaries[l])).toEqual(Object.keys(dictionaries.en));for(const [key,value]of Object.entries(dictionaries[l])){expect(key).toMatch(/^[\w.-]+$/);expect(value.trim()).not.toBe('');expect(value).not.toMatch(/<\/?[a-zA-Z]|<script|onerror=/);const slots=(s:string)=>[...s.matchAll(/\{(\w+)\}/g)].map(x=>x[1]).sort();expect(slots(value)).toEqual(slots(dictionaries.en[key]));}}});
 it.each([['zh-Hant','zh-TW'],['zh-HK','zh-TW'],['zh-TW','zh-TW'],['zh-SG','zh-CN'],['ja-JP','ja'],['ko-KR','ko'],['en-GB','en'],['fr',null]])('matches supported browser language %s', (a,b)=>expect(matchLocale(a)).toBe(b));
 it('prioritizes URL, saved language, navigator.languages, then English',()=>{expect(detectLocale('https://example.test/?lang=ja','ko',['zh-CN'])).toBe('ja');expect(detectLocale('https://example.test/','ko',['zh-CN'])).toBe('ko');expect(detectLocale('https://example.test/',null,['fr','zh-Hant'])).toBe('zh-TW');expect(detectLocale('https://example.test/?lang=xx',null,['fr'])).toBe('en');});
 it.each(locales)('interpolates and uses Intl numbers in %s without changing raw IDs',l=>{setLocale(l,false);const value=t('message.entrance',{field:'las0_1',entry:59,scenario:0});expect(value).toContain('las0_1');expect(value).toContain('59');expect(formatNumber(12345.678,2)).toBe(new Intl.NumberFormat(l,{maximumFractionDigits:2}).format(12345.678));});
 it('safe missing-key fallback and immediate subscription with cleanup',()=>{const listener=vi.fn(),unsub=onLocaleChange(listener);setLocale('ja',false);expect(t('ui.display')).toBe('表示');expect(listener).toHaveBeenCalledOnce();unsub();setLocale('ko',false);expect(listener).toHaveBeenCalledOnce();expect(t('future.missing')).toBe('future.missing');});
 it('falls back to English for a missing translated entry',()=>{const value=dictionaries.ja['ui.display'];delete dictionaries.ja['ui.display'];try{setLocale('ja',false);expect(t('ui.display')).toBe('Display');}finally{dictionaries.ja['ui.display']=value;}});
 it('saves preference and preserves locale URL without reload',()=>{const save=vi.fn(),replace=vi.fn();vi.stubGlobal('localStorage',{setItem:save});vi.stubGlobal('location',{href:'https://example.test/?lang=en#location=midgar'});vi.stubGlobal('history',{replaceState:replace});setLocale('ja');expect(save).toHaveBeenCalledWith('gaiagis.locale','ja');expect(String(replace.mock.calls[0][2])).toBe('https://example.test/?lang=ja#location=midgar');});
});
