// SPDX-License-Identifier: GPL-3.0-only
import {describe,it,expect} from 'vitest';
import {OrthographicCamera,PerspectiveCamera} from 'three';
import {freshUserState,UserStateStorage,validateUserState,migrateUserState,parseLocalView,parseTour,RECENT_LIMIT,USER_STATE_KEY} from '../src/app/userState';
import type {IdentityTarget,LocalView,StoragePort,TourStop} from '../src/app/userState';
import {defaultOpacities,defaultVisibility,layerIds} from '../src/app/layers';
import {encodeShare,decodeShare,validateShareState} from '../src/app/shareState';
import type {ShareState} from '../src/app/shareState';
import {NearbyIndex} from '../src/navigation/nearby';
import type {NearbyAnchor} from '../src/navigation/nearby';
import {TourPlayback,RoutePlayback} from '../src/navigation/playback';
import {localScreenScale,screenGeographic} from '../src/navigation/scale';
import {REFERENCE_RADIUS,measureDistance} from '../src/analysis/sphere';
import {projections} from '../src/projections';
const target=(id='midgar',kind:IdentityTarget['kind']='location'):IdentityTarget=>({kind,id,mapId:'WM0'});
const view=():LocalView=>({mapId:'WM0',projection:'mercator',native:'3d',camera:{position:[0,1,8],target:[0,1,0],up:[0,1,0],zoom:2,center:[0,0]},layers:defaultVisibility(),opacity:defaultOpacities(),selected:target()});
class Memory implements StoragePort {data=new Map<string,string>();getItem(k:string){return this.data.get(k)??null;}setItem(k:string,v:string){this.data.set(k,v);}removeItem(k:string){this.data.delete(k);}}
const bookmark=(id='bookmark-a',t:IdentityTarget|null=target())=>({id,name:'My place',note:'Local note',created:123,target:t,view:t?null:view()});
describe('central private user-state lifecycle',()=>{
 it('starts independently of workspace version and recovers unavailable storage',()=>{expect(freshUserState().version).toBe(1);const s=new UserStateStorage(null);s.update(s=>s.bookmarks.push(bookmark()));expect(s.status).toBe('memory');expect(s.state.bookmarks).toHaveLength(1);});
 it('migrates identity-only version 0 and writes version 1 on edit',()=>{const m=new Memory();m.setItem(USER_STATE_KEY,JSON.stringify({schema:'gaiagis-user-state',version:0,favorites:[target()]}));const s=new UserStateStorage(m);expect(s.state.bookmarks[0].target?.id).toBe('midgar');s.update(s=>s.bookmarks[0].name='Renamed');expect(JSON.parse(m.getItem(USER_STATE_KEY)!).version).toBe(1);});
 it.each(['{bad',JSON.stringify({schema:'workspace',version:1}),JSON.stringify({...freshUserState(),version:99})])('recovers invalid stored state %s',raw=>{const m=new Memory();m.setItem(USER_STATE_KEY,raw);const s=new UserStateStorage(m);expect(s.status).toBe('recovered');expect(s.state.bookmarks).toHaveLength(0);});
 it('retains edited memory after quota errors and read exceptions',()=>{const m={getItem(){throw Error('Denied');},setItem(){throw Error('Quota');},removeItem(){}};const s=new UserStateStorage(m);s.update(s=>s.bookmarks.push(bookmark()));expect(s.state.bookmarks).toHaveLength(1);expect(s.status).toBe('memory');});
 it.each(['location','atlas','entrance','transition'] as const)('persists/re-resolves %s identities without copying coordinates',kind=>{const m=new Memory(),s=new UserStateStorage(m);s.update(s=>s.bookmarks.push(bookmark('b',target('known-id',kind))));expect(new UserStateStorage(m).state.bookmarks[0].target).toEqual(target('known-id',kind));expect(JSON.stringify(s.state.bookmarks[0])).not.toMatch(/longitude|latitude|summary|sources/);});
 it('stores private view camera locally, renames and deletes with recent cleanup',()=>{const m=new Memory(),s=new UserStateStorage(m);s.update(s=>s.bookmarks.push(bookmark('view-a',null)));s.addRecent(null,'view-a');s.update(s=>{s.bookmarks[0].name='New';s.bookmarks[0].note='A note';});expect(new UserStateStorage(m).state.bookmarks[0].view?.camera?.zoom).toBe(2);s.deleteBookmark('view-a');expect(s.state.recent).toHaveLength(0);});
 it('rejects malformed/duplicate bookmarks, blob data and unbounded camera',()=>{const a=freshUserState();a.bookmarks=[bookmark(),bookmark()];expect(()=>validateUserState(a)).toThrow();const b={...freshUserState(),workspace:{}};expect(()=>validateUserState(b)).toThrow();const v=view();v.camera!.position[0]=Infinity;expect(()=>parseLocalView(v)).toThrow();});
 it('bounds, deduplicates and orders recent identities',()=>{const s=new UserStateStorage(new Memory());for(let i=0;i<50;i++)s.addRecent(target('p'+i),null,i);expect(s.state.recent).toHaveLength(RECENT_LIMIT);s.addRecent(target('p35'),null,100);expect(s.state.recent[0].target?.id).toBe('p35');expect(s.state.recent.filter(r=>r.target?.id==='p35')).toHaveLength(1);});
 it.each(['all','bookmarks','recent','tours','preferences'] as const)('selectively clears %s',group=>{const s=new UserStateStorage(new Memory());s.update(s=>{s.bookmarks=[bookmark()];s.preferences.scale=false;});s.addRecent(target());s.clear(group);expect(group==='all'||group==='bookmarks'?s.state.bookmarks.length:s.state.bookmarks.length).toBe(group==='all'||group==='bookmarks'?0:1);if(group==='all'||group==='preferences')expect(s.state.preferences.scale).toBe(true);});
 it('rejects unsupported state without mutating a valid stored record',()=>{const m=new Memory(),s=new UserStateStorage(m);expect(()=>s.update(s=>{s.bookmarks=[{...bookmark(),target:{...target(),hash:'secret'} as IdentityTarget}];})).toThrow();expect(s.state.bookmarks).toHaveLength(0);});
});
const share=():ShareState=>({schema:'gaiagis-share-state',version:1,language:'en',mapId:'WM0',projection:'globe',native:'3d',layers:['atlas'],spoilers:'hide-major',target:{kind:'location',id:'midgar'}});
describe('share allowlist is independent from private camera/state',()=>{
 it('round-trips concise public configuration and identity',()=>{const url=encodeShare('https://example.org/app?private=1#triangle=8',share());expect(url.length).toBeLessThan(250);expect(decodeShare(url)).toEqual(share());expect(url).not.toMatch(/private|triangle|hash|camera/);});
 for(const key of ['camera','position','longitude','latitude','absolutePath','workspaceHashes','sourceHash','triangleId','routeNodes','explorerPackId','bookmarks'])it('rejects '+key,()=>{expect(()=>validateShareState({...share(),[key]:'secret'})).toThrow();expect(decodeShare('https://example.org/?'+key+'=secret')).toBeNull();});
 it('rejects private target kinds and unknown fields; unknown public IDs safely fall back',()=>{expect(()=>validateShareState({...share(),target:{kind:'entrance',id:'entry-private'}})).toThrow();expect(decodeShare('https://example.org/?place=unknown')?.target).toBeNull();expect(decodeShare('https://example.org/?place=midgar&place=kalm')).toBeNull();});
 it('supports Atlas cards, native view config and spoiler/language choices',()=>{const a=share();a.target={kind:'atlas',id:'ancient-forest'};a.language='ja';a.spoilers='show-all';expect(decodeShare(encodeShare('https://example.org/',a))).toEqual(a);a.mapId='WM2';a.target=null;a.native='topdown';expect(decodeShare(encodeShare('https://example.org/',a))).toEqual(a);});
 it('rejects unsupported versions, overlong URLs and non-public IDs',()=>{expect(()=>validateShareState({...share(),version:2})).toThrow();expect(()=>validateShareState({...share(),target:{kind:'atlas',id:'D:/private'}})).toThrow();expect(decodeShare('https://example.org/?place='+('x'.repeat(1000)))).toBeNull();});
});
const anchor=(id:string,lon:number,lat:number,precision='entrance_level'):NearbyAnchor=>({target:target(id,'atlas'),name:id,point:[lon,lat,0],precision:precision as NearbyAnchor['precision'],group:'places'});
describe('reference-sphere nearby authority',()=>{
 it('includes only actual anchors and never parent/field/unresolved reward distance',()=>{const idx=new NearbyIndex([anchor('ok',0,0),...['parent_place','field_only','unresolved','non_spatial'].map(p=>anchor(p,0,0,p))]);expect(idx.size).toBe(1);expect(idx.query([0,0,0])[0].distance).toBe(0);});
 it('filters radius and orders known equatorial distances',()=>{const idx=new NearbyIndex([anchor('a',1,0),anchor('b',2,0)]);expect(idx.query([0,0,0],150000).map(r=>r.target.id)).toEqual(['a']);expect(idx.query([0,0,0])[0].distance).toBeCloseTo(REFERENCE_RADIUS*Math.PI/180,6);});
 it('crosses the antimeridian by the short arc',()=>{const idx=new NearbyIndex([anchor('seam',-179.9,0)]);expect(idx.query([179.9,0,0])[0].distance).toBeCloseTo(REFERENCE_RADIUS*Math.PI/900,5);});
 it('handles the pole and same-point singularities',()=>{const idx=new NearbyIndex([anchor('pole',120,90)]);expect(idx.query([-150,90,0])[0].distance).toBeLessThan(1e-6);expect(idx.query([120,89,0])[0].distance).toBeCloseTo(REFERENCE_RADIUS*Math.PI/180,5);});
 it('excludes native-domain entries and duplicates, bounds result count',()=>{const a=anchor('a',0,0),native={...anchor('native',0,0),target:{...target('native'),mapId:'WM2' as const}};expect(new NearbyIndex([a,a,native]).size).toBe(1);expect(new NearbyIndex([a]).query([0,0,0],-1)).toHaveLength(0);});
});
const stops:TourStop[]=['midgar','kalm','junon'].map(id=>({id:'stop-'+id,target:target(id),duration:2,title:''}));
describe('tour and route playback lifecycle',()=>{
 it('plays, pauses, navigates stops and restores once on finish/stop',()=>{const visited:string[]=[],events:string[]=[];const t=new TourPlayback(stops,s=>{visited.push(s.target.id);return true;},()=>events.push('capture'),()=>events.push('restore'));expect(t.play()).toBe(true);t.pause();t.tick(1);expect(t.elapsed).toBe(0);t.play();t.next();t.previous();expect(t.index).toBe(0);t.next();t.next();t.tick(1);t.tick(1);expect(t.phase).toBe('finished');t.stop();expect(events).toEqual(['capture','restore']);expect(visited).toContain('junon');});
 it('skips invalid targets, handles empty tours and signals reduced motion',()=>{expect(new TourPlayback([],()=>true,()=>{},()=>{}).play()).toBe(false);let reduced=false;const t=new TourPlayback(stops,(s,r)=>{reduced=r;return s.target.id==='junon';},()=>{},()=>{},true);expect(t.play()).toBe(true);expect(t.index).toBe(2);expect(reduced).toBe(true);t.stop();});
 it('validates strict local tours without coordinates',()=>{expect(parseTour({id:'tour',name:'World',stops,created:123}).stops).toHaveLength(3);expect(()=>parseTour({id:'tour',name:'World',stops:[{...stops[0],position:[0,0]}],created:123})).toThrow();expect(()=>parseTour({id:'tour',name:'World',stops:[{...stops[0],duration:999}],created:123})).toThrow();});
 it('plays/pauses/restarts with speed and follow flags; no route and changes clear progress',()=>{const r=new RoutePlayback();expect(r.play()).toBe(false);r.setRoute(100);expect(r.play()).toBe(true);r.tick(1);const p=r.progress;r.pause();r.tick(1);expect(r.progress).toBe(p);r.speed=2;r.follow=true;r.play();r.tick(1);expect(r.progress).toBeGreaterThan(p);r.restart();expect(r.progress).toBe(0);r.setRoute(0);expect(r.phase).toBe('idle');expect(r.follow).toBe(true);});
 it('does not modify solved route coordinates or node sequence',()=>{const solved=[1,2,4,9],before=JSON.stringify(solved),r=new RoutePlayback();r.setRoute(solved.length);r.play();for(let i=0;i<20;i++)r.tick(1);expect(r.phase).toBe('finished');expect(JSON.stringify(solved)).toBe(before);});
 it('validates opacity/visibility defaults, multiple-layer persistence and reset',()=>{expect(layerIds).toHaveLength(8);const m=new Memory(),s=new UserStateStorage(m);s.update(s=>{s.preferences.opacity.atlas=.3;s.preferences.opacity.traversal=.6;s.preferences.visibility.atlas=true;});expect(new UserStateStorage(m).state.preferences.opacity.atlas).toBe(.3);s.clear('preferences');expect(s.state.preferences.opacity).toEqual(defaultOpacities());expect(s.state.preferences.visibility).toEqual(defaultVisibility());expect(()=>s.update(s=>{s.preferences.opacity.atlas=NaN;})).toThrow();});
});
const context={radius:REFERENCE_RADIUS,mercatorLimit:80.071528814895,centerLon:0,centerLat:0};
function planar(x=0,y=0){const c=new OrthographicCamera(-2,2,1,-1,.1,20);c.position.set(x,y,8);c.lookAt(x,y,0);c.updateProjectionMatrix();return c;}
describe('local horizontal screen scale without projection changes',()=>{
 it('matches known equatorial inverse samples',()=>{const c=planar(),s=localScreenScale(c,'equirectangular',context,1000,500)!;expect(s.metersPerPixel).toBeCloseTo(4*REFERENCE_RADIUS/1000,4);expect(s.pixels).toBeGreaterThan(0);});
 it('Mercator ground scale changes with latitude',()=>{const equator=localScreenScale(planar(),'mercator',context,1000,500)!,p=projections.mercator.project(0,60,0,context),high=localScreenScale(planar(p[0],p[1]),'mercator',context,1000,500,[0,60,0])!;expect(high.metersPerPixel/equator.metersPerPixel).toBeCloseTo(.5,2);});
 it.each(['equal-earth','winkel-tripel','mollweide','gall-peters','robinson','natural-earth','sinusoidal','orthographic','laea','aeqd'] as const)('agrees with inverse finite-screen geodesic in %s',id=>{const s=localScreenScale(planar(),id,context,1000,500)!;expect(s).not.toBeNull();expect(s.metersPerPixel).toBeCloseTo(measureDistance([s.a,s.b]).total/96,5);});
 it('Globe uses sphere hits and hides unstable/missed rays',()=>{const c=new PerspectiveCamera(45,2,.01,100);c.position.set(0,0,3);c.lookAt(0,0,0);c.updateProjectionMatrix();expect(localScreenScale(c,'globe',context,1000,500)).not.toBeNull();expect(screenGeographic(c,'globe',context,0,0,1000,500)).toBeNull();c.lookAt(0,10,3);expect(localScreenScale(c,'globe',context,1000,500)).toBeNull();});
});
