// SPDX-License-Identifier: GPL-3.0-only
import {describe,it,expect,vi} from 'vitest';
import {readFileSync,existsSync} from 'node:fs';
import {parseRouting,connectedComponents,findRoute,routeProfiles,routeState,entranceEndpoints,loadOptionalRouting} from '../src/data/routing';
import {parseMesh} from '../src/data/mesh';
import {routeSegments} from '../src/viewer/route';
import {routingFixture} from './fixtures/routing';
describe('source routing transport and static analysis',()=>{
 it('decodes synthetic CSR without any source geometry',()=>{const g=parseRouting(routingFixture());expect(g.count).toBe(4);expect(g.arcs).toBe(8);expect(g.lineage.get('0/0/3')).toBe(3);expect(g.weights[0]).toBe(2);});
 it.each([0,8,10,12,16,20,24,28,32,36,44,48,96])('rejects corrupt header field %s',at=>{const b=routingFixture();new DataView(b).setUint16(at,65535,true);expect(()=>parseRouting(b)).toThrow();});
 it('rejects truncated buffers and source fingerprint mismatch',()=>{expect(()=>parseRouting(routingFixture().slice(0,150))).toThrow();expect(()=>parseRouting(routingFixture(),{stage1:{source_wm0_sha256:'bb'.repeat(32)}} as never)).toThrow(/different WM0/);});
 it('validates exact lineage/count, origin, terrain and script against mesh',()=>{const g=parseRouting(routingFixture()),mesh={sourceTriangleCount:4,attributes:(i:number)=>({section:0,mesh:0,triangle:i,terrain:0,script:0,origin:0})};expect(parseRouting(routingFixture(),undefined,mesh as never).count).toBe(4);mesh.attributes=()=>({section:0,mesh:0,triangle:99,terrain:0,script:0,origin:0});expect(()=>parseRouting(routingFixture(),undefined,mesh as never)).toThrow();});
 it('rejects terrain range, duplicate lineage, missing reverse edge, NaN weight and negative area',()=>{for(const corrupt of [(v:DataView)=>v.setUint8(134,32),(v:DataView)=>v.setUint16(148,0,true),(v:DataView)=>v.setUint32(212,3,true),(v:DataView)=>v.setFloat64(244,NaN,true),(v:DataView)=>v.setFloat64(136,-1,true)]){const b=routingFixture();corrupt(new DataView(b));expect(()=>parseRouting(b)).toThrow();}});
 it('covers all 32 codes for nine routable modes and excludes Highwind Landing',()=>{expect(routeProfiles).toHaveLength(9);expect(()=>routeState('highwind-landing',0)).toThrow();for(const p of routeProfiles)for(let i=0;i<32;i++)expect(['allowed','blocked','conditional','unknown']).toContain(routeState(p.id,i));expect(()=>routeState('foot',32)).toThrow();});
 it('excludes blocked and conditional triangles by default',()=>{const g=parseRouting(routingFixture([0,13,0,3],[[0,1,1],[1,2,1],[2,3,1]]));expect([...connectedComponents(g,'foot').labels]).toEqual([0,-1,1,-1]);expect([...connectedComponents(g,'foot',true).labels]).toEqual([0,0,0,-1]);});
 it('deterministic components aggregate reference area',()=>{const g=parseRouting(routingFixture()),a=connectedComponents(g,'foot');expect(a).toEqual(connectedComponents(g,'foot'));expect(a.components).toEqual([{id:0,triangles:4,area:406}]);});
 it('Dijkstra chooses weighted optimal corridor, not fewest hops',()=>{const g=parseRouting(routingFixture()),labels=connectedComponents(g,'foot').labels,r=findRoute(g,labels,[{node:0,entrance:'start'}],[{node:3,entrance:'end'}]);expect(r).toEqual({nodes:[0,1,2,3],distance:9,startEntrance:'start',targetEntrance:'end',component:0});expect(r).toEqual(findRoute(g,labels,[{node:0,entrance:'start'}],[{node:3,entrance:'end'}]));});
 it('same-triangle, disconnected, blocked and multiple entrance endpoints',()=>{const g=parseRouting(routingFixture([0,0,0,3],[[0,1,2]])),l=connectedComponents(g,'foot').labels;expect(findRoute(g,l,[{node:0,entrance:'a'}],[{node:0,entrance:'b'}])?.distance).toBe(0);expect(findRoute(g,l,[{node:0,entrance:'a'}],[{node:2,entrance:'b'}])).toBeNull();expect(findRoute(g,l,[{node:3,entrance:'blocked'}],[{node:0,entrance:'a'}])).toBeNull();expect(findRoute(g,l,[{node:2,entrance:'isolated'},{node:0,entrance:'primary'}],[{node:1,entrance:'end'}])?.startEntrance).toBe('primary');});
 it.each(routeProfiles.map(p=>p.id))('%s routes a synthetic compatible edge without vehicle transfer assumptions',id=>{const terrain=Array.from({length:32},(_,i)=>i).find(i=>routeState(id,i)==='allowed')!,g=parseRouting(routingFixture([terrain,terrain],[[0,1,7]])),labels=connectedComponents(g,id).labels;expect(findRoute(g,labels,[{node:0,entrance:'synthetic-start'}],[{node:1,entrance:'synthetic-end'}])?.distance).toBe(7);});
 it('entrances bind all exact source trigger IDs, never nearest point',()=>{const g=parseRouting(routingFixture()),ends=entranceEndpoints(g,[{id:'a',section_id:0,mesh_id:0,trigger_triangle_ids:[0,2,999]},{id:'b',section_id:0,mesh_id:0,trigger_triangle_ids:[1]}] as never);expect(ends).toEqual([{node:0,entrance:'a'},{node:1,entrance:'b'},{node:2,entrance:'a'}]);});
 it('splits route display at antimeridian without a long map-spanning chord',()=>{const s=routeSegments([[179.5,10,0],[-179.5,12,0]]);for(let i=0;i<s.length;i+=6){expect(Math.abs(s[i+3]-s[i])).toBeLessThanOrEqual(1);expect(s[i]).toBeGreaterThanOrEqual(-180);expect(s[i+3]).toBeLessThanOrEqual(180);}expect([...s]).toContain(180);expect([...s]).toContain(-180);});
 it('missing optional routing leaves geometry intact',async()=>{vi.stubGlobal('fetch',async()=>new Response('',{status:404}));expect(await loadOptionalRouting({} as never,{} as never)).toBeNull();vi.unstubAllGlobals();});
 it.skipIf(!existsSync('public/data/gaia-routing.bin'))('real locally generated routing matches frozen mesh lineage',()=>{const binary=(file:string)=>{const b=readFileSync(file);return b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength);};const meta=JSON.parse(readFileSync('public/data/gaia-meta.json','utf8')),mesh=parseMesh(binary('public/data/gaia-mesh.bin'),meta),g=parseRouting(binary('public/data/gaia-routing.bin'),meta,mesh);expect(g.count).toBe(mesh.sourceTriangleCount);expect(g.seamEdges).toBe(224);for(const p of routeProfiles){const r=connectedComponents(g,p.id);expect(r.components.length).toBeGreaterThan(0);expect(r.labels.length).toBe(mesh.sourceTriangleCount);}});
});
