// SPDX-License-Identifier: GPL-3.0-only
import {BufferAttribute,BufferGeometry,Camera,Color,LineBasicMaterial,LineSegments,Mesh,OrthographicCamera,PerspectiveCamera,Scene,Sphere,Vector3,WebGLRenderer} from 'three';
import {projectDisplay} from '../data/display';
import type {DisplayMesh} from '../data/display';
import {projections} from '../projections';
import {fitProjectionToViewport} from '../projections/Projection';
import type {GeoPoint,ProjectionId,ProjectionContext} from '../projections/Projection';
import {linkedContext} from '../analysis/distortion';
import {rotatesCenter} from '../projections/registry';
import {createSurfaceMaterial} from './surfaceMaterial';
import {CartographicLine} from './cartographicLines';
import {LocationsOverlay} from './locations';
import {t} from '../i18n';
import type {Location} from '../data/poi';
import {screenGridPolicy} from './gridPolicy';
import {adaptiveGrid} from '../analysis/adaptive';
import type {GridMode} from '../analysis/adaptive';
export interface LinkedView {center:GeoPoint;zoom:number;centerResolved?:boolean;}
export class ComparisonView {
 readonly host=document.createElement('div');readonly renderer:WebGLRenderer;readonly scene=new Scene();readonly surface:Mesh;readonly locations:LocationsOverlay;readonly events:LocationsOverlay;
 readonly measurement=new CartographicLine('#73e4ed');readonly tissot=new CartographicLine('#dfb4ff',true);readonly route=new CartographicLine('#ffe18c');readonly comparedRoutes=[new CartographicLine('#6de0d0'),new CartographicLine('#ffab82'),new CartographicLine('#c5acff')];readonly grid=new CartographicLine('#c3d6de');
 private planar=new OrthographicCamera();private spherical=new PerspectiveCamera(45,1,.005,100);private camera:Camera=this.planar;private key='';private size='';private frame?:ReturnType<typeof projectDisplay>;private caption=document.createElement('div');drawCalls=0;
 private gridKey='';private gridCameraKey='';private gridLast=-Infinity;gridInterval=30;gridGenerationMs=0;gridRegenerations=0;
 constructor(private container:HTMLElement,private display:DisplayMesh,color:BufferAttribute,onLocation:(location:Location)=>void,onEvent:(location:Location)=>void){this.host.id='comparison-viewport';this.host.className='comparison-viewport';container.append(this.host);this.renderer=new WebGLRenderer({alpha:true,antialias:true});this.renderer.setClearColor(0,0);this.renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));this.renderer.domElement.setAttribute('aria-label',t('compare.canvas'));this.host.append(this.renderer.domElement);this.caption.className='compare-caption';this.host.append(this.caption);const geometry=new BufferGeometry();geometry.setAttribute('color',color);geometry.boundingSphere=new Sphere(new Vector3(),6);this.surface=new Mesh(geometry,createSurfaceMaterial());this.surface.frustumCulled=false;this.scene.add(this.surface);this.locations=new LocationsOverlay(this.host,onLocation);this.events=new LocationsOverlay(this.host,onEvent,'event');for(const o of [this.measurement,this.tissot,this.route,this.grid,...this.comparedRoutes])this.scene.add(o.line);}
 update(id:ProjectionId,context:ProjectionContext,view:LinkedView,gridMode:GridMode,gridMinor:boolean,gridVisible:boolean){const width=Math.max(1,this.host.clientWidth),height=Math.max(1,this.host.clientHeight),size=`${width}:${height}`;if(size!==this.size){this.renderer.setSize(width,height);this.size=size;}const c=linkedContext(id,context,view.center),key=`${id}:${c.centerLon.toFixed(5)}:${c.centerLat.toFixed(5)}`;if(key!==this.key||!this.frame){if(!this.frame){this.frame=projectDisplay(this.display,projections[id],c);this.surface.geometry.setAttribute('position',new BufferAttribute(this.frame.positions,3));this.surface.geometry.setAttribute('gaiaMask',new BufferAttribute(this.frame.mask,1));}else{projectDisplay(this.display,projections[id],c,this.frame.positions,this.frame.mask);this.surface.geometry.getAttribute('position').needsUpdate=true;this.surface.geometry.getAttribute('gaiaMask').needsUpdate=true;}this.key=key;}
 const fit=fitProjectionToViewport(projections[id].bounds(c),width/height),zoom=Math.max(.3,Math.min(20,view.zoom));if(id==='globe'){const camera=this.spherical,distance=(fit.halfHeight/Math.tan(Math.PI/8)+.45)/zoom;camera.aspect=width/height;camera.updateProjectionMatrix();camera.position.set(...projections.globe.project(view.center[0],view.center[1],0,c)).multiplyScalar(Math.max(1.08,distance));camera.lookAt(0,0,0);this.camera=camera;}else{const center=rotatesCenter(id)?[0,0]:projections[id].project(view.center[0],view.center[1],0,c),camera=this.planar;camera.left=-fit.halfWidth;camera.right=fit.halfWidth;camera.top=fit.halfHeight;camera.bottom=-fit.halfHeight;camera.zoom=zoom;camera.position.set(center[0],center[1],8);camera.lookAt(center[0],center[1],0);camera.updateProjectionMatrix();this.camera=camera;}this.camera.updateMatrixWorld();
 const signature=`${id}:${Math.round(Math.log(zoom)*40)}:${Math.round(view.center[0]*2)}:${Math.round(view.center[1]*2)}:${size}:${gridMode}:${gridMinor}`,time=performance.now();if(gridVisible&&time-this.gridLast>=180&&signature!==this.gridCameraKey){this.gridLast=time;this.gridCameraKey=signature;const policy=screenGridPolicy(id,c,this.camera,width,height,view.center,gridMode,this.gridInterval,gridMinor),key=`${policy.interval}:${policy.minor}:${JSON.stringify(policy.bounds)}`;this.gridInterval=policy.interval;if(key!==this.gridKey){const begin=performance.now();const data=adaptiveGrid(policy.interval,policy.bounds,policy.minor);this.grid.set(data.geo);this.grid.line.material.vertexColors=true;this.grid.line.material.color.set('#ffffff');const colors=new Float32Array(data.geo.length);for(let i=0;i<data.kind.length;i++){const kind=data.kind[i],color=new Color(kind===2?'#f2c879':kind===3?'#8dd9de':'#d3dde2');if(kind===1)color.multiplyScalar(.4);colors.set([color.r,color.g,color.b],i*3);}this.grid.line.geometry.setAttribute('color',new BufferAttribute(colors,3));this.gridKey=key;this.gridGenerationMs=performance.now()-begin;this.gridRegenerations++;}}this.grid.line.visible=gridVisible;for(const o of [this.measurement,this.tissot,this.route,this.grid,...this.comparedRoutes])o.update(id,c,undefined,this.camera.position);this.locations.update(id,c,this.camera);this.events.update(id,c,this.camera);this.caption.textContent=`B · ${t(`projection.${id}`)}`+(view.centerResolved===false?' · '+t('compare.lastCenter'):'');this.host.dataset.center=`${view.center[0]},${view.center[1]}`;this.host.dataset.zoom=String(zoom);this.renderer.domElement.setAttribute('aria-label',t('compare.canvas'));this.renderer.render(this.scene,this.camera);this.drawCalls=this.renderer.info.render.calls;}
 dispose(){this.locations.dispose();this.events.dispose();for(const o of [this.measurement,this.tissot,this.route,this.grid,...this.comparedRoutes])o.dispose();this.surface.geometry.deleteAttribute('color');this.surface.geometry.dispose();(this.surface.material as ReturnType<typeof createSurfaceMaterial>).dispose();this.renderer.dispose();this.renderer.forceContextLoss();this.host.remove();this.frame=undefined;}
}
