// SPDX-License-Identifier: GPL-3.0-only
import {BufferAttribute,BufferGeometry,Color,DoubleSide,Mesh,MeshBasicMaterial,OrthographicCamera,PerspectiveCamera,Raycaster,Scene,Triangle,Vector2,Vector3,WebGLRenderer} from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import type {NativeMap,MapTransition} from '../data/nativeMaps';
import type {DecodedTextures} from '../data/textures';
import {textureAlpha} from '../data/textures';
import {TexturedSurface} from './texturedSurface';
import {terrainPalette} from '../styles/terrainPalette';
import {regionColor} from '../data/regions';
import {validateExaggeration} from './relief';

export class NativeViewer {
 captureExplorer=false;onExplorerFrame:(seconds:number)=>void=()=>{};onExplorerPick:(triangle:number,weights:[number,number,number])=>void=()=>{};private explorerLast=performance.now();
 readonly renderer=new WebGLRenderer({antialias:true});readonly scene=new Scene();
 readonly geometry=new BufferGeometry();readonly material=new MeshBasicMaterial({vertexColors:true,side:DoubleSide});
 readonly surface=new Mesh(this.geometry,this.material);readonly textured:TexturedSurface;
 readonly perspective=new PerspectiveCamera(45,1,.001,1000);readonly orthographic=new OrthographicCamera(-1,1,1,-1,.001,1000);
 controls:OrbitControls;camera:PerspectiveCamera|OrthographicCamera;pack:DecodedTextures|null=null;exaggeration=1;topdown=false;selected:number|null=null;
 readonly resizeObserver:ResizeObserver;readonly scale:number;private frames=0;private began=performance.now();private linear=false;private origin=new Vector2();
 readonly diagnostics={fps:0,drawCalls:0,textures:0,geometryBytes:0,atlasBytes:0};
 onPick:(triangle:number)=>void=()=>{};onTransition:(record:MapTransition)=>void=()=>{};
 private markers:{node:HTMLButtonElement;record:MapTransition}[]=[];
 constructor(readonly container:HTMLElement,readonly map:NativeMap){
  this.scale=Math.max(...map.header.extent);this.camera=this.perspective;
  const positions=new Float32Array(map.positions.length),colors=new Float32Array(positions.length);
  for(let t=0;t<map.sourceTriangleCount;t++){const c=new Color(terrainPalette[map.attributes(t).terrain!]);for(let j=0;j<3;j++)colors.set([c.r,c.g,c.b],t*9+j*3);}
  this.geometry.setAttribute('position',new BufferAttribute(positions,3));this.geometry.setAttribute('color',new BufferAttribute(colors,3));this.textured=new TexturedSurface(this.material,this.geometry);this.scene.add(this.surface);this.scene.background=new Color('#0a1724');
  this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.container.append(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.screenSpacePanning=true;this.updatePositions();this.reset();
  this.renderer.domElement.tabIndex=0;this.renderer.domElement.addEventListener('pointerdown',e=>this.origin.set(e.clientX,e.clientY));this.renderer.domElement.addEventListener('pointerup',e=>{if(this.origin.distanceTo(new Vector2(e.clientX,e.clientY))<6)this.pick(e.clientX,e.clientY);});
  this.renderer.domElement.addEventListener('keydown',e=>{if(e.key==='Home'){e.preventDefault();this.reset();}});
  this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.resize();this.renderer.setAnimationLoop(time=>{const dt=Math.min(.1,Math.max(0,(time-this.explorerLast)/1000));this.explorerLast=time;if(this.captureExplorer)this.onExplorerFrame(dt);else this.controls.update();this.renderer.render(this.scene,this.camera);this.frames++;if(time-this.began>500){this.diagnostics.fps=this.frames*1000/(time-this.began);this.began=time;this.frames=0;}this.diagnostics.drawCalls=this.renderer.info.render.calls;this.diagnostics.textures=this.renderer.info.memory.textures;this.placeMarkers();});
  this.diagnostics.geometryBytes=positions.byteLength+colors.byteLength+map.sourceTriangleCount*3*7*4;
 }
 private updatePositions(){const p=this.geometry.getAttribute('position') as BufferAttribute;for(let i=0;i<this.map.positions.length;i+=3){p.setXYZ(i/3,(this.map.positions[i]-this.map.header.extent[0]/2)/this.scale,this.topdown?0:this.map.positions[i+2]*this.exaggeration/this.scale,(this.map.positions[i+1]-this.map.header.extent[1]/2)/this.scale);}p.needsUpdate=true;this.geometry.computeBoundingSphere();}
 setRelief(value:number){this.exaggeration=validateExaggeration(value);this.updatePositions();}
 setView(topdown:boolean){this.topdown=topdown;this.controls.dispose();this.camera=topdown?this.orthographic:this.perspective;this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableRotate=!topdown;this.controls.enableDamping=true;this.controls.screenSpacePanning=true;this.updatePositions();this.reset();this.resize();}
 reset(){this.geometry.computeBoundingSphere();const bound=this.geometry.boundingSphere!,radius=Math.max(.6,bound.radius),center=this.topdown?new Vector3():bound.center;this.controls.target.copy(center);this.camera.position.copy(center).add(new Vector3(0,this.topdown?2:radius*2,this.topdown?.000001:radius*1.8));this.camera.lookAt(center);this.camera.zoom=1;this.camera.updateProjectionMatrix();this.controls.update();}
 focus(position:number[]){const target=new Vector3((position[0]-this.map.header.extent[0]/2)/this.scale,this.topdown?0:(position[2]??0)*this.exaggeration/this.scale,(position[1]-this.map.header.extent[1]/2)/this.scale);const delta=target.clone().sub(this.controls.target);this.controls.target.copy(target);this.camera.position.add(delta);this.controls.update();}
 resize(){const w=Math.max(1,this.container.clientWidth),h=Math.max(1,this.container.clientHeight),aspect=w/h;this.renderer.setSize(w,h);this.perspective.aspect=aspect;this.perspective.updateProjectionMatrix();this.orthographic.left=-aspect*.65;this.orthographic.right=aspect*.65;this.orthographic.top=.65;this.orthographic.bottom=-.65;this.orthographic.updateProjectionMatrix();}
 setLayer(mode:'terrain'|'region'|'texture'){const color=this.geometry.getAttribute('color') as BufferAttribute;for(let t=0;t<this.map.sourceTriangleCount;t++){const a=this.map.attributes(t),c=new Color(mode==='region'?regionColor(a.region!):terrainPalette[a.terrain!]);if(t===this.selected)c.lerp(new Color('#fff'),.35);for(let j=0;j<3;j++)color.setXYZ(t*3+j,c.r,c.g,c.b);}color.needsUpdate=true;this.textured.uniforms.gaiaTextureEnabled.value=mode==='texture'&&this.pack?1:0;}
 loadTextures(pack:DecodedTextures){const uv=new Float32Array(this.map.sourceTriangleCount*6),rect=new Float32Array(this.map.sourceTriangleCount*12);for(let t=0;t<this.map.sourceTriangleCount;t++){const a=this.map.attributes(t),r=pack.resources.get(a.texture!),p=pack.records.get(`${a.section}/${a.mesh}/${a.triangle}`);if(!r||p===undefined)continue;for(let j=0;j<3;j++){uv.set([(pack.uv.getUint8(p+8+j*2)-r.u_offset)/r.width,(pack.uv.getUint8(p+9+j*2)-r.v_offset)/r.height],t*6+j*2);rect.set([r.x/pack.metadata.atlas.width,r.y/pack.metadata.atlas.height,r.width/pack.metadata.atlas.width,r.height/pack.metadata.atlas.height],t*12+j*4);}}this.textured.load(pack,this.geometry,{uv,rect});this.filtering(this.linear);this.pack?.image.close();this.pack=pack;this.diagnostics.atlasBytes=pack.image.width*pack.image.height*4;this.setLayer('texture');}
 filtering(linear:boolean){this.linear=linear;this.textured.filtering(linear);}
 shading(on:boolean){this.textured.uniforms.gaiaShading.value=on?1:0;}
 pick(clientX:number,clientY:number){const box=this.renderer.domElement.getBoundingClientRect(),ray=new Raycaster();ray.setFromCamera(new Vector2((clientX-box.left)/box.width*2-1,-(clientY-box.top)/box.height*2+1),this.camera);for(const hit of ray.intersectObject(this.surface)){const t=hit.faceIndex;if(t==null)continue;if(this.pack&&this.textured.uniforms.gaiaTextureEnabled.value){const a=this.map.attributes(t),r=this.pack.resources.get(a.texture!),offset=this.pack.records.get(`${a.section}/${a.mesh}/${a.triangle}`);if(r&&offset!==undefined){const p=this.geometry.getAttribute('position'),corners=[0,1,2].map(j=>new Vector3().fromBufferAttribute(p,t*3+j)),weights=Triangle.getBarycoord(hit.point,corners[0],corners[1],corners[2],new Vector3());if(weights){const w=[weights.x,weights.y,weights.z];let u=0,v=0;for(let j=0;j<3;j++){u+=w[j]*(this.pack.uv.getUint8(offset+8+j*2)-r.u_offset)/r.width;v+=w[j]*(this.pack.uv.getUint8(offset+9+j*2)-r.v_offset)/r.height;}if(textureAlpha(this.pack,a.texture!,u,v,this.linear)<.005)continue;}}}if(this.captureExplorer){const pos=this.geometry.getAttribute('position'),corners=[0,1,2].map(j=>new Vector3().fromBufferAttribute(pos,t*3+j)),w=Triangle.getBarycoord(hit.point,corners[0],corners[1],corners[2],new Vector3());if(w)this.onExplorerPick(t,[w.x,w.y,w.z]);return t;}this.selected=t;this.onPick(t);return t;}return null;}
 setTransitions(records:MapTransition[],visible:boolean){for(const m of this.markers)m.node.remove();this.markers=[];if(!visible)return;for(const record of records){if(record.from_map!==this.map.header.mapId||!record.from_native_position)continue;const node=document.createElement('button');node.className='native-transition-marker';node.textContent='↗';node.title=`${record.from_map} → ${record.to_map}`;node.addEventListener('click',()=>this.onTransition(record));this.container.append(node);this.markers.push({node,record});}this.placeMarkers();}
 private placeMarkers(){for(const {node,record}of this.markers){const p=record.from_native_position!;const v=new Vector3((p[0]-this.map.header.extent[0]/2)/this.scale,this.topdown?0:p[2]*this.exaggeration/this.scale,(p[1]-this.map.header.extent[1]/2)/this.scale).project(this.camera);node.hidden=Math.abs(v.x)>1||Math.abs(v.y)>1||Math.abs(v.z)>1;node.style.left=`${(v.x+1)*this.container.clientWidth/2}px`;node.style.top=`${(1-v.y)*this.container.clientHeight/2}px`;}}
 dispose(){this.renderer.setAnimationLoop(null);this.controls.dispose();this.resizeObserver.disconnect();this.markers.forEach(m=>m.node.remove());this.geometry.dispose();this.material.dispose();this.textured.dispose();this.pack?.image.close();this.pack=null;this.renderer.dispose();this.renderer.forceContextLoss();this.renderer.domElement.remove();}
}
