// SPDX-License-Identifier: GPL-3.0-only
import {BufferAttribute,BufferGeometry,LineBasicMaterial,LineSegments} from 'three';
import type {GaiaMesh} from '../data/mesh';
import type {ProjectionId,ProjectionContext,GeoPoint} from '../projections/Projection';
import {projections} from '../projections';
import {projectGraticule} from './graticule';
import {addVisibilityMask} from './visibility';
export function corridorPoints(mesh:GaiaMesh,nodes:number[]):GeoPoint[]{return nodes.map(t=>{const corners=[0,1,2].map(j=>{const i=mesh.indices[t*3+j]*3;return [mesh.geographic[i],mesh.geographic[i+1],mesh.geographic[i+2]];});let lon=corners[0][0];for(let i=1;i<3;i++)lon+=corners[i][0]+360*Math.round((corners[0][0]-corners[i][0])/360);return [((lon/3+180)%360+360)%360-180,corners.reduce((s,p)=>s+p[1]/3,0),corners.reduce((s,p)=>s+p[2]/3,0)+1500];});}
export function routeSegments(points:GeoPoint[]){const result:number[]=[];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],lon=b[0]+360*Math.round((a[0]-b[0])/360),steps=Math.max(1,Math.ceil(Math.max(Math.abs(lon-a[0]),Math.abs(b[1]-a[1]))/1));let prev=a;for(let j=1;j<=steps;j++){const f=j/steps,next:GeoPoint=[a[0]+f*(lon-a[0]),a[1]+f*(b[1]-a[1]),a[2]+f*(b[2]-a[2])];const shift=360*Math.floor((prev[0]+180)/360),x=prev[0]-shift,y=next[0]-shift;if(y>180||y< -180){const seam=y>180?180:-180,k=(seam-x)/(y-x),lat=prev[1]+k*(next[1]-prev[1]),h=prev[2]+k*(next[2]-prev[2]);result.push(x,prev[1],prev[2],seam,lat,h,-seam,lat,h,y-Math.sign(y)*360,next[1],next[2]);}else result.push(x,prev[1],prev[2],y,next[1],next[2]);prev=next;}}return new Float32Array(result);}
export class RouteOverlay {
  line:LineSegments;private geo=new Float32Array();private cached?:ReturnType<typeof projectGraticule>;private cacheKey="";private from?:ReturnType<typeof projectGraticule>;private to?:ReturnType<typeof projectGraticule>;
  constructor(){const material=new LineBasicMaterial({color:'#ffe18c',depthTest:false,transparent:true,opacity:.95});addVisibilityMask(material);this.line=new LineSegments(new BufferGeometry(),material);this.line.frustumCulled=false;this.line.renderOrder=9;this.line.visible=false;}
  set(mesh:GaiaMesh,nodes:number[]){this.geo=routeSegments(corridorPoints(mesh,nodes));this.line.geometry.dispose();this.line.geometry=new BufferGeometry();this.line.geometry.setAttribute('position',new BufferAttribute(new Float32Array(this.geo.length),3));this.line.geometry.setAttribute('gaiaMask',new BufferAttribute(new Float32Array(this.geo.length/3),1));this.line.visible=nodes.length>1;this.from=this.to=this.cached=undefined;this.cacheKey="";}
  begin(from:ProjectionId,to:ProjectionId,c:ProjectionContext,interrupted=false){this.from=interrupted&&this.line.visible?{positions:new Float32Array(this.line.geometry.getAttribute('position').array),mask:new Float32Array(this.line.geometry.getAttribute('gaiaMask').array)}:projectGraticule(this.geo,projections[from],c);this.to=projectGraticule(this.geo,projections[to],c);}
  update(id:ProjectionId,c:ProjectionContext,ease?:number){if(!this.line.visible)return;const key=`${id}:${c.centerLon}:${c.centerLat}`;if(key!==this.cacheKey||!this.cached){this.cached=projectGraticule(this.geo,projections[id],c);this.cacheKey=key;}const current=this.cached,position=this.line.geometry.getAttribute('position').array,mask=this.line.geometry.getAttribute('gaiaMask').array;for(let i=0;i<position.length;i++)position[i]=ease!==undefined&&this.from&&this.to?this.from.positions[i]+(this.to.positions[i]-this.from.positions[i])*ease:current.positions[i];for(let i=0;i<mask.length;i++)mask[i]=ease!==undefined&&this.from&&this.to?this.from.mask[i]+(this.to.mask[i]-this.from.mask[i])*ease:current.mask[i];this.line.geometry.getAttribute('position').needsUpdate=true;this.line.geometry.getAttribute('gaiaMask').needsUpdate=true;}
}
