// SPDX-License-Identifier: GPL-3.0-only
import {t,onLocaleChange} from '../i18n';
import {workspaceLoader,loadedAsset} from './assets';
import {appStore} from './state';
import {decodePresentation,UISounds} from '../data/presentation';
export type LightingPreset='original'|'flat'|'debug';
export interface PresentationPreferences {theme:'ff7'|'scientific';lighting:LightingPreset;sounds:boolean;volume:number;}
export function readPreferences(value:unknown):PresentationPreferences{const p=value as Partial<PresentationPreferences>|null;return {theme:p?.theme==='scientific'?'scientific':'ff7',lighting:['original','flat','debug'].includes(p?.lighting??'')?p!.lighting!:'original',sounds:p?.sounds===true,volume:typeof p?.volume==='number'&&Number.isFinite(p.volume)?Math.max(0,Math.min(1,p.volume)):.25};}
let saved:unknown;try{saved=JSON.parse(localStorage.getItem('gaiagis.presentation')??'null');}catch{}
export const presentation=readPreferences(saved),uiSounds=new UISounds();
export function setPresentation(update:Partial<PresentationPreferences>){Object.assign(presentation,readPreferences({...presentation,...update}));document.documentElement.dataset.theme=presentation.theme;uiSounds.enabled=presentation.sounds;uiSounds.volume=presentation.volume;try{localStorage.setItem('gaiagis.presentation',JSON.stringify(presentation));}catch{}document.dispatchEvent(new Event('gaiagis-presentation'));}
export function initializePresentation(){setPresentation({});const gesture=()=>uiSounds.unlock();document.addEventListener('pointerdown',gesture);document.addEventListener('keydown',gesture);document.addEventListener('change',e=>{if((e.target as Element).matches('select'))uiSounds.play('cursor');});document.addEventListener('click',e=>{const el=(e.target as Element).closest('button,summary');if(el)uiSounds.play(/close|exit|cancel|back/.test(el.id)?'cancel':el.tagName==='SUMMARY'?'open':'confirm');});}
export function mountPresentation(parent:HTMLElement){const root=document.createElement('details');root.className='presentation-settings';root.id='presentation-settings';const title=document.createElement('summary');root.append(title);parent.prepend(root);
 const select=(id:string,options:string[])=>{const label=document.createElement('label'),el=document.createElement('select');el.id=id;label.htmlFor=id;for(const value of options){const o=document.createElement('option');o.value=value;el.append(o);}root.append(label,el);return {label,el};};
 const theme=select('presentation-theme',['ff7','scientific']),light=select('presentation-lighting',['original','flat','debug']);const sounds=document.createElement('input'),soundLabel=document.createElement('label'),volume=document.createElement('input'),volumeLabel=document.createElement('label'),status=document.createElement('p');sounds.id='presentation-sounds';sounds.type='checkbox';volume.id='presentation-volume';volume.type='range';volume.min='0';volume.max='100';volume.step='1';soundLabel.htmlFor=sounds.id;volumeLabel.htmlFor=volume.id;root.append(soundLabel,sounds,volumeLabel,volume,status);
 theme.el.onchange=()=>setPresentation({theme:theme.el.value as PresentationPreferences['theme']});light.el.onchange=()=>setPresentation({lighting:light.el.value as LightingPreset});sounds.onchange=()=>setPresentation({sounds:sounds.checked});volume.oninput=()=>setPresentation({volume:Number(volume.value)/100});
 const refresh=()=>{title.textContent=t('present.title');theme.label.textContent=t('present.theme');light.label.textContent=t('present.lighting');for(const o of [...theme.el.options,...light.el.options])o.textContent=t('present.'+o.value);theme.el.value=presentation.theme;light.el.value=presentation.lighting;sounds.checked=presentation.sounds;sounds.disabled=!uiSounds.available;volume.value=String(presentation.volume*100);soundLabel.textContent=t('present.sounds');volumeLabel.textContent=t('present.volume')+' · '+Math.round(presentation.volume*100)+'%';status.textContent=t(uiSounds.available?'present.audioReady':'present.noAudio');};
 let generation=appStore.state.data.generation;const unsubscribe=appStore.subscribe(state=>{if(state.data.generation!==generation){generation=state.data.generation;uiSounds.dispose();refresh();}});
 const unregister=workspaceLoader.register('presentation',async files=>{const pack=decodePresentation(JSON.parse(await files[0].text()));await uiSounds.load(pack);loadedAsset('presentation',files[0].size);document.dispatchEvent(new Event('gaiagis-presentation'));refresh();});const stop=onLocaleChange(refresh);document.addEventListener('gaiagis-presentation',refresh);refresh();return ()=>{stop();unsubscribe();unregister();uiSounds.dispose();document.removeEventListener('gaiagis-presentation',refresh);root.remove();};
}
