import {navigationSelection} from './navigation';
// SPDX-License-Identifier: GPL-3.0-only
import {appStore,capabilities,features,featureAvailable} from './state';
import type {AssetId,PanelId} from './state';
import {assetFiles,directoryFiles} from './workspace';
import type {LocalDirectory} from './workspace';
import {workspaceLoader} from './assets';
import {ResourceScope} from './resources';
import {t,onLocaleChange,locale} from '../i18n';

export function mountShell(){
 const scope=new ResourceScope(),root=document.createElement('aside');root.id='integrated-panel';root.className='integrated-panel panel';
 const nav=document.createElement('nav');nav.setAttribute('role','tablist');nav.setAttribute('aria-label',t('workspace.title'));
 const content=document.createElement('div');content.className='integrated-content';const tabs=new Map<PanelId,HTMLButtonElement>(),groups=new Map<PanelId,HTMLElement>();
 const moved:{element:Element;parent:Node;next:ChildNode|null}[]=[];
 const secondary=document.createElement('aside');secondary.id='integrated-inspector';secondary.className='integrated-inspector panel';secondary.setAttribute('aria-label',t('app.selected'));document.body.append(secondary);scope.own(()=>secondary.remove());
 const close=document.createElement('button');close.id='integrated-close';close.textContent='×';close.setAttribute('aria-label',t('app.close'));close.onclick=()=>{root.classList.remove('open');document.getElementById('app-menu')?.focus();};root.append(close,nav,content);document.body.append(root);
 const menu=document.createElement('button');menu.id='app-menu';menu.className='app-menu';menu.setAttribute('aria-controls',root.id);menu.setAttribute('aria-expanded','false');menu.textContent=t('workspace.title');menu.onclick=()=>{const open=root.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));if(open)tabs.get(appStore.state.preferences.panel)?.focus();};document.body.append(menu);scope.own(()=>menu.remove());
 const move=(element:Element|null,group:HTMLElement)=>{if(element?.parentNode){moved.push({element,parent:element.parentNode,next:element.nextSibling});group.append(element);}};
 function activate(id:PanelId,focus=false){appStore.dispatch({type:'panel',panel:id});root.classList.add('open');if(id==='analysis'){const panel=document.getElementById('analysis-panel');if(panel)panel.hidden=appStore.state.map.id!=='WM0';}if(focus)tabs.get(id)?.focus();try{localStorage.setItem('gaiagis.panel',id);}catch{}}
 for(const id of ['explore','layers','analysis','map','view','data'] as PanelId[]){const button=document.createElement('button'),group=document.createElement('section');button.id=`app-tab-${id}`;group.id=`app-group-${id}`;button.setAttribute('role','tab');button.setAttribute('aria-controls',group.id);group.setAttribute('role','tabpanel');group.setAttribute('aria-labelledby',button.id);button.onclick=()=>activate(id);tabs.set(id,button);groups.set(id,group);nav.append(button);content.append(group);}
 const get=(id:PanelId)=>groups.get(id)!;
 move(document.querySelector('.locations-controls'),get('explore'));move(document.getElementById('explorer-panel'),get('explore'));move(document.getElementById('explorer-launch'),get('explore'));
 const wm0Layers=document.createElement('section');get('layers').append(wm0Layers);const controls=document.querySelector('.controls');
 if(controls){for(const child of [...controls.children]){if(child.classList.contains('panel-heading'))continue;if(child.classList.contains('texture-controls'))move(child,get('view'));else if(child.id==='projection-info')move(child,get('view'));else move(child,wm0Layers);}(controls as HTMLElement).hidden=true;}
 move(document.getElementById('analysis-panel'),get('analysis'));
 const bar=document.querySelector('.multimap-bar');if(bar)for(const child of [...bar.children])move(child,get('map'));
 const nativePanel=document.querySelector<HTMLElement>('.native-panel');move(nativePanel,get('map'));
 const nativeView=document.createElement('section');get('view').append(nativeView);const nativeLayers=document.createElement('section');get('layers').append(nativeLayers);
 const nativeLayerLabel=document.createElement('label');nativeLayerLabel.htmlFor='native-layer';nativeLayerLabel.textContent=t('ui.color');nativeLayers.append(nativeLayerLabel);move(document.getElementById('native-layer'),nativeLayers);
 for(const id of ['native-view','native-relief','native-filter','native-shading']){move(document.querySelector(`label[for="${id}"]`),nativeView);move(document.getElementById(id),nativeView);}
 const nativeAnalysisNote=document.createElement('p');nativeAnalysisNote.className='control-note';nativeAnalysisNote.textContent=t('map.noGlobal');get('analysis').append(nativeAnalysisNote);

 const infoPanel=document.getElementById('info-panel'),nativeInspector=document.getElementById('native-inspector');move(infoPanel,secondary);move(nativeInspector,secondary);
 move(document.querySelector('.projection-control'),get('view'));
 const breadcrumbs=document.createElement('p');breadcrumbs.id='map-breadcrumb';breadcrumbs.className='map-breadcrumb';document.body.append(breadcrumbs);scope.own(()=>breadcrumbs.remove());
 const hud=document.createElement('section');hud.id='explorer-hud';hud.className='explorer-hud';hud.hidden=true;const hudMap=document.createElement('span'),hudExit=document.createElement('button');hudExit.id='explorer-hud-exit';hudExit.textContent=t('explore.exit');hudExit.onclick=()=>document.getElementById('explorer-exit')?.click();hud.append(hudMap,hudExit);document.body.append(hud);scope.own(()=>hud.remove());
 const data=get('data'),heading=document.createElement('h2');heading.textContent=t('workspace.title');data.append(heading);
 const folder=document.createElement('button'),individual=document.createElement('button'),files=document.createElement('input'),fallback=document.createElement('input'),status=document.createElement('p');folder.id='load-workspace-folder';individual.id='load-workspace-files';files.id='workspace-files';fallback.id='workspace-directory';files.type=fallback.type='file';files.multiple=fallback.multiple=true;files.hidden=fallback.hidden=true;fallback.setAttribute('webkitdirectory','');status.id='workspace-status';status.textContent=capabilities(appStore.state).canInspectSurface?'':t('workspace.empty');status.setAttribute('role','status');data.append(folder,individual,files,fallback,status);
 const local=document.createElement('p');local.className='control-note';local.textContent=t('workspace.local');data.append(local);
 const list=document.createElement('dl');list.id='workspace-assets';list.className='property-list';data.append(list);
 const diagnostics=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre'),copy=document.createElement('button');summary.textContent=t('workspace.diagnostics');copy.textContent=t('workspace.copy');copy.id='copy-diagnostics';diagnostics.append(summary,copy,pre);data.append(diagnostics);
 const diagnostic=()=>({app:'GaiaGIS',map:appStore.state.map,view:appStore.state.view,assets:Object.fromEntries(Object.entries(appStore.state.data.assets).map(([id,a])=>[id,{status:a?.status,version:a?.version,bytes:a?.bytes,sourceHashes:a?.sourceHashes}])),privateContentIncluded:false});
 copy.onclick=()=>{if(!navigator.clipboard){status.textContent=t('workspace.error');return;}void navigator.clipboard.writeText(JSON.stringify(diagnostic(),null,2)).catch(()=>{status.textContent=t('workspace.error');});};
 async function load(chosen:File[]){status.textContent=t('workspace.loading');const began=performance.now();try{await workspaceLoader.load(chosen);const target=document.getElementById('workspace-status');if(target)target.textContent=t(capabilities(appStore.state).canInspectSurface?'workspace.loaded':'workspace.error');document.getElementById('integrated-panel')!.dataset.workspaceLoadMs=String(performance.now()-began);}catch{const target=document.getElementById('workspace-status');if(target)target.textContent=t('workspace.error');}}
 individual.onclick=()=>files.click();files.onchange=()=>{if(files.files)void load([...files.files]);files.value='';};fallback.onchange=()=>{if(fallback.files)void load([...fallback.files].filter(f=>f.name==='gaia-workspace.json'||Object.values(assetFiles).flat().includes(f.name)));fallback.value='';};
 folder.onclick=async()=>{const picker=(window as Window&{showDirectoryPicker?:()=>Promise<LocalDirectory>}).showDirectoryPicker;if(!picker){fallback.click();return;}try{await load(await directoryFiles(await picker()));}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))status.textContent=t('workspace.error');}};
 const selected=document.createElement('div');selected.id='selection-context';const selectedTitle=document.createElement('p'),actions=document.createElement('div');actions.className='analysis-actions';selected.append(selectedTitle,actions);secondary.prepend(selected);scope.own(()=>selected.remove());
 const clearContext=document.createElement('button');clearContext.id='clear-context';clearContext.textContent='×';clearContext.setAttribute('aria-label',t('app.close'));clearContext.onclick=()=>{document.getElementById('clear-selection')?.click();appStore.dispatch({type:'select',selection:null});(innerWidth<=700?menu:document.querySelector<HTMLCanvasElement>('.viewport canvas'))?.focus();};secondary.prepend(clearContext);
 function currentLocation(){return navigationSelection()?.location.display_name??null;}
 for(const [key,target]of [['app.routeFrom','route-from'],['app.routeTo','route-to']] as const){const button=document.createElement('button');button.textContent=t(key);button.dataset.capability='canRoute';button.onclick=()=>{const name=currentLocation(),input=document.getElementById(target) as HTMLInputElement|null;if(name&&input){input.value=name;input.dispatchEvent(new Event('input'));activate('analysis');input.focus();}};actions.append(button);}
 const measure=document.createElement('button');measure.textContent=t('app.measureHere');measure.dataset.capability='canMeasureSphere';measure.onclick=()=>{activate('analysis');const context=navigationSelection(),point=context?[context.entrance.longitude,context.entrance.latitude]:appStore.state.selection?.geographicPoint;if(point){for(const [id,value]of [['measure-lon',point[0]],['measure-lat',point[1]]] as const){const field=document.getElementById(id) as HTMLInputElement|null;if(field)field.value=String(value);}document.getElementById('measure-add')?.click();}const group=document.getElementById('analysis-measurement') as HTMLDetailsElement|null;if(group)group.open=true;document.getElementById('measure-start')?.click();};actions.append(measure);const explore=document.createElement('button');explore.textContent=t('app.exploreHere');explore.dataset.capability='canExplore';explore.onclick=()=>{const context=navigationSelection();if(context){activate('explore');document.dispatchEvent(new CustomEvent('gaiagis-explore-entrance',{detail:context.entrance}));}};actions.append(explore);
 scope.listen(document,'change',((e:Event)=>{const el=e.target as HTMLSelectElement;if(el.id==='projection')appStore.dispatch({type:'view',view:{projection:el.value as typeof appStore.state.view.projection}});if(el.id==='compare-projections')appStore.dispatch({type:'view',view:{compare:(el as unknown as HTMLInputElement).checked}});if(el.id==='graticule-spacing')appStore.dispatch({type:'preference',preferences:{graticule:el.value}});if(el.id==='surface-style')appStore.dispatch({type:'preference',preferences:{surfaceStyle:el.value as 'terrain'|'region'|'texture'}});if(el.id==='native-view')appStore.dispatch({type:'view',view:{native:el.value as '3d'|'topdown'}});if(['projection','graticule-spacing','surface-style'].includes(el.id))try{localStorage.setItem('gaiagis.preference.'+el.id,el.value);}catch{}}) as EventListener);
 scope.listen(root,'keydown',((e:KeyboardEvent)=>{if(e.key==='Escape'){root.classList.remove('open');document.getElementById('app-menu')?.focus();}}) as EventListener);
 scope.listen(nav,'keydown',((e:KeyboardEvent)=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const ids=[...tabs.keys()],index=ids.indexOf(appStore.state.preferences.panel);activate(ids[e.key==='Home'?0:e.key==='End'?ids.length-1:(index+(e.key==='ArrowRight'?1:-1)+ids.length)%ids.length],true);}) as EventListener);
 scope.listen(document,'click',((e:Event)=>{const target=(e.target as Element).closest('button');if(target?.id?.startsWith('measure-'))appStore.dispatch({type:'analysis',tool:'measurement'});if(['find-route','show-reachable'].includes(target?.id??''))appStore.dispatch({type:'analysis',tool:'routing'});if(target?.id==='distortion-probe')appStore.dispatch({type:'analysis',tool:'distortion'});if(target?.id?.startsWith('compare-'))appStore.dispatch({type:'analysis',tool:'compare'});if(target?.id==='measure-clear'&&appStore.state.selection?.kind==='measurement'||target?.id==='clear-analysis'&&appStore.state.selection?.kind==='route')appStore.dispatch({type:'select',selection:null});if(target?.id==='open-analysis')activate('analysis');if(target?.id==='mobile-display'){root.classList.toggle('open');document.querySelector('.controls')?.classList.remove('mobile-open');target.setAttribute('aria-expanded',String(root.classList.contains('open')));}}) as EventListener);
 const toolInspector=document.createElement('section');toolInspector.id='tool-inspector';toolInspector.hidden=true;secondary.append(toolInspector);
 function renderTool(){const kind=appStore.state.selection?.kind,tool=kind==='route'||kind==='measurement';toolInspector.hidden=!tool;if(tool){const id=kind==='route'?'route-result':'measurement-result';toolInspector.replaceChildren();const summary=document.createElement('p');summary.style.whiteSpace='pre-line';summary.textContent=document.getElementById(id)?.textContent??'';toolInspector.append(summary);const note=document.createElement('p');note.className='control-note';note.textContent=t(kind==='route'?'routing.scope':'measure.scope');toolInspector.append(note);}}

 for(const [id,kind]of [['route-result','route'],['measurement-result','measurement']] as const){const result=document.getElementById(id);if(!result)continue;result.tabIndex=0;result.setAttribute('role','button');const select=()=>{if(result.textContent&&!(kind==='route'&&Number(document.getElementById('analysis-panel')?.dataset.routeNodes??0)===0)&&!(kind==='measurement'&&Number(document.getElementById('analysis-measurement')?.dataset.points??0)===0))appStore.dispatch({type:'select',selection:{kind,id:'current',mapId:'WM0'}});};const observer=new MutationObserver(()=>{if(appStore.state.selection?.kind===kind)renderTool();});observer.observe(result,{childList:true,subtree:true,characterData:true});scope.own(()=>observer.disconnect());scope.listen(result,'click',select);scope.listen(result,'keydown',((e:KeyboardEvent)=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select();}}) as EventListener);}
 let lastSelection='';
 const refresh=()=>{const s=appStore.state,c=capabilities(s);secondary.dataset.selection=s.selection?.kind??'none';root.dataset.features=features.filter(f=>featureAvailable(f.id,s)).map(f=>f.id).join(',');const selectionKey=JSON.stringify(s.selection);if(selectionKey!==lastSelection){lastSelection=selectionKey;if(s.selection&&innerWidth<=700){root.classList.remove('open');menu.setAttribute('aria-expanded','false');}}for(const [id,button]of tabs){const active=id===s.preferences.panel;button.textContent=t(`app.${id}`);button.setAttribute('aria-selected',String(active));button.tabIndex=active?0:-1;get(id).hidden=!active;}folder.textContent=t('workspace.folder');individual.textContent=t('workspace.files');
  list.replaceChildren();for(const id of Object.keys(assetFiles) as AssetId[]){const a=s.data.assets[id],row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=id;dd.textContent=t('workspace.'+(a?.status??(id==='geometry'?'missing':'optional')));if(a?.reason)dd.title=t(a.reason);row.append(dt,dd);list.append(row);}pre.textContent=JSON.stringify(diagnostic(),null,2);
  wm0Layers.hidden=s.map.id!=='WM0';nativeView.hidden=nativeLayers.hidden=s.map.id==='WM0';nativeAnalysisNote.hidden=s.map.id==='WM0';const analysisPanel=document.getElementById('analysis-panel');if(analysisPanel)analysisPanel.hidden=s.map.id!=='WM0';for(const node of get('view').children)if(node!==nativeView)(node as HTMLElement).hidden=s.map.id!=='WM0';if(nativePanel)nativePanel.hidden=s.map.id==='WM0';const tool=s.selection?.kind==='route'||s.selection?.kind==='measurement';renderTool();if(infoPanel)infoPanel.hidden=s.map.id!=='WM0'||s.selection?.kind==='transition'||tool;if(nativeInspector)nativeInspector.hidden=s.map.id==='WM0'&&s.selection?.kind!=='transition';secondary.classList.toggle('has-selection',!!s.selection);menu.textContent=t('app.'+s.preferences.panel);breadcrumbs.textContent='Gaia > '+t('map.'+s.map.id)+(s.map.id==='WM0'?'':' · '+s.map.coordinateSpace);selectedTitle.textContent=t('app.selected')+': '+(s.selection?t(({triangle:'ui.triangleInspector',location:'ui.locations',entrance:'ui.entrances',encounter:'ui.encounters',event:'ui.events',transition:'map.transitions',route:'routing.title',measurement:'analysis.measure',explorer:'explore.title'})[s.selection.kind]):t('app.inspectNone'));for(const button of actions.querySelectorAll<HTMLButtonElement>('button')){button.hidden=!s.selection;button.disabled=!c[button.dataset.capability as keyof typeof c]||['canRoute','canExplore'].includes(button.dataset.capability??'')&&!['location','entrance'].includes(s.selection?.kind??'')||button.dataset.capability==='canMeasureSphere'&&!['location','entrance','triangle','encounter'].includes(s.selection?.kind??'');}
  for(const id of ['find-route','show-reachable','compare-routes','compare-reachable']){const b=document.getElementById(id) as HTMLButtonElement|null;if(b)b.disabled=!featureAvailable('routing',s);}
  hud.hidden=s.explorer.phase!=='active';if(s.explorer.phase==='active'&&innerWidth<=700){root.classList.remove('open');menu.setAttribute('aria-expanded','false');}hudMap.textContent=t('map.'+s.map.id)+' · '+t('explore.preview');hudExit.textContent=t('explore.exit');
  root.classList.toggle('explorer-minimal',s.explorer.phase!=='idle');if(s.explorer.phase!=='idle'){get('explore').hidden=false;if(innerWidth>700){const panel=document.getElementById('explorer-panel') as HTMLDetailsElement|null;if(panel)panel.open=true;}const locations=get('explore').querySelector<HTMLElement>('.locations-controls');if(locations)locations.hidden=true;}else {const locations=get('explore').querySelector<HTMLElement>('.locations-controls');if(locations)locations.hidden=s.map.id!=='WM0';}
 };
 scope.own(appStore.subscribe(refresh));scope.own(onLocaleChange(()=>appStore.dispatch({type:'preference',preferences:{language:locale()}})));appStore.dispatch({type:'preference',preferences:{language:locale()}});
 try{const saved=localStorage.getItem('gaiagis.panel') as PanelId;if(tabs.has(saved))appStore.dispatch({type:'panel',panel:saved});}catch{}
 const restorePreferences=()=>{for(const id of ['projection','graticule-spacing','surface-style']){const field=document.getElementById(id) as HTMLSelectElement|null;let saved:string|null=null;try{saved=localStorage.getItem('gaiagis.preference.'+id);}catch{}if(field&&saved&&field.value!==saved&&[...field.options].some(o=>o.value===saved&&!o.disabled)){field.value=saved;field.dispatchEvent(new Event('change',{bubbles:true}));}}};restorePreferences();
 const style=document.getElementById('surface-style');if(style){const observer=new MutationObserver(restorePreferences);observer.observe(style,{subtree:true,attributes:true,attributeFilter:['disabled']});scope.own(()=>observer.disconnect());}
 let seen=false;try{seen=localStorage.getItem('gaiagis.seenIntro')==='true';}catch{}
 if(!seen&&!capabilities(appStore.state).canInspectSurface){const intro=document.createElement('section');intro.id='gaia-intro';intro.className='gaia-intro';intro.setAttribute('role','dialog');intro.setAttribute('aria-label','GaiaGIS 2.0');const title=document.createElement('h2'),note=document.createElement('p');title.textContent='GaiaGIS 2.0';note.textContent=t('app.introText')+' '+t('app.introData');note.id='intro-description';intro.setAttribute('aria-describedby',note.id);intro.append(title,note);for(const [key,action]of [['app.start',()=>{}],['workspace.folder',()=>{activate('data');folder.click();}],['app.about',()=>document.querySelector<HTMLDialogElement>('#about-dialog')?.showModal()]] as const){const button=document.createElement('button');button.textContent=t(key);button.onclick=()=>{try{localStorage.setItem('gaiagis.seenIntro','true');}catch{}intro.remove();(innerWidth<=700?menu:tabs.get('explore'))?.focus();action();};intro.append(button);}document.body.append(intro);intro.querySelector('button')?.focus();scope.own(()=>intro.remove());}
 return {activate,dispose(){scope.dispose();const persistent=document.getElementById('explorer-panel');if(persistent&&root.contains(persistent))document.querySelector('.multimap-bar')?.append(persistent);for(const {element,parent,next}of moved.reverse())if(element.id==='explorer-launch'&&document.getElementById('explorer-panel'))continue;else if(next?.parentNode===parent)parent.insertBefore(element,next);else parent.appendChild(element);root.remove();}};
}
